package net.civeira.phylax.features.access.scopeassignation.application.service.visibility;

import java.util.Optional;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import net.civeira.phylax.common.security.PropertiesProposal;
import net.civeira.phylax.features.access.scopeassignation.ScopeAssignationRef;

@Data
@SuperBuilder(toBuilder = true)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class ScopeAssignationFixedFieldsProposal extends PropertiesProposal {

  /**
   * @autogenerated FixedFieldsProposalGenerator
   */
  private final ScopeAssignationRef scopeAssignation;

  /**
   * @autogenerated FixedFieldsProposalGenerator
   * @return
   */
  public Optional<ScopeAssignationRef> getScopeAssignation() {
    return Optional.ofNullable(scopeAssignation);
  }

  /**
   * @autogenerated FixedFieldsProposalGenerator
   * @return
   */
  public String resourceName() {
    return "scope-assignation";
  }

  /**
   * @autogenerated FixedFieldsProposalGenerator
   * @return
   */
  public String viewName() {
    return "update";
  }
}
