package net.civeira.phylax.features.access.consentpurpose.domain;

import java.time.LocalDateTime;
import java.time.ZoneId;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import net.civeira.phylax.features.access.consentpurpose.domain.valueobject.ActivationDateVO;
import net.civeira.phylax.features.access.consentpurpose.domain.valueobject.DescriptionVO;
import net.civeira.phylax.features.access.consentpurpose.domain.valueobject.KeyVO;
import net.civeira.phylax.features.access.consentpurpose.domain.valueobject.RequiredVO;
import net.civeira.phylax.features.access.consentpurpose.domain.valueobject.TenantVO;
import net.civeira.phylax.features.access.consentpurpose.domain.valueobject.TitleVO;
import net.civeira.phylax.features.access.consentpurpose.domain.valueobject.UidVO;
import net.civeira.phylax.features.access.consentpurpose.domain.valueobject.VersionVO;
import net.civeira.phylax.features.access.tenant.domain.TenantReference;

class ConsentPurposeUnitTest {

  /**
   * @autogenerated CachedGenerator
   */
  @Test
  @DisplayName("Test a entity reference contruction")
  void test_consent_purpose_builder() {
    ConsentPurpose one = ConsentPurpose.builder().uidValue(UidVO.from("one"))
        .tenantValue(TenantVO.from(TenantReference.of("one")))
        .keyValue(KeyVO.from(ConsentPurposeKeyOptions.MARKETING)).titleValue(TitleVO.from("one"))
        .descriptionValue(DescriptionVO.from("one")).requiredValue(RequiredVO.from(true))
        .activationDateValue(ActivationDateVO.from(LocalDateTime.of(1980, 8, 20, 0, 0)
            .atZone(ZoneId.of("Europe/Madrid")).toOffsetDateTime()))
        .versionValue(VersionVO.from(1)).build();
    ConsentPurpose withOne = one.withVersionValue(VersionVO.from(1));
    Assertions.assertEquals(2, withOne.withNextVersion().getVersion().get());
    ConsentPurpose deleted = one.delete();
    Assertions.assertEquals(1, deleted.getRecordedEvents().size(),
        "After delete, one event must be stored");
    Assertions.assertTrue(one.getRecordedEvents().isEmpty(),
        "No events can affect the original entity");
  }
}
