package net.civeira.phylax.features.document.snippet.infrastructure.event;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.features.document.snippet.domain.Snippet;
import net.civeira.phylax.features.document.snippet.domain.event.SnippetEvent;

@ApplicationScoped
@RequiredArgsConstructor
public class SnippetEventDispatcher {

  /**
   * @autogenerated EventDispatcherGenerator
   */
  private final Event<SnippetEvent> emitter;

  /**
   * @autogenerated EventDispatcherGenerator
   * @param entity
   */
  public void dispatch(final Snippet entity) {
    entity.getRecordedEvents().forEach(emitter::fire);
  }
}
