package net.civeira.phylax.features.access.clientidentity.infrastructure.repository;

import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Predicate;

import javax.sql.DataSource;

import io.opentelemetry.api.trace.Tracer;
import jakarta.enterprise.context.ApplicationScoped;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import net.civeira.phylax.common.algorithms.Slider;
import net.civeira.phylax.common.exception.ConstraintException;
import net.civeira.phylax.common.exception.NotFoundException;
import net.civeira.phylax.common.infrastructure.sql.OptimistLockException;
import net.civeira.phylax.common.infrastructure.sql.PartialWhere;
import net.civeira.phylax.common.infrastructure.sql.SqlCommand;
import net.civeira.phylax.common.infrastructure.sql.SqlConverter;
import net.civeira.phylax.common.infrastructure.sql.SqlListParameterValue;
import net.civeira.phylax.common.infrastructure.sql.SqlOperator;
import net.civeira.phylax.common.infrastructure.sql.SqlParameterValue;
import net.civeira.phylax.common.infrastructure.sql.SqlQuery;
import net.civeira.phylax.common.infrastructure.sql.SqlResult;
import net.civeira.phylax.common.infrastructure.sql.SqlSchematicQuery;
import net.civeira.phylax.common.infrastructure.sql.SqlTemplate;
import net.civeira.phylax.features.access.clientidentity.domain.ClientIdentity;
import net.civeira.phylax.features.access.clientidentity.domain.ClientIdentityRef;
import net.civeira.phylax.features.access.clientidentity.domain.gateway.ClientIdentityCursor;
import net.civeira.phylax.features.access.clientidentity.domain.gateway.ClientIdentityFilter;
import net.civeira.phylax.features.access.clientidentity.domain.valueobject.RelyingPartyVO;
import net.civeira.phylax.features.access.clientidentity.domain.valueobject.RolesVO;
import net.civeira.phylax.features.access.clientidentity.domain.valueobject.TrustedClientVO;
import net.civeira.phylax.features.access.clientidentity.domain.valueobject.UidVO;
import net.civeira.phylax.features.access.clientidentity.domain.valueobject.UserVO;
import net.civeira.phylax.features.access.clientidentity.domain.valueobject.VersionVO;

@ApplicationScoped
@RequiredArgsConstructor
@Slf4j
public class ClientIdentityRepository {

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String ACCESS_CLIENT_IDENTITY_RELYING_PARTY =
      "access_client_identity.relying_party";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String ACCESS_CLIENT_IDENTITY_ROLES = "access_client_identity.roles";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String ACCESS_CLIENT_IDENTITY_SNAKE = "access_client_identity";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String ACCESS_CLIENT_IDENTITY_TRUSTED_CLIENT =
      "access_client_identity.trusted_client";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String ACCESS_CLIENT_IDENTITY_UID = "access_client_identity.uid";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String ACCESS_CLIENT_IDENTITY_USER = "access_client_identity.user";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String ACCESS_CLIENT_IDENTITY_USER_TENANT =
      "access_client_identity_user.tenant";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String ACCESS_CLIENT_IDENTITY_VERSION = "access_client_identity.version";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String RELYING_PARTY = "relyingParty";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String RELYING_PARTY_SNAKE = "relying_party";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String ROLES = "roles";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String TRUSTED_CLIENT = "trustedClient";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String TRUSTED_CLIENT_SNAKE = "trusted_client";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String UID = "uid";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String USER = "user";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String VERSION = "version";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private final DataSource datasource;

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private final Tracer tracer;

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public long count(ClientIdentityFilter filter) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlSchematicQuery<Long> sq = filteredQuery(template, filter);
      sq.select("count(uid) as uid");
      return sq.query(row -> Optional.of(row.getLong(1))).one().orElse(0l);
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   * @return
   */
  public ClientIdentity create(ClientIdentity entity) {
    return runCreate(entity, null);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   * @param verifier
   * @return
   */
  public ClientIdentity create(ClientIdentity entity, Predicate<ClientIdentity> verifier) {
    return runCreate(entity, verifier);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   */
  public void delete(ClientIdentity entity) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlCommand sq =
          template.createSqlCommand("delete from \"access_client_identity\" where \"uid\" = :uid");
      sq.with(UID, SqlParameterValue.of(entity.getUid()));
      int num = sq.execute();
      if (0 == num) {
        throw new IllegalArgumentException("No delete from");
      }
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param uid
   * @param filter
   * @return
   */
  public boolean exists(String uid, Optional<ClientIdentityFilter> filter) {
    return retrieve(uid, filter).isPresent();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param uid
   * @param filter
   * @return
   */
  public boolean existsForUpdate(String uid, Optional<ClientIdentityFilter> filter) {
    return retrieveForUpdate(uid, filter).isPresent();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public Optional<ClientIdentity> find(ClientIdentityFilter filter) {
    ClientIdentityCursor cursor = ClientIdentityCursor.builder().build();
    return new ClientIdentitySlider(runList(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor).one();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @return sq.where("uid", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public Optional<ClientIdentity> find(final String sql,
      final Map<String, SqlParameterValue> params) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlQuery<ClientIdentity> createSqlQuery = template.createSqlQuery(sql);
      params.forEach(createSqlQuery::with);
      return createSqlQuery.query(converter()).one();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public Optional<ClientIdentity> findForUpdate(ClientIdentityFilter filter) {
    ClientIdentityCursor cursor = ClientIdentityCursor.builder().build();
    return new ClientIdentitySlider(runListForUpdate(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor).one();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @return sq.where("uid", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public Optional<ClientIdentity> findForUpdate(final String sql,
      final Map<String, SqlParameterValue> params) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlQuery<ClientIdentity> createSqlQuery = template.createSqlQuery(sql);
      params.forEach(createSqlQuery::with);
      return createSqlQuery.forUpdate().query(converter()).one();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public List<ClientIdentity> list(ClientIdentityFilter filter) {
    ClientIdentityCursor cursor = ClientIdentityCursor.builder().build();
    return new ClientIdentitySlider(runList(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor).all();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @return sq.where("uid", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public List<ClientIdentity> list(final String sql, final Map<String, SqlParameterValue> params) {
    return list(sql, params, null, false);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @param limit
   * @return sq.where("uid", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public List<ClientIdentity> list(final String sql, final Map<String, SqlParameterValue> params,
      final int limit) {
    return list(sql, params, Integer.valueOf(limit), false);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public List<ClientIdentity> listForUpdate(ClientIdentityFilter filter) {
    ClientIdentityCursor cursor = ClientIdentityCursor.builder().build();
    return new ClientIdentitySlider(runListForUpdate(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor).all();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @return sq.where("uid", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public List<ClientIdentity> listForUpdate(final String sql,
      final Map<String, SqlParameterValue> params) {
    return list(sql, params, null, true);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @param limit
   * @return sq.where("uid", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public List<ClientIdentity> listForUpdate(final String sql,
      final Map<String, SqlParameterValue> params, final int limit) {
    return list(sql, params, Integer.valueOf(limit), true);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param reference
   * @return
   */
  public ClientIdentity resolve(ClientIdentityRef reference) {
    return reference instanceof ClientIdentity clientIdentity ? clientIdentity
        : retrieve(reference.getUid(), Optional.empty()).orElseThrow(() -> new NotFoundException(
            "Trying to resolve inexistent ClientIdentity: " + reference.getUid()));
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param reference
   * @return
   */
  public ClientIdentity resolveForUpdate(ClientIdentityRef reference) {
    return reference instanceof ClientIdentity clientIdentity ? clientIdentity
        : retrieveForUpdate(reference.getUid(), Optional.empty())
            .orElseThrow(() -> new NotFoundException(
                "Trying to resolve inexistent ClientIdentity: " + reference.getUid()));
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param uid
   * @param filter
   * @return
   */
  public Optional<ClientIdentity> retrieve(String uid, Optional<ClientIdentityFilter> filter) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      ClientIdentityFilter readyFilter = filter.map(val -> val.withUid(uid))
          .orElseGet(() -> ClientIdentityFilter.builder().uid(uid).build());
      SqlSchematicQuery<ClientIdentity> sq = filteredQuery(template, readyFilter);
      return sq.query(converter()).one();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param uid
   * @param filter
   * @return
   */
  public Optional<ClientIdentity> retrieveForUpdate(String uid,
      Optional<ClientIdentityFilter> filter) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      ClientIdentityFilter readyFilter = filter.map(val -> val.withUid(uid))
          .orElseGet(() -> ClientIdentityFilter.builder().uid(uid).build());
      SqlSchematicQuery<ClientIdentity> sq = filteredQuery(template, readyFilter);
      return sq.forUpdate().query(converter()).one();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @param cursor
   * @return
   */
  public Slider<ClientIdentity> slide(ClientIdentityFilter filter, ClientIdentityCursor cursor) {
    return new ClientIdentitySlider(runList(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @param cursor
   * @return
   */
  public Slider<ClientIdentity> slideForUpdate(ClientIdentityFilter filter,
      ClientIdentityCursor cursor) {
    return new ClientIdentitySlider(runListForUpdate(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   * @return
   */
  public ClientIdentity update(ClientIdentity entity) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlCommand sq = template.createSqlCommand(
          "update \"access_client_identity\" set  \"user\" = :user, \"relying_party\" = :relyingParty, \"trusted_client\" = :trustedClient, \"roles\" = :roles, \"version\" = \"version\" + 1 where \"uid\" = :uid and \"version\" = :version");
      sq.with(UID, SqlParameterValue.of(entity.getUid()));
      sq.with(USER, SqlParameterValue.of(entity.getUserUid()));
      sq.with(RELYING_PARTY, entity.getRelyingPartyUid().map(SqlParameterValue::of)
          .orElseGet(SqlParameterValue::ofNullString));
      sq.with(TRUSTED_CLIENT, entity.getTrustedClientUid().map(SqlParameterValue::of)
          .orElseGet(SqlParameterValue::ofNullString));
      sq.with(ROLES,
          entity.getRoles().map(SqlParameterValue::of).orElseGet(SqlParameterValue::ofNullString));
      sq.with(VERSION, entity.getVersion().map(SqlParameterValue::of)
          .orElseGet(SqlParameterValue::ofNullInteger));
      int num = sq.execute();
      if (0 == num) {
        throw new OptimistLockException("No delete from");
      }
      return entity.withNextVersion();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @return
   */
  private SqlConverter<ClientIdentity> converter() {
    return row -> {
      try {
        return Optional.of(ClientIdentity.builder().uidValue(UidVO.from(row.getString(UID)))
            .userValue(UserVO.fromReference(row.getString(USER)))
            .relyingPartyValue(RelyingPartyVO.fromReference(row.getString(RELYING_PARTY_SNAKE)))
            .trustedClientValue(TrustedClientVO.fromReference(row.getString(TRUSTED_CLIENT_SNAKE)))
            .rolesValue(RolesVO.from(row.getString(ROLES)))
            .versionValue(VersionVO.from(row.getInt(VERSION))).build());
      } catch (ConstraintException ce) {
        log.error("Unable to map data for {}", row.getString(1), ce);
        return Optional.empty();
      }
    };
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param template
   * @param filter
   * @return
   */
  private <T> SqlSchematicQuery<T> filteredQuery(SqlTemplate template,
      ClientIdentityFilter filter) {
    SqlSchematicQuery<T> sq = template.createSqlSchematicQuery(ACCESS_CLIENT_IDENTITY_SNAKE);
    sq.selectFields(ACCESS_CLIENT_IDENTITY_UID, ACCESS_CLIENT_IDENTITY_USER,
        ACCESS_CLIENT_IDENTITY_RELYING_PARTY, ACCESS_CLIENT_IDENTITY_TRUSTED_CLIENT,
        ACCESS_CLIENT_IDENTITY_ROLES, ACCESS_CLIENT_IDENTITY_VERSION);
    filter.getUid().ifPresent(uid -> sq.where(UID, SqlOperator.EQ, SqlParameterValue.of(uid)));
    if (!filter.getUids().isEmpty()) {
      sq.where(UID, SqlOperator.IN, SqlListParameterValue.strings(filter.getUids()));
    }
    filter.getSearch().ifPresent(
        search -> sq.where("uid", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%")));
    sq.where(PartialWhere.or(
        filter.getForAllAudiences().filter(Boolean.TRUE::equals)
            .map(_ -> PartialWhere.where("relying_party", SqlOperator.IS_NULL,
                SqlParameterValue.ofNullString())),
        filter.getForAllAudiences().filter(Boolean.TRUE::equals).map(_ -> PartialWhere
            .where("trusted_client", SqlOperator.IS_NULL, SqlParameterValue.ofNullString()))));
    filter.getUser()
        .ifPresent(user -> sq.where(USER, SqlOperator.EQ, SqlParameterValue.of(user.getUid())));
    if (!filter.getUsers().isEmpty()) {
      sq.where(USER, SqlOperator.IN, SqlListParameterValue.strings(filter.getUsers()));
    }
    filter.getRelyingParty().ifPresent(relyingParty -> sq.where(RELYING_PARTY_SNAKE, SqlOperator.EQ,
        SqlParameterValue.of(relyingParty.getUid())));
    if (!filter.getRelyingPartys().isEmpty()) {
      sq.where(RELYING_PARTY_SNAKE, SqlOperator.IN,
          SqlListParameterValue.strings(filter.getRelyingPartys()));
    }
    filter.getTrustedClient().ifPresent(trustedClient -> sq.where(TRUSTED_CLIENT_SNAKE,
        SqlOperator.EQ, SqlParameterValue.of(trustedClient.getUid())));
    if (!filter.getTrustedClients().isEmpty()) {
      sq.where(TRUSTED_CLIENT_SNAKE, SqlOperator.IN,
          SqlListParameterValue.strings(filter.getTrustedClients()));
    }
    filter.getUserTenantTenantAccesible().ifPresent(userTenantTenantAccesible -> {
      sq.join("access_user", "access_client_identity_user", "access_client_identity.user",
          "access_client_identity_user.uid");
      sq.where(ACCESS_CLIENT_IDENTITY_USER_TENANT, SqlOperator.EQ,
          SqlParameterValue.of(userTenantTenantAccesible));
    });
    return sq;
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @param limit
   * @param forUpdate
   * @return sq.where("uid", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  private List<ClientIdentity> list(final String sql, final Map<String, SqlParameterValue> params,
      final Integer limit, final boolean forUpdate) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlQuery<ClientIdentity> createSqlQuery = template.createSqlQuery(sql);
      params.forEach(createSqlQuery::with);
      if (forUpdate) {
        createSqlQuery = createSqlQuery.forUpdate();
      }
      SqlResult<ClientIdentity> query = createSqlQuery.query(converter());
      return null == limit ? query.all() : query.limit(limit);
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   * @param verifier
   * @return
   */
  private ClientIdentity runCreate(ClientIdentity entity, Predicate<ClientIdentity> verifier) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlCommand sq = template.createSqlCommand(
          "insert into \"access_client_identity\" ( \"uid\", \"user\", \"relying_party\", \"trusted_client\", \"roles\", \"version\") values ( :uid, :user, :relyingParty, :trustedClient, :roles, :version)");
      sq.with(UID, SqlParameterValue.of(entity.getUid()));
      sq.with(USER, SqlParameterValue.of(entity.getUserUid()));
      sq.with(RELYING_PARTY, entity.getRelyingPartyUid().map(SqlParameterValue::of)
          .orElseGet(SqlParameterValue::ofNullString));
      sq.with(TRUSTED_CLIENT, entity.getTrustedClientUid().map(SqlParameterValue::of)
          .orElseGet(SqlParameterValue::ofNullString));
      sq.with(ROLES,
          entity.getRoles().map(SqlParameterValue::of).orElseGet(SqlParameterValue::ofNullString));
      sq.with(VERSION, entity.getVersion().map(SqlParameterValue::of)
          .orElseGet(SqlParameterValue::ofNullInteger));
      int num = sq.execute();
      if (0 == num) {
        throw new IllegalArgumentException("No insert into");
      }
      return verifier == null ? entity : verified(verifier.test(entity), entity, template);
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @param cursor
   * @return
   */
  private Iterator<ClientIdentity> runList(ClientIdentityFilter filter,
      ClientIdentityCursor cursor) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlSchematicQuery<ClientIdentity> sq = filteredQuery(template, filter);
      cursor.getSinceUid()
          .ifPresent(since -> sq.where(UID, SqlOperator.GT, SqlParameterValue.of(since)));
      sq.orderAsc("uid");
      return sq.query(converter()).limit(cursor.getLimit()).iterator();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @param cursor
   * @return
   */
  private Iterator<ClientIdentity> runListForUpdate(ClientIdentityFilter filter,
      ClientIdentityCursor cursor) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlSchematicQuery<ClientIdentity> sq = filteredQuery(template, filter);
      cursor.getSinceUid()
          .ifPresent(since -> sq.where(UID, SqlOperator.GT, SqlParameterValue.of(since)));
      sq.orderAsc("uid");
      return sq.forUpdate().query(converter()).limit(cursor.getLimit()).iterator();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param exists
   * @param entity
   * @param template
   * @return
   */
  private ClientIdentity verified(boolean exists, ClientIdentity entity, SqlTemplate template) {
    if (exists) {
      return entity;
    } else {
      template.createSqlCommand("delete from \"access_client_identity\" where \"uid\" = :uid")
          .with("uid", SqlParameterValue.of(entity.getUid())).execute();
      throw new NotFoundException("");
    }
  }
}
