package net.civeira.phylax.features.access.user.domain.valueobject;

import java.time.LocalDateTime;
import java.time.ZoneId;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import net.civeira.phylax.common.exception.ConstraintException;

class WellcomeAtVOUnitTest {

  /**
   * @autogenerated ValueObjectGenerator
   */
  @Test
  @DisplayName("Test value object contruction for property wellcome at of user ")
  void test_wellcome_at_v_o_builder() {
    Assertions.assertFalse(WellcomeAtVO.nullValue().getWellcomeAt().isPresent(),
        "A empty vo should have a null value");
    Assertions.assertFalse(WellcomeAtVO.tryFrom(null).getWellcomeAt().isPresent(),
        "With a null value, no present result");
    Assertions.assertEquals(
        LocalDateTime.of(1980, 8, 20, 0, 0).atZone(ZoneId.of("Europe/Madrid")).toOffsetDateTime(),
        WellcomeAtVO.from(LocalDateTime.of(1980, 8, 20, 0, 0).atZone(ZoneId.of("Europe/Madrid"))
            .toOffsetDateTime()).getWellcomeAt().orElse(null));
    Object falingInstance = new Object() {};
    Assertions.assertThrows(ConstraintException.class, () -> WellcomeAtVO.tryFrom(falingInstance));
    Assertions.assertEquals(
        "[" + LocalDateTime.of(1980, 8, 20, 0, 0).atZone(ZoneId.of("Europe/Madrid"))
            .toOffsetDateTime() + "]",
        WellcomeAtVO.from(LocalDateTime.of(1980, 8, 20, 0, 0).atZone(ZoneId.of("Europe/Madrid"))
            .toOffsetDateTime()).toString());
  }
}
