package net.civeira.phylax.features.document.snippet.infrastructure.repository;

import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Predicate;

import javax.sql.DataSource;

import io.opentelemetry.api.trace.Tracer;
import jakarta.enterprise.context.ApplicationScoped;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import net.civeira.phylax.common.algorithms.Slider;
import net.civeira.phylax.common.exception.ConstraintException;
import net.civeira.phylax.common.exception.NotFoundException;
import net.civeira.phylax.common.infrastructure.sql.OptimistLockException;
import net.civeira.phylax.common.infrastructure.sql.PartialWhere;
import net.civeira.phylax.common.infrastructure.sql.SqlCommand;
import net.civeira.phylax.common.infrastructure.sql.SqlConverter;
import net.civeira.phylax.common.infrastructure.sql.SqlListParameterValue;
import net.civeira.phylax.common.infrastructure.sql.SqlOperator;
import net.civeira.phylax.common.infrastructure.sql.SqlParameterValue;
import net.civeira.phylax.common.infrastructure.sql.SqlQuery;
import net.civeira.phylax.common.infrastructure.sql.SqlResult;
import net.civeira.phylax.common.infrastructure.sql.SqlSchematicQuery;
import net.civeira.phylax.common.infrastructure.sql.SqlTemplate;
import net.civeira.phylax.features.document.snippet.domain.Snippet;
import net.civeira.phylax.features.document.snippet.domain.SnippetRef;
import net.civeira.phylax.features.document.snippet.domain.gateway.SnippetCursor;
import net.civeira.phylax.features.document.snippet.domain.gateway.SnippetFilter;
import net.civeira.phylax.features.document.snippet.domain.gateway.SnippetOrder;
import net.civeira.phylax.features.document.snippet.domain.valueobject.CodeVO;
import net.civeira.phylax.features.document.snippet.domain.valueobject.EnabledVO;
import net.civeira.phylax.features.document.snippet.domain.valueobject.TenantVO;
import net.civeira.phylax.features.document.snippet.domain.valueobject.UidVO;
import net.civeira.phylax.features.document.snippet.domain.valueobject.VersionVO;

@ApplicationScoped
@RequiredArgsConstructor
@Slf4j
public class SnippetRepository {

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String CODE = "code";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_SNIPPET_CODE = "document_snippet.code";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_SNIPPET_ENABLED = "document_snippet.enabled";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_SNIPPET_SNAKE = "document_snippet";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_SNIPPET_TENANT = "document_snippet.tenant";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_SNIPPET_UID = "document_snippet.uid";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_SNIPPET_VERSION = "document_snippet.version";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String ENABLED = "enabled";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String TENANT = "tenant";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String UID = "uid";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String VERSION = "version";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private final DataSource datasource;

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private final Tracer tracer;

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public long count(SnippetFilter filter) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlSchematicQuery<Long> sq = filteredQuery(template, filter);
      sq.select("count(uid) as uid");
      return sq.query(row -> Optional.of(row.getLong(1))).one().orElse(0l);
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   * @return
   */
  public Snippet create(Snippet entity) {
    return runCreate(entity, null);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   * @param verifier
   * @return
   */
  public Snippet create(Snippet entity, Predicate<Snippet> verifier) {
    return runCreate(entity, verifier);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   */
  public void delete(Snippet entity) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlCommand sq =
          template.createSqlCommand("delete from \"document_snippet\" where \"uid\" = :uid");
      sq.with(UID, SqlParameterValue.of(entity.getUid()));
      int num = sq.execute();
      if (0 == num) {
        throw new IllegalArgumentException("No delete from");
      }
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param uid
   * @param filter
   * @return
   */
  public boolean exists(String uid, Optional<SnippetFilter> filter) {
    return retrieve(uid, filter).isPresent();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param uid
   * @param filter
   * @return
   */
  public boolean existsForUpdate(String uid, Optional<SnippetFilter> filter) {
    return retrieveForUpdate(uid, filter).isPresent();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public Optional<Snippet> find(SnippetFilter filter) {
    SnippetCursor cursor = SnippetCursor.builder().build();
    return new SnippetSlider(runList(filter, cursor), cursor.getLimit().orElse(0), this::runList,
        filter, cursor).one();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public Optional<Snippet> find(final String sql, final Map<String, SqlParameterValue> params) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlQuery<Snippet> createSqlQuery = template.createSqlQuery(sql);
      params.forEach(createSqlQuery::with);
      return createSqlQuery.query(converter()).one();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public Optional<Snippet> findForUpdate(SnippetFilter filter) {
    SnippetCursor cursor = SnippetCursor.builder().build();
    return new SnippetSlider(runListForUpdate(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor).one();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public Optional<Snippet> findForUpdate(final String sql,
      final Map<String, SqlParameterValue> params) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlQuery<Snippet> createSqlQuery = template.createSqlQuery(sql);
      params.forEach(createSqlQuery::with);
      return createSqlQuery.forUpdate().query(converter()).one();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public List<Snippet> list(SnippetFilter filter) {
    SnippetCursor cursor = SnippetCursor.builder().build();
    return new SnippetSlider(runList(filter, cursor), cursor.getLimit().orElse(0), this::runList,
        filter, cursor).all();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public List<Snippet> list(final String sql, final Map<String, SqlParameterValue> params) {
    return list(sql, params, null, false);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @param limit
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public List<Snippet> list(final String sql, final Map<String, SqlParameterValue> params,
      final int limit) {
    return list(sql, params, Integer.valueOf(limit), false);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public List<Snippet> listForUpdate(SnippetFilter filter) {
    SnippetCursor cursor = SnippetCursor.builder().build();
    return new SnippetSlider(runListForUpdate(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor).all();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public List<Snippet> listForUpdate(final String sql,
      final Map<String, SqlParameterValue> params) {
    return list(sql, params, null, true);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @param limit
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public List<Snippet> listForUpdate(final String sql, final Map<String, SqlParameterValue> params,
      final int limit) {
    return list(sql, params, Integer.valueOf(limit), true);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param reference
   * @return
   */
  public Snippet resolve(SnippetRef reference) {
    return reference instanceof Snippet snippet ? snippet
        : retrieve(reference.getUid(), Optional.empty()).orElseThrow(() -> new NotFoundException(
            "Trying to resolve inexistent Snippet: " + reference.getUid()));
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param reference
   * @return
   */
  public Snippet resolveForUpdate(SnippetRef reference) {
    return reference instanceof Snippet snippet ? snippet
        : retrieveForUpdate(reference.getUid(), Optional.empty())
            .orElseThrow(() -> new NotFoundException(
                "Trying to resolve inexistent Snippet: " + reference.getUid()));
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param uid
   * @param filter
   * @return
   */
  public Optional<Snippet> retrieve(String uid, Optional<SnippetFilter> filter) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SnippetFilter readyFilter = filter.map(val -> val.withUid(uid))
          .orElseGet(() -> SnippetFilter.builder().uid(uid).build());
      SqlSchematicQuery<Snippet> sq = filteredQuery(template, readyFilter);
      return sq.query(converter()).one();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param uid
   * @param filter
   * @return
   */
  public Optional<Snippet> retrieveForUpdate(String uid, Optional<SnippetFilter> filter) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SnippetFilter readyFilter = filter.map(val -> val.withUid(uid))
          .orElseGet(() -> SnippetFilter.builder().uid(uid).build());
      SqlSchematicQuery<Snippet> sq = filteredQuery(template, readyFilter);
      return sq.forUpdate().query(converter()).one();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @param cursor
   * @return
   */
  public Slider<Snippet> slide(SnippetFilter filter, SnippetCursor cursor) {
    return new SnippetSlider(runList(filter, cursor), cursor.getLimit().orElse(0), this::runList,
        filter, cursor);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @param cursor
   * @return
   */
  public Slider<Snippet> slideForUpdate(SnippetFilter filter, SnippetCursor cursor) {
    return new SnippetSlider(runListForUpdate(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   * @return
   */
  public Snippet update(Snippet entity) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlCommand sq = template.createSqlCommand(
          "update \"document_snippet\" set  \"code\" = :code, \"tenant\" = :tenant, \"enabled\" = :enabled, \"version\" = \"version\" + 1 where \"uid\" = :uid and \"version\" = :version");
      sq.with(UID, SqlParameterValue.of(entity.getUid()));
      sq.with(CODE, SqlParameterValue.of(entity.getCode()));
      sq.with(TENANT, entity.getTenantUid().map(SqlParameterValue::of)
          .orElseGet(SqlParameterValue::ofNullString));
      sq.with(ENABLED, SqlParameterValue.of(entity.isEnabled()));
      sq.with(VERSION, entity.getVersion().map(SqlParameterValue::of)
          .orElseGet(SqlParameterValue::ofNullInteger));
      int num = sq.execute();
      if (0 == num) {
        throw new OptimistLockException("No delete from");
      }
      return entity.withNextVersion();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sq
   * @param cursor
   */
  private void attachWithOrder(SqlSchematicQuery<Snippet> sq, SnippetCursor cursor) {
    PartialWhere[] offset = new PartialWhere[] {PartialWhere.empty(), PartialWhere.empty()};
    for (SnippetOrder order : cursor.getOrder()) {
      tryToOrderByCodeAsc(sq, offset, cursor, order);
      tryToOrderByCodeDesc(sq, offset, cursor, order);
    }
    Optional<String> sinceUid = cursor.getSinceUid();
    if (sinceUid.isPresent()) {
      offset[0] = PartialWhere.or(offset[0], PartialWhere.and(offset[1],
          PartialWhere.where("uid", SqlOperator.GT, SqlParameterValue.of(sinceUid.get()))));
    }
    sq.where(offset[0]);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @return
   */
  private SqlConverter<Snippet> converter() {
    return row -> {
      try {
        return Optional.of(Snippet.builder().uidValue(UidVO.from(row.getString(UID)))
            .codeValue(CodeVO.from(row.getString(CODE)))
            .tenantValue(TenantVO.fromReference(row.getString(TENANT)))
            .enabledValue(EnabledVO.from(row.getBoolean(ENABLED)))
            .versionValue(VersionVO.from(row.getInt(VERSION))).build());
      } catch (ConstraintException ce) {
        log.error("Unable to map data for {}", row.getString(1), ce);
        return Optional.empty();
      }
    };
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param template
   * @param filter
   * @return
   */
  private <T> SqlSchematicQuery<T> filteredQuery(SqlTemplate template, SnippetFilter filter) {
    SqlSchematicQuery<T> sq = template.createSqlSchematicQuery(DOCUMENT_SNIPPET_SNAKE);
    sq.selectFields(DOCUMENT_SNIPPET_UID, DOCUMENT_SNIPPET_CODE, DOCUMENT_SNIPPET_TENANT,
        DOCUMENT_SNIPPET_ENABLED, DOCUMENT_SNIPPET_VERSION);
    filter.getUid().ifPresent(uid -> sq.where(UID, SqlOperator.EQ, SqlParameterValue.of(uid)));
    if (!filter.getUids().isEmpty()) {
      sq.where(UID, SqlOperator.IN, SqlListParameterValue.strings(filter.getUids()));
    }
    filter.getSearch().ifPresent(
        search -> sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%")));
    filter.getGlobal().filter(Boolean.TRUE::equals)
        .ifPresent(_ -> sq.where(TENANT, SqlOperator.IS_NULL, SqlParameterValue.ofNullString()));
    filter.getCode()
        .ifPresent(codeParam -> sq.where(CODE, SqlOperator.EQ, SqlParameterValue.of(codeParam)));
    filter.getTenant().ifPresent(tenantParam -> sq.where(TENANT, SqlOperator.EQ,
        SqlParameterValue.of(tenantParam.getUid())));
    if (!filter.getTenants().isEmpty()) {
      sq.where(TENANT, SqlOperator.IN, SqlListParameterValue.strings(filter.getTenants()));
    }
    filter.getTenantTenantAccesible()
        .ifPresent(tenantTenantAccesibleParam -> sq.where(DOCUMENT_SNIPPET_TENANT, SqlOperator.EQ,
            SqlParameterValue.of(tenantTenantAccesibleParam)));
    return sq;
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @param limit
   * @param forUpdate
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  private List<Snippet> list(final String sql, final Map<String, SqlParameterValue> params,
      final Integer limit, final boolean forUpdate) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlQuery<Snippet> createSqlQuery = template.createSqlQuery(sql);
      params.forEach(createSqlQuery::with);
      if (forUpdate) {
        createSqlQuery = createSqlQuery.forUpdate();
      }
      SqlResult<Snippet> query = createSqlQuery.query(converter());
      return null == limit ? query.all() : query.limit(limit);
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   * @param verifier
   * @return
   */
  private Snippet runCreate(Snippet entity, Predicate<Snippet> verifier) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlCommand sq = template.createSqlCommand(
          "insert into \"document_snippet\" ( \"uid\", \"code\", \"tenant\", \"enabled\", \"version\") values ( :uid, :code, :tenant, :enabled, :version)");
      sq.with(UID, SqlParameterValue.of(entity.getUid()));
      sq.with(CODE, SqlParameterValue.of(entity.getCode()));
      sq.with(TENANT, entity.getTenantUid().map(SqlParameterValue::of)
          .orElseGet(SqlParameterValue::ofNullString));
      sq.with(ENABLED, SqlParameterValue.of(entity.isEnabled()));
      sq.with(VERSION, entity.getVersion().map(SqlParameterValue::of)
          .orElseGet(SqlParameterValue::ofNullInteger));
      int num = sq.execute();
      if (0 == num) {
        throw new IllegalArgumentException("No insert into");
      }
      return verifier == null ? entity : verified(verifier.test(entity), entity, template);
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @param cursor
   * @return
   */
  private Iterator<Snippet> runList(SnippetFilter filter, SnippetCursor cursor) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlSchematicQuery<Snippet> sq = filteredQuery(template, filter);
      if (null != cursor.getOrder()) {
        attachWithOrder(sq, cursor);
      } else {
        cursor.getSinceUid()
            .ifPresent(since -> sq.where(UID, SqlOperator.GT, SqlParameterValue.of(since)));
      }
      sq.orderAsc("uid");
      return sq.query(converter()).limit(cursor.getLimit()).iterator();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @param cursor
   * @return
   */
  private Iterator<Snippet> runListForUpdate(SnippetFilter filter, SnippetCursor cursor) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlSchematicQuery<Snippet> sq = filteredQuery(template, filter);
      if (null != cursor.getOrder()) {
        attachWithOrder(sq, cursor);
      } else {
        cursor.getSinceUid()
            .ifPresent(since -> sq.where(UID, SqlOperator.GT, SqlParameterValue.of(since)));
      }
      sq.orderAsc("uid");
      return sq.forUpdate().query(converter()).limit(cursor.getLimit()).iterator();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sq
   * @param offset
   * @param cursor
   * @param order
   * @return
   */
  private PartialWhere[] tryToOrderByCodeAsc(SqlSchematicQuery<Snippet> sq, PartialWhere[] offset,
      SnippetCursor cursor, SnippetOrder order) {
    if (order == SnippetOrder.CODE_ASC) {
      sq.addOrderAsc("code");
      Optional<String> sinceCode = cursor.getSinceCode();
      if (sinceCode.isPresent()) {
        String sinceCodeValue = sinceCode.get();
        offset[0] = PartialWhere.or(offset[0], PartialWhere.and(offset[1],
            PartialWhere.where("code", SqlOperator.GT, SqlParameterValue.of(sinceCodeValue))));
        offset[1] = PartialWhere.and(offset[1],
            PartialWhere.where("code", SqlOperator.EQ, SqlParameterValue.of(sinceCodeValue)));
      }
    }
    return offset;
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sq
   * @param offset
   * @param cursor
   * @param order
   * @return
   */
  private PartialWhere[] tryToOrderByCodeDesc(SqlSchematicQuery<Snippet> sq, PartialWhere[] offset,
      SnippetCursor cursor, SnippetOrder order) {
    if (order == SnippetOrder.CODE_DESC) {
      sq.addOrderDesc("code");
      Optional<String> sinceCode = cursor.getSinceCode();
      if (sinceCode.isPresent()) {
        String sinceCodeValue = sinceCode.get();
        offset[0] = PartialWhere.or(offset[0], PartialWhere.and(offset[1],
            PartialWhere.where("code", SqlOperator.GT, SqlParameterValue.of(sinceCodeValue))));
        offset[1] = PartialWhere.and(offset[1],
            PartialWhere.where("code", SqlOperator.EQ, SqlParameterValue.of(sinceCodeValue)));
      }
    }
    return offset;
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param exists
   * @param entity
   * @param template
   * @return
   */
  private Snippet verified(boolean exists, Snippet entity, SqlTemplate template) {
    if (exists) {
      return entity;
    } else {
      template.createSqlCommand("delete from \"document_snippet\" where \"uid\" = :uid")
          .with("uid", SqlParameterValue.of(entity.getUid())).execute();
      throw new NotFoundException("");
    }
  }
}
