package net.civeira.phylax.features.access.relyingparty.application.policy;

import jakarta.enterprise.event.Observes;
import net.civeira.phylax.common.security.Actor;
import net.civeira.phylax.features.access.relyingparty.application.usecase.retrieve.RelyingPartyRetrieveAuthorizationDecision;

public class RetrieveOnlyForRoot {

  /**
   * @autogenerated ConditionPolicyGenerator
   * @param allowDecision
   */
  public void checkAllow(@Observes RelyingPartyRetrieveAuthorizationDecision allowDecision) {
    Actor actor = allowDecision.getActor();
    if (!((actor.hasScope("platform:global_access") && actor.hasRole("admin")))) {
      allowDecision.deny("Retrieve only for root");
    }
  }
}
