package net.civeira.phylax.features.access.user.valueobject;

import java.util.Optional;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.With;
import net.civeira.phylax.common.exception.ConstraintException;
import net.civeira.phylax.common.value.validation.AbstractFailList;
import net.civeira.phylax.common.value.validation.ConstraintFail;
import net.civeira.phylax.common.value.validation.ConstraintFailList;

/**
 * Value Object representing el temporal password de user of user.
 * <p>
 * This class ensures that the temporal password is a {@code String} and encapsulates its validation
 * and formatting logic. It is immutable and compliant with DDD (Domain-Driven Design) principles.
 * </p>
 * <p>
 * Use {@link #from(String)} or {@link #tryFrom(Object)} to safely create instances. Validation
 * errors are reported via {@link ConstraintFailList} or thrown as {@link ConstraintException}.
 * </p>
 */
@Getter
@RequiredArgsConstructor
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class TemporalPasswordVO {

  /**
   * An empty instance
   *
   * @autogenerated ValueObjectGenerator
   * @param temporalPassword
   * @return An empty instance
   */
  public static TemporalPasswordVO from(final Boolean temporalPassword) {
    return tryFrom(temporalPassword);
  }

  /**
   * An empty instance
   *
   * @autogenerated ValueObjectGenerator
   * @return An empty instance
   */
  public static TemporalPasswordVO nullValue() {
    return new TemporalPasswordVO(null);
  }

  /**
   * An empty instance
   *
   * @autogenerated ValueObjectGenerator
   * @param temporalPassword
   * @return An empty instance
   */
  public static TemporalPasswordVO tryFrom(final Object temporalPassword) {
    ConstraintFailList list = new ConstraintFailList();
    TemporalPasswordVO result = tryFrom(temporalPassword, list);
    if (list.hasErrors()) {
      throw new ConstraintException(list);
    }
    return result;
  }

  /**
   * An empty instance
   *
   * @autogenerated ValueObjectGenerator
   * @param temporalPassword temptative value
   * @param fails Error list
   * @return An empty instance
   */
  public static <T extends AbstractFailList> TemporalPasswordVO tryFrom(
      final Object temporalPassword, final T fails) {
    if (null == temporalPassword) {
      return new TemporalPasswordVO(null);
    } else if (temporalPassword instanceof Boolean castedTemporalPassword) {
      return new TemporalPasswordVO(castedTemporalPassword);
    } else {
      fails.add(new ConstraintFail("wrong-type", "temporalPassword", temporalPassword.getClass(),
          "A Boolean type is expected for temporalPassword"));
      return null;
    }
  }

  /**
   * The actual value of the name.
   *
   * @autogenerated ValueObjectGenerator
   */
  private final Boolean value;

  /**
   * @autogenerated ValueObjectGenerator
   * @return
   */
  public Optional<Boolean> getValue() {
    return Optional.ofNullable(value);
  }

  /**
   * the string value wrapped in square brackets.
   *
   * @autogenerated ValueObjectGenerator
   * @return the string value wrapped in square brackets.
   */
  @Override
  public String toString() {
    return "[" + value + "]";
  }
}
