package net.civeira.phylax.features.access.consentpurpose.domain.valueobject;

import java.util.Map;

import lombok.EqualsAndHashCode;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.exception.ConstraintException;
import net.civeira.phylax.common.value.validation.AbstractFailList;
import net.civeira.phylax.common.value.validation.ConstraintFail;
import net.civeira.phylax.common.value.validation.ConstraintFailList;

/**
 * Value Object representing el title de consent purpose of consentPurpose.
 * <p>
 * This class ensures that the title is a non-null {@code String} and encapsulates its validation
 * and formatting logic. It is immutable and compliant with DDD (Domain-Driven Design) principles.
 * </p>
 * <p>
 * Use {@link #from(String)} or {@link #tryFrom(Object)} to safely create instances. Validation
 * errors are reported via {@link ConstraintFailList} or thrown as {@link ConstraintException}.
 * </p>
 */
@RequiredArgsConstructor
@EqualsAndHashCode
public class TitleVO {

  /**
   * Crear an empty instance with no value
   *
   * @autogenerated ValueObjectGenerator
   * @param title
   * @return An empty instance
   */
  public static TitleVO from(final String title) {
    return tryFrom(title);
  }

  /**
   * Crear an empty instance with no value
   *
   * @autogenerated ValueObjectGenerator
   * @param title
   * @return An empty instance
   */
  public static TitleVO tryFrom(final Object title) {
    ConstraintFailList list = new ConstraintFailList();
    TitleVO result = tryFrom(title, list);
    if (list.hasErrors()) {
      throw new ConstraintException("Invalid value for TitleVO.title", list);
    }
    return result;
  }

  /**
   * Crear an empty instance with no value
   *
   * @autogenerated ValueObjectGenerator
   * @param title temptative value
   * @param fails Error list
   * @return An empty instance
   */
  public static <T extends AbstractFailList> TitleVO tryFrom(final Object title, final T fails) {
    if (null == title) {
      fails.add(new ConstraintFail("not-null", "title", null, "Cant be null"));
      return null;
    } else if (title instanceof String castedTitle) {
      return new TitleVO(castedTitle);
    } else {
      fails.add(new ConstraintFail("wrong-type", "title", title.getClass(),
          "A String type is expected for title"));
      return null;
    }
  }

  /**
   * The actual value of the name. * It is guaranteed to be a non-null String after successful
   * value.validation.
   *
   * @autogenerated ValueObjectGenerator
   */
  private final String value;

  /**
   * Get the vo value
   *
   * @autogenerated ValueObjectGenerator
   * @return
   */
  public String getTitle() {
    return value;
  }

  /**
   * @autogenerated ValueObjectGenerator
   * @param map
   */
  public void titleToMap(final Map<String, String> map) {
    if (null != value) {
      map.put("title", String.valueOf(value));
    }
  }

  /**
   * Returns a formatted string representation of the name.
   *
   * @autogenerated ValueObjectGenerator
   * @return the string value wrapped in square brackets.
   */
  @Override
  public String toString() {
    return "[" + value + "]";
  }
}
