package net.civeira.phylax.features.document.templateasset.domain.valueobject;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import net.civeira.phylax.common.exception.ConstraintException;
import net.civeira.phylax.common.value.validation.ConstraintFailList;
import net.civeira.phylax.features.document.template.domain.TemplateReference;

class TemplateVOUnitTest {

  /**
   * @autogenerated ValueObjectGenerator
   */
  @Test
  @DisplayName("Test value object contruction for property template of template asset ")
  void test_template_v_o_builder() {
    ConstraintFailList fails = new ConstraintFailList();
    Assertions.assertEquals("10", TemplateVO.fromReference("10").getTemplateUid(),
        "The builder must store the reference value");
    Assertions.assertEquals("11", TemplateVO.tryFromReference("11").getTemplateUid(),
        "The builder must store the reference value");
    Assertions.assertEquals("12", TemplateVO.tryFromReference("12", fails).getTemplateUid(),
        "The builder must store the reference value");
    Assertions.assertTrue(fails.isEmpty());
    Assertions.assertThrows(ConstraintException.class, () -> TemplateVO.tryFrom(null));
    Assertions.assertEquals(TemplateReference.of("one"),
        TemplateVO.from(TemplateReference.of("one")).getTemplate());
    Assertions.assertThrows(ConstraintException.class, () -> TemplateVO.tryFrom(new Object() {}));
    Assertions.assertEquals("[" + TemplateReference.of("one") + "]",
        TemplateVO.from(TemplateReference.of("one")).toString());
  }
}
