package net.civeira.phylax.features.access.apikeyclient.application.usecase.update;

import java.util.Optional;

import net.civeira.phylax.common.security.AuthorizationDecision;
import net.civeira.phylax.common.security.OperationContext;
import net.civeira.phylax.common.security.Permission;
import net.civeira.phylax.features.access.apikeyclient.domain.ApiKeyClientRef;

public class ApiKeyClientUpdateAuthorizationDecision extends AuthorizationDecision {

  /**
   * @autogenerated UpdateAuthorizationDecisionGenerator
   */
  private final ApiKeyClientRef reference;

  /**
   * @autogenerated UpdateAuthorizationDecisionGenerator
   * @param context
   * @param initial
   */
  public ApiKeyClientUpdateAuthorizationDecision(final OperationContext context,
      final Permission initial) {
    super(context, initial);
    this.reference = null;
  }

  /**
   * @autogenerated UpdateAuthorizationDecisionGenerator
   * @param context
   * @param reference
   * @param initial
   */
  public ApiKeyClientUpdateAuthorizationDecision(final OperationContext context,
      final ApiKeyClientRef reference, final Permission initial) {
    super(context, initial);
    this.reference = reference;
  }

  /**
   * @autogenerated UpdateAuthorizationDecisionGenerator
   * @return
   */
  public String actionName() {
    return "update";
  }

  /**
   * @autogenerated UpdateAuthorizationDecisionGenerator
   * @return
   */
  public Optional<ApiKeyClientRef> getReference() {
    return Optional.ofNullable(reference);
  }

  /**
   * @autogenerated UpdateAuthorizationDecisionGenerator
   * @return
   */
  public String resourceName() {
    return "api-key-client";
  }
}
