package net.civeira.phylax.features.document.snippet.domain;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NonNull;
import lombok.ToString;
import lombok.With;
import lombok.experimental.Delegate;
import net.civeira.phylax.common.exception.ConstraintException;
import net.civeira.phylax.common.value.validation.ConstraintFailList;
import net.civeira.phylax.features.document.snippet.domain.event.SnippetCreateEvent;
import net.civeira.phylax.features.document.snippet.domain.event.SnippetDeleteEvent;
import net.civeira.phylax.features.document.snippet.domain.event.SnippetDisableEvent;
import net.civeira.phylax.features.document.snippet.domain.event.SnippetEnableEvent;
import net.civeira.phylax.features.document.snippet.domain.event.SnippetEvent;
import net.civeira.phylax.features.document.snippet.domain.event.SnippetUpdateEvent;
import net.civeira.phylax.features.document.snippet.domain.valueobject.CodeVO;
import net.civeira.phylax.features.document.snippet.domain.valueobject.EnabledVO;
import net.civeira.phylax.features.document.snippet.domain.valueobject.TenantVO;
import net.civeira.phylax.features.document.snippet.domain.valueobject.UidVO;
import net.civeira.phylax.features.document.snippet.domain.valueobject.VersionVO;

/**
 * snippet
 */
@Builder
@Getter
@With
@ToString
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@EqualsAndHashCode
public class Snippet implements SnippetRef {

  /**
   * Prepare a new snippet with the provided values
   *
   * @autogenerated EntityGenerator
   * @param change A set of values to create a new snippet
   * @throws ConstraintException If there are some constraints fails on the changes.
   * @return A well formed snippet.
   */
  public static Snippet create(final SnippetChangeSet change) throws ConstraintException {
    change.enabled(true);
    Snippet instance = new Snippet(change, Optional.empty());
    instance.addEvent(SnippetCreateEvent.builder().payload(instance).build());
    return instance;
  }

  /**
   * legal.footer, gdpr.notice, company.address...
   *
   * @autogenerated EntityGenerator
   */
  @Delegate
  @NonNull
  private CodeVO codeValue;

  /**
   * El enabled de snippet
   *
   * @autogenerated EntityGenerator
   */
  @Delegate
  @Builder.Default
  private EnabledVO enabledValue = EnabledVO.nullValue();

  /**
   * List of events
   *
   * @autogenerated EntityGenerator
   */
  @Builder.Default
  private List<SnippetEvent> recordedEvents = List.of();

  /**
   * null = global, valor = override por tenant
   *
   * @autogenerated EntityGenerator
   */
  @Delegate
  @Builder.Default
  private TenantVO tenantValue = TenantVO.nullValue();

  /**
   * El uid de snippet
   *
   * @autogenerated EntityGenerator
   */
  @Delegate
  @NonNull
  private UidVO uidValue;

  /**
   * Campo con el número de version de snippet para controlar bloqueos optimistas
   *
   * @autogenerated EntityGenerator
   */
  @Delegate
  @Builder.Default
  private VersionVO versionValue = VersionVO.nullValue();

  /**
   * @autogenerated EntityGenerator
   * @param attribute
   * @param previous
   */
  private Snippet(final SnippetChangeSet attribute, final Optional<Snippet> previous) {
    ConstraintFailList list = new ConstraintFailList();
    this.uidValue = attribute.readUid(previous, list);
    this.codeValue = attribute.readCode(previous, list);
    this.tenantValue = attribute.readTenant(previous, list);
    this.enabledValue = attribute.readEnabled(previous, list);
    this.versionValue = attribute.readVersion(previous, list);
    if (list.hasErrors()) {
      throw new ConstraintException("Invalid values on Snippet", list);
    }
    this.recordedEvents = previous.map(Snippet::getRecordedEvents).orElseGet(List::of);
  }

  /**
   * Apply changes to delete a snippet
   *
   * @autogenerated EntityGenerator
   * @return A instance of snippet ready to be deleted
   */
  public Snippet delete() {
    Snippet instance = new Snippet(new SnippetChangeSet(), Optional.of(this));
    instance.addEvent(SnippetDeleteEvent.builder().payload(instance).build());
    return instance;
  }

  /**
   * Apply disable on snippet.
   *
   * @autogenerated EntityGenerator
   * @return A modified instance of snippet
   */
  public Snippet disable() {
    SnippetChangeSet attr = new SnippetChangeSet();
    attr.enabled(false);
    Snippet instance = new Snippet(attr, Optional.of(this));
    instance.addEvent(SnippetDisableEvent.builder().payload(instance).build());
    return instance;
  }

  /**
   * Apply enable on snippet.
   *
   * @autogenerated EntityGenerator
   * @return A modified instance of snippet
   */
  public Snippet enable() {
    SnippetChangeSet attr = new SnippetChangeSet();
    attr.enabled(true);
    Snippet instance = new Snippet(attr, Optional.of(this));
    instance.addEvent(SnippetEnableEvent.builder().payload(instance).build());
    return instance;
  }

  /**
   * @autogenerated EntityGenerator
   * @return
   */
  public Map<String, String> toMap() {
    Map<String, String> map = new HashMap<>(5);
    uidToMap(map);
    codeToMap(map);
    tenantToMap(map);
    enabledToMap(map);
    versionToMap(map);
    return map;
  }

  /**
   * Modify the values for some of the properties of a snippet
   *
   * @autogenerated EntityGenerator
   * @param change The properties to be modified
   * @throws ConstraintException If there are some constraints fails on the changes.
   * @return A modified instance of snippet
   */
  public Snippet update(final SnippetChangeSet change) throws ConstraintException {
    change.unsetEnabled();
    Snippet instance = new Snippet(change, Optional.of(this));
    instance.addEvent(SnippetUpdateEvent.builder().payload(instance).build());
    return instance;
  }

  /**
   * @autogenerated EntityGenerator
   * @return
   */
  public Snippet withNextVersion() {
    return withVersionValue(VersionVO.from(nextVersion()));
  }

  /**
   * @autogenerated EntityGenerator
   * @param event
   */
  private void addEvent(final SnippetEvent event) {
    List<SnippetEvent> events = new ArrayList<>(this.recordedEvents);
    events.add(event);
    this.recordedEvents = List.copyOf(events);
  }
}
