package net.civeira.phylax.features.document.snippet.application.visibility;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.exception.NotFoundException;
import net.civeira.phylax.common.security.OperationContext;
import net.civeira.phylax.features.access.tenant.application.visibility.TenantsVisibility;
import net.civeira.phylax.features.document.snippet.domain.Snippet;
import net.civeira.phylax.features.document.snippet.domain.SnippetChangeSet;
import net.civeira.phylax.features.document.snippet.domain.SnippetRef;
import net.civeira.phylax.features.document.snippet.domain.gateway.SnippetCacheGateway;
import net.civeira.phylax.features.document.snippet.domain.gateway.SnippetCached;
import net.civeira.phylax.features.document.snippet.domain.gateway.SnippetCursor;
import net.civeira.phylax.features.document.snippet.domain.gateway.SnippetFilter;
import net.civeira.phylax.features.document.snippet.domain.gateway.SnippetReadRepositoryGateway;
import net.civeira.phylax.features.document.snippet.domain.gateway.SnippetWriteRepositoryGateway;
import net.civeira.phylax.features.document.snippet.domain.valueobject.TenantVO;

@ApplicationScoped
@RequiredArgsConstructor
public class SnippetsVisibility {

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final SnippetCacheGateway cache;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<SnippetVisibilityCheck> filterProposalEmitter;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<SnippetFixedPropertiesProposal> fixedFieldsEmitter;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<SnippetAccesibleCheck> guardEmitter;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<SnippetHiddenPropertiesProposal> hiddenFieldsEmitter;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<SnippetEntityEnrichment> presetEmitter;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final SnippetReadRepositoryGateway snippetReadRepositoryGateway;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final SnippetWriteRepositoryGateway snippetWriteRepositoryGateway;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final TenantsVisibility tenantsVisibility;

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param uid
   * @return The input entity with the copy values without hidden
   */
  public boolean checkVisibility(OperationContext prev, String uid) {
    return retrieveVisible(prev, uid).isPresent();
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param uids
   * @return The input entity with the copy values without hidden
   */
  public boolean checkVisibility(OperationContext prev, List<String> uids) {
    return uids.size() == listVisibles(prev, SnippetVisibilityFilter.builder().uids(uids).build(),
        SnippetCursor.builder().build()).size();
  }

  /**
   * Retrieve the list of fields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param source The source OperationContext
   * @param original The source OperationContext
   * @return The input entity with the copy values without hidden
   */
  public SnippetChangeSet copyWithFixed(OperationContext prev, SnippetChangeSet source,
      Snippet original) {
    SnippetChangeSet withReferences = visiblesReferences(prev, source);
    fieldsToFix(prev, original).forEach(withReferences::unset);
    SnippetEntityEnrichment proposal = new SnippetEntityEnrichment(prev, withReferences, original);
    presetEmitter.fire(proposal);
    return proposal.getDto();
  }

  /**
   * Retrieve the list of fields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param source The source OperationContext
   * @return The input entity with the copy values without hidden
   */
  public SnippetChangeSet copyWithFixed(OperationContext prev, SnippetChangeSet source) {
    SnippetChangeSet withReferences = visiblesReferences(prev, source);
    fieldsToFix(prev).forEach(withReferences::unset);
    SnippetEntityEnrichment proposal = new SnippetEntityEnrichment(prev, withReferences);
    presetEmitter.fire(proposal);
    return proposal.getDto();
  }

  /**
   * Retrieve the list of fields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param snippet
   * @return The input dto with hidden values
   */
  public SnippetVisibleProjection copyWithHidden(OperationContext prev, Snippet snippet) {
    SnippetVisibleProjection target = new SnippetVisibleProjection(snippet);
    fieldsToHide(prev, snippet).forEach(target::unset);
    return target;
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param filter The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  public long countVisibles(OperationContext prev, SnippetVisibilityFilter filter) {
    return snippetReadRepositoryGateway.count(applyPreVisibilityFilter(prev, filter));
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @return initialsFixFields
   */
  public Set<String> fieldsToFix(OperationContext prev) {
    Set<String> fields = new HashSet<>(fieldsToHide(prev));
    SnippetFixedPropertiesProposal proposal = new SnippetFixedPropertiesProposal(prev, fields);
    fixedFieldsEmitter.fire(proposal);
    return proposal.getFields();
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param snippet
   * @return initialsFixFields
   */
  public Set<String> fieldsToFix(OperationContext prev, SnippetRef snippet) {
    Set<String> fields = new HashSet<>(fieldsToHide(prev, snippet));
    SnippetFixedPropertiesProposal proposal =
        new SnippetFixedPropertiesProposal(prev, snippet, fields);
    fixedFieldsEmitter.fire(proposal);
    return proposal.getFields();
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @return initialsHideFields
   */
  public Set<String> fieldsToHide(OperationContext prev) {
    Set<String> fields = new HashSet<>();
    SnippetHiddenPropertiesProposal proposal = new SnippetHiddenPropertiesProposal(prev, fields);
    hiddenFieldsEmitter.fire(proposal);
    return proposal.getFields();
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param snippet
   * @return initialsHideFields
   */
  public Set<String> fieldsToHide(OperationContext prev, SnippetRef snippet) {
    Set<String> fields = new HashSet<>(fieldsToHide(prev));
    SnippetHiddenPropertiesProposal proposal =
        new SnippetHiddenPropertiesProposal(prev, snippet, fields);
    hiddenFieldsEmitter.fire(proposal);
    return proposal.getFields();
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  public SnippetCached listCachedVisibles(OperationContext prev, SnippetVisibilityFilter filter,
      SnippetCursor cursor) {
    SnippetFilter visibleFilter = applyPreVisibilityFilter(prev, filter);
    return cache.retrieve(visibleFilter, cursor)
        .orElseGet(() -> cache.store(visibleFilter, cursor, listVisibles(prev, filter, cursor)));
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  public List<Snippet> listVisibles(OperationContext prev, SnippetVisibilityFilter filter,
      SnippetCursor cursor) {
    return queryItems(prev, applyPreVisibilityFilter(prev, filter), cursor);
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  public List<Snippet> listVisiblesForUpdate(OperationContext prev, SnippetVisibilityFilter filter,
      SnippetCursor cursor) {
    return queryItemsForUpdate(prev, applyPreVisibilityFilter(prev, filter), cursor);
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param uid
   * @return The input entity with the copy values without hidden
   */
  public SnippetCached retrieveCachedVisible(OperationContext prev, String uid) {
    SnippetCursor cursor = SnippetCursor.builder().limit(1).build();
    SnippetFilter visibleFilter =
        applyPreVisibilityFilter(prev, SnippetVisibilityFilter.builder().uid(uid).build());
    return cache.retrieve(visibleFilter, cursor).orElseGet(() -> {
      List<Snippet> list =
          retrieveVisible(prev, uid).<List<Snippet>>map(List::of).orElseGet(List::of);
      return cache.store(visibleFilter, cursor, list);
    });
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param uid
   * @return The input entity with the copy values without hidden
   */
  public Optional<Snippet> retrieveVisible(OperationContext prev, String uid) {
    SnippetFilter filter =
        applyPreVisibilityFilter(prev, SnippetVisibilityFilter.builder().uid(uid).build());
    return queryItem(prev, uid, filter);
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param uid
   * @return The input entity with the copy values without hidden
   */
  public Optional<Snippet> retrieveVisibleForUpdate(OperationContext prev, String uid) {
    SnippetFilter filter =
        applyPreVisibilityFilter(prev, SnippetVisibilityFilter.builder().uid(uid).build());
    return queryItemForUpdate(prev, uid, filter);
  }

  /**
   * Retrieve the list of fields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param filter The filter to retrieve values
   * @return The self filter modified with the prepared values.
   */
  private SnippetFilter applyPreVisibilityFilter(OperationContext prev,
      SnippetVisibilityFilter filter) {
    SnippetVisibilityCheck proposal = new SnippetVisibilityCheck(prev, filter);
    filterProposalEmitter.fire(proposal);
    SnippetVisibilityFilter modified = proposal.getFilter();
    return SnippetFilter.builder().uid(modified.getUid().orElse(null))
        .uids(modified.getUids().stream().toList()).search(modified.getSearch().orElse(null))
        .global(modified.getGlobal().orElse(null)).code(modified.getCode().orElse(null))
        .tenant(modified.getTenant().orElse(null)).tenants(modified.getTenants())
        .tenantTenantAccesible(modified.getTenantTenantAccesible().orElse(null)).build();
  }

  /**
   * Retrieve the list of fields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param snippetRef The source OperationContext
   * @return The input dto with hidden values
   */
  private boolean evaluatePostVisibility(OperationContext prev, Snippet snippetRef) {
    SnippetAccesibleCheck proposal = new SnippetAccesibleCheck(prev, snippetRef);
    guardEmitter.fire(proposal);
    return Boolean.TRUE.equals(proposal.getVisible());
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param uid
   * @param filter The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  private Optional<Snippet> queryItem(OperationContext prev, String uid, SnippetFilter filter) {
    return snippetReadRepositoryGateway.retrieve(uid, Optional.of(filter))
        .filter(values -> evaluatePostVisibility(prev, values));
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param uid
   * @param filter The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  private Optional<Snippet> queryItemForUpdate(OperationContext prev, String uid,
      SnippetFilter filter) {
    return snippetWriteRepositoryGateway.retrieveForUpdate(uid, Optional.of(filter))
        .filter(values -> evaluatePostVisibility(prev, values));
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  private List<Snippet> queryItems(OperationContext prev, SnippetFilter filter,
      SnippetCursor cursor) {
    List<Snippet> list = new ArrayList<>();
    Iterator<Snippet> slide = snippetReadRepositoryGateway.slide(filter, cursor)
        .slide(values -> evaluatePostVisibility(prev, values));
    while (slide.hasNext()) {
      list.add(slide.next());
    }
    return list;
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  private List<Snippet> queryItemsForUpdate(OperationContext prev, SnippetFilter filter,
      SnippetCursor cursor) {
    List<Snippet> list = new ArrayList<>();
    Iterator<Snippet> slide = snippetWriteRepositoryGateway.slideForUpdate(filter, cursor)
        .slide(values -> evaluatePostVisibility(prev, values));
    while (slide.hasNext()) {
      list.add(slide.next());
    }
    return list;
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source OperationContext
   * @param source The source OperationContext
   * @return The input entity with the copy values without hidden
   */
  private SnippetChangeSet visiblesReferences(OperationContext prev, SnippetChangeSet source) {
    source.getTenantValue().flatMap(TenantVO::getTenantUid).ifPresent(ref -> {
      boolean visible = tenantsVisibility.checkVisibility(prev, ref);
      if (!visible) {
        throw new NotFoundException("No tenant - " + ref);
      }
    });
    return source;
  }
}
