package net.civeira.phylax.features.access.tenantloginprovider.application.policy;

import jakarta.enterprise.event.Observes;
import net.civeira.phylax.common.security.Actor;
import net.civeira.phylax.features.access.tenantloginprovider.application.visibility.TenantLoginProviderFixedPropertiesProposal;

public class FixTenantExcludingRoot {

  /**
   * Constant for platformAdmin field
   *
   * @autogenerated VisibilityPolicyGenerator
   */
  private static final String ROL_PLATFORM_ADMIN = "platform:admin";

  /**
   * @autogenerated VisibilityPolicyGenerator
   * @param fixed
   */
  public void fixedFields(@Observes TenantLoginProviderFixedPropertiesProposal fixed) {
    Actor actor = fixed.getActor();
    if (!actor.hasRole(ROL_PLATFORM_ADMIN)) {
      fixed.add("tenant");
    }
  }
}
