quarkus:
  mailer:
    mock: false
    thread-pool: ${threads.mailer:1}
    auth-methods: ${mailer.auth.methods:PLAIN LOGIN}
    host: ${mailer.host}
    port: ${mailer.port}
    start-tls: ${mailer.start.tls}
    from: ${mailer.from.email}
    username: ${mailer.username} 
    password: ${mailer.password}
