quarkus:
  log:
    console:
      enabled: true
      level: INFO
      json:
        enabled: false
      format: "%d{HH:mm:ss} %-5p [%c] %s%n"
    file:
      enabled: true
      path: logs/log.jsonl
      level: INFO
      json:
        enabled: true
      rotation:
        max-file-size: 30M
        max-backup-index: 5

  otel:
    enabled: true
    file:
      enabled: true
      path: logs/traces.jsonl
      rotation:
        max-file-size: 30M
        max-backup-index: 5