package net.civeira.phylax.features.document.snippetasset.application.usecase.enable;

import java.time.Duration;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.batch.BatchIdentificator;
import net.civeira.phylax.common.batch.BatchProgress;
import net.civeira.phylax.common.batch.BatchService;
import net.civeira.phylax.common.batch.ExecutorByDeferSteps;
import net.civeira.phylax.common.batch.ExecutorPlan;
import net.civeira.phylax.common.exception.NotAllowedException;
import net.civeira.phylax.common.exception.NotFoundException;
import net.civeira.phylax.common.security.OperationContext;
import net.civeira.phylax.common.security.Permission;
import net.civeira.phylax.common.telemetry.Observed;
import net.civeira.phylax.common.telemetry.Trace;
import net.civeira.phylax.features.document.snippetasset.application.visibility.SnippetAssetVisibilityFilter;
import net.civeira.phylax.features.document.snippetasset.application.visibility.SnippetAssetsVisibility;
import net.civeira.phylax.features.document.snippetasset.domain.SnippetAsset;
import net.civeira.phylax.features.document.snippetasset.domain.SnippetAssetRef;
import net.civeira.phylax.features.document.snippetasset.domain.gateway.SnippetAssetAuditGateway;
import net.civeira.phylax.features.document.snippetasset.domain.gateway.SnippetAssetCacheGateway;
import net.civeira.phylax.features.document.snippetasset.domain.gateway.SnippetAssetWriteRepositoryGateway;

@ApplicationScoped
@RequiredArgsConstructor
public class SnippetAssetEnableUsecase {

  /**
   * Service to register audit events
   *
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final SnippetAssetAuditGateway audit;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final BatchService batch;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final SnippetAssetCacheGateway cache;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final Event<SnippetAssetEnableAuthorizationDecision> execAllowEmitter;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final Event<SnippetAssetEnableCheck> execProposalEmitter;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final SnippetAssetWriteRepositoryGateway gateway;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final SnippetAssetsVisibility visibility;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param reference
   * @return
   */
  @Observed("enable an entity of snippet asset")
  public Permission allow(final OperationContext context, final SnippetAssetRef reference) {
    Trace.setAttribute("ref", reference.getUid());
    Permission response = checkPermission(context, reference);
    Trace.setAttribute("allowed", response.isAllowed());
    return response;
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @return
   */
  @Observed("enable an entity of snippet asset")
  public Permission allow(final OperationContext context) {
    Permission response = checkPermission(context);
    Trace.setAttribute("allowed", response.isAllowed());
    return response;
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param filter
   * @return The slide with some values
   */
  @Observed("enable a set of entity of snippet asset")
  public BatchIdentificator batchEnable(final OperationContext context,
      final SnippetAssetEnableFilter filter) {
    Permission detail = checkPermission(context);
    if (!detail.isAllowed()) {
      Trace.addEvent(
          "The policies for snippet asset dont allow to enable: " + detail.getDescription());
      throw new NotAllowedException(detail.getDescription());
    }
    SnippetAssetVisibilityFilter filterWithVisibility = SnippetAssetVisibilityFilter.builder()
        .uid(filter.getUid().orElse(null)).uids(filter.getUids().stream().toList())
        .search(filter.getSearch().orElse(null)).code(filter.getCode().orElse(null))
        .snippet(filter.getSnippet().orElse(null)).snippets(filter.getSnippets())
        .snippetTenantTenantAccesible(filter.getSnippetTenantTenantAccesible().orElse(null))
        .build();
    SnippetAssetEnableAllInBatchCommand command =
        new SnippetAssetEnableAllInBatchCommand(context, filterWithVisibility);
    return batch.start(context.getActor().getName().orElse("-"), Duration.ofHours(6), ExecutorPlan
        .<SnippetAssetEnableAllInBatchCommand>builder().params(command).name("enable-snippet-asset")
        .executor(
            ExecutorByDeferSteps.<SnippetAsset, SnippetAsset, SnippetAssetEnableAllInBatchCommand, SnippetAssetEnablesInBatchExecutor.SnippetAssetPaginableBatch>builder()
                .initializer(SnippetAssetEnablesInBatchExecutor.class)
                .counter(SnippetAssetEnablesInBatchExecutor.class)
                .descriptor(SnippetAssetEnablesInBatchExecutor.class)
                .reader(SnippetAssetEnablesInBatchExecutor.class)
                .processor(SnippetAssetEnablesInBatchExecutor.class)
                .writer(SnippetAssetEnablesInBatchExecutor.class)
                .finalizer(SnippetAssetEnablesInBatchExecutor.class).build())
        .build());
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param query a filter to retrieve only matching values
   * @return The slide with some values
   */
  public BatchProgress checkProgress(final OperationContext context,
      final SnippetAssetEnableStatus query) {
    return context.getActor().getName()
        .flatMap(name -> batch.retrieve(query.getTaskId(), context.getSource().getLocale(), name))
        .orElseThrow(() -> new NotFoundException());
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param reference
   * @return The slide with some values
   */
  @Observed("enable an entity of snippet asset")
  public SnippetAssetEnableProjection enable(final OperationContext context,
      final SnippetAssetRef reference) {
    Trace.setAttribute("ref", reference.getUid());
    Permission detail = checkPermission(context, reference);
    if (!detail.isAllowed()) {
      Trace.addEvent(
          "The policies for snippet asset dont allow to enable: " + detail.getDescription());
      throw new NotAllowedException(detail.getDescription());
    }
    SnippetAsset original = visibility.retrieveVisibleForUpdate(context, reference.getUid())
        .orElseThrow(() -> new NotFoundException(""));
    SnippetAsset saved = doEnable(context, original);
    cacheUpdate(saved);
    // Register audit operation
    audit.updated("enable", saved, original, context);
    return SnippetAssetEnableProjection.from(visibility.copyWithHidden(context, saved));
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param saved
   */
  void cacheUpdate(final SnippetAsset saved) {
    cache.update(saved);
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param reference
   * @return
   */
  Permission checkPermission(final OperationContext context, final SnippetAssetRef reference) {
    SnippetAssetEnableAuthorizationDecision proposal = new SnippetAssetEnableAuthorizationDecision(
        context, reference, Permission.allow("Allow to enable by default"));
    execAllowEmitter.fire(proposal);
    return proposal.getPermission();
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @return
   */
  Permission checkPermission(final OperationContext context) {
    SnippetAssetEnableAuthorizationDecision proposal = new SnippetAssetEnableAuthorizationDecision(
        context, Permission.allow("Allow to enable by default"));
    execAllowEmitter.fire(proposal);
    return proposal.getPermission();
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param original
   * @return
   */
  SnippetAsset doEnable(final OperationContext context, final SnippetAsset original) {
    SnippetAssetEnableCheck proposal = new SnippetAssetEnableCheck(context, original);
    execProposalEmitter.fire(proposal);
    SnippetAsset result = original.enable();
    SnippetAsset saved = gateway.update(original, result);
    return saved;
  }
}
