package net.civeira.phylax.features.document.snippetasset.application.usecase.enable;

import java.util.List;
import java.util.Optional;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.With;
import net.civeira.phylax.features.document.snippet.domain.SnippetRef;

@Data
@Builder(toBuilder = true)
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class SnippetAssetEnableFilter {

  /**
   * @autogenerated ActionFilterGenerator
   */
  private String code;

  /**
   * The filter to select the results to retrieve
   *
   * @autogenerated ActionFilterGenerator
   */
  private String search;

  /**
   * @autogenerated ActionFilterGenerator
   */
  private SnippetRef snippet;

  /**
   * @autogenerated ActionFilterGenerator
   */
  private String snippetTenantAccesible;

  /**
   * @autogenerated ActionFilterGenerator
   */
  private List<String> snippets;

  /**
   * The filter to select the results to retrieve
   *
   * @autogenerated ActionFilterGenerator
   */
  private String uid;

  /**
   * The filter to select the results to retrieve
   *
   * @autogenerated ActionFilterGenerator
   */
  private List<String> uids;

  /**
   * @autogenerated ActionFilterGenerator
   * @return
   */
  public Optional<String> getCode() {
    return Optional.ofNullable(code);
  }

  /**
   * @autogenerated ActionFilterGenerator
   * @return
   */
  public Optional<String> getSearch() {
    return Optional.ofNullable(search);
  }

  /**
   * @autogenerated ActionFilterGenerator
   * @return
   */
  public Optional<SnippetRef> getSnippet() {
    return Optional.ofNullable(snippet);
  }

  /**
   * @autogenerated ActionFilterGenerator
   * @return
   */
  public Optional<String> getSnippetTenantAccesible() {
    return Optional.ofNullable(snippetTenantAccesible);
  }

  /**
   * @autogenerated ActionFilterGenerator
   * @return
   */
  public List<String> getSnippets() {
    return null == snippets ? List.of() : List.copyOf(snippets);
  }

  /**
   * @autogenerated ActionFilterGenerator
   * @return
   */
  public Optional<String> getUid() {
    return Optional.ofNullable(uid);
  }

  /**
   * @autogenerated ActionFilterGenerator
   * @return
   */
  public List<String> getUids() {
    return null == uids ? List.of() : List.copyOf(uids);
  }
}
