package net.civeira.phylax.features.access.securityscope.application.usecase.update;

import java.util.Optional;
import java.util.function.UnaryOperator;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.With;
import net.civeira.phylax.common.security.Interaction;
import net.civeira.phylax.features.access.securityscope.domain.SecurityScopeRef;

@Data
@Builder(toBuilder = true)
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class SecurityScopeUpdateEnrich {

  /**
   * @autogenerated UpdateEnrichGenerator
   */
  @NonNull
  private final Interaction interaction;

  /**
   * @autogenerated UpdateEnrichGenerator
   */
  private final SecurityScopeRef reference;

  /**
   * @autogenerated UpdateEnrichGenerator
   */
  @NonNull
  private SecurityScopeUpdateInput input;

  /**
   * @autogenerated UpdateEnrichGenerator
   * @return
   */
  public Optional<SecurityScopeRef> getReference() {
    return Optional.ofNullable(reference);
  }

  /**
   * @autogenerated UpdateEnrichGenerator
   * @param mapper
   */
  public void map(UnaryOperator<SecurityScopeUpdateInput> mapper) {
    input = mapper.apply(input);
  }
}
