package net.civeira.phylax.features.access.relyingparty.infrastructure.driven;

import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.SpanContext;
import jakarta.enterprise.context.ApplicationScoped;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.infrastructure.audit.AuditEvent;
import net.civeira.phylax.common.infrastructure.audit.AuditWriteService;
import net.civeira.phylax.common.security.OperationContext;
import net.civeira.phylax.features.access.relyingparty.domain.RelyingParty;
import net.civeira.phylax.features.access.relyingparty.domain.gateway.RelyingPartyAuditGateway;

@ApplicationScoped
@RequiredArgsConstructor
public class RelyingPartyAuditAdapter implements RelyingPartyAuditGateway {

  /**
   * @autogenerated AuditAdapterGenerator
   */
  private final AuditWriteService writer;

  /**
   * @autogenerated AuditAdapterGenerator
   * @param usecase The usecase responsible to the action
   * @param relyingParty
   * @param context The interaction
   */
  @Override
  public void created(final String usecase, final RelyingParty relyingParty,
      final OperationContext context) {
    writer.record("_audit_access_relying_party",
        AuditEvent.builder().operation("create").usecase(usecase).traceId(currentTraceId())
            .spanId(currentSpanId()).entityType("relyingParty").entityId(relyingParty.getUid())
            .newValue(relyingParty.toMap()).performedBy(context.getActor().getName())
            .tenant(context.getActor().getTenant()).timestamp(context.getSource().getStartTime())
            .sourceRequest(context.getSource().getRequestId())
            .remoteAddress(context.getSource().getIp())
            .remoteApplication(context.getSource().getApplication())
            .remoteDevice(context.getSource().getDevice()).build());
  }

  /**
   * @autogenerated AuditAdapterGenerator
   * @param usecase The usecase responsible to the action
   * @param relyingParty
   * @param context The interaction
   */
  @Override
  public void deleted(final String usecase, final RelyingParty relyingParty,
      final OperationContext context) {
    writer.record("_audit_access_relying_party",
        AuditEvent.builder().operation("delete").usecase(usecase).traceId(currentTraceId())
            .spanId(currentSpanId()).entityType("relyingParty").entityId(relyingParty.getUid())
            .oldValue(relyingParty.toMap()).performedBy(context.getActor().getName())
            .tenant(context.getActor().getTenant()).timestamp(context.getSource().getStartTime())
            .sourceRequest(context.getSource().getRequestId())
            .remoteAddress(context.getSource().getIp())
            .remoteApplication(context.getSource().getApplication())
            .remoteDevice(context.getSource().getDevice()).build());
  }

  /**
   * @autogenerated AuditAdapterGenerator
   * @param usecase The usecase responsible to the action
   * @param relyingParty
   * @param relyingPartyOriginal
   * @param context The interaction
   */
  @Override
  public void updated(final String usecase, final RelyingParty relyingParty,
      final RelyingParty relyingPartyOriginal, final OperationContext context) {
    writer.record("_audit_access_relying_party",
        AuditEvent.builder().operation("update").usecase(usecase).traceId(currentTraceId())
            .spanId(currentSpanId()).entityType("relyingParty").entityId(relyingParty.getUid())
            .newValue(relyingParty.toMap()).oldValue(relyingPartyOriginal.toMap())
            .performedBy(context.getActor().getName()).tenant(context.getActor().getTenant())
            .timestamp(context.getSource().getStartTime())
            .sourceRequest(context.getSource().getRequestId())
            .remoteAddress(context.getSource().getIp())
            .remoteApplication(context.getSource().getApplication())
            .remoteDevice(context.getSource().getDevice()).build());
  }

  /**
   * @autogenerated AuditAdapterGenerator
   * @return
   */
  private String currentSpanId() {
    String value = "<<no-span>>";
    Span current = Span.current();
    if (null != current) {
      SpanContext spanContext = current.getSpanContext();
      if (null != spanContext) {
        value = spanContext.getSpanId();
      }
    }
    return value;
  }

  /**
   * @autogenerated AuditAdapterGenerator
   * @return
   */
  private String currentTraceId() {
    String value = "<<no-trace>>";
    Span current = Span.current();
    if (null != current) {
      SpanContext spanContext = current.getSpanContext();
      if (null != spanContext) {
        value = spanContext.getTraceId();
      }
    }
    return value;
  }
}
