package net.civeira.phylax.features.access.tenant.infrastructure.bootstrap;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.function.UnaryOperator;

import jakarta.enterprise.context.ApplicationScoped;
import net.civeira.phylax.common.infrastructure.projection.ExecutionAggregation;
import net.civeira.phylax.common.infrastructure.projection.ExecutionNode;
import net.civeira.phylax.common.infrastructure.projection.ParamKind;
import net.civeira.phylax.common.infrastructure.projection.ProjectionDescriptor;
import net.civeira.phylax.common.infrastructure.projection.RelationshipDefinition;
import net.civeira.phylax.features.access.tenantconfig.infrastructure.bootstrap.TenantConfigProjectionDescriptor.TenantConfigExecutionPlanner;
import net.civeira.phylax.features.access.tenantloginprovider.infrastructure.bootstrap.TenantLoginProviderProjectionDescriptor.TenantLoginProviderExecutionPlanner;
import net.civeira.phylax.features.access.tenanttermsofuse.infrastructure.bootstrap.TenantTermsOfUseProjectionDescriptor.TenantTermsOfUseExecutionPlanner;
import net.civeira.phylax.features.access.user.infrastructure.bootstrap.UserProjectionDescriptor.UserExecutionPlanner;
import net.civeira.phylax.features.document.template.infrastructure.bootstrap.TemplateProjectionDescriptor.TemplateExecutionPlanner;
import net.civeira.phylax.features.document.templateasset.infrastructure.bootstrap.TemplateAssetProjectionDescriptor.TemplateAssetExecutionPlanner;
import net.civeira.phylax.features.document.templatesnippet.infrastructure.bootstrap.TemplateSnippetProjectionDescriptor.TemplateSnippetExecutionPlanner;
import net.civeira.phylax.features.document.templatevariable.infrastructure.bootstrap.TemplateVariableProjectionDescriptor.TemplateVariableExecutionPlanner;
import net.civeira.phylax.features.document.theme.infrastructure.bootstrap.ThemeProjectionDescriptor.ThemeExecutionPlanner;
import net.civeira.phylax.features.notification.message.infrastructure.bootstrap.MessageProjectionDescriptor.MessageExecutionPlanner;
import net.civeira.phylax.features.notification.smtpoutboundconfig.infrastructure.bootstrap.SmtpOutboundConfigProjectionDescriptor.SmtpOutboundConfigExecutionPlanner;

@ApplicationScoped
public class TenantProjectionDescriptor implements ProjectionDescriptor {

  /**
   * @autogenerated ProjectionDescriptorGeneratorGenerator
   */
  public static class TenantExecutionPlanner {

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     */
    private final List<ExecutionAggregation> aggregation = new ArrayList<>();

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     */
    String prefix;

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     */
    public TenantExecutionPlanner() {
      this.prefix = "";
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param prefix
     */
    public TenantExecutionPlanner(final String prefix) {
      this.prefix = prefix + ".";
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @return
     */
    public List<ExecutionAggregation> build() {
      return aggregation;
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @return
     */
    public TenantExecutionPlanner withDomain() {
      return withDomain(prefix + "domain");
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @return
     */
    public TenantExecutionPlanner withDomain(final String alias) {
      aggregation.add(
          ExecutionAggregation.builder().name("domain").alias(alias).selection(List.of()).build());
      return this;
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @return
     */
    public TenantExecutionPlanner withEnabled() {
      return withEnabled(prefix + "enabled");
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @return
     */
    public TenantExecutionPlanner withEnabled(final String alias) {
      aggregation.add(
          ExecutionAggregation.builder().name("enabled").alias(alias).selection(List.of()).build());
      return this;
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @return
     */
    public TenantExecutionPlanner withMarkForDelete() {
      return withMarkForDelete(prefix + "markForDelete");
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @return
     */
    public TenantExecutionPlanner withMarkForDelete(final String alias) {
      aggregation.add(ExecutionAggregation.builder().name("markForDelete").alias(alias)
          .selection(List.of()).build());
      return this;
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @return
     */
    public TenantExecutionPlanner withMarkForDeleteTime() {
      return withMarkForDeleteTime(prefix + "markForDeleteTime");
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @return
     */
    public TenantExecutionPlanner withMarkForDeleteTime(final String alias) {
      aggregation.add(ExecutionAggregation.builder().name("markForDeleteTime").alias(alias)
          .selection(List.of()).build());
      return this;
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @return
     */
    public TenantExecutionPlanner withMessage() {
      return withMessage(prefix + "message", null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @return
     */
    public TenantExecutionPlanner withMessage(final String alias) {
      return withMessage(alias, null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withMessage(
        final UnaryOperator<MessageExecutionPlanner> callback) {
      return withMessage(prefix + "message", callback);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withMessage(final String alias,
        final UnaryOperator<MessageExecutionPlanner> callback) {
      aggregation
          .add(ExecutionAggregation.builder().name("message").alias(alias)
              .selection(null != callback
                  ? callback.apply(new MessageExecutionPlanner(prefix + alias)).build()
                  : List.of())
              .build());
      return this;
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @return
     */
    public TenantExecutionPlanner withName() {
      return withName(prefix + "name");
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @return
     */
    public TenantExecutionPlanner withName(final String alias) {
      aggregation.add(
          ExecutionAggregation.builder().name("name").alias(alias).selection(List.of()).build());
      return this;
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @return
     */
    public TenantExecutionPlanner withRoot() {
      return withRoot(prefix + "root");
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @return
     */
    public TenantExecutionPlanner withRoot(final String alias) {
      aggregation.add(
          ExecutionAggregation.builder().name("root").alias(alias).selection(List.of()).build());
      return this;
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @return
     */
    public TenantExecutionPlanner withSmtpOutboundConfig() {
      return withSmtpOutboundConfig(prefix + "smtpOutboundConfig", null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @return
     */
    public TenantExecutionPlanner withSmtpOutboundConfig(final String alias) {
      return withSmtpOutboundConfig(alias, null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withSmtpOutboundConfig(
        final UnaryOperator<SmtpOutboundConfigExecutionPlanner> callback) {
      return withSmtpOutboundConfig(prefix + "smtpOutboundConfig", callback);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withSmtpOutboundConfig(final String alias,
        final UnaryOperator<SmtpOutboundConfigExecutionPlanner> callback) {
      aggregation.add(ExecutionAggregation.builder().name("smtpOutboundConfig").alias(alias)
          .selection(null != callback
              ? callback.apply(new SmtpOutboundConfigExecutionPlanner(prefix + alias)).build()
              : List.of())
          .build());
      return this;
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @return
     */
    public TenantExecutionPlanner withTemplate() {
      return withTemplate(prefix + "template", null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @return
     */
    public TenantExecutionPlanner withTemplate(final String alias) {
      return withTemplate(alias, null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withTemplate(
        final UnaryOperator<TemplateExecutionPlanner> callback) {
      return withTemplate(prefix + "template", callback);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withTemplate(final String alias,
        final UnaryOperator<TemplateExecutionPlanner> callback) {
      aggregation.add(ExecutionAggregation.builder().name("template").alias(alias)
          .selection(null != callback
              ? callback.apply(new TemplateExecutionPlanner(prefix + alias)).build()
              : List.of())
          .build());
      return this;
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @return
     */
    public TenantExecutionPlanner withTemplateAsset() {
      return withTemplateAsset(prefix + "templateAsset", null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @return
     */
    public TenantExecutionPlanner withTemplateAsset(final String alias) {
      return withTemplateAsset(alias, null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withTemplateAsset(
        final UnaryOperator<TemplateAssetExecutionPlanner> callback) {
      return withTemplateAsset(prefix + "templateAsset", callback);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withTemplateAsset(final String alias,
        final UnaryOperator<TemplateAssetExecutionPlanner> callback) {
      aggregation.add(ExecutionAggregation.builder().name("templateAsset").alias(alias)
          .selection(null != callback
              ? callback.apply(new TemplateAssetExecutionPlanner(prefix + alias)).build()
              : List.of())
          .build());
      return this;
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @return
     */
    public TenantExecutionPlanner withTemplateSnippet() {
      return withTemplateSnippet(prefix + "templateSnippet", null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @return
     */
    public TenantExecutionPlanner withTemplateSnippet(final String alias) {
      return withTemplateSnippet(alias, null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withTemplateSnippet(
        final UnaryOperator<TemplateSnippetExecutionPlanner> callback) {
      return withTemplateSnippet(prefix + "templateSnippet", callback);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withTemplateSnippet(final String alias,
        final UnaryOperator<TemplateSnippetExecutionPlanner> callback) {
      aggregation.add(ExecutionAggregation.builder().name("templateSnippet").alias(alias)
          .selection(null != callback
              ? callback.apply(new TemplateSnippetExecutionPlanner(prefix + alias)).build()
              : List.of())
          .build());
      return this;
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @return
     */
    public TenantExecutionPlanner withTemplateVariable() {
      return withTemplateVariable(prefix + "templateVariable", null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @return
     */
    public TenantExecutionPlanner withTemplateVariable(final String alias) {
      return withTemplateVariable(alias, null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withTemplateVariable(
        final UnaryOperator<TemplateVariableExecutionPlanner> callback) {
      return withTemplateVariable(prefix + "templateVariable", callback);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withTemplateVariable(final String alias,
        final UnaryOperator<TemplateVariableExecutionPlanner> callback) {
      aggregation.add(ExecutionAggregation.builder().name("templateVariable").alias(alias)
          .selection(null != callback
              ? callback.apply(new TemplateVariableExecutionPlanner(prefix + alias)).build()
              : List.of())
          .build());
      return this;
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @return
     */
    public TenantExecutionPlanner withTenantConfig() {
      return withTenantConfig(prefix + "tenantConfig", null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @return
     */
    public TenantExecutionPlanner withTenantConfig(final String alias) {
      return withTenantConfig(alias, null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withTenantConfig(
        final UnaryOperator<TenantConfigExecutionPlanner> callback) {
      return withTenantConfig(prefix + "tenantConfig", callback);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withTenantConfig(final String alias,
        final UnaryOperator<TenantConfigExecutionPlanner> callback) {
      aggregation.add(ExecutionAggregation.builder().name("tenantConfig").alias(alias)
          .selection(null != callback
              ? callback.apply(new TenantConfigExecutionPlanner(prefix + alias)).build()
              : List.of())
          .build());
      return this;
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @return
     */
    public TenantExecutionPlanner withTenantLoginProvider() {
      return withTenantLoginProvider(prefix + "tenantLoginProvider", null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @return
     */
    public TenantExecutionPlanner withTenantLoginProvider(final String alias) {
      return withTenantLoginProvider(alias, null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withTenantLoginProvider(
        final UnaryOperator<TenantLoginProviderExecutionPlanner> callback) {
      return withTenantLoginProvider(prefix + "tenantLoginProvider", callback);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withTenantLoginProvider(final String alias,
        final UnaryOperator<TenantLoginProviderExecutionPlanner> callback) {
      aggregation.add(ExecutionAggregation.builder().name("tenantLoginProvider").alias(alias)
          .selection(null != callback
              ? callback.apply(new TenantLoginProviderExecutionPlanner(prefix + alias)).build()
              : List.of())
          .build());
      return this;
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @return
     */
    public TenantExecutionPlanner withTenantTermsOfUse() {
      return withTenantTermsOfUse(prefix + "tenantTermsOfUse", null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @return
     */
    public TenantExecutionPlanner withTenantTermsOfUse(final String alias) {
      return withTenantTermsOfUse(alias, null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withTenantTermsOfUse(
        final UnaryOperator<TenantTermsOfUseExecutionPlanner> callback) {
      return withTenantTermsOfUse(prefix + "tenantTermsOfUse", callback);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withTenantTermsOfUse(final String alias,
        final UnaryOperator<TenantTermsOfUseExecutionPlanner> callback) {
      aggregation.add(ExecutionAggregation.builder().name("tenantTermsOfUse").alias(alias)
          .selection(null != callback
              ? callback.apply(new TenantTermsOfUseExecutionPlanner(prefix + alias)).build()
              : List.of())
          .build());
      return this;
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @return
     */
    public TenantExecutionPlanner withTheme() {
      return withTheme(prefix + "theme", null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @return
     */
    public TenantExecutionPlanner withTheme(final String alias) {
      return withTheme(alias, null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withTheme(final UnaryOperator<ThemeExecutionPlanner> callback) {
      return withTheme(prefix + "theme", callback);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withTheme(final String alias,
        final UnaryOperator<ThemeExecutionPlanner> callback) {
      aggregation
          .add(ExecutionAggregation.builder().name("theme").alias(alias)
              .selection(null != callback
                  ? callback.apply(new ThemeExecutionPlanner(prefix + alias)).build()
                  : List.of())
              .build());
      return this;
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @return
     */
    public TenantExecutionPlanner withUid() {
      return withUid(prefix + "uid");
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @return
     */
    public TenantExecutionPlanner withUid(final String alias) {
      aggregation.add(
          ExecutionAggregation.builder().name("uid").alias(alias).selection(List.of()).build());
      return this;
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @return
     */
    public TenantExecutionPlanner withUser() {
      return withUser(prefix + "user", null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @return
     */
    public TenantExecutionPlanner withUser(final String alias) {
      return withUser(alias, null);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withUser(final UnaryOperator<UserExecutionPlanner> callback) {
      return withUser(prefix + "user", callback);
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @param callback
     * @return
     */
    public TenantExecutionPlanner withUser(final String alias,
        final UnaryOperator<UserExecutionPlanner> callback) {
      aggregation
          .add(ExecutionAggregation.builder().name("user").alias(alias)
              .selection(null != callback
                  ? callback.apply(new UserExecutionPlanner(prefix + alias)).build()
                  : List.of())
              .build());
      return this;
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @return
     */
    public TenantExecutionPlanner withVersion() {
      return withVersion(prefix + "version");
    }

    /**
     * @autogenerated ProjectionDescriptorGeneratorGenerator
     * @param alias
     * @return
     */
    public TenantExecutionPlanner withVersion(final String alias) {
      aggregation.add(
          ExecutionAggregation.builder().name("version").alias(alias).selection(List.of()).build());
      return this;
    }
  }

  /**
   * @autogenerated ProjectionDescriptorGeneratorGenerator
   * @param baseServer
   * @return
   */
  @Override
  public List<ExecutionNode> baseNodes(final String baseServer) {
    Map<String, RelationshipDefinition> relations = relations(baseServer);
    return List.of(
        ExecutionNode.builder().server(baseServer).endpoint("/api/access/tenants").method("GET")
            .list(true).params(Map.of()).relations(relations).build(),
        ExecutionNode.builder().server(baseServer).endpoint("/api/access/tenants/{uid}")
            .method("GET").list(false).params(Map.of("uid", ParamKind.PATH)).relations(relations)
            .build());
  }

  /**
   * @autogenerated ProjectionDescriptorGeneratorGenerator
   * @param baseServer
   * @return
   */
  private Map<String, RelationshipDefinition> relations(final String baseServer) {
    return Map.of("template",
        RelationshipDefinition.builder().list(true).id("/api/document/template")
            .url(baseServer + "/api/document/template").method("GET").batchParam("tenants")
            .referenceField("tenant").build(),
        "message",
        RelationshipDefinition.builder().list(true).id("/api/template/template")
            .url(baseServer + "/api/template/template").method("GET").batchParam("tenants")
            .referenceField("tenant").build(),
        "tenantConfig",
        RelationshipDefinition.builder().list(true).id("/api/access/tenants-config")
            .url(baseServer + "/api/access/tenants-config").method("GET").batchParam("tenants")
            .referenceField("tenant").build(),
        "templateSnippet", RelationshipDefinition.builder().list(true)
            .id("/api/document/template-snippet").url(baseServer + "/api/document/template-snippet")
            .method("GET").batchParam("tenants").referenceField("tenant").build(),
        "smtpOutboundConfig",
        RelationshipDefinition.builder().list(true).id("/api/template/smtp-outbound-config")
            .url(baseServer + "/api/template/smtp-outbound-config").method("GET")
            .batchParam("tenants").referenceField("tenant").build(),
        "tenantLoginProvider", RelationshipDefinition.builder().list(true)
            .id("/api/access/login-providers").url(baseServer + "/api/access/login-providers")
            .method("GET").batchParam("tenants").referenceField("tenant").build(),
        "tenantTermsOfUse",
        RelationshipDefinition.builder().list(true).id("/api/access/tenants-terms-of-use")
            .url(baseServer + "/api/access/tenants-terms-of-use").method("GET")
            .batchParam("tenants").referenceField("tenant").build(),
        "templateVariable",
        RelationshipDefinition.builder().list(true).id("/api/document/template-variable")
            .url(baseServer + "/api/document/template-variable").method("GET").batchParam("tenants")
            .referenceField("tenant").build(),
        "theme",
        RelationshipDefinition.builder().list(true).id("/api/document/theme")
            .url(baseServer + "/api/document/theme").method("GET").batchParam("tenants")
            .referenceField("tenant").build(),
        "templateAsset",
        RelationshipDefinition.builder().list(true).id("/api/document/template-asset")
            .url(baseServer + "/api/document/template-asset").method("GET").batchParam("tenants")
            .referenceField("tenant").build(),
        "user",
        RelationshipDefinition.builder().list(true).id("/api/access/users")
            .url(baseServer + "/api/access/users").method("GET").batchParam("tenants")
            .referenceField("tenant").build());
  }
}
