package net.civeira.phylax.features.access.securitydomain.infrastructure.driver.rest;

import java.util.ArrayList;

import jakarta.ws.rs.core.Response;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.infrastructure.CurrentRequest;
import net.civeira.phylax.common.security.Allow;
import net.civeira.phylax.common.security.Interaction;
import net.civeira.phylax.features.access.securitydomain.application.service.visibility.SecurityDomainsVisibility;
import net.civeira.phylax.features.access.securitydomain.application.usecase.create.SecurityDomainCreateUsecase;
import net.civeira.phylax.features.access.securitydomain.application.usecase.delete.SecurityDomainDeleteUsecase;
import net.civeira.phylax.features.access.securitydomain.application.usecase.disable.SecurityDomainDisableUsecase;
import net.civeira.phylax.features.access.securitydomain.application.usecase.enable.SecurityDomainEnableUsecase;
import net.civeira.phylax.features.access.securitydomain.application.usecase.list.SecurityDomainListUsecase;
import net.civeira.phylax.features.access.securitydomain.application.usecase.retrieve.SecurityDomainRetrieveUsecase;
import net.civeira.phylax.features.access.securitydomain.application.usecase.update.SecurityDomainUpdateUsecase;
import net.civeira.phylax.generated.openapi.api.SecurityDomainAclApi;
import net.civeira.phylax.generated.openapi.model.CommonAllow;
import net.civeira.phylax.generated.openapi.model.SecurityDomainAclFields;
import net.civeira.phylax.generated.openapi.model.SecurityDomainAclGenericAllows;
import net.civeira.phylax.generated.openapi.model.SecurityDomainAclSpecificAllows;
import net.civeira.phylax.generated.openapi.model.SecurityDomainGenericAcl;
import net.civeira.phylax.generated.openapi.model.SecurityDomainSpecificAcl;

@RequiredArgsConstructor
public class SecurityDomainAclController implements SecurityDomainAclApi {

  /**
   * @autogenerated AclControllerGenerator
   */
  private final SecurityDomainCreateUsecase create;

  /**
   * SecurityDomain
   *
   * @autogenerated AclControllerGenerator
   */
  private final CurrentRequest currentRequest;

  /**
   * @autogenerated AclControllerGenerator
   */
  private final SecurityDomainDeleteUsecase delete;

  /**
   * @autogenerated AclControllerGenerator
   */
  private final SecurityDomainDisableUsecase disable;

  /**
   * @autogenerated AclControllerGenerator
   */
  private final SecurityDomainEnableUsecase enable;

  /**
   * @autogenerated AclControllerGenerator
   */
  private final SecurityDomainListUsecase list;

  /**
   * @autogenerated AclControllerGenerator
   */
  private final SecurityDomainRetrieveUsecase retrieve;

  /**
   * @autogenerated AclControllerGenerator
   */
  private final SecurityDomainUpdateUsecase update;

  /**
   * @autogenerated AclControllerGenerator
   */
  private final SecurityDomainsVisibility visibility;

  /**
   * @autogenerated AclControllerGenerator
   * @param uid
   * @return
   */
  @Override
  public Response securityDomainApiContextualAcl(final String uid) {
    Interaction interaction = currentRequest.interaction();
    SecurityDomainSpecificAcl response = new SecurityDomainSpecificAcl();
    response.setAllows(new SecurityDomainAclSpecificAllows());
    response.setFields(new SecurityDomainAclFields());
    response.getFields().setNoEditables(new ArrayList<>());
    response.getFields().setNoVisibles(new ArrayList<>());
    fixedFields(response.getFields(), interaction);
    hiddenFields(response.getFields(), interaction);
    updateAllows(response, interaction);
    deleteAllows(response, interaction);
    retrieveAllows(response, interaction);
    enableAllows(response, interaction);
    disableAllows(response, interaction);
    return Response.ok(response).build();
  }

  /**
   * @autogenerated AclControllerGenerator
   * @return
   */
  @Override
  public Response securityDomainApiGenericAcl() {
    Interaction interaction = currentRequest.interaction();
    SecurityDomainGenericAcl response = new SecurityDomainGenericAcl();
    response.setAllows(new SecurityDomainAclGenericAllows());
    response.setFields(new SecurityDomainAclFields());
    response.getFields().setNoEditables(new ArrayList<>());
    response.getFields().setNoVisibles(new ArrayList<>());
    fixedFields(response.getFields(), interaction);
    hiddenFields(response.getFields(), interaction);
    listAllows(response, interaction);
    createAllows(response, interaction);
    updateAllows(response, interaction);
    deleteAllows(response, interaction);
    retrieveAllows(response, interaction);
    enableAllows(response, interaction);
    disableAllows(response, interaction);
    return Response.ok(response).build();
  }

  /**
   * @autogenerated AclControllerGenerator
   * @param response
   * @param query
   */
  private void createAllows(final SecurityDomainGenericAcl response, final Interaction query) {
    Allow detail = create.allow(query);
    response.getAllows()
        .setCreate(new CommonAllow().allowed(detail.isAllowed()).reason(detail.getDescription()));
  }

  /**
   * @autogenerated AclControllerGenerator
   * @param response
   * @param query
   */
  private void deleteAllows(final SecurityDomainGenericAcl response, final Interaction query) {
    Allow detail = delete.allow(query);
    response.getAllows()
        .setDelete(new CommonAllow().allowed(detail.isAllowed()).reason(detail.getDescription()));
  }

  /**
   * @autogenerated AclControllerGenerator
   * @param response
   * @param query
   */
  private void deleteAllows(final SecurityDomainSpecificAcl response, final Interaction query) {
    Allow detail = delete.allow(query);
    response.getAllows()
        .setDelete(new CommonAllow().allowed(detail.isAllowed()).reason(detail.getDescription()));
  }

  /**
   * @autogenerated AclControllerGenerator
   * @param response
   * @param query
   */
  private void disableAllows(final SecurityDomainGenericAcl response, final Interaction query) {
    Allow detail = disable.allow(query);
    response.getAllows()
        .setDisable(new CommonAllow().allowed(detail.isAllowed()).reason(detail.getDescription()));
  }

  /**
   * @autogenerated AclControllerGenerator
   * @param response
   * @param query
   */
  private void disableAllows(final SecurityDomainSpecificAcl response, final Interaction query) {
    Allow detail = disable.allow(query);
    response.getAllows()
        .setDisable(new CommonAllow().allowed(detail.isAllowed()).reason(detail.getDescription()));
  }

  /**
   * @autogenerated AclControllerGenerator
   * @param response
   * @param query
   */
  private void enableAllows(final SecurityDomainGenericAcl response, final Interaction query) {
    Allow detail = enable.allow(query);
    response.getAllows()
        .setEnable(new CommonAllow().allowed(detail.isAllowed()).reason(detail.getDescription()));
  }

  /**
   * @autogenerated AclControllerGenerator
   * @param response
   * @param query
   */
  private void enableAllows(final SecurityDomainSpecificAcl response, final Interaction query) {
    Allow detail = enable.allow(query);
    response.getAllows()
        .setEnable(new CommonAllow().allowed(detail.isAllowed()).reason(detail.getDescription()));
  }

  /**
   * @autogenerated AclControllerGenerator
   * @param response
   * @param query
   */
  private void fixedFields(final SecurityDomainAclFields response, final Interaction query) {
    visibility.fieldsToFix(query).forEach(field -> response.getNoEditables().add(field));
  }

  /**
   * @autogenerated AclControllerGenerator
   * @param response
   * @param query
   */
  private void hiddenFields(final SecurityDomainAclFields response, final Interaction query) {
    visibility.fieldsToHide(query).forEach(field -> response.getNoVisibles().add(field));
  }

  /**
   * @autogenerated AclControllerGenerator
   * @param response
   * @param query
   */
  private void listAllows(final SecurityDomainGenericAcl response, final Interaction query) {
    Allow detail = list.allow(query);
    response.getAllows()
        .setList(new CommonAllow().allowed(detail.isAllowed()).reason(detail.getDescription()));
  }

  /**
   * @autogenerated AclControllerGenerator
   * @param response
   * @param query
   */
  private void retrieveAllows(final SecurityDomainGenericAcl response, final Interaction query) {
    Allow detail = retrieve.allow(query);
    response.getAllows()
        .setRetrieve(new CommonAllow().allowed(detail.isAllowed()).reason(detail.getDescription()));
  }

  /**
   * @autogenerated AclControllerGenerator
   * @param response
   * @param query
   */
  private void retrieveAllows(final SecurityDomainSpecificAcl response, final Interaction query) {
    Allow detail = retrieve.allow(query);
    response.getAllows()
        .setRetrieve(new CommonAllow().allowed(detail.isAllowed()).reason(detail.getDescription()));
  }

  /**
   * @autogenerated AclControllerGenerator
   * @param response
   * @param query
   */
  private void updateAllows(final SecurityDomainGenericAcl response, final Interaction query) {
    Allow detail = update.allow(query);
    response.getAllows()
        .setUpdate(new CommonAllow().allowed(detail.isAllowed()).reason(detail.getDescription()));
  }

  /**
   * @autogenerated AclControllerGenerator
   * @param response
   * @param query
   */
  private void updateAllows(final SecurityDomainSpecificAcl response, final Interaction query) {
    Allow detail = update.allow(query);
    response.getAllows()
        .setUpdate(new CommonAllow().allowed(detail.isAllowed()).reason(detail.getDescription()));
  }
}
