package net.civeira.phylax.features.access.useridentity.application.usecase.delete;

import java.time.Duration;

import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.SpanKind;
import io.opentelemetry.api.trace.Tracer;
import io.opentelemetry.context.Context;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.batch.BatchIdentificator;
import net.civeira.phylax.common.batch.BatchProgress;
import net.civeira.phylax.common.batch.BatchService;
import net.civeira.phylax.common.batch.ExecutorByDeferSteps;
import net.civeira.phylax.common.batch.ExecutorPlan;
import net.civeira.phylax.common.exception.NotAllowedException;
import net.civeira.phylax.common.exception.NotFoundException;
import net.civeira.phylax.common.security.Allow;
import net.civeira.phylax.common.security.Interaction;
import net.civeira.phylax.features.access.useridentity.application.visibility.UserIdentityVisibilityFilter;
import net.civeira.phylax.features.access.useridentity.application.visibility.UserIdentitysVisibility;
import net.civeira.phylax.features.access.useridentity.domain.UserIdentity;
import net.civeira.phylax.features.access.useridentity.domain.UserIdentityRef;
import net.civeira.phylax.features.access.useridentity.domain.gateway.UserIdentityAuditGateway;
import net.civeira.phylax.features.access.useridentity.domain.gateway.UserIdentityCacheGateway;
import net.civeira.phylax.features.access.useridentity.domain.gateway.UserIdentityWriteRepositoryGateway;

@ApplicationScoped
@RequiredArgsConstructor
public class UserIdentityDeleteUsecase {

  /**
   * Service to register audit events
   *
   * @autogenerated DeleteUsecaseGenerator
   */
  private final UserIdentityAuditGateway audit;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final BatchService batch;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final UserIdentityCacheGateway cache;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final Event<UserIdentityDeleteAllowDecision> deleteAllowEmitter;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final Event<UserIdentityDeleteCheck> deleteCheckEmitter;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final UserIdentityWriteRepositoryGateway gateway;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final Tracer tracer;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final UserIdentitysVisibility visibility;

  /**
   * @autogenerated DeleteUsecaseGenerator
   * @param query
   * @param reference
   * @return
   */
  public Allow allow(final Interaction query, final UserIdentityRef reference) {
    Span span = tracer.spanBuilder("Checking if is allowed to delete an entity of user identity")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      span.setAttribute("ref", reference.getUid());
      Allow response = checkAllow(query, reference);
      span.setAttribute("allowed", response.isAllowed());
      return response;
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * @autogenerated DeleteUsecaseGenerator
   * @param query
   * @return
   */
  public Allow allow(final Interaction query) {
    Span span = tracer.spanBuilder("Checking if is allowed to delete an entity of user identity")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      Allow response = checkAllow(query);
      span.setAttribute("allowed", response.isAllowed());
      return response;
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated DeleteUsecaseGenerator
   * @param query
   * @param filter
   * @return The slide with some values
   */
  public BatchIdentificator batchDelete(final Interaction query,
      final UserIdentityDeleteFilter filter) {
    Span span = tracer.spanBuilder("Deleting a set of entities of user identity")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      Allow detail = checkAllow(query);
      if (!detail.isAllowed()) {
        span.addEvent(
            "The policies for user identity dont allow to delete: " + detail.getDescription());
        throw new NotAllowedException(detail.getDescription());
      }
      UserIdentityVisibilityFilter filterOnVisibles = UserIdentityVisibilityFilter.builder()
          .uid(filter.getUid().orElse(null)).uids(filter.getUids().stream().toList())
          .search(filter.getSearch().orElse(null))
          .forAllAudiences(filter.getForAllAudiences().orElse(null))
          .user(filter.getUser().orElse(null)).users(filter.getUsers())
          .relyingParty(filter.getRelyingParty().orElse(null))
          .relyingPartys(filter.getRelyingPartys())
          .trustedClient(filter.getTrustedClient().orElse(null))
          .trustedClients(filter.getTrustedClients())
          .userTenantTenantAccesible(filter.getUserTenantTenantAccesible().orElse(null)).build();
      UserIdentityDeleteAllInBatchCommand command = UserIdentityDeleteAllInBatchCommand.builder()
          .interaction(query).filter(filterOnVisibles).build();
      return batch.start(query.getActor().getName().orElse("-"), Duration.ofHours(6), ExecutorPlan
          .<UserIdentityDeleteAllInBatchCommand>builder().params(command).name("delete-color")
          .executor(
              ExecutorByDeferSteps.<UserIdentity, UserIdentity, UserIdentityDeleteAllInBatchCommand, UserIdentitysInBatchExecutor.UserIdentityPaginableBatch>builder()
                  .initializer(UserIdentitysInBatchExecutor.class)
                  .counter(UserIdentitysInBatchExecutor.class)
                  .descriptor(UserIdentitysInBatchExecutor.class)
                  .reader(UserIdentitysInBatchExecutor.class)
                  .processor(UserIdentitysInBatchExecutor.class)
                  .writer(UserIdentitysInBatchExecutor.class)
                  .finalizer(UserIdentitysInBatchExecutor.class).build())
          .build());
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated DeleteUsecaseGenerator
   * @param query a filter to retrieve only matching values
   * @return The slide with some values
   */
  public BatchProgress checkProgress(final UserIdentityCheckBatchDeleteStatus query) {
    return query.getActor().getName()
        .flatMap(name -> batch.retrieve(query.getTaskId(), query.getConnection().getLocale(), name))
        .orElseThrow(() -> new NotFoundException());
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated DeleteUsecaseGenerator
   * @param query
   * @param reference
   */
  public void delete(final Interaction query, final UserIdentityRef reference) {
    Span span = tracer.spanBuilder("Deleting an entity of user identity")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      span.setAttribute("ref", reference.getUid());
      Allow detail = checkAllow(query, reference);
      if (!detail.isAllowed()) {
        span.addEvent(
            "The policies for user identity dont allow to delete: " + detail.getDescription());
        throw new NotAllowedException(detail.getDescription());
      }
      UserIdentity original = visibility.retrieveVisibleForUpdate(query, reference.getUid())
          .orElseThrow(() -> new NotFoundException(""));
      doDelete(query, original);
      cacheEvict();
      // Register audit operation
      audit.deleted("delete", original, query);
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  void cacheEvict() {
    cache.evict();
  }

  /**
   * @autogenerated DeleteUsecaseGenerator
   * @param query
   * @param reference
   * @return
   */
  Allow checkAllow(final Interaction query, final UserIdentityRef reference) {
    UserIdentityDeleteAllowDecision base = UserIdentityDeleteAllowDecision.builder()
        .detail(Allow.builder().allowed(true).description("Allowed by default").build())
        .query(query).reference(reference).build();
    deleteAllowEmitter.fire(base);
    return base.getDetail();
  }

  /**
   * @autogenerated DeleteUsecaseGenerator
   * @param query
   * @return
   */
  Allow checkAllow(final Interaction query) {
    UserIdentityDeleteAllowDecision base = UserIdentityDeleteAllowDecision.builder()
        .detail(Allow.builder().allowed(true).description("Allowed by default").build())
        .query(query).build();
    deleteAllowEmitter.fire(base);
    return base.getDetail();
  }

  /**
   * @autogenerated DeleteUsecaseGenerator
   * @param interaction
   * @param original
   */
  void doDelete(final Interaction interaction, final UserIdentity original) {
    UserIdentityDeleteCheck proposal =
        UserIdentityDeleteCheck.builder().reference(original).interaction(interaction).build();
    deleteCheckEmitter.fire(proposal);
    UserIdentity clean = original.delete();
    gateway.delete(clean);
  }
}
