package net.civeira.phylax.features.access.useridentity.application.usecase.delete;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.With;
import net.civeira.phylax.common.security.Interaction;
import net.civeira.phylax.features.access.useridentity.query.UserIdentityFilter;

@Data
@Builder(toBuilder = true)
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class UserIdentityDeleteAllInBatchCommand {

  /**
   * The filter to select the results to retrieve
   *
   * @autogenerated EntityGenerator
   */
  @NonNull
  private final UserIdentityFilter filter;

  /**
   * @autogenerated EntityGenerator
   */
  @NonNull
  private final Interaction interaction;
}
