package net.civeira.phylax.features.access.useridentity.application.usecase.delete;

import java.util.Optional;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.With;
import net.civeira.phylax.common.security.Interaction;
import net.civeira.phylax.features.access.useridentity.domain.UserIdentityRef;

@Data
@Builder(toBuilder = true)
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class UserIdentityDeleteCheck {

  /**
   * @autogenerated DeleteCheckGenerator
   */
  @NonNull
  private final Interaction interaction;

  /**
   * @autogenerated DeleteCheckGenerator
   */
  private final UserIdentityRef reference;

  /**
   * @autogenerated DeleteCheckGenerator
   * @return
   */
  public Optional<UserIdentityRef> getReference() {
    return Optional.ofNullable(reference);
  }
}
