package net.civeira.phylax.features.access.tenant.application.usecase.disable;

import java.time.Duration;

import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.SpanKind;
import io.opentelemetry.api.trace.Tracer;
import io.opentelemetry.context.Context;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.batch.BatchIdentificator;
import net.civeira.phylax.common.batch.BatchProgress;
import net.civeira.phylax.common.batch.BatchService;
import net.civeira.phylax.common.batch.ExecutorByDeferSteps;
import net.civeira.phylax.common.batch.ExecutorPlan;
import net.civeira.phylax.common.exception.NotAllowedException;
import net.civeira.phylax.common.exception.NotFoundException;
import net.civeira.phylax.common.security.Allow;
import net.civeira.phylax.common.security.Interaction;
import net.civeira.phylax.features.access.tenant.application.visibility.TenantVisibilityFilter;
import net.civeira.phylax.features.access.tenant.application.visibility.TenantsVisibility;
import net.civeira.phylax.features.access.tenant.domain.Tenant;
import net.civeira.phylax.features.access.tenant.domain.TenantRef;
import net.civeira.phylax.features.access.tenant.domain.gateway.TenantCacheGateway;
import net.civeira.phylax.features.access.tenant.domain.gateway.TenantWriteRepositoryGateway;

@ApplicationScoped
@RequiredArgsConstructor
public class TenantDisableUsecase {

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final BatchService batch;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final TenantCacheGateway cache;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final Event<TenantDisableAllowDecision> execAllowEmitter;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final Event<TenantDisableCheck> execProposalEmitter;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final TenantWriteRepositoryGateway gateway;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final Tracer tracer;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final TenantsVisibility visibility;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param query
   * @param reference
   * @return
   */
  public Allow allow(final Interaction query, final TenantRef reference) {
    Span span = tracer.spanBuilder("Checking if is allowed to update an entity of tenant")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      span.setAttribute("ref", reference.getUid());
      Allow response = checkAllow(query, reference);
      span.setAttribute("allowed", response.isAllowed());
      return response;
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param query
   * @return
   */
  public Allow allow(final Interaction query) {
    Span span = tracer.spanBuilder("Checking if is allowed to update an entity of tenant")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      Allow response = checkAllow(query);
      span.setAttribute("allowed", response.isAllowed());
      return response;
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated ActionChangeUsecaseGenerator
   * @param query a filter to retrieve only matching values
   * @return The slide with some values
   */
  public BatchProgress checkProgress(final TenantDisableStatus query) {
    return query.getActor().getName()
        .flatMap(name -> batch.retrieve(query.getTaskId(), query.getConnection().getLocale(), name))
        .orElseThrow(() -> new NotFoundException());
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated ActionChangeUsecaseGenerator
   * @param query
   * @param reference
   * @return The slide with some values
   */
  public TenantDisableProjection disable(final Interaction query, final TenantRef reference) {
    Span span = tracer.spanBuilder("disable an entity of tenant")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      span.setAttribute("ref", reference.getUid());
      Allow detail = checkAllow(query, reference);
      if (!detail.isAllowed()) {
        span.addEvent("The policies for tenant dont allow to disable: " + detail.getDescription());
        throw new NotAllowedException(detail.getDescription());
      }
      Tenant original = visibility.retrieveVisibleForUpdate(query, reference.getUid())
          .orElseThrow(() -> new NotFoundException(""));
      Tenant saved = disable(query, original);
      flush();
      return TenantDisableProjection.from(visibility.copyWithHidden(query, saved));
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated ActionChangeUsecaseGenerator
   * @param query
   * @param filter
   * @return The slide with some values
   */
  public BatchIdentificator disable(final Interaction query, final TenantDisableFilter filter) {
    Span span = tracer.spanBuilder("disable a set of entities of tenant")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      Allow detail = checkAllow(query);
      if (!detail.isAllowed()) {
        span.addEvent("The policies for tenant dont allow to disable: " + detail.getDescription());
        throw new NotAllowedException(detail.getDescription());
      }
      TenantVisibilityFilter filterWithVisibility = TenantVisibilityFilter.builder()
          .uid(filter.getUid().orElse(null)).uids(filter.getUids().stream().toList())
          .search(filter.getSearch().orElse(null)).name(filter.getName().orElse(null))
          .tenantAccesible(filter.getTenantAccesible().orElse(null)).build();
      TenantDisableAllInBatchCommand command = TenantDisableAllInBatchCommand.builder()
          .interaction(query).filter(filterWithVisibility).build();
      return batch.start(command.getInteraction().getActor().getName().orElse("-"),
          Duration.ofHours(6),
          ExecutorPlan.<TenantDisableAllInBatchCommand>builder().params(command)
              .name("disable-tenant")
              .executor(
                  ExecutorByDeferSteps.<Tenant, Tenant, TenantDisableAllInBatchCommand, TenantDisablesInBatchExecutor.TenantPaginableBatch>builder()
                      .initializer(TenantDisablesInBatchExecutor.class)
                      .counter(TenantDisablesInBatchExecutor.class)
                      .descriptor(TenantDisablesInBatchExecutor.class)
                      .reader(TenantDisablesInBatchExecutor.class)
                      .processor(TenantDisablesInBatchExecutor.class)
                      .writer(TenantDisablesInBatchExecutor.class)
                      .finalizer(TenantDisablesInBatchExecutor.class).build())
              .build());
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param query
   * @param reference
   * @return
   */
  Allow checkAllow(final Interaction query, final TenantRef reference) {
    TenantDisableAllowDecision base = TenantDisableAllowDecision.builder()
        .detail(Allow.builder().allowed(true).description("Allowed by default").build())
        .query(query).reference(reference).build();
    execAllowEmitter.fire(base);
    return base.getDetail();
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param query
   * @return
   */
  Allow checkAllow(final Interaction query) {
    TenantDisableAllowDecision base = TenantDisableAllowDecision.builder()
        .detail(Allow.builder().allowed(true).description("Allowed by default").build())
        .query(query).build();
    execAllowEmitter.fire(base);
    return base.getDetail();
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param interaction
   * @param original
   * @return
   */
  Tenant disable(final Interaction interaction, final Tenant original) {
    TenantDisableCheck proposal =
        TenantDisableCheck.builder().reference(original).interaction(interaction).build();
    execProposalEmitter.fire(proposal);
    Tenant result = original.disable();
    Tenant saved = gateway.update(original, result);
    return saved;
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  void flush() {
    cache.evict();
  }
}
