package net.civeira.phylax.features.access.loginprovider.application.usecase.disable;

import java.util.Optional;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.With;
import net.civeira.phylax.common.security.Interaction;
import net.civeira.phylax.features.access.loginprovider.domain.LoginProviderRef;

@Data
@Builder(toBuilder = true)
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class LoginProviderDisableCheck {

  /**
   * @autogenerated ActionCheckGenerator
   */
  @NonNull
  private final Interaction interaction;

  /**
   * @autogenerated ActionCheckGenerator
   */
  private final LoginProviderRef reference;

  /**
   * @autogenerated ActionCheckGenerator
   * @return
   */
  public Optional<LoginProviderRef> getReference() {
    return Optional.ofNullable(reference);
  }
}
