package net.civeira.phylax.features.document.template.application.usecase.disable;

import java.time.Duration;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.batch.BatchIdentificator;
import net.civeira.phylax.common.batch.BatchProgress;
import net.civeira.phylax.common.batch.BatchService;
import net.civeira.phylax.common.batch.ExecutorByDeferSteps;
import net.civeira.phylax.common.batch.ExecutorPlan;
import net.civeira.phylax.common.exception.NotAllowedException;
import net.civeira.phylax.common.exception.NotFoundException;
import net.civeira.phylax.common.security.OperationContext;
import net.civeira.phylax.common.security.Permission;
import net.civeira.phylax.common.telemetry.Observed;
import net.civeira.phylax.common.telemetry.Trace;
import net.civeira.phylax.features.document.template.application.visibility.TemplateVisibilityFilter;
import net.civeira.phylax.features.document.template.application.visibility.TemplatesVisibility;
import net.civeira.phylax.features.document.template.domain.Template;
import net.civeira.phylax.features.document.template.domain.TemplateRef;
import net.civeira.phylax.features.document.template.domain.gateway.TemplateAuditGateway;
import net.civeira.phylax.features.document.template.domain.gateway.TemplateCacheGateway;
import net.civeira.phylax.features.document.template.domain.gateway.TemplateWriteRepositoryGateway;

@ApplicationScoped
@RequiredArgsConstructor
public class TemplateDisableUsecase {

  /**
   * Service to register audit events
   *
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final TemplateAuditGateway audit;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final BatchService batch;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final TemplateCacheGateway cache;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final Event<TemplateDisableAuthorizationDecision> execAllowEmitter;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final Event<TemplateDisableCheck> execProposalEmitter;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final TemplateWriteRepositoryGateway gateway;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final TemplatesVisibility visibility;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param reference
   * @return
   */
  @Observed("disable an entity of template")
  public Permission allow(final OperationContext context, final TemplateRef reference) {
    Trace.setAttribute("ref", reference.getUid());
    Permission response = checkPermission(context, reference);
    Trace.setAttribute("allowed", response.isAllowed());
    return response;
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @return
   */
  @Observed("disable an entity of template")
  public Permission allow(final OperationContext context) {
    Permission response = checkPermission(context);
    Trace.setAttribute("allowed", response.isAllowed());
    return response;
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param filter
   * @return The slide with some values
   */
  @Observed("disable a set of entity of template")
  public BatchIdentificator batchDisable(final OperationContext context,
      final TemplateDisableFilter filter) {
    Permission detail = checkPermission(context);
    if (!detail.isAllowed()) {
      Trace.addEvent("The policies for template dont allow to disable: " + detail.getDescription());
      throw new NotAllowedException(detail.getDescription());
    }
    TemplateVisibilityFilter filterWithVisibility =
        TemplateVisibilityFilter.builder().uid(filter.getUid().orElse(null))
            .uids(filter.getUids().stream().toList()).search(filter.getSearch().orElse(null))
            .global(filter.getGlobal().orElse(null)).code(filter.getCode().orElse(null))
            .tenant(filter.getTenant().orElse(null)).tenants(filter.getTenants())
            .tenantAccesible(filter.getTenantAccesible().orElse(null)).build();
    TemplateDisableAllInBatchCommand command =
        new TemplateDisableAllInBatchCommand(context, filterWithVisibility);
    return batch.start(context.getActor().getName(), Duration.ofHours(6), ExecutorPlan
        .<TemplateDisableAllInBatchCommand>builder().params(command).name("disable-template")
        .executor(
            ExecutorByDeferSteps.<Template, Template, TemplateDisableAllInBatchCommand, TemplateDisablesInBatchExecutor.TemplatePaginableBatch>builder()
                .initializer(TemplateDisablesInBatchExecutor.class)
                .counter(TemplateDisablesInBatchExecutor.class)
                .descriptor(TemplateDisablesInBatchExecutor.class)
                .reader(TemplateDisablesInBatchExecutor.class)
                .processor(TemplateDisablesInBatchExecutor.class)
                .writer(TemplateDisablesInBatchExecutor.class)
                .finalizer(TemplateDisablesInBatchExecutor.class).build())
        .build());
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param query a filter to retrieve only matching values
   * @return The slide with some values
   */
  public BatchProgress checkProgress(final OperationContext context,
      final TemplateDisableStatus query) {
    String name = context.getActor().getName();
    return batch.retrieve(query.getTaskId(), context.getSource().getLocale(), name)
        .orElseThrow(() -> new NotFoundException());
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param reference
   * @return The slide with some values
   */
  @Observed("disable an entity of template")
  public TemplateDisableProjection disable(final OperationContext context,
      final TemplateRef reference) {
    Trace.setAttribute("ref", reference.getUid());
    Permission detail = checkPermission(context, reference);
    if (!detail.isAllowed()) {
      Trace.addEvent("The policies for template dont allow to disable: " + detail.getDescription());
      throw new NotAllowedException(detail.getDescription());
    }
    Template original = visibility.retrieveVisibleForUpdate(context, reference.getUid())
        .orElseThrow(() -> new NotFoundException(""));
    Template saved = doDisable(context, original);
    cacheUpdate(saved);
    // Register audit operation
    audit.updated("disable", saved, original, context);
    return TemplateDisableProjection.from(visibility.copyWithHidden(context, saved));
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param saved
   */
  void cacheUpdate(final Template saved) {
    cache.update(saved);
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param reference
   * @return
   */
  Permission checkPermission(final OperationContext context, final TemplateRef reference) {
    TemplateDisableAuthorizationDecision proposal = new TemplateDisableAuthorizationDecision(
        context, reference, Permission.allow("Allow to disable by default"));
    execAllowEmitter.fire(proposal);
    return proposal.getPermission();
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @return
   */
  Permission checkPermission(final OperationContext context) {
    TemplateDisableAuthorizationDecision proposal = new TemplateDisableAuthorizationDecision(
        context, Permission.allow("Allow to disable by default"));
    execAllowEmitter.fire(proposal);
    return proposal.getPermission();
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param original
   * @return
   */
  Template doDisable(final OperationContext context, final Template original) {
    TemplateDisableCheck proposal = new TemplateDisableCheck(context, original);
    execProposalEmitter.fire(proposal);
    Template result = original.disable();
    Template saved = gateway.update(original, result);
    return saved;
  }
}
