/* @autogenerated */
package net.civeira.phylax.features.oauth.key.domain.model;

import lombok.Builder;
import lombok.Getter;

@Builder
@Getter
public class PublicKeyInformation {
  private final String keyId;
  private final String publicKey;
}
