package net.civeira.phylax.features.document.templatevariable.application.visibility;

import java.util.Optional;
import java.util.function.Consumer;

import lombok.Getter;
import lombok.NonNull;
import net.civeira.phylax.common.security.Actor;
import net.civeira.phylax.common.security.InvocationSource;
import net.civeira.phylax.common.security.OperationContext;
import net.civeira.phylax.features.document.templatevariable.domain.TemplateVariable;
import net.civeira.phylax.features.document.templatevariable.domain.TemplateVariableChangeSet;

/**
 * Entity Enrichment events happen when a dto params is read throught the visibility service from
 * some input parameters to store on the repository.The programmers could add policies to fill
 * calculated values to store at the application level.
 */
@Getter
public class TemplateVariableEntityEnrichment {

  /**
   * @autogenerated EntityEnrichmentGenerator
   */
  @NonNull
  private final OperationContext context;

  /**
   * @autogenerated EntityEnrichmentGenerator
   */
  @NonNull
  private final TemplateVariableChangeSet dto;

  /**
   * @autogenerated EntityEnrichmentGenerator
   */
  private final TemplateVariable original;

  /**
   * @autogenerated EntityEnrichmentGenerator
   * @param context
   * @param dto
   */
  public TemplateVariableEntityEnrichment(OperationContext context, TemplateVariableChangeSet dto) {
    this.context = context;
    this.dto = dto;
    this.original = null;
  }

  /**
   * @autogenerated EntityEnrichmentGenerator
   * @param context
   * @param dto
   * @param original
   */
  public TemplateVariableEntityEnrichment(OperationContext context, TemplateVariableChangeSet dto,
      TemplateVariable original) {
    this.context = context;
    this.dto = dto;
    this.original = original;
  }

  /**
   * @autogenerated EntityEnrichmentGenerator
   * @return
   */
  public Actor getActor() {
    return this.context.getActor();
  }

  /**
   * @autogenerated EntityEnrichmentGenerator
   * @return
   */
  public Optional<TemplateVariable> getOriginal() {
    return Optional.ofNullable(this.original);
  }

  /**
   * @autogenerated EntityEnrichmentGenerator
   * @return
   */
  public InvocationSource getSource() {
    return this.context.getSource();
  }

  /**
   * @autogenerated EntityEnrichmentGenerator
   * @param mapper
   */
  public void peek(Consumer<TemplateVariableChangeSet> mapper) {
    mapper.accept(dto);
  }
}
