/* @autogenerated */
package net.civeira.phylax.features.oauth.authentication.application.spi;

import net.civeira.phylax.features.oauth.authentication.application.interaction.command.RecoverPasswordCommand;
import net.civeira.phylax.features.oauth.authentication.domain.model.AuthRequest;

public interface RecoverPasswordSpi {
  boolean allowRecover(AuthRequest request);

  void recover(AuthRequest request, String email, String urlWithParams);

  boolean checkRecoverCode(AuthRequest request, String email, RecoverPasswordCommand rcoverRequest);
}
