package net.civeira.phylax.features.document.snippetasset.domain;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NonNull;
import lombok.ToString;
import lombok.With;
import lombok.experimental.Delegate;
import net.civeira.phylax.common.exception.ConstraintException;
import net.civeira.phylax.common.value.validation.ConstraintFailList;
import net.civeira.phylax.features.document.snippetasset.domain.event.SnippetAssetCreateEvent;
import net.civeira.phylax.features.document.snippetasset.domain.event.SnippetAssetDeleteEvent;
import net.civeira.phylax.features.document.snippetasset.domain.event.SnippetAssetDisableEvent;
import net.civeira.phylax.features.document.snippetasset.domain.event.SnippetAssetEnableEvent;
import net.civeira.phylax.features.document.snippetasset.domain.event.SnippetAssetEvent;
import net.civeira.phylax.features.document.snippetasset.domain.event.SnippetAssetUpdateEvent;
import net.civeira.phylax.features.document.snippetasset.domain.valueobject.CodeVO;
import net.civeira.phylax.features.document.snippetasset.domain.valueobject.ContentVO;
import net.civeira.phylax.features.document.snippetasset.domain.valueobject.EnabledVO;
import net.civeira.phylax.features.document.snippetasset.domain.valueobject.SnippetVO;
import net.civeira.phylax.features.document.snippetasset.domain.valueobject.TypeVO;
import net.civeira.phylax.features.document.snippetasset.domain.valueobject.UidVO;
import net.civeira.phylax.features.document.snippetasset.domain.valueobject.VersionVO;

/**
 * snippet-asset
 */
@Builder
@Getter
@With
@ToString
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@EqualsAndHashCode
public class SnippetAsset implements SnippetAssetRef {

  /**
   * Prepare a new snippet asset with the provided values
   *
   * @autogenerated EntityGenerator
   * @param change A set of values to create a new snippet asset
   * @throws ConstraintException If there are some constraints fails on the changes.
   * @return A well formed snippet asset.
   */
  public static SnippetAsset create(final SnippetAssetChangeSet change) throws ConstraintException {
    change.enabled(true);
    SnippetAsset instance = new SnippetAsset(change, Optional.empty());
    instance.addEvent(SnippetAssetCreateEvent.builder().payload(instance).build());
    return instance;
  }

  /**
   * icon, separator...
   *
   * @autogenerated EntityGenerator
   */
  @Delegate
  @NonNull
  private CodeVO codeValue;

  /**
   * El content de snippet asset
   *
   * @autogenerated EntityGenerator
   */
  @Delegate
  @NonNull
  private ContentVO contentValue;

  /**
   * El enabled de snippet asset
   *
   * @autogenerated EntityGenerator
   */
  @Delegate
  @Builder.Default
  private EnabledVO enabledValue = EnabledVO.nullValue();

  /**
   * List of events
   *
   * @autogenerated EntityGenerator
   */
  @Builder.Default
  private List<SnippetAssetEvent> recordedEvents = List.of();

  /**
   * El snippet de snippet asset
   *
   * @autogenerated EntityGenerator
   */
  @Delegate
  @NonNull
  private SnippetVO snippetValue;

  /**
   * IMAGE, CSS, FONT...
   *
   * @autogenerated EntityGenerator
   */
  @Delegate
  @NonNull
  private TypeVO typeValue;

  /**
   * El uid de snippet asset
   *
   * @autogenerated EntityGenerator
   */
  @Delegate
  @NonNull
  private UidVO uidValue;

  /**
   * Campo con el número de version de snippet asset para controlar bloqueos optimistas
   *
   * @autogenerated EntityGenerator
   */
  @Delegate
  @Builder.Default
  private VersionVO versionValue = VersionVO.nullValue();

  /**
   * @autogenerated EntityGenerator
   * @param attribute
   * @param previous
   */
  private SnippetAsset(final SnippetAssetChangeSet attribute,
      final Optional<SnippetAsset> previous) {
    ConstraintFailList list = new ConstraintFailList();
    this.uidValue = attribute.readUid(previous, list);
    this.snippetValue = attribute.readSnippet(previous, list);
    this.codeValue = attribute.readCode(previous, list);
    this.typeValue = attribute.readType(previous, list);
    this.contentValue = attribute.readContent(previous, list);
    this.enabledValue = attribute.readEnabled(previous, list);
    this.versionValue = attribute.readVersion(previous, list);
    if (list.hasErrors()) {
      throw new ConstraintException("Invalid values on SnippetAsset", list);
    }
    this.recordedEvents = previous.map(SnippetAsset::getRecordedEvents).orElseGet(List::of);
  }

  /**
   * Apply changes to delete a snippet asset
   *
   * @autogenerated EntityGenerator
   * @return A instance of snippet asset ready to be deleted
   */
  public SnippetAsset delete() {
    SnippetAsset instance = new SnippetAsset(new SnippetAssetChangeSet(), Optional.of(this));
    instance.addEvent(SnippetAssetDeleteEvent.builder().payload(instance).build());
    return instance;
  }

  /**
   * Apply disable on snippet asset.
   *
   * @autogenerated EntityGenerator
   * @return A modified instance of snippet asset
   */
  public SnippetAsset disable() {
    SnippetAssetChangeSet attr = new SnippetAssetChangeSet();
    attr.enabled(false);
    SnippetAsset instance = new SnippetAsset(attr, Optional.of(this));
    instance.addEvent(SnippetAssetDisableEvent.builder().payload(instance).build());
    return instance;
  }

  /**
   * Apply enable on snippet asset.
   *
   * @autogenerated EntityGenerator
   * @return A modified instance of snippet asset
   */
  public SnippetAsset enable() {
    SnippetAssetChangeSet attr = new SnippetAssetChangeSet();
    attr.enabled(true);
    SnippetAsset instance = new SnippetAsset(attr, Optional.of(this));
    instance.addEvent(SnippetAssetEnableEvent.builder().payload(instance).build());
    return instance;
  }

  /**
   * @autogenerated EntityGenerator
   * @return
   */
  public Map<String, String> toMap() {
    Map<String, String> map = new HashMap<>(7);
    uidToMap(map);
    snippetToMap(map);
    codeToMap(map);
    typeToMap(map);
    contentToMap(map);
    enabledToMap(map);
    versionToMap(map);
    return map;
  }

  /**
   * Modify the values for some of the properties of a snippet asset
   *
   * @autogenerated EntityGenerator
   * @param change The properties to be modified
   * @throws ConstraintException If there are some constraints fails on the changes.
   * @return A modified instance of snippet asset
   */
  public SnippetAsset update(final SnippetAssetChangeSet change) throws ConstraintException {
    change.unsetEnabled();
    SnippetAsset instance = new SnippetAsset(change, Optional.of(this));
    instance.addEvent(SnippetAssetUpdateEvent.builder().payload(instance).build());
    return instance;
  }

  /**
   * @autogenerated EntityGenerator
   * @return
   */
  public SnippetAsset withNextVersion() {
    return withVersionValue(VersionVO.from(nextVersion()));
  }

  /**
   * @autogenerated EntityGenerator
   * @param event
   */
  private void addEvent(final SnippetAssetEvent event) {
    List<SnippetAssetEvent> events = new ArrayList<>(this.recordedEvents);
    events.add(event);
    this.recordedEvents = List.copyOf(events);
  }
}
