package net.civeira.phylax.features.access.tenant.application.service.visibility;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.exception.NotFoundException;
import net.civeira.phylax.common.security.Interaction;
import net.civeira.phylax.features.access.relyingparty.application.service.visibility.RelyingPartysVisibility;
import net.civeira.phylax.features.access.tenant.Tenant;
import net.civeira.phylax.features.access.tenant.TenantFacade;
import net.civeira.phylax.features.access.tenant.TenantRef;
import net.civeira.phylax.features.access.tenant.application.projection.TenantStateProyection;
import net.civeira.phylax.features.access.tenant.application.request.TenantStateChange;
import net.civeira.phylax.features.access.tenant.gateway.TenantCacheGateway;
import net.civeira.phylax.features.access.tenant.gateway.TenantCached;
import net.civeira.phylax.features.access.tenant.gateway.TenantReadRepositoryGateway;
import net.civeira.phylax.features.access.tenant.gateway.TenantWriteRepositoryGateway;
import net.civeira.phylax.features.access.tenant.query.TenantCursor;
import net.civeira.phylax.features.access.tenant.query.TenantFilter;
import net.civeira.phylax.features.access.tenant.valueobject.RelingPartiesVO;
import net.civeira.phylax.features.access.tenant.valueobject.TrustedClientsVO;
import net.civeira.phylax.features.access.trustedclient.application.service.visibility.TrustedClientsVisibility;

@ApplicationScoped
@RequiredArgsConstructor
public class TenantsVisibility {

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final TenantFacade aggregate;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final TenantCacheGateway cache;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<TenantFilterProposal> filterProposalEmitter;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<TenantFixedFieldsProposal> fixedFieldsEmitter;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<TenantVisibleContentProposal> guardEmitter;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<TenantHiddenFieldsProposal> hiddenFieldsEmitter;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<TenantPresetProposal> presetEmitter;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final RelyingPartysVisibility relyingPartysVisibility;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final TenantReadRepositoryGateway tenantReadRepositoryGateway;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final TenantWriteRepositoryGateway tenantWriteRepositoryGateway;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final TrustedClientsVisibility trustedClientsVisibility;

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uid
   * @return The input entity with the copy values without hidden
   */
  public boolean checkVisibility(Interaction prev, String uid) {
    return retrieveVisible(prev, uid).isPresent();
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uids
   * @return The input entity with the copy values without hidden
   */
  public boolean checkVisibility(Interaction prev, List<String> uids) {
    return uids.size() == listVisibles(prev, TenantFilter.builder().uids(uids).build(),
        TenantCursor.builder().build()).size();
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param source The source interaction
   * @param original The source interaction
   * @return The input entity with the copy values without hidden
   */
  public TenantStateChange copyWithFixed(Interaction prev, TenantStateChange source,
      Tenant original) {
    TenantStateChange withReferences = visiblesReferences(prev, source);
    fieldsToFix(prev, original).forEach(withReferences::unset);
    TenantPresetProposal proposal = TenantPresetProposal.builder().dto(withReferences)
        .interaction(prev).original(original).build();
    presetEmitter.fire(proposal);
    return proposal.getDto();
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param source The source interaction
   * @return The input entity with the copy values without hidden
   */
  public TenantStateChange copyWithFixed(Interaction prev, TenantStateChange source) {
    TenantStateChange withReferences = visiblesReferences(prev, source);
    fieldsToFix(prev).forEach(withReferences::unset);
    TenantPresetProposal proposal =
        TenantPresetProposal.builder().dto(withReferences).interaction(prev).build();
    presetEmitter.fire(proposal);
    return proposal.getDto();
  }

  /**
   * The input dto with hidden values
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param tenant
   * @return The input dto with hidden values
   */
  public TenantStateProyection copyWithHidden(Interaction prev, Tenant tenant) {
    TenantStateProyection target = new TenantStateProyection(tenant);
    fieldsToHide(prev, tenant).forEach(target::unset);
    return target;
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  public long countVisibles(Interaction prev, TenantFilter filter) {
    return tenantReadRepositoryGateway.count(applyPreVisibilityFilter(prev, filter));
  }

  /**
   * initialsFixFields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @return initialsFixFields
   */
  public Set<String> fieldsToFix(Interaction prev) {
    Set<String> fields = new HashSet<>(fieldsToHide(prev));
    fields.addAll(aggregate.readonlyFields());
    TenantFixedFieldsProposal proposal =
        TenantFixedFieldsProposal.builder().fields(fields).query(prev).build();
    fixedFieldsEmitter.fire(proposal);
    return proposal.getFields();
  }

  /**
   * initialsFixFields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param tenant
   * @return initialsFixFields
   */
  public Set<String> fieldsToFix(Interaction prev, TenantRef tenant) {
    Set<String> fields = new HashSet<>(fieldsToHide(prev, tenant));
    fields.addAll(aggregate.readonlyFields());
    TenantFixedFieldsProposal proposal =
        TenantFixedFieldsProposal.builder().fields(fields).tenant(tenant).query(prev).build();
    fixedFieldsEmitter.fire(proposal);
    return proposal.getFields();
  }

  /**
   * initialsHideFields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @return initialsHideFields
   */
  public Set<String> fieldsToHide(Interaction prev) {
    Set<String> fields = new HashSet<>();
    TenantHiddenFieldsProposal proposal =
        TenantHiddenFieldsProposal.builder().fields(fields).query(prev).build();
    hiddenFieldsEmitter.fire(proposal);
    return proposal.getFields();
  }

  /**
   * initialsHideFields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param tenant
   * @return initialsHideFields
   */
  public Set<String> fieldsToHide(Interaction prev, TenantRef tenant) {
    Set<String> fields = new HashSet<>(fieldsToHide(prev));
    TenantHiddenFieldsProposal proposal =
        TenantHiddenFieldsProposal.builder().fields(fields).tenant(tenant).query(prev).build();
    hiddenFieldsEmitter.fire(proposal);
    return proposal.getFields();
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  public TenantCached listCachedVisibles(Interaction prev, TenantFilter filter,
      TenantCursor cursor) {
    TenantFilter visibleFilter = applyPreVisibilityFilter(prev, filter);
    return cache.retrieve(visibleFilter, cursor)
        .orElseGet(() -> cache.store(visibleFilter, cursor, listVisibles(prev, filter, cursor)));
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  public List<Tenant> listVisibles(Interaction prev, TenantFilter filter, TenantCursor cursor) {
    return queryItems(prev, applyPreVisibilityFilter(prev, filter), cursor);
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  public List<Tenant> listVisiblesForUpdate(Interaction prev, TenantFilter filter,
      TenantCursor cursor) {
    return queryItemsForUpdate(prev, applyPreVisibilityFilter(prev, filter), cursor);
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uid
   * @return The input entity with the copy values without hidden
   */
  public TenantCached retrieveCachedVisible(Interaction prev, String uid) {
    TenantCursor cursor = TenantCursor.builder().limit(1).build();
    TenantFilter visibleFilter =
        applyPreVisibilityFilter(prev, TenantFilter.builder().uid(uid).build());
    return cache.retrieve(visibleFilter, cursor).orElseGet(() -> {
      List<Tenant> list =
          retrieveVisible(prev, uid).<List<Tenant>>map(List::of).orElseGet(List::of);
      return cache.store(visibleFilter, cursor, list);
    });
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uid
   * @return The input entity with the copy values without hidden
   */
  public Optional<Tenant> retrieveVisible(Interaction prev, String uid) {
    TenantFilter filter = applyPreVisibilityFilter(prev, TenantFilter.builder().uid(uid).build());
    return queryItem(prev, uid, filter);
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uid
   * @return The input entity with the copy values without hidden
   */
  public Optional<Tenant> retrieveVisibleForUpdate(Interaction prev, String uid) {
    TenantFilter filter = applyPreVisibilityFilter(prev, TenantFilter.builder().uid(uid).build());
    return queryItemForUpdate(prev, uid, filter);
  }

  /**
   * The self filter modified with the prepared values.
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @return The self filter modified with the prepared values.
   */
  private TenantFilter applyPreVisibilityFilter(Interaction prev, TenantFilter filter) {
    TenantFilterProposal proposal =
        TenantFilterProposal.builder().filter(filter).interaction(prev).build();
    filterProposalEmitter.fire(proposal);
    return proposal.getFilter();
  }

  /**
   * The input dto with hidden values
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param tenantRef The source interaction
   * @return The input dto with hidden values
   */
  private boolean evaluatePostVisibility(Interaction prev, Tenant tenantRef) {
    TenantVisibleContentProposal proposal = TenantVisibleContentProposal.builder().visible(true)
        .entity(tenantRef).interaction(prev).build();
    guardEmitter.fire(proposal);
    return Boolean.TRUE.equals(proposal.getVisible());
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uid
   * @param filter The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  private Optional<Tenant> queryItem(Interaction prev, String uid, TenantFilter filter) {
    return tenantReadRepositoryGateway.retrieve(uid, Optional.of(filter))
        .filter(values -> evaluatePostVisibility(prev, values));
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uid
   * @param filter The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  private Optional<Tenant> queryItemForUpdate(Interaction prev, String uid, TenantFilter filter) {
    return tenantWriteRepositoryGateway.retrieveForUpdate(uid, Optional.of(filter))
        .filter(values -> evaluatePostVisibility(prev, values));
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  private List<Tenant> queryItems(Interaction prev, TenantFilter filter, TenantCursor cursor) {
    List<Tenant> list = new ArrayList<>();
    Iterator<Tenant> slide = tenantReadRepositoryGateway.slide(filter, cursor)
        .slide(values -> evaluatePostVisibility(prev, values));
    while (slide.hasNext()) {
      list.add(slide.next());
    }
    return list;
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  private List<Tenant> queryItemsForUpdate(Interaction prev, TenantFilter filter,
      TenantCursor cursor) {
    List<Tenant> list = new ArrayList<>();
    Iterator<Tenant> slide = tenantWriteRepositoryGateway.slideForUpdate(filter, cursor)
        .slide(values -> evaluatePostVisibility(prev, values));
    while (slide.hasNext()) {
      list.add(slide.next());
    }
    return list;
  }

  /**
   * The input entity with the copy values without hidden
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param source The source interaction
   * @return The input entity with the copy values without hidden
   */
  private TenantStateChange visiblesReferences(Interaction prev, TenantStateChange source) {
    visiblesReferencesFromTrustedClients(prev, source);
    visiblesReferencesFromRelingParties(prev, source);
    return source;
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param source The source interaction
   */
  private void visiblesReferencesFromRelingParties(Interaction prev, TenantStateChange source) {
    source.getRelingParties().map(RelingPartiesVO::getValue).ifPresent(collector -> {
      List<String> collectRelyingParty = new ArrayList<>();
      collector.forEach(item -> {
        if (null != item.getRelyingParty()) {
          String idRelyingParty = item.getRelyingPartyReferenceValue();
          if (!collectRelyingParty.contains(idRelyingParty)) {
            collectRelyingParty.add(idRelyingParty);
          }
        }
      });
      if (!collectRelyingParty.isEmpty()) {
        boolean visible = relyingPartysVisibility.checkVisibility(prev, collectRelyingParty);
        if (!visible) {
          throw new NotFoundException("No all relying party exists: " + collectRelyingParty);
        }
      }
    });
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param source The source interaction
   */
  private void visiblesReferencesFromTrustedClients(Interaction prev, TenantStateChange source) {
    source.getTrustedClients().map(TrustedClientsVO::getValue).ifPresent(collector -> {
      List<String> collectTrustedClient = new ArrayList<>();
      collector.forEach(item -> {
        if (null != item.getTrustedClient()) {
          String idTrustedClient = item.getTrustedClientReferenceValue();
          if (!collectTrustedClient.contains(idTrustedClient)) {
            collectTrustedClient.add(idTrustedClient);
          }
        }
      });
      if (!collectTrustedClient.isEmpty()) {
        boolean visible = trustedClientsVisibility.checkVisibility(prev, collectTrustedClient);
        if (!visible) {
          throw new NotFoundException("No all trusted client exists: " + collectTrustedClient);
        }
      }
    });
  }
}
