package net.civeira.phylax.features.access.apikeyclient.application.visibility;

import java.util.NoSuchElementException;
import java.util.Optional;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import net.civeira.phylax.features.access.apikeyclient.domain.ApiKeyClient;
import net.civeira.phylax.features.access.apikeyclient.domain.ApiKeyClientReference;
import net.civeira.phylax.features.access.apikeyclient.domain.valueobject.CodeVO;
import net.civeira.phylax.features.access.apikeyclient.domain.valueobject.EnabledVO;
import net.civeira.phylax.features.access.apikeyclient.domain.valueobject.KeyVO;
import net.civeira.phylax.features.access.apikeyclient.domain.valueobject.ScopesVO;
import net.civeira.phylax.features.access.apikeyclient.domain.valueobject.UidVO;
import net.civeira.phylax.features.access.apikeyclient.domain.valueobject.VersionVO;

/**
 * Visible projection events happen when a dto is filled throught an existint entity when the
 * visibility service is preparing to send at user.The programmers could add policies to fill dto
 * values to show to user at the application level.
 */
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ApiKeyClientVisibleProjection {

  /**
   * El código identificativo de la aplicación
   *
   * @autogenerated VisibleProjectionGenerator
   */
  @Builder.Default
  private Optional<CodeVO> code = Optional.empty();

  /**
   * The indicator to allow the account be used without deleting it
   *
   * @autogenerated VisibleProjectionGenerator
   */
  @Builder.Default
  private Optional<EnabledVO> enabled = Optional.empty();

  /**
   * The key for the api
   *
   * @autogenerated VisibleProjectionGenerator
   */
  @Builder.Default
  private Optional<KeyVO> key = Optional.empty();

  /**
   * A coma separated scopes for the api key
   *
   * @autogenerated VisibleProjectionGenerator
   */
  @Builder.Default
  private Optional<ScopesVO> scopes = Optional.empty();

  /**
   * El identificador de la aplicacion
   *
   * @autogenerated VisibleProjectionGenerator
   */
  @Builder.Default
  private Optional<UidVO> uid = Optional.empty();

  /**
   * Campo con el número de version de api key client para controlar bloqueos optimistas
   *
   * @autogenerated VisibleProjectionGenerator
   */
  @Builder.Default
  private Optional<VersionVO> version = Optional.empty();

  /**
   * Create a dto instance with all the values of an entity
   *
   * @autogenerated VisibleProjectionGenerator
   * @param entity The entity who provide values.
   */
  public ApiKeyClientVisibleProjection(final ApiKeyClient entity) {
    uid = Optional.of(entity.getUidValue());
    code = Optional.of(entity.getCodeValue());
    key = Optional.of(entity.getKeyValue());
    enabled = Optional.of(entity.getEnabledValue());
    scopes = Optional.of(entity.getScopesValue());
    version = Optional.of(entity.getVersionValue());
  }

  /**
   * Create a reference for api key client with his inner assigned value.
   *
   * @autogenerated VisibleProjectionGenerator
   * @throws NoSuchElementException If no uid is set with a value
   * @return A reference if the direct reference build from stored value, otherwise an exception
   *         will be thrown.
   */
  public ApiKeyClientReference asReference() throws NoSuchElementException {
    return uid.map(UidVO::getUid).map(ApiKeyClientReference::of).orElseThrow();
  }

  /**
   * Inform for a possible change propolsal in Code
   *
   * @autogenerated VisibleProjectionGenerator
   * @return empty if there is no change proposal for Code, otherwise the value for Code
   */
  public Optional<CodeVO> getCode() {
    return code;
  }

  /**
   * Inform for a possible change propolsal in Enabled
   *
   * @autogenerated VisibleProjectionGenerator
   * @return empty if there is no change proposal for Enabled, otherwise the value for Enabled
   */
  public Optional<EnabledVO> getEnabled() {
    return enabled;
  }

  /**
   * Inform for a possible change propolsal in Key
   *
   * @autogenerated VisibleProjectionGenerator
   * @return empty if there is no change proposal for Key, otherwise the value for Key
   */
  public Optional<KeyVO> getKey() {
    return key;
  }

  /**
   * Inform for a possible change propolsal in Scopes
   *
   * @autogenerated VisibleProjectionGenerator
   * @return empty if there is no change proposal for Scopes, otherwise the value for Scopes
   */
  public Optional<ScopesVO> getScopes() {
    return scopes;
  }

  /**
   * Inform for a possible change propolsal in Uid
   *
   * @autogenerated VisibleProjectionGenerator
   * @return empty if there is no change proposal for Uid, otherwise the value for Uid
   */
  public Optional<UidVO> getUid() {
    return uid;
  }

  /**
   * Inform for a possible change propolsal in Version
   *
   * @autogenerated VisibleProjectionGenerator
   * @return empty if there is no change proposal for Version, otherwise the value for Version
   */
  public Optional<VersionVO> getVersion() {
    return version;
  }

  /**
   * Assigna change proposal for Code to be apply for the aggregate.
   *
   * @autogenerated VisibleProjectionGenerator
   * @param value The proposal value for ApiKeyClientVisibleProjection
   * @return self instance to enable a flow code
   */
  public ApiKeyClientVisibleProjection setCode(final String value) {
    this.code = Optional.of(CodeVO.from(value));
    return this;
  }

  /**
   * Assigna change proposal for Enabled to be apply for the aggregate.
   *
   * @autogenerated VisibleProjectionGenerator
   * @param value The proposal value for ApiKeyClientVisibleProjection
   * @return self instance to enable a flow code
   */
  public ApiKeyClientVisibleProjection setEnabled(final Boolean value) {
    this.enabled = Optional.of(EnabledVO.from(value));
    return this;
  }

  /**
   * Assigna change proposal for Key to be apply for the aggregate.
   *
   * @autogenerated VisibleProjectionGenerator
   * @param value The proposal value for ApiKeyClientVisibleProjection
   * @return self instance to enable a flow code
   */
  public ApiKeyClientVisibleProjection setKey(final String value) {
    this.key = Optional.of(KeyVO.from(value));
    return this;
  }

  /**
   * Assigna change proposal for Scopes to be apply for the aggregate.
   *
   * @autogenerated VisibleProjectionGenerator
   * @param value The proposal value for ApiKeyClientVisibleProjection
   * @return self instance to enable a flow code
   */
  public ApiKeyClientVisibleProjection setScopes(final String value) {
    this.scopes = Optional.of(ScopesVO.from(value));
    return this;
  }

  /**
   * Assigna change proposal for Uid to be apply for the aggregate.
   *
   * @autogenerated VisibleProjectionGenerator
   * @param value The proposal value for ApiKeyClientVisibleProjection
   * @return self instance to enable a flow code
   */
  public ApiKeyClientVisibleProjection setUid(final String value) {
    this.uid = Optional.of(UidVO.from(value));
    return this;
  }

  /**
   * Assigna change proposal for Version to be apply for the aggregate.
   *
   * @autogenerated VisibleProjectionGenerator
   * @param value The proposal value for ApiKeyClientVisibleProjection
   * @return self instance to enable a flow code
   */
  public ApiKeyClientVisibleProjection setVersion(final Integer value) {
    this.version = Optional.of(VersionVO.from(value));
    return this;
  }

  /**
   * Unset a value by the property name. Unset values will no provide command change neither provide
   * information to the output context (hidden or readonly fields, or policy restrictions).
   *
   * @autogenerated VisibleProjectionGenerator
   * @param field The field name to unset.
   */
  public void unset(final String field) {
    if ("uid".equals(field)) {
      this.unsetUid();
    }
    if ("code".equals(field)) {
      this.unsetCode();
    }
    if ("key".equals(field)) {
      this.unsetKey();
    }
    if ("enabled".equals(field)) {
      this.unsetEnabled();
    }
    if ("scopes".equals(field)) {
      this.unsetScopes();
    }
    if ("version".equals(field)) {
      this.unsetVersion();
    }
  }

  /**
   * Remove the change propolsal for Code
   *
   * @autogenerated VisibleProjectionGenerator
   * @return self instance to enable a flow code.
   */
  public ApiKeyClientVisibleProjection unsetCode() {
    this.code = Optional.empty();
    return this;
  }

  /**
   * Remove the change propolsal for Enabled
   *
   * @autogenerated VisibleProjectionGenerator
   * @return self instance to enable a flow code.
   */
  public ApiKeyClientVisibleProjection unsetEnabled() {
    this.enabled = Optional.empty();
    return this;
  }

  /**
   * Remove the change propolsal for Key
   *
   * @autogenerated VisibleProjectionGenerator
   * @return self instance to enable a flow code.
   */
  public ApiKeyClientVisibleProjection unsetKey() {
    this.key = Optional.empty();
    return this;
  }

  /**
   * Remove the change propolsal for Scopes
   *
   * @autogenerated VisibleProjectionGenerator
   * @return self instance to enable a flow code.
   */
  public ApiKeyClientVisibleProjection unsetScopes() {
    this.scopes = Optional.empty();
    return this;
  }

  /**
   * Remove the change propolsal for Uid
   *
   * @autogenerated VisibleProjectionGenerator
   * @return self instance to enable a flow code.
   */
  public ApiKeyClientVisibleProjection unsetUid() {
    this.uid = Optional.empty();
    return this;
  }

  /**
   * Remove the change propolsal for Version
   *
   * @autogenerated VisibleProjectionGenerator
   * @return self instance to enable a flow code.
   */
  public ApiKeyClientVisibleProjection unsetVersion() {
    this.version = Optional.empty();
    return this;
  }
}
