package net.civeira.phylax.features.access.tenantconfig.domain.valueobject;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import net.civeira.phylax.common.exception.ConstraintException;

class InvitationExpiryDaysVOUnitTest {

  /**
   * @autogenerated ValueObjectGenerator
   */
  @Test
  @DisplayName("Test value object contruction for property invitation expiry days of tenant config ")
  void test_invitation_expiry_days_v_o_builder() {
    Assertions.assertThrows(ConstraintException.class, () -> InvitationExpiryDaysVO.tryFrom(null));
    Assertions.assertEquals(1, InvitationExpiryDaysVO.from(1).getInvitationExpiryDays());
    Object falingInstance = new Object() {};
    Assertions.assertThrows(ConstraintException.class,
        () -> InvitationExpiryDaysVO.tryFrom(falingInstance));
    Assertions.assertEquals("[" + 1 + "]", InvitationExpiryDaysVO.from(1).toString());
  }
}
