package net.civeira.phylax.features.document.snippetasset.application.usecase.contentupload;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.exception.NotAllowedException;
import net.civeira.phylax.common.exception.NotFoundException;
import net.civeira.phylax.common.infrastructure.store.BinaryContent;
import net.civeira.phylax.common.security.OperationContext;
import net.civeira.phylax.common.security.Permission;
import net.civeira.phylax.common.telemetry.Observed;
import net.civeira.phylax.common.telemetry.Trace;
import net.civeira.phylax.features.document.snippetasset.domain.gateway.SnippetAssetContentUploadGateway;

@ApplicationScoped
@RequiredArgsConstructor
public class SnippetAssetContentTemporalUploadUsecase {

  /**
   * @autogenerated ListUsecaseGenerator
   */
  private final SnippetAssetContentUploadGateway store;

  /**
   * @autogenerated ListUsecaseGenerator
   */
  private final Event<SnippetAssetContentTemporalUploadAuthorizationDecision> tempUploadAllowEmitter;

  /**
   * @autogenerated ListUsecaseGenerator
   * @param context
   * @return
   */
  @Observed("Checking if is allowed to upload a content in an entity of snippet asset")
  public Permission allow(final OperationContext context) {
    Permission response = checkPermission(context);
    Trace.setAttribute("allowed", response.isAllowed());
    return response;
  }

  /**
   * @autogenerated ListUsecaseGenerator
   * @param context
   * @param key
   * @return
   */
  @Observed("Reading temporal uplad of a content in an entity of snippet asset")
  public BinaryContent read(final OperationContext context, final String key) {
    Permission detail = checkPermission(context);
    if (!detail.isAllowed()) {
      Trace.addEvent(
          "The policies for snippet asset dont allow to create: " + detail.getDescription());
      throw new NotAllowedException(detail.getDescription());
    }
    return store.readTemporalContent(key).orElseThrow(() -> new NotFoundException(""));
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated ListUsecaseGenerator
   * @param context
   * @param binary a filter to retrieve only matching values
   * @return The slide with some values
   */
  @Observed("Uploading a content in an entity of snippet asset")
  public String upload(final OperationContext context, final BinaryContent binary) {
    Permission detail = checkPermission(context);
    if (!detail.isAllowed()) {
      Trace.addEvent(
          "The policies for snippet asset dont allow to create: " + detail.getDescription());
      throw new NotAllowedException(detail.getDescription());
    }
    return store.storeTemporalContent(binary);
  }

  /**
   * @autogenerated ListUsecaseGenerator
   * @param context
   * @return
   */
  private Permission checkPermission(final OperationContext context) {
    SnippetAssetContentTemporalUploadAuthorizationDecision proposal =
        new SnippetAssetContentTemporalUploadAuthorizationDecision(context,
            Permission.allow("Allow to upload by default"));
    tempUploadAllowEmitter.fire(proposal);
    return proposal.getPermission();
  }
}
