package net.civeira.phylax.features.access.trustedclient.domain.valueobject;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import net.civeira.phylax.common.exception.ConstraintException;

class JwksUriVOUnitTest {

  /**
   * @autogenerated ValueObjectGenerator
   */
  @Test
  @DisplayName("Test value object contruction for property jwks uri of trusted client ")
  void test_jwks_uri_v_o_builder() {
    Assertions.assertFalse(JwksUriVO.nullValue().getJwksUri().isPresent(),
        "A empty vo should have a null value");
    Assertions.assertFalse(JwksUriVO.tryFrom(null).getJwksUri().isPresent(),
        "With a null value, no present result");
    Assertions.assertEquals("one", JwksUriVO.from("one").getJwksUri().orElse(null));
    Object falingInstance = new Object() {};
    Assertions.assertThrows(ConstraintException.class, () -> JwksUriVO.tryFrom(falingInstance));
    Assertions.assertEquals("[" + "one" + "]", JwksUriVO.from("one").toString());
  }
}
