package net.civeira.phylax.features.access.tenantloginprovider.domain.valueobject;

import java.util.Map;
import java.util.Optional;

import lombok.EqualsAndHashCode;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.exception.ConstraintException;
import net.civeira.phylax.common.value.validation.AbstractFailList;
import net.civeira.phylax.common.value.validation.ConstraintFail;
import net.civeira.phylax.common.value.validation.ConstraintFailList;

/**
 * Value Object representing el saml idp entity id de tenant login provider of tenantLoginProvider.
 * <p>
 * This class ensures that the saml idp entity id is a {@code String} and encapsulates its
 * validation and formatting logic. It is immutable and compliant with DDD (Domain-Driven Design)
 * principles.
 * </p>
 * <p>
 * Use {@link #from(String)} or {@link #tryFrom(Object)} to safely create instances. Validation
 * errors are reported via {@link ConstraintFailList} or thrown as {@link ConstraintException}.
 * </p>
 */
@RequiredArgsConstructor
@EqualsAndHashCode
public class SamlIdpEntityIdVO {

  /**
   * Crear an empty instance with no value
   *
   * @autogenerated ValueObjectGenerator
   * @param samlIdpEntityId
   * @return An empty instance
   */
  public static SamlIdpEntityIdVO from(final String samlIdpEntityId) {
    return tryFrom(samlIdpEntityId);
  }

  /**
   * Crear an empty instance with no value
   *
   * @autogenerated ValueObjectGenerator
   * @return An empty instance
   */
  public static SamlIdpEntityIdVO nullValue() {
    return new SamlIdpEntityIdVO(null);
  }

  /**
   * Crear an empty instance with no value
   *
   * @autogenerated ValueObjectGenerator
   * @param samlIdpEntityId
   * @return An empty instance
   */
  public static SamlIdpEntityIdVO tryFrom(final Object samlIdpEntityId) {
    ConstraintFailList list = new ConstraintFailList();
    SamlIdpEntityIdVO result = tryFrom(samlIdpEntityId, list);
    if (list.hasErrors()) {
      throw new ConstraintException("Invalid value for SamlIdpEntityIdVO.saml-idp-entity-id", list);
    }
    return result;
  }

  /**
   * Crear an empty instance with no value
   *
   * @autogenerated ValueObjectGenerator
   * @param samlIdpEntityId temptative value
   * @param fails Error list
   * @return An empty instance
   */
  public static <T extends AbstractFailList> SamlIdpEntityIdVO tryFrom(final Object samlIdpEntityId,
      final T fails) {
    if (null == samlIdpEntityId) {
      return new SamlIdpEntityIdVO(null);
    } else if (samlIdpEntityId instanceof String castedSamlIdpEntityId) {
      return new SamlIdpEntityIdVO(castedSamlIdpEntityId);
    } else {
      fails.add(new ConstraintFail("wrong-type", "samlIdpEntityId", samlIdpEntityId.getClass(),
          "A String type is expected for samlIdpEntityId"));
      return null;
    }
  }

  /**
   * The actual value of the name.
   *
   * @autogenerated ValueObjectGenerator
   */
  private final String value;

  /**
   * Get the vo value
   *
   * @autogenerated ValueObjectGenerator
   * @return
   */
  public Optional<String> getSamlIdpEntityId() {
    return Optional.ofNullable(value);
  }

  /**
   * @autogenerated ValueObjectGenerator
   * @param map
   */
  public void samlIdpEntityIdToMap(final Map<String, String> map) {
    if (null != value) {
      map.put("samlIdpEntityId", String.valueOf(value));
    }
  }

  /**
   * Returns a formatted string representation of the name.
   *
   * @autogenerated ValueObjectGenerator
   * @return the string value wrapped in square brackets.
   */
  @Override
  public String toString() {
    return "[" + value + "]";
  }
}
