package net.civeira.phylax.features.access.securitydomain.valueobject;

import java.util.Optional;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.With;
import net.civeira.phylax.common.exception.ConstraintException;
import net.civeira.phylax.common.value.validation.AbstractFailList;
import net.civeira.phylax.common.value.validation.ConstraintFail;
import net.civeira.phylax.common.value.validation.ConstraintFailList;

/**
 * Value Object representing allow to write on every scope of securityDomain.
 * <p>
 * This class ensures that the write all is a {@code String} and encapsulates its validation and
 * formatting logic. It is immutable and compliant with DDD (Domain-Driven Design) principles.
 * </p>
 * <p>
 * Use {@link #from(String)} or {@link #tryFrom(Object)} to safely create instances. Validation
 * errors are reported via {@link ConstraintFailList} or thrown as {@link ConstraintException}.
 * </p>
 */
@Getter
@RequiredArgsConstructor
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class WriteAllVO {

  /**
   * An empty instance
   *
   * @autogenerated ValueObjectGenerator
   * @param writeAll
   * @return An empty instance
   */
  public static WriteAllVO from(final Boolean writeAll) {
    return tryFrom(writeAll);
  }

  /**
   * An empty instance
   *
   * @autogenerated ValueObjectGenerator
   * @return An empty instance
   */
  public static WriteAllVO nullValue() {
    return new WriteAllVO(null);
  }

  /**
   * An empty instance
   *
   * @autogenerated ValueObjectGenerator
   * @param writeAll
   * @return An empty instance
   */
  public static WriteAllVO tryFrom(final Object writeAll) {
    ConstraintFailList list = new ConstraintFailList();
    WriteAllVO result = tryFrom(writeAll, list);
    if (list.hasErrors()) {
      throw new ConstraintException(list);
    }
    return result;
  }

  /**
   * An empty instance
   *
   * @autogenerated ValueObjectGenerator
   * @param writeAll temptative value
   * @param fails Error list
   * @return An empty instance
   */
  public static <T extends AbstractFailList> WriteAllVO tryFrom(final Object writeAll,
      final T fails) {
    if (null == writeAll) {
      return new WriteAllVO(null);
    } else if (writeAll instanceof Boolean castedWriteAll) {
      return new WriteAllVO(castedWriteAll);
    } else {
      fails.add(new ConstraintFail("wrong-type", "writeAll", writeAll.getClass(),
          "A Boolean type is expected for writeAll"));
      return null;
    }
  }

  /**
   * The actual value of the name.
   *
   * @autogenerated ValueObjectGenerator
   */
  private final Boolean value;

  /**
   * @autogenerated ValueObjectGenerator
   * @return
   */
  public Optional<Boolean> getValue() {
    return Optional.ofNullable(value);
  }

  /**
   * the string value wrapped in square brackets.
   *
   * @autogenerated ValueObjectGenerator
   * @return the string value wrapped in square brackets.
   */
  @Override
  public String toString() {
    return "[" + value + "]";
  }
}
