package net.civeira.phylax.features.access.clientidentity.application.visibility;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.exception.NotFoundException;
import net.civeira.phylax.common.security.Interaction;
import net.civeira.phylax.features.access.clientidentity.domain.ClientIdentity;
import net.civeira.phylax.features.access.clientidentity.domain.ClientIdentityChangeSet;
import net.civeira.phylax.features.access.clientidentity.domain.ClientIdentityRef;
import net.civeira.phylax.features.access.clientidentity.domain.gateway.ClientIdentityCacheGateway;
import net.civeira.phylax.features.access.clientidentity.domain.gateway.ClientIdentityCached;
import net.civeira.phylax.features.access.clientidentity.domain.gateway.ClientIdentityCursor;
import net.civeira.phylax.features.access.clientidentity.domain.gateway.ClientIdentityFilter;
import net.civeira.phylax.features.access.clientidentity.domain.gateway.ClientIdentityReadRepositoryGateway;
import net.civeira.phylax.features.access.clientidentity.domain.gateway.ClientIdentityWriteRepositoryGateway;
import net.civeira.phylax.features.access.clientidentity.domain.valueobject.RelyingPartyVO;
import net.civeira.phylax.features.access.clientidentity.domain.valueobject.TrustedClientVO;
import net.civeira.phylax.features.access.clientidentity.domain.valueobject.UserVO;
import net.civeira.phylax.features.access.relyingparty.application.visibility.RelyingPartysVisibility;
import net.civeira.phylax.features.access.trustedclient.application.visibility.TrustedClientsVisibility;
import net.civeira.phylax.features.access.user.application.visibility.UsersVisibility;

@ApplicationScoped
@RequiredArgsConstructor
public class ClientIdentitysVisibility {

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final ClientIdentityCacheGateway cache;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final ClientIdentityReadRepositoryGateway clientIdentityReadRepositoryGateway;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final ClientIdentityWriteRepositoryGateway clientIdentityWriteRepositoryGateway;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<ClientIdentityVisibilityCheck> filterProposalEmitter;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<ClientIdentityFixedFieldsCheck> fixedFieldsEmitter;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<ClientIdentityAccesibleCheck> guardEmitter;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<ClientIdentityHiddenFieldsCheck> hiddenFieldsEmitter;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final Event<ClientIdentityEntityEnrichment> presetEmitter;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final RelyingPartysVisibility relyingPartysVisibility;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final TrustedClientsVisibility trustedClientsVisibility;

  /**
   * @autogenerated VisibilityServiceGenerator
   */
  private final UsersVisibility usersVisibility;

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uid
   * @return The input entity with the copy values without hidden
   */
  public boolean checkVisibility(Interaction prev, String uid) {
    return retrieveVisible(prev, uid).isPresent();
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uids
   * @return The input entity with the copy values without hidden
   */
  public boolean checkVisibility(Interaction prev, List<String> uids) {
    return uids
        .size() == listVisibles(prev, ClientIdentityVisibilityFilter.builder().uids(uids).build(),
            ClientIdentityCursor.builder().build()).size();
  }

  /**
   * Retrieve the list of fields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param source The source interaction
   * @param original The source interaction
   * @return The input entity with the copy values without hidden
   */
  public ClientIdentityChangeSet copyWithFixed(Interaction prev, ClientIdentityChangeSet source,
      ClientIdentity original) {
    ClientIdentityChangeSet withReferences = visiblesReferences(prev, source);
    fieldsToFix(prev, original).forEach(withReferences::unset);
    ClientIdentityEntityEnrichment proposal = ClientIdentityEntityEnrichment.builder()
        .dto(withReferences).interaction(prev).original(original).build();
    presetEmitter.fire(proposal);
    return proposal.getDto();
  }

  /**
   * Retrieve the list of fields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param source The source interaction
   * @return The input entity with the copy values without hidden
   */
  public ClientIdentityChangeSet copyWithFixed(Interaction prev, ClientIdentityChangeSet source) {
    ClientIdentityChangeSet withReferences = visiblesReferences(prev, source);
    fieldsToFix(prev).forEach(withReferences::unset);
    ClientIdentityEntityEnrichment proposal =
        ClientIdentityEntityEnrichment.builder().dto(withReferences).interaction(prev).build();
    presetEmitter.fire(proposal);
    return proposal.getDto();
  }

  /**
   * Retrieve the list of fields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param clientIdentity
   * @return The input dto with hidden values
   */
  public ClientIdentityVisibleProjection copyWithHidden(Interaction prev,
      ClientIdentity clientIdentity) {
    ClientIdentityVisibleProjection target = new ClientIdentityVisibleProjection(clientIdentity);
    fieldsToHide(prev, clientIdentity).forEach(target::unset);
    return target;
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  public long countVisibles(Interaction prev, ClientIdentityVisibilityFilter filter) {
    return clientIdentityReadRepositoryGateway.count(applyPreVisibilityFilter(prev, filter));
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @return initialsFixFields
   */
  public Set<String> fieldsToFix(Interaction prev) {
    Set<String> fields = new HashSet<>(fieldsToHide(prev));
    ClientIdentityFixedFieldsCheck proposal =
        ClientIdentityFixedFieldsCheck.builder().fields(fields).query(prev).build();
    fixedFieldsEmitter.fire(proposal);
    return proposal.getFields();
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param clientIdentity
   * @return initialsFixFields
   */
  public Set<String> fieldsToFix(Interaction prev, ClientIdentityRef clientIdentity) {
    Set<String> fields = new HashSet<>(fieldsToHide(prev, clientIdentity));
    ClientIdentityFixedFieldsCheck proposal = ClientIdentityFixedFieldsCheck.builder()
        .fields(fields).clientIdentity(clientIdentity).query(prev).build();
    fixedFieldsEmitter.fire(proposal);
    return proposal.getFields();
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @return initialsHideFields
   */
  public Set<String> fieldsToHide(Interaction prev) {
    Set<String> fields = new HashSet<>();
    ClientIdentityHiddenFieldsCheck proposal =
        ClientIdentityHiddenFieldsCheck.builder().fields(fields).query(prev).build();
    hiddenFieldsEmitter.fire(proposal);
    return proposal.getFields();
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param clientIdentity
   * @return initialsHideFields
   */
  public Set<String> fieldsToHide(Interaction prev, ClientIdentityRef clientIdentity) {
    Set<String> fields = new HashSet<>(fieldsToHide(prev));
    ClientIdentityHiddenFieldsCheck proposal = ClientIdentityHiddenFieldsCheck.builder()
        .fields(fields).clientIdentity(clientIdentity).query(prev).build();
    hiddenFieldsEmitter.fire(proposal);
    return proposal.getFields();
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  public ClientIdentityCached listCachedVisibles(Interaction prev,
      ClientIdentityVisibilityFilter filter, ClientIdentityCursor cursor) {
    ClientIdentityFilter visibleFilter = applyPreVisibilityFilter(prev, filter);
    return cache.retrieve(visibleFilter, cursor)
        .orElseGet(() -> cache.store(visibleFilter, cursor, listVisibles(prev, filter, cursor)));
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  public List<ClientIdentity> listVisibles(Interaction prev, ClientIdentityVisibilityFilter filter,
      ClientIdentityCursor cursor) {
    return queryItems(prev, applyPreVisibilityFilter(prev, filter), cursor);
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  public List<ClientIdentity> listVisiblesForUpdate(Interaction prev,
      ClientIdentityVisibilityFilter filter, ClientIdentityCursor cursor) {
    return queryItemsForUpdate(prev, applyPreVisibilityFilter(prev, filter), cursor);
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uid
   * @return The input entity with the copy values without hidden
   */
  public ClientIdentityCached retrieveCachedVisible(Interaction prev, String uid) {
    ClientIdentityCursor cursor = ClientIdentityCursor.builder().limit(1).build();
    ClientIdentityFilter visibleFilter =
        applyPreVisibilityFilter(prev, ClientIdentityVisibilityFilter.builder().uid(uid).build());
    return cache.retrieve(visibleFilter, cursor).orElseGet(() -> {
      List<ClientIdentity> list =
          retrieveVisible(prev, uid).<List<ClientIdentity>>map(List::of).orElseGet(List::of);
      return cache.store(visibleFilter, cursor, list);
    });
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uid
   * @return The input entity with the copy values without hidden
   */
  public Optional<ClientIdentity> retrieveVisible(Interaction prev, String uid) {
    ClientIdentityFilter filter =
        applyPreVisibilityFilter(prev, ClientIdentityVisibilityFilter.builder().uid(uid).build());
    return queryItem(prev, uid, filter);
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uid
   * @return The input entity with the copy values without hidden
   */
  public Optional<ClientIdentity> retrieveVisibleForUpdate(Interaction prev, String uid) {
    ClientIdentityFilter filter =
        applyPreVisibilityFilter(prev, ClientIdentityVisibilityFilter.builder().uid(uid).build());
    return queryItemForUpdate(prev, uid, filter);
  }

  /**
   * Retrieve the list of fields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @return The self filter modified with the prepared values.
   */
  private ClientIdentityFilter applyPreVisibilityFilter(Interaction prev,
      ClientIdentityVisibilityFilter filter) {
    ClientIdentityVisibilityCheck proposal =
        ClientIdentityVisibilityCheck.builder().filter(filter).interaction(prev).build();
    filterProposalEmitter.fire(proposal);
    ClientIdentityVisibilityFilter modified = proposal.getFilter();
    return ClientIdentityFilter.builder().uid(modified.getUid().orElse(null))
        .uids(modified.getUids().stream().toList()).search(modified.getSearch().orElse(null))
        .forAllAudiences(modified.getForAllAudiences().orElse(null))
        .user(modified.getUser().orElse(null)).users(modified.getUsers())
        .relyingParty(modified.getRelyingParty().orElse(null))
        .relyingPartys(modified.getRelyingPartys())
        .trustedClient(modified.getTrustedClient().orElse(null))
        .trustedClients(modified.getTrustedClients())
        .userTenantTenantAccesible(modified.getUserTenantTenantAccesible().orElse(null)).build();
  }

  /**
   * Retrieve the list of fields
   *
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param clientIdentityRef The source interaction
   * @return The input dto with hidden values
   */
  private boolean evaluatePostVisibility(Interaction prev, ClientIdentity clientIdentityRef) {
    ClientIdentityAccesibleCheck proposal = ClientIdentityAccesibleCheck.builder().visible(true)
        .entity(clientIdentityRef).interaction(prev).build();
    guardEmitter.fire(proposal);
    return Boolean.TRUE.equals(proposal.getVisible());
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uid
   * @param filter The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  private Optional<ClientIdentity> queryItem(Interaction prev, String uid,
      ClientIdentityFilter filter) {
    return clientIdentityReadRepositoryGateway.retrieve(uid, Optional.of(filter))
        .filter(values -> evaluatePostVisibility(prev, values));
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param uid
   * @param filter The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  private Optional<ClientIdentity> queryItemForUpdate(Interaction prev, String uid,
      ClientIdentityFilter filter) {
    return clientIdentityWriteRepositoryGateway.retrieveForUpdate(uid, Optional.of(filter))
        .filter(values -> evaluatePostVisibility(prev, values));
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  private List<ClientIdentity> queryItems(Interaction prev, ClientIdentityFilter filter,
      ClientIdentityCursor cursor) {
    List<ClientIdentity> list = new ArrayList<>();
    Iterator<ClientIdentity> slide = clientIdentityReadRepositoryGateway.slide(filter, cursor)
        .slide(values -> evaluatePostVisibility(prev, values));
    while (slide.hasNext()) {
      list.add(slide.next());
    }
    return list;
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param filter The filter to retrieve values
   * @param cursor The filter to retrieve values
   * @return The input entity with the copy values without hidden
   */
  private List<ClientIdentity> queryItemsForUpdate(Interaction prev, ClientIdentityFilter filter,
      ClientIdentityCursor cursor) {
    List<ClientIdentity> list = new ArrayList<>();
    Iterator<ClientIdentity> slide = clientIdentityWriteRepositoryGateway
        .slideForUpdate(filter, cursor).slide(values -> evaluatePostVisibility(prev, values));
    while (slide.hasNext()) {
      list.add(slide.next());
    }
    return list;
  }

  /**
   * @autogenerated VisibilityServiceGenerator
   * @param prev The source interaction
   * @param source The source interaction
   * @return The input entity with the copy values without hidden
   */
  private ClientIdentityChangeSet visiblesReferences(Interaction prev,
      ClientIdentityChangeSet source) {
    source.getUserValue().map(UserVO::getUserUid).ifPresent(user -> {
      boolean visible = usersVisibility.checkVisibility(prev, user);
      if (!visible) {
        throw new NotFoundException("No user - " + user);
      }
    });
    source.getRelyingPartyValue().flatMap(RelyingPartyVO::getRelyingPartyUid).ifPresent(ref -> {
      boolean visible = relyingPartysVisibility.checkVisibility(prev, ref);
      if (!visible) {
        throw new NotFoundException("No relying party - " + ref);
      }
    });
    source.getTrustedClientValue().flatMap(TrustedClientVO::getTrustedClientUid).ifPresent(ref -> {
      boolean visible = trustedClientsVisibility.checkVisibility(prev, ref);
      if (!visible) {
        throw new NotFoundException("No trusted client - " + ref);
      }
    });
    return source;
  }
}
