package net.civeira.phylax.features.access.apikeyclient.infrastructure.repository;

import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Predicate;

import javax.sql.DataSource;

import io.opentelemetry.api.trace.Tracer;
import jakarta.enterprise.context.ApplicationScoped;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import net.civeira.phylax.common.algorithms.Slider;
import net.civeira.phylax.common.exception.ConstraintException;
import net.civeira.phylax.common.exception.NotFoundException;
import net.civeira.phylax.common.infrastructure.sql.OptimistLockException;
import net.civeira.phylax.common.infrastructure.sql.SqlCommand;
import net.civeira.phylax.common.infrastructure.sql.SqlConverter;
import net.civeira.phylax.common.infrastructure.sql.SqlListParameterValue;
import net.civeira.phylax.common.infrastructure.sql.SqlOperator;
import net.civeira.phylax.common.infrastructure.sql.SqlParameterValue;
import net.civeira.phylax.common.infrastructure.sql.SqlQuery;
import net.civeira.phylax.common.infrastructure.sql.SqlResult;
import net.civeira.phylax.common.infrastructure.sql.SqlSchematicQuery;
import net.civeira.phylax.common.infrastructure.sql.SqlTemplate;
import net.civeira.phylax.features.access.apikeyclient.domain.ApiKeyClient;
import net.civeira.phylax.features.access.apikeyclient.domain.ApiKeyClientRef;
import net.civeira.phylax.features.access.apikeyclient.domain.gateway.ApiKeyClientCursor;
import net.civeira.phylax.features.access.apikeyclient.domain.gateway.ApiKeyClientFilter;
import net.civeira.phylax.features.access.apikeyclient.domain.valueobject.CodeVO;
import net.civeira.phylax.features.access.apikeyclient.domain.valueobject.EnabledVO;
import net.civeira.phylax.features.access.apikeyclient.domain.valueobject.KeyVO;
import net.civeira.phylax.features.access.apikeyclient.domain.valueobject.ScopesVO;
import net.civeira.phylax.features.access.apikeyclient.domain.valueobject.UidVO;
import net.civeira.phylax.features.access.apikeyclient.domain.valueobject.VersionVO;

@ApplicationScoped
@RequiredArgsConstructor
@Slf4j
public class ApiKeyClientRepository {

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String ACCESS_API_KEY_CLIENT_CODE = "access_api_key_client.code";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String ACCESS_API_KEY_CLIENT_ENABLED = "access_api_key_client.enabled";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String ACCESS_API_KEY_CLIENT_KEY = "access_api_key_client.key";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String ACCESS_API_KEY_CLIENT_SCOPES = "access_api_key_client.scopes";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String ACCESS_API_KEY_CLIENT_SNAKE = "access_api_key_client";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String ACCESS_API_KEY_CLIENT_UID = "access_api_key_client.uid";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String ACCESS_API_KEY_CLIENT_VERSION = "access_api_key_client.version";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String CODE = "code";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String ENABLED = "enabled";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String KEY = "key";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String SCOPES = "scopes";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String UID = "uid";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String VERSION = "version";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private final DataSource datasource;

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private final Tracer tracer;

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public long count(ApiKeyClientFilter filter) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlSchematicQuery<Long> sq = filteredQuery(template, filter);
      sq.select("count(uid) as uid");
      return sq.query(row -> Optional.of(row.getLong(1))).one().orElse(0l);
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   * @return
   */
  public ApiKeyClient create(ApiKeyClient entity) {
    return runCreate(entity, null);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   * @param verifier
   * @return
   */
  public ApiKeyClient create(ApiKeyClient entity, Predicate<ApiKeyClient> verifier) {
    return runCreate(entity, verifier);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   */
  public void delete(ApiKeyClient entity) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlCommand sq =
          template.createSqlCommand("delete from \"access_api_key_client\" where \"uid\" = :uid");
      sq.with(UID, SqlParameterValue.of(entity.getUid()));
      int num = sq.execute();
      if (0 == num) {
        throw new IllegalArgumentException("No delete from");
      }
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param uid
   * @param filter
   * @return
   */
  public boolean exists(String uid, Optional<ApiKeyClientFilter> filter) {
    return retrieve(uid, filter).isPresent();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param uid
   * @param filter
   * @return
   */
  public boolean existsForUpdate(String uid, Optional<ApiKeyClientFilter> filter) {
    return retrieveForUpdate(uid, filter).isPresent();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public Optional<ApiKeyClient> find(ApiKeyClientFilter filter) {
    ApiKeyClientCursor cursor = ApiKeyClientCursor.builder().build();
    return new ApiKeyClientSlider(runList(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor).one();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @return sq.where("uid", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public Optional<ApiKeyClient> find(final String sql,
      final Map<String, SqlParameterValue> params) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlQuery<ApiKeyClient> createSqlQuery = template.createSqlQuery(sql);
      params.forEach(createSqlQuery::with);
      return createSqlQuery.query(converter()).one();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public Optional<ApiKeyClient> findForUpdate(ApiKeyClientFilter filter) {
    ApiKeyClientCursor cursor = ApiKeyClientCursor.builder().build();
    return new ApiKeyClientSlider(runListForUpdate(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor).one();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @return sq.where("uid", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public Optional<ApiKeyClient> findForUpdate(final String sql,
      final Map<String, SqlParameterValue> params) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlQuery<ApiKeyClient> createSqlQuery = template.createSqlQuery(sql);
      params.forEach(createSqlQuery::with);
      return createSqlQuery.forUpdate().query(converter()).one();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public List<ApiKeyClient> list(ApiKeyClientFilter filter) {
    ApiKeyClientCursor cursor = ApiKeyClientCursor.builder().build();
    return new ApiKeyClientSlider(runList(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor).all();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @return sq.where("uid", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public List<ApiKeyClient> list(final String sql, final Map<String, SqlParameterValue> params) {
    return list(sql, params, null, false);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @param limit
   * @return sq.where("uid", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public List<ApiKeyClient> list(final String sql, final Map<String, SqlParameterValue> params,
      final int limit) {
    return list(sql, params, Integer.valueOf(limit), false);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public List<ApiKeyClient> listForUpdate(ApiKeyClientFilter filter) {
    ApiKeyClientCursor cursor = ApiKeyClientCursor.builder().build();
    return new ApiKeyClientSlider(runListForUpdate(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor).all();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @return sq.where("uid", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public List<ApiKeyClient> listForUpdate(final String sql,
      final Map<String, SqlParameterValue> params) {
    return list(sql, params, null, true);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @param limit
   * @return sq.where("uid", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public List<ApiKeyClient> listForUpdate(final String sql,
      final Map<String, SqlParameterValue> params, final int limit) {
    return list(sql, params, Integer.valueOf(limit), true);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param reference
   * @return
   */
  public ApiKeyClient resolve(ApiKeyClientRef reference) {
    return reference instanceof ApiKeyClient apiKeyClient ? apiKeyClient
        : retrieve(reference.getUid(), Optional.empty()).orElseThrow(() -> new NotFoundException(
            "Trying to resolve inexistent ApiKeyClient: " + reference.getUid()));
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param reference
   * @return
   */
  public ApiKeyClient resolveForUpdate(ApiKeyClientRef reference) {
    return reference instanceof ApiKeyClient apiKeyClient ? apiKeyClient
        : retrieveForUpdate(reference.getUid(), Optional.empty())
            .orElseThrow(() -> new NotFoundException(
                "Trying to resolve inexistent ApiKeyClient: " + reference.getUid()));
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param uid
   * @param filter
   * @return
   */
  public Optional<ApiKeyClient> retrieve(String uid, Optional<ApiKeyClientFilter> filter) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      ApiKeyClientFilter readyFilter = filter.map(val -> val.withUid(uid))
          .orElseGet(() -> ApiKeyClientFilter.builder().uid(uid).build());
      SqlSchematicQuery<ApiKeyClient> sq = filteredQuery(template, readyFilter);
      return sq.query(converter()).one();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param uid
   * @param filter
   * @return
   */
  public Optional<ApiKeyClient> retrieveForUpdate(String uid, Optional<ApiKeyClientFilter> filter) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      ApiKeyClientFilter readyFilter = filter.map(val -> val.withUid(uid))
          .orElseGet(() -> ApiKeyClientFilter.builder().uid(uid).build());
      SqlSchematicQuery<ApiKeyClient> sq = filteredQuery(template, readyFilter);
      return sq.forUpdate().query(converter()).one();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @param cursor
   * @return
   */
  public Slider<ApiKeyClient> slide(ApiKeyClientFilter filter, ApiKeyClientCursor cursor) {
    return new ApiKeyClientSlider(runList(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @param cursor
   * @return
   */
  public Slider<ApiKeyClient> slideForUpdate(ApiKeyClientFilter filter, ApiKeyClientCursor cursor) {
    return new ApiKeyClientSlider(runListForUpdate(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   * @return
   */
  public ApiKeyClient update(ApiKeyClient entity) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlCommand sq = template.createSqlCommand(
          "update \"access_api_key_client\" set  \"code\" = :code, \"key\" = :key, \"enabled\" = :enabled, \"scopes\" = :scopes, \"version\" = \"version\" + 1 where \"uid\" = :uid and \"version\" = :version");
      sq.with(UID, SqlParameterValue.of(entity.getUid()));
      sq.with(CODE, SqlParameterValue.of(entity.getCode()));
      sq.with(KEY,
          entity.getKey().map(SqlParameterValue::of).orElseGet(SqlParameterValue::ofNullString));
      sq.with(ENABLED, SqlParameterValue.of(entity.isEnabled()));
      sq.with(SCOPES,
          entity.getScopes().map(SqlParameterValue::of).orElseGet(SqlParameterValue::ofNullString));
      sq.with(VERSION, entity.getVersion().map(SqlParameterValue::of)
          .orElseGet(SqlParameterValue::ofNullInteger));
      int num = sq.execute();
      if (0 == num) {
        throw new OptimistLockException("No delete from");
      }
      return entity.withNextVersion();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @return
   */
  private SqlConverter<ApiKeyClient> converter() {
    return row -> {
      try {
        return Optional.of(ApiKeyClient.builder().uidValue(UidVO.from(row.getString(UID)))
            .codeValue(CodeVO.from(row.getString(CODE))).keyValue(KeyVO.from(row.getString(KEY)))
            .enabledValue(EnabledVO.from(row.getBoolean(ENABLED)))
            .scopesValue(ScopesVO.from(row.getString(SCOPES)))
            .versionValue(VersionVO.from(row.getInt(VERSION))).build());
      } catch (ConstraintException ce) {
        log.error("Unable to map data for {}", row.getString(1), ce);
        return Optional.empty();
      }
    };
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param template
   * @param filter
   * @return
   */
  private <T> SqlSchematicQuery<T> filteredQuery(SqlTemplate template, ApiKeyClientFilter filter) {
    SqlSchematicQuery<T> sq = template.createSqlSchematicQuery(ACCESS_API_KEY_CLIENT_SNAKE);
    sq.selectFields(ACCESS_API_KEY_CLIENT_UID, ACCESS_API_KEY_CLIENT_CODE,
        ACCESS_API_KEY_CLIENT_KEY, ACCESS_API_KEY_CLIENT_ENABLED, ACCESS_API_KEY_CLIENT_SCOPES,
        ACCESS_API_KEY_CLIENT_VERSION);
    filter.getUid().ifPresent(uid -> sq.where(UID, SqlOperator.EQ, SqlParameterValue.of(uid)));
    if (!filter.getUids().isEmpty()) {
      sq.where(UID, SqlOperator.IN, SqlListParameterValue.strings(filter.getUids()));
    }
    filter.getSearch().ifPresent(
        search -> sq.where("uid", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%")));
    filter.getKey().ifPresent(key -> sq.where(KEY, SqlOperator.EQ, SqlParameterValue.of(key)));
    return sq;
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @param limit
   * @param forUpdate
   * @return sq.where("uid", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  private List<ApiKeyClient> list(final String sql, final Map<String, SqlParameterValue> params,
      final Integer limit, final boolean forUpdate) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlQuery<ApiKeyClient> createSqlQuery = template.createSqlQuery(sql);
      params.forEach(createSqlQuery::with);
      if (forUpdate) {
        createSqlQuery = createSqlQuery.forUpdate();
      }
      SqlResult<ApiKeyClient> query = createSqlQuery.query(converter());
      return null == limit ? query.all() : query.limit(limit);
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   * @param verifier
   * @return
   */
  private ApiKeyClient runCreate(ApiKeyClient entity, Predicate<ApiKeyClient> verifier) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlCommand sq = template.createSqlCommand(
          "insert into \"access_api_key_client\" ( \"uid\", \"code\", \"key\", \"enabled\", \"scopes\", \"version\") values ( :uid, :code, :key, :enabled, :scopes, :version)");
      sq.with(UID, SqlParameterValue.of(entity.getUid()));
      sq.with(CODE, SqlParameterValue.of(entity.getCode()));
      sq.with(KEY,
          entity.getKey().map(SqlParameterValue::of).orElseGet(SqlParameterValue::ofNullString));
      sq.with(ENABLED, SqlParameterValue.of(entity.isEnabled()));
      sq.with(SCOPES,
          entity.getScopes().map(SqlParameterValue::of).orElseGet(SqlParameterValue::ofNullString));
      sq.with(VERSION, entity.getVersion().map(SqlParameterValue::of)
          .orElseGet(SqlParameterValue::ofNullInteger));
      int num = sq.execute();
      if (0 == num) {
        throw new IllegalArgumentException("No insert into");
      }
      return verifier == null ? entity : verified(verifier.test(entity), entity, template);
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @param cursor
   * @return
   */
  private Iterator<ApiKeyClient> runList(ApiKeyClientFilter filter, ApiKeyClientCursor cursor) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlSchematicQuery<ApiKeyClient> sq = filteredQuery(template, filter);
      cursor.getSinceUid()
          .ifPresent(since -> sq.where(UID, SqlOperator.GT, SqlParameterValue.of(since)));
      sq.orderAsc("uid");
      return sq.query(converter()).limit(cursor.getLimit()).iterator();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @param cursor
   * @return
   */
  private Iterator<ApiKeyClient> runListForUpdate(ApiKeyClientFilter filter,
      ApiKeyClientCursor cursor) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlSchematicQuery<ApiKeyClient> sq = filteredQuery(template, filter);
      cursor.getSinceUid()
          .ifPresent(since -> sq.where(UID, SqlOperator.GT, SqlParameterValue.of(since)));
      sq.orderAsc("uid");
      return sq.forUpdate().query(converter()).limit(cursor.getLimit()).iterator();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param exists
   * @param entity
   * @param template
   * @return
   */
  private ApiKeyClient verified(boolean exists, ApiKeyClient entity, SqlTemplate template) {
    if (exists) {
      return entity;
    } else {
      template.createSqlCommand("delete from \"access_api_key_client\" where \"uid\" = :uid")
          .with("uid", SqlParameterValue.of(entity.getUid())).execute();
      throw new NotFoundException("");
    }
  }
}
