package net.civeira.phylax.features.document.snippetversion.application.importation;

import java.util.Map;
import java.util.Optional;

import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.value.validation.ConstraintFail;
import net.civeira.phylax.common.value.validation.ConstraintFailList;
import net.civeira.phylax.features.document.snippet.domain.Snippet;
import net.civeira.phylax.features.document.snippet.domain.SnippetChangeSet;
import net.civeira.phylax.features.document.snippet.domain.gateway.SnippetFilter;
import net.civeira.phylax.features.document.snippet.domain.gateway.SnippetReadRepositoryGateway;
import net.civeira.phylax.features.document.snippet.domain.gateway.SnippetWriteRepositoryGateway;
import net.civeira.phylax.features.document.snippetversion.domain.SnippetVersion;
import net.civeira.phylax.features.document.snippetversion.domain.SnippetVersionChangeSet;
import net.civeira.phylax.features.document.snippetversion.domain.gateway.SnippetVersionFilter;
import net.civeira.phylax.features.document.snippetversion.domain.gateway.SnippetVersionWriteRepositoryGateway;

@RequiredArgsConstructor
public class SnippetVersionImportationService {

  /**
   * @autogenerated VisibilityFilterGenerator
   */
  private final SnippetVersionWriteRepositoryGateway repository;

  /**
   * @autogenerated VisibilityFilterGenerator
   */
  private final SnippetReadRepositoryGateway snippetReadRepository;

  /**
   * @autogenerated VisibilityFilterGenerator
   */
  private final SnippetWriteRepositoryGateway snippetWriteRepository;

  /**
   * @autogenerated VisibilityFilterGenerator
   * @param row
   * @return
   */
  public SnippetVersionImportationResult load(final Map<String, String> row) {
    return load(row, SnippetVersionImportationRelatedResolver.builder().build());
  }

  /**
   * @autogenerated VisibilityFilterGenerator
   * @param row
   * @param resolver
   * @return
   */
  public SnippetVersionImportationResult load(final Map<String, String> row,
      final SnippetVersionImportationRelatedResolver resolver) {
    ConstraintFailList fails = new ConstraintFailList();
    String uid = row.get("uid");
    if (null == uid) {
      fails.add(new ConstraintFail("NOT_NULL", "uid", null));
    }
    boolean exists = false;
    SnippetVersion entity = null;
    if (!fails.isEmpty()) {
      Optional<SnippetVersion> existing =
          repository.findForUpdate(SnippetVersionFilter.builder().uid(uid).build());
      SnippetVersionChangeSet change = toChangeSet(row, fails, resolver);
      if (existing.isPresent()) {
        entity = existing.get().update(change);
        exists = true;
      } else {
        entity = SnippetVersion.create(change.newUid());
      }
    }
    return fails.isEmpty() ? new SnippetVersionImportationResult(entity, exists)
        : new SnippetVersionImportationResult(fails);
  }

  /**
   * @autogenerated VisibilityFilterGenerator
   * @param row
   * @param fails
   * @param resolver
   * @return
   */
  public SnippetVersionChangeSet toChangeSet(final Map<String, String> row,
      final ConstraintFailList fails, final SnippetVersionImportationRelatedResolver resolver) {
    SnippetVersionChangeSet change = new SnippetVersionChangeSet();
    change = readSnippet(change, row, fails, resolver);
    change = readLocale(change, row, fails, resolver);
    change = readSubject(change, row, fails, resolver);
    change = readContentHtml(change, row, fails, resolver);
    change = readContentText(change, row, fails, resolver);
    return change;
  }

  /**
   * @autogenerated VisibilityFilterGenerator
   * @param change
   * @param row
   * @param fails
   * @param resolver
   * @return
   */
  private SnippetVersionChangeSet readContentHtml(final SnippetVersionChangeSet change,
      final Map<String, String> row, final ConstraintFailList fails,
      final SnippetVersionImportationRelatedResolver resolver) {
    String contentHtml = row.get("contentHtml");
    if (contentHtml != null) {
      return change.contentHtml(contentHtml);
    } else {
      return change.unsetContentHtml();
    }
  }

  /**
   * @autogenerated VisibilityFilterGenerator
   * @param change
   * @param row
   * @param fails
   * @param resolver
   * @return
   */
  private SnippetVersionChangeSet readContentText(final SnippetVersionChangeSet change,
      final Map<String, String> row, final ConstraintFailList fails,
      final SnippetVersionImportationRelatedResolver resolver) {
    String contentText = row.get("contentText");
    if (contentText != null) {
      return change.contentText(contentText);
    } else {
      return change.unsetContentText();
    }
  }

  /**
   * @autogenerated VisibilityFilterGenerator
   * @param change
   * @param row
   * @param fails
   * @param resolver
   * @return
   */
  private SnippetVersionChangeSet readLocale(final SnippetVersionChangeSet change,
      final Map<String, String> row, final ConstraintFailList fails,
      final SnippetVersionImportationRelatedResolver resolver) {
    String locale = row.get("locale");
    if (locale != null) {
      return change.locale(locale);
    } else {
      return change.unsetLocale();
    }
  }

  /**
   * @autogenerated VisibilityFilterGenerator
   * @param change
   * @param row
   * @param fails
   * @param resolver
   * @return
   */
  private SnippetVersionChangeSet readSnippet(final SnippetVersionChangeSet change,
      final Map<String, String> row, final ConstraintFailList fails,
      final SnippetVersionImportationRelatedResolver resolver) {
    String snippet = row.get("snippet");
    if (snippet != null) {
      Optional<Snippet> existing =
          snippetReadRepository.find(SnippetFilter.builder().code(snippet).build());
      if (existing.isPresent()) {
        return change.snippet(existing.get());
      } else if (resolver.isCreateMissingSnippet()) {
        SnippetChangeSet childChanges = new SnippetChangeSet().newUid();
        Snippet entity =
            (null == resolver.getMissingSnippetFactory()) ? Snippet.create(childChanges)
                : resolver.getMissingSnippetFactory().apply(childChanges);
        return change.snippet(snippetWriteRepository.create(entity));
      } else {
        fails.add(new ConstraintFail("NOT_FOUND", "snippet", snippet));
        return change;
      }
    } else {
      return change.unsetSnippet();
    }
  }

  /**
   * @autogenerated VisibilityFilterGenerator
   * @param change
   * @param row
   * @param fails
   * @param resolver
   * @return
   */
  private SnippetVersionChangeSet readSubject(final SnippetVersionChangeSet change,
      final Map<String, String> row, final ConstraintFailList fails,
      final SnippetVersionImportationRelatedResolver resolver) {
    String subject = row.get("subject");
    if (subject != null) {
      return change.subject(subject);
    } else {
      return change.unsetSubject();
    }
  }
}
