package net.civeira.phylax.features.access.consentpurpose.application.usecase.update;

import java.util.Optional;

import net.civeira.phylax.common.security.AuthorizationDecision;
import net.civeira.phylax.common.security.OperationContext;
import net.civeira.phylax.common.security.Permission;
import net.civeira.phylax.features.access.consentpurpose.domain.ConsentPurposeRef;

public class ConsentPurposeUpdateAuthorizationDecision extends AuthorizationDecision {

  /**
   * @autogenerated UpdateAuthorizationDecisionGenerator
   */
  private final ConsentPurposeRef reference;

  /**
   * @autogenerated UpdateAuthorizationDecisionGenerator
   * @param context
   * @param initial
   */
  public ConsentPurposeUpdateAuthorizationDecision(final OperationContext context,
      final Permission initial) {
    super(context, initial);
    this.reference = null;
  }

  /**
   * @autogenerated UpdateAuthorizationDecisionGenerator
   * @param context
   * @param reference
   * @param initial
   */
  public ConsentPurposeUpdateAuthorizationDecision(final OperationContext context,
      final ConsentPurposeRef reference, final Permission initial) {
    super(context, initial);
    this.reference = reference;
  }

  /**
   * @autogenerated UpdateAuthorizationDecisionGenerator
   * @return
   */
  public String actionName() {
    return "update";
  }

  /**
   * @autogenerated UpdateAuthorizationDecisionGenerator
   * @return
   */
  public Optional<ConsentPurposeRef> getReference() {
    return Optional.ofNullable(reference);
  }

  /**
   * @autogenerated UpdateAuthorizationDecisionGenerator
   * @return
   */
  public String resourceName() {
    return "consent-purpose";
  }
}
