package net.civeira.phylax.features.access.tenantconfig.domain.valueholder;

import java.util.Optional;

import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.value.validation.ConstraintFailList;
import net.civeira.phylax.features.access.tenantconfig.domain.TenantConfig;
import net.civeira.phylax.features.access.tenantconfig.domain.valueobject.InnerLabelVO;

@RequiredArgsConstructor
public class InnerLabelValueHolder<T> {

  /**
   * @autogenerated ValueHolderGenerator
   */
  private final T holder;

  /**
   * @autogenerated ValueHolderGenerator
   */
  private Optional<InnerLabelVO> value = Optional.empty();

  /**
   * @autogenerated ValueHolderGenerator
   * @return
   */
  public Optional<String> getInnerLabel() {
    return value.flatMap(InnerLabelVO::getInnerLabel);
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @return
   */
  public Optional<InnerLabelVO> getInnerLabelValue() {
    return value;
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @param innerLabel
   * @return
   */
  public T innerLabel(InnerLabelVO innerLabel) {
    this.value = Optional.of(innerLabel);
    return this.holder;
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @param innerLabel
   * @return
   */
  public T innerLabel(Optional<InnerLabelVO> innerLabel) {
    this.value = innerLabel;
    return this.holder;
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @param innerLabel
   * @return
   */
  public T innerLabel(String innerLabel) {
    this.value = Optional.of(InnerLabelVO.from(innerLabel));
    return this.holder;
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @return
   */
  public T innerLabelNull() {
    this.value = Optional.empty();
    return this.holder;
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @param original
   * @param fails
   * @return
   */
  public InnerLabelVO readInnerLabel(final Optional<TenantConfig> original,
      final ConstraintFailList fails) {
    return value
        .orElse(original.map(TenantConfig::getInnerLabelValue).orElseGet(InnerLabelVO::nullValue));
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @return
   */
  public T unsetInnerLabel() {
    value = Optional.empty();
    return holder;
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @param field
   * @return
   */
  public T unsetInnerLabelIfMatches(final String field) {
    if ("innerLabel".equals(field)) {
      value = Optional.empty();
    }
    return holder;
  }
}
