/* @autogenerated */
package net.civeira.phylax.features.oauth.delegated.domain.model;

import lombok.Data;

@Data
public class DelegatedAccessDescriptor {
  private String id;
  private String name;
  private String logo;
}
