package net.civeira.phylax.features.access.user.transition;

import java.time.OffsetDateTime;
import java.util.Optional;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import net.civeira.phylax.common.value.Uuid;
import net.civeira.phylax.features.access.tenant.TenantRef;
import net.civeira.phylax.features.access.user.User;
import net.civeira.phylax.features.access.user.UserReference;
import net.civeira.phylax.features.access.user.command.UserWriteAttributes;
import net.civeira.phylax.features.access.user.valueobject.BlockedUntilVO;
import net.civeira.phylax.features.access.user.valueobject.EmailVO;
import net.civeira.phylax.features.access.user.valueobject.EnabledVO;
import net.civeira.phylax.features.access.user.valueobject.LanguageVO;
import net.civeira.phylax.features.access.user.valueobject.NameVO;
import net.civeira.phylax.features.access.user.valueobject.PasswordVO;
import net.civeira.phylax.features.access.user.valueobject.ProviderVO;
import net.civeira.phylax.features.access.user.valueobject.SecondFactorSeedVO;
import net.civeira.phylax.features.access.user.valueobject.TemporalPasswordVO;
import net.civeira.phylax.features.access.user.valueobject.TenantVO;
import net.civeira.phylax.features.access.user.valueobject.UidVO;
import net.civeira.phylax.features.access.user.valueobject.UseSecondFactorsVO;
import net.civeira.phylax.features.access.user.valueobject.VersionVO;

@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UserChangeProposal implements UserWriteAttributes {

  /**
   * @autogenerated EntityChangeProposalGenerator
   */
  public static class UserChangeProposalBuilder {

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param blockedUntil
     * @return
     */
    public UserChangeProposalBuilder blockedUntil(final OffsetDateTime blockedUntil) {
      return blockedUntil(Optional.of(BlockedUntilVO.from(blockedUntil)));
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param blockedUntil
     * @return
     */
    public UserChangeProposalBuilder blockedUntil(final Optional<BlockedUntilVO> blockedUntil) {
      this.blockedUntil$value = blockedUntil;
      this.blockedUntil$set = true;
      return this;
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param email
     * @return
     */
    public UserChangeProposalBuilder email(final String email) {
      return email(Optional.of(EmailVO.from(email)));
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param email
     * @return
     */
    public UserChangeProposalBuilder email(final Optional<EmailVO> email) {
      this.email$value = email;
      this.email$set = true;
      return this;
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param enabled
     * @return
     */
    public UserChangeProposalBuilder enabled(final Boolean enabled) {
      return enabled(Optional.of(EnabledVO.from(enabled)));
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param enabled
     * @return
     */
    public UserChangeProposalBuilder enabled(final Optional<EnabledVO> enabled) {
      this.enabled$value = enabled;
      this.enabled$set = true;
      return this;
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param language
     * @return
     */
    public UserChangeProposalBuilder language(final String language) {
      return language(Optional.of(LanguageVO.from(language)));
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param language
     * @return
     */
    public UserChangeProposalBuilder language(final Optional<LanguageVO> language) {
      this.language$value = language;
      this.language$set = true;
      return this;
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param name
     * @return
     */
    public UserChangeProposalBuilder name(final String name) {
      return name(Optional.of(NameVO.from(name)));
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param name
     * @return
     */
    public UserChangeProposalBuilder name(final Optional<NameVO> name) {
      this.name$value = name;
      this.name$set = true;
      return this;
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @return
     */
    public UserChangeProposalBuilder newUid() {
      return version(0).uid(Uuid.comb().toString());
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param password
     * @return
     */
    public UserChangeProposalBuilder password(final String password) {
      return password(Optional.of(PasswordVO.fromPlain(password)));
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param password
     * @return
     */
    public UserChangeProposalBuilder password(final Optional<PasswordVO> password) {
      this.password$value = password;
      this.password$set = true;
      return this;
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param provider
     * @return
     */
    public UserChangeProposalBuilder provider(final String provider) {
      return provider(Optional.of(ProviderVO.from(provider)));
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param provider
     * @return
     */
    public UserChangeProposalBuilder provider(final Optional<ProviderVO> provider) {
      this.provider$value = provider;
      this.provider$set = true;
      return this;
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param secondFactorSeed
     * @return
     */
    public UserChangeProposalBuilder secondFactorSeed(final String secondFactorSeed) {
      return secondFactorSeed(Optional.of(SecondFactorSeedVO.fromPlain(secondFactorSeed)));
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param secondFactorSeed
     * @return
     */
    public UserChangeProposalBuilder secondFactorSeed(
        final Optional<SecondFactorSeedVO> secondFactorSeed) {
      this.secondFactorSeed$value = secondFactorSeed;
      this.secondFactorSeed$set = true;
      return this;
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param temporalPassword
     * @return
     */
    public UserChangeProposalBuilder temporalPassword(final Boolean temporalPassword) {
      return temporalPassword(Optional.of(TemporalPasswordVO.from(temporalPassword)));
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param temporalPassword
     * @return
     */
    public UserChangeProposalBuilder temporalPassword(
        final Optional<TemporalPasswordVO> temporalPassword) {
      this.temporalPassword$value = temporalPassword;
      this.temporalPassword$set = true;
      return this;
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param tenant
     * @return
     */
    public UserChangeProposalBuilder tenant(final TenantRef tenant) {
      return tenant(Optional.of(TenantVO.from(tenant)));
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param tenant
     * @return
     */
    public UserChangeProposalBuilder tenant(final Optional<TenantVO> tenant) {
      this.tenant$value = tenant;
      this.tenant$set = true;
      return this;
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param uid
     * @return
     */
    public UserChangeProposalBuilder uid(final String uid) {
      return uid(Optional.of(UidVO.from(uid)));
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param uid
     * @return
     */
    public UserChangeProposalBuilder uid(final Optional<UidVO> uid) {
      this.uid$value = uid;
      this.uid$set = true;
      return this;
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param useSecondFactors
     * @return
     */
    public UserChangeProposalBuilder useSecondFactors(final Boolean useSecondFactors) {
      return useSecondFactors(Optional.of(UseSecondFactorsVO.from(useSecondFactors)));
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param useSecondFactors
     * @return
     */
    public UserChangeProposalBuilder useSecondFactors(
        final Optional<UseSecondFactorsVO> useSecondFactors) {
      this.useSecondFactors$value = useSecondFactors;
      this.useSecondFactors$set = true;
      return this;
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param version
     * @return
     */
    public UserChangeProposalBuilder version(final Integer version) {
      return version(Optional.of(VersionVO.from(version)));
    }

    /**
     * @autogenerated EntityChangeProposalGenerator
     * @param version
     * @return
     */
    public UserChangeProposalBuilder version(final Optional<VersionVO> version) {
      this.version$value = version;
      this.version$set = true;
      return this;
    }
  }

  /**
   * A bloqued user cant login on the system, until these date. On his login attempst, hue will
   * recive a generic not allowed message.
   *
   * @autogenerated EntityChangeProposalGenerator
   */
  @Builder.Default
  private Optional<BlockedUntilVO> blockedUntil = Optional.empty();

  /**
   * An optional email used to send notifications to the user
   *
   * @autogenerated EntityChangeProposalGenerator
   */
  @Builder.Default
  private Optional<EmailVO> email = Optional.empty();

  /**
   * A disabled user cant login on the system. On his login attempts, he will recive a specific warn
   * of his disabled account.
   *
   * @autogenerated EntityChangeProposalGenerator
   */
  @Builder.Default
  private Optional<EnabledVO> enabled = Optional.empty();

  /**
   * El language de user
   *
   * @autogenerated EntityChangeProposalGenerator
   */
  @Builder.Default
  private Optional<LanguageVO> language = Optional.empty();

  /**
   * The user name to identify on the login screen
   *
   * @autogenerated EntityChangeProposalGenerator
   */
  @Builder.Default
  private Optional<NameVO> name = Optional.empty();

  /**
   * If the user is not delegated, the phrasse to identify
   *
   * @autogenerated EntityChangeProposalGenerator
   */
  @Builder.Default
  private Optional<PasswordVO> password = Optional.empty();

  /**
   * Si se identificó con un proveedor, se marca con cual (aunque el provedor cambie luego)
   *
   * @autogenerated EntityChangeProposalGenerator
   */
  @Builder.Default
  private Optional<ProviderVO> provider = Optional.empty();

  /**
   * the seed used to the otp login
   *
   * @autogenerated EntityChangeProposalGenerator
   */
  @Builder.Default
  private Optional<SecondFactorSeedVO> secondFactorSeed = Optional.empty();

  /**
   * El temporal password de user
   *
   * @autogenerated EntityChangeProposalGenerator
   */
  @Builder.Default
  private Optional<TemporalPasswordVO> temporalPassword = Optional.empty();

  /**
   * Los usuarios que no tienen tenant son roots del sistema
   *
   * @autogenerated EntityChangeProposalGenerator
   */
  @Builder.Default
  private Optional<TenantVO> tenant = Optional.empty();

  /**
   * A uid string to identify the entity
   *
   * @autogenerated EntityChangeProposalGenerator
   */
  @Builder.Default
  private Optional<UidVO> uid = Optional.empty();

  /**
   * If is true, the user has a otp to force mfa on login
   *
   * @autogenerated EntityChangeProposalGenerator
   */
  @Builder.Default
  private Optional<UseSecondFactorsVO> useSecondFactors = Optional.empty();

  /**
   * Campo con el número de version de user para controlar bloqueos optimistas
   *
   * @autogenerated EntityChangeProposalGenerator
   */
  @Builder.Default
  private Optional<VersionVO> version = Optional.empty();

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @param attributes
   */
  public UserChangeProposal(final UserWriteAttributes attributes) {
    uid = attributes.getUid();
    tenant = attributes.getTenant();
    name = attributes.getName();
    password = attributes.getPassword();
    email = attributes.getEmail();
    enabled = attributes.getEnabled();
    temporalPassword = attributes.getTemporalPassword();
    useSecondFactors = attributes.getUseSecondFactors();
    secondFactorSeed = attributes.getSecondFactorSeed();
    blockedUntil = attributes.getBlockedUntil();
    language = attributes.getLanguage();
    provider = attributes.getProvider();
    version = attributes.getVersion();
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @param entity
   */
  public UserChangeProposal(final User entity) {
    uid = Optional.of(entity.getUid());
    tenant = Optional.of(entity.getTenant());
    name = Optional.of(entity.getName());
    password = Optional.of(entity.getPassword());
    email = Optional.of(entity.getEmail());
    enabled = Optional.of(entity.getEnabled());
    temporalPassword = Optional.of(entity.getTemporalPassword());
    useSecondFactors = Optional.of(entity.getUseSecondFactors());
    secondFactorSeed = Optional.of(entity.getSecondFactorSeed());
    blockedUntil = Optional.of(entity.getBlockedUntil());
    language = Optional.of(entity.getLanguage());
    provider = Optional.of(entity.getProvider());
    version = Optional.of(entity.getVersion());
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  public UserReference asReference() {
    return uid.map(UidVO::getValue).map(UserReference::of).orElseThrow();
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  @Override
  public Optional<BlockedUntilVO> getBlockedUntil() {
    return blockedUntil;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  @Override
  public Optional<EmailVO> getEmail() {
    return email;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  @Override
  public Optional<EnabledVO> getEnabled() {
    return enabled;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  @Override
  public Optional<LanguageVO> getLanguage() {
    return language;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  @Override
  public Optional<NameVO> getName() {
    return name;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  @Override
  public Optional<PasswordVO> getPassword() {
    return password;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  @Override
  public Optional<ProviderVO> getProvider() {
    return provider;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  @Override
  public Optional<SecondFactorSeedVO> getSecondFactorSeed() {
    return secondFactorSeed;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  @Override
  public Optional<TemporalPasswordVO> getTemporalPassword() {
    return temporalPassword;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  @Override
  public Optional<TenantVO> getTenant() {
    return tenant;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  @Override
  public Optional<UidVO> getUid() {
    return uid;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  @Override
  public Optional<UseSecondFactorsVO> getUseSecondFactors() {
    return useSecondFactors;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  @Override
  public Optional<VersionVO> getVersion() {
    return version;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @param value
   * @return
   */
  public UserChangeProposal setBlockedUntil(final OffsetDateTime value) {
    this.blockedUntil = Optional.of(BlockedUntilVO.from(value));
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @param value
   * @return
   */
  public UserChangeProposal setEmail(final String value) {
    this.email = Optional.of(EmailVO.from(value));
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @param value
   * @return
   */
  public UserChangeProposal setEnabled(final Boolean value) {
    this.enabled = Optional.of(EnabledVO.from(value));
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @param value
   * @return
   */
  public UserChangeProposal setLanguage(final String value) {
    this.language = Optional.of(LanguageVO.from(value));
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @param value
   * @return
   */
  public UserChangeProposal setName(final String value) {
    this.name = Optional.of(NameVO.from(value));
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @param value
   * @return
   */
  public UserChangeProposal setPassword(final String value) {
    this.password = Optional.of(PasswordVO.fromPlain(value));
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @param value
   * @return
   */
  public UserChangeProposal setProvider(final String value) {
    this.provider = Optional.of(ProviderVO.from(value));
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @param value
   * @return
   */
  public UserChangeProposal setSecondFactorSeed(final String value) {
    this.secondFactorSeed = Optional.of(SecondFactorSeedVO.fromPlain(value));
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @param value
   * @return
   */
  public UserChangeProposal setTemporalPassword(final Boolean value) {
    this.temporalPassword = Optional.of(TemporalPasswordVO.from(value));
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @param value
   * @return
   */
  public UserChangeProposal setTenant(final TenantRef value) {
    this.tenant = Optional.of(TenantVO.from(value));
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @param value
   * @return
   */
  public UserChangeProposal setUid(final String value) {
    this.uid = Optional.of(UidVO.from(value));
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @param value
   * @return
   */
  public UserChangeProposal setUseSecondFactors(final Boolean value) {
    this.useSecondFactors = Optional.of(UseSecondFactorsVO.from(value));
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @param value
   * @return
   */
  public UserChangeProposal setVersion(final Integer value) {
    this.version = Optional.of(VersionVO.from(value));
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @param field
   */
  public void unset(final String field) {
    if ("uid".equals(field)) {
      this.unsetUid();
    }
    if ("tenant".equals(field)) {
      this.unsetTenant();
    }
    if ("name".equals(field)) {
      this.unsetName();
    }
    if ("password".equals(field)) {
      this.unsetPassword();
    }
    if ("email".equals(field)) {
      this.unsetEmail();
    }
    if ("enabled".equals(field)) {
      this.unsetEnabled();
    }
    if ("temporalPassword".equals(field)) {
      this.unsetTemporalPassword();
    }
    if ("useSecondFactors".equals(field)) {
      this.unsetUseSecondFactors();
    }
    if ("secondFactorSeed".equals(field)) {
      this.unsetSecondFactorSeed();
    }
    if ("blockedUntil".equals(field)) {
      this.unsetBlockedUntil();
    }
    if ("language".equals(field)) {
      this.unsetLanguage();
    }
    if ("provider".equals(field)) {
      this.unsetProvider();
    }
    if ("version".equals(field)) {
      this.unsetVersion();
    }
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  public UserChangeProposal unsetBlockedUntil() {
    this.blockedUntil = Optional.empty();
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  public UserChangeProposal unsetEmail() {
    this.email = Optional.empty();
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  public UserChangeProposal unsetEnabled() {
    this.enabled = Optional.empty();
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  public UserChangeProposal unsetLanguage() {
    this.language = Optional.empty();
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  public UserChangeProposal unsetName() {
    this.name = Optional.empty();
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  public UserChangeProposal unsetPassword() {
    this.password = Optional.empty();
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  public UserChangeProposal unsetProvider() {
    this.provider = Optional.empty();
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  public UserChangeProposal unsetSecondFactorSeed() {
    this.secondFactorSeed = Optional.empty();
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  public UserChangeProposal unsetTemporalPassword() {
    this.temporalPassword = Optional.empty();
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  public UserChangeProposal unsetTenant() {
    this.tenant = Optional.empty();
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  public UserChangeProposal unsetUid() {
    this.uid = Optional.empty();
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  public UserChangeProposal unsetUseSecondFactors() {
    this.useSecondFactors = Optional.empty();
    return this;
  }

  /**
   * @autogenerated EntityChangeProposalGenerator
   * @return
   */
  public UserChangeProposal unsetVersion() {
    this.version = Optional.empty();
    return this;
  }
}
