package net.civeira.phylax.features.document.themeasset.domain;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NonNull;
import lombok.ToString;
import lombok.With;
import lombok.experimental.Delegate;
import net.civeira.phylax.common.exception.ConstraintException;
import net.civeira.phylax.common.value.validation.ConstraintFailList;
import net.civeira.phylax.features.document.themeasset.domain.event.ThemeAssetCreateEvent;
import net.civeira.phylax.features.document.themeasset.domain.event.ThemeAssetDeleteEvent;
import net.civeira.phylax.features.document.themeasset.domain.event.ThemeAssetDisableEvent;
import net.civeira.phylax.features.document.themeasset.domain.event.ThemeAssetEnableEvent;
import net.civeira.phylax.features.document.themeasset.domain.event.ThemeAssetEvent;
import net.civeira.phylax.features.document.themeasset.domain.event.ThemeAssetUpdateEvent;
import net.civeira.phylax.features.document.themeasset.domain.valueobject.CodeVO;
import net.civeira.phylax.features.document.themeasset.domain.valueobject.ContentVO;
import net.civeira.phylax.features.document.themeasset.domain.valueobject.EnabledVO;
import net.civeira.phylax.features.document.themeasset.domain.valueobject.ThemeVO;
import net.civeira.phylax.features.document.themeasset.domain.valueobject.TypeVO;
import net.civeira.phylax.features.document.themeasset.domain.valueobject.UidVO;
import net.civeira.phylax.features.document.themeasset.domain.valueobject.VersionVO;

/**
 * theme-asset
 */
@Builder
@Getter
@With
@ToString
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@EqualsAndHashCode
public class ThemeAsset implements ThemeAssetRef {

  /**
   * Prepare a new theme asset with the provided values
   *
   * @autogenerated EntityGenerator
   * @param change A set of values to create a new theme asset
   * @throws ConstraintException If there are some constraints fails on the changes.
   * @return A well formed theme asset.
   */
  public static ThemeAsset create(final ThemeAssetChangeSet change) throws ConstraintException {
    change.enabled(true);
    ThemeAsset instance = new ThemeAsset(change, Optional.empty());
    instance.addEvent(ThemeAssetCreateEvent.builder().payload(instance).build());
    return instance;
  }

  /**
   * logo, corporate.css, banner...
   *
   * @autogenerated EntityGenerator
   */
  @Delegate
  @NonNull
  private CodeVO codeValue;

  /**
   * El content de theme asset
   *
   * @autogenerated EntityGenerator
   */
  @Delegate
  @NonNull
  private ContentVO contentValue;

  /**
   * El enabled de theme asset
   *
   * @autogenerated EntityGenerator
   */
  @Delegate
  @Builder.Default
  private EnabledVO enabledValue = EnabledVO.nullValue();

  /**
   * List of events
   *
   * @autogenerated EntityGenerator
   */
  @Builder.Default
  private List<ThemeAssetEvent> recordedEvents = List.of();

  /**
   * El theme de theme asset
   *
   * @autogenerated EntityGenerator
   */
  @Delegate
  @NonNull
  private ThemeVO themeValue;

  /**
   * IMAGE, CSS, FONT...
   *
   * @autogenerated EntityGenerator
   */
  @Delegate
  @NonNull
  private TypeVO typeValue;

  /**
   * El uid de theme asset
   *
   * @autogenerated EntityGenerator
   */
  @Delegate
  @NonNull
  private UidVO uidValue;

  /**
   * Campo con el número de version de theme asset para controlar bloqueos optimistas
   *
   * @autogenerated EntityGenerator
   */
  @Delegate
  @Builder.Default
  private VersionVO versionValue = VersionVO.nullValue();

  /**
   * @autogenerated EntityGenerator
   * @param attribute
   * @param previous
   */
  private ThemeAsset(final ThemeAssetChangeSet attribute, final Optional<ThemeAsset> previous) {
    ConstraintFailList list = new ConstraintFailList();
    this.uidValue = attribute.readUid(previous, list);
    this.themeValue = attribute.readTheme(previous, list);
    this.codeValue = attribute.readCode(previous, list);
    this.typeValue = attribute.readType(previous, list);
    this.contentValue = attribute.readContent(previous, list);
    this.enabledValue = attribute.readEnabled(previous, list);
    this.versionValue = attribute.readVersion(previous, list);
    if (list.hasErrors()) {
      throw new ConstraintException("Invalid values on ThemeAsset", list);
    }
    this.recordedEvents = previous.map(ThemeAsset::getRecordedEvents).orElseGet(List::of);
  }

  /**
   * Apply changes to delete a theme asset
   *
   * @autogenerated EntityGenerator
   * @return A instance of theme asset ready to be deleted
   */
  public ThemeAsset delete() {
    ThemeAsset instance = new ThemeAsset(new ThemeAssetChangeSet(), Optional.of(this));
    instance.addEvent(ThemeAssetDeleteEvent.builder().payload(instance).build());
    return instance;
  }

  /**
   * Apply disable on theme asset.
   *
   * @autogenerated EntityGenerator
   * @return A modified instance of theme asset
   */
  public ThemeAsset disable() {
    ThemeAssetChangeSet attr = new ThemeAssetChangeSet();
    attr.enabled(false);
    ThemeAsset instance = new ThemeAsset(attr, Optional.of(this));
    instance.addEvent(ThemeAssetDisableEvent.builder().payload(instance).build());
    return instance;
  }

  /**
   * Apply enable on theme asset.
   *
   * @autogenerated EntityGenerator
   * @return A modified instance of theme asset
   */
  public ThemeAsset enable() {
    ThemeAssetChangeSet attr = new ThemeAssetChangeSet();
    attr.enabled(true);
    ThemeAsset instance = new ThemeAsset(attr, Optional.of(this));
    instance.addEvent(ThemeAssetEnableEvent.builder().payload(instance).build());
    return instance;
  }

  /**
   * @autogenerated EntityGenerator
   * @return
   */
  public Map<String, String> toMap() {
    Map<String, String> map = new HashMap<>(7);
    uidToMap(map);
    themeToMap(map);
    codeToMap(map);
    typeToMap(map);
    contentToMap(map);
    enabledToMap(map);
    versionToMap(map);
    return map;
  }

  /**
   * Modify the values for some of the properties of a theme asset
   *
   * @autogenerated EntityGenerator
   * @param change The properties to be modified
   * @throws ConstraintException If there are some constraints fails on the changes.
   * @return A modified instance of theme asset
   */
  public ThemeAsset update(final ThemeAssetChangeSet change) throws ConstraintException {
    change.unsetEnabled();
    ThemeAsset instance = new ThemeAsset(change, Optional.of(this));
    instance.addEvent(ThemeAssetUpdateEvent.builder().payload(instance).build());
    return instance;
  }

  /**
   * @autogenerated EntityGenerator
   * @return
   */
  public ThemeAsset withNextVersion() {
    return withVersionValue(VersionVO.from(nextVersion()));
  }

  /**
   * @autogenerated EntityGenerator
   * @param event
   */
  private void addEvent(final ThemeAssetEvent event) {
    List<ThemeAssetEvent> events = new ArrayList<>(this.recordedEvents);
    events.add(event);
    this.recordedEvents = List.copyOf(events);
  }
}
