package net.civeira.phylax.features.access.tenantconfig.domain;

import lombok.NoArgsConstructor;
import lombok.experimental.Delegate;
import net.civeira.phylax.common.value.Uuid;
import net.civeira.phylax.features.access.tenantconfig.domain.valueholder.AllowRecoverPassValueHolder;
import net.civeira.phylax.features.access.tenantconfig.domain.valueholder.AllowRegisterValueHolder;
import net.civeira.phylax.features.access.tenantconfig.domain.valueholder.DisabledUserEmailValueHolder;
import net.civeira.phylax.features.access.tenantconfig.domain.valueholder.DynamicRegistrationPolicyValueHolder;
import net.civeira.phylax.features.access.tenantconfig.domain.valueholder.EnableRegisterUsersValueHolder;
import net.civeira.phylax.features.access.tenantconfig.domain.valueholder.EnabledUserEmailValueHolder;
import net.civeira.phylax.features.access.tenantconfig.domain.valueholder.ForceMfaValueHolder;
import net.civeira.phylax.features.access.tenantconfig.domain.valueholder.InnerLabelValueHolder;
import net.civeira.phylax.features.access.tenantconfig.domain.valueholder.MagicLinkEnabledValueHolder;
import net.civeira.phylax.features.access.tenantconfig.domain.valueholder.RecoverPassEmailValueHolder;
import net.civeira.phylax.features.access.tenantconfig.domain.valueholder.RegisterdEmailValueHolder;
import net.civeira.phylax.features.access.tenantconfig.domain.valueholder.TenantValueHolder;
import net.civeira.phylax.features.access.tenantconfig.domain.valueholder.UidValueHolder;
import net.civeira.phylax.features.access.tenantconfig.domain.valueholder.VersionValueHolder;
import net.civeira.phylax.features.access.tenantconfig.domain.valueholder.WebauthnEnabledValueHolder;
import net.civeira.phylax.features.access.tenantconfig.domain.valueholder.WebauthnRpIdValueHolder;
import net.civeira.phylax.features.access.tenantconfig.domain.valueholder.WebauthnRpNameValueHolder;
import net.civeira.phylax.features.access.tenantconfig.domain.valueholder.WellcomeEmailValueHolder;

/**
 * A dto transfer to hold tenant config attribute values
 */
@NoArgsConstructor
public class TenantConfigChangeSet {

  /**
   * El allow recover pass de tenant config
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private AllowRecoverPassValueHolder<TenantConfigChangeSet> allowRecoverPassValue =
      new AllowRecoverPassValueHolder<>(this);

  /**
   * El allow register de tenant config
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private AllowRegisterValueHolder<TenantConfigChangeSet> allowRegisterValue =
      new AllowRegisterValueHolder<>(this);

  /**
   * Email send when a user is disabled
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private DisabledUserEmailValueHolder<TenantConfigChangeSet> disabledUserEmailValue =
      new DisabledUserEmailValueHolder<>(this);

  /**
   * El dynamic registration policy de tenant config
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private DynamicRegistrationPolicyValueHolder<TenantConfigChangeSet> dynamicRegistrationPolicyValue =
      new DynamicRegistrationPolicyValueHolder<>(this);

  /**
   * El enable register users de tenant config
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private EnableRegisterUsersValueHolder<TenantConfigChangeSet> enableRegisterUsersValue =
      new EnableRegisterUsersValueHolder<>(this);

  /**
   * Email send when a user is enabled
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private EnabledUserEmailValueHolder<TenantConfigChangeSet> enabledUserEmailValue =
      new EnabledUserEmailValueHolder<>(this);

  /**
   * El force mfa de tenant config
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private ForceMfaValueHolder<TenantConfigChangeSet> forceMfaValue =
      new ForceMfaValueHolder<>(this);

  /**
   * Tenant could use these field to label the application for the users
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private InnerLabelValueHolder<TenantConfigChangeSet> innerLabelValue =
      new InnerLabelValueHolder<>(this);

  /**
   * El magic link enabled de tenant config
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private MagicLinkEnabledValueHolder<TenantConfigChangeSet> magicLinkEnabledValue =
      new MagicLinkEnabledValueHolder<>(this);

  /**
   * Email send to the user to recover the password
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private RecoverPassEmailValueHolder<TenantConfigChangeSet> recoverPassEmailValue =
      new RecoverPassEmailValueHolder<>(this);

  /**
   * Email send when a user register
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private RegisterdEmailValueHolder<TenantConfigChangeSet> registerdEmailValue =
      new RegisterdEmailValueHolder<>(this);

  /**
   * The name to identify the account.
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private TenantValueHolder<TenantConfigChangeSet> tenantValue = new TenantValueHolder<>(this);

  /**
   * A number to identify the db record
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private UidValueHolder<TenantConfigChangeSet> uidValue = new UidValueHolder<>(this);

  /**
   * Campo con el número de version de tenant config para controlar bloqueos optimistas
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private VersionValueHolder<TenantConfigChangeSet> versionValue = new VersionValueHolder<>(this);

  /**
   * El webauthn enabled de tenant config
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private WebauthnEnabledValueHolder<TenantConfigChangeSet> webauthnEnabledValue =
      new WebauthnEnabledValueHolder<>(this);

  /**
   * El webauthn rp id de tenant config
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private WebauthnRpIdValueHolder<TenantConfigChangeSet> webauthnRpIdValue =
      new WebauthnRpIdValueHolder<>(this);

  /**
   * El webauthn rp name de tenant config
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private WebauthnRpNameValueHolder<TenantConfigChangeSet> webauthnRpNameValue =
      new WebauthnRpNameValueHolder<>(this);

  /**
   * Email send to the enabled user
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private WellcomeEmailValueHolder<TenantConfigChangeSet> wellcomeEmailValue =
      new WellcomeEmailValueHolder<>(this);

  /**
   * @autogenerated EntityChangeSetGenerator
   * @return
   */
  public TenantConfigChangeSet newUid() {
    return version(0).uid(Uuid.comb().toString());
  }

  /**
   * Unset a value by the property name. Unset values will no provide command change neither provide
   * information to the output context (hidden or readonly fields, or policy restrictions).
   *
   * @autogenerated EntityChangeSetGenerator
   * @param field The field name to unset.
   */
  public void unset(final String field) {
    uidValue.unsetUidIfMatches(field);
    tenantValue.unsetTenantIfMatches(field);
    innerLabelValue.unsetInnerLabelIfMatches(field);
    forceMfaValue.unsetForceMfaIfMatches(field);
    dynamicRegistrationPolicyValue.unsetDynamicRegistrationPolicyIfMatches(field);
    allowRegisterValue.unsetAllowRegisterIfMatches(field);
    enableRegisterUsersValue.unsetEnableRegisterUsersIfMatches(field);
    magicLinkEnabledValue.unsetMagicLinkEnabledIfMatches(field);
    webauthnEnabledValue.unsetWebauthnEnabledIfMatches(field);
    webauthnRpIdValue.unsetWebauthnRpIdIfMatches(field);
    webauthnRpNameValue.unsetWebauthnRpNameIfMatches(field);
    wellcomeEmailValue.unsetWellcomeEmailIfMatches(field);
    registerdEmailValue.unsetRegisterdEmailIfMatches(field);
    disabledUserEmailValue.unsetDisabledUserEmailIfMatches(field);
    enabledUserEmailValue.unsetEnabledUserEmailIfMatches(field);
    allowRecoverPassValue.unsetAllowRecoverPassIfMatches(field);
    recoverPassEmailValue.unsetRecoverPassEmailIfMatches(field);
    versionValue.unsetVersionIfMatches(field);
  }
}
