package net.civeira.phylax.features.access.user.application.usecase.unlock;

import java.util.List;

import io.quarkus.arc.Unremovable;
import jakarta.enterprise.context.ApplicationScoped;
import lombok.Data;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.batch.stepper.ItemDescriptor;
import net.civeira.phylax.common.batch.stepper.ItemProcessor;
import net.civeira.phylax.common.batch.stepper.ItemReader;
import net.civeira.phylax.common.batch.stepper.ItemWriter;
import net.civeira.phylax.common.batch.stepper.StepContext;
import net.civeira.phylax.common.batch.stepper.StepCounter;
import net.civeira.phylax.common.batch.stepper.StepFinalizer;
import net.civeira.phylax.common.batch.stepper.StepInitializer;
import net.civeira.phylax.common.exception.ExecutionException;
import net.civeira.phylax.common.security.Allow;
import net.civeira.phylax.features.access.user.User;
import net.civeira.phylax.features.access.user.application.service.visibility.UsersVisibility;
import net.civeira.phylax.features.access.user.query.UserCursor;

@Unremovable
@ApplicationScoped
@RequiredArgsConstructor
class UserUnlocksInBatchExecutor implements
    StepCounter<UserUnlockAllInBatchCommand, UserUnlocksInBatchExecutor.UserPaginableBatch>,
    StepFinalizer<UserUnlockAllInBatchCommand, UserUnlocksInBatchExecutor.UserPaginableBatch>,
    StepInitializer<UserUnlockAllInBatchCommand, UserUnlocksInBatchExecutor.UserPaginableBatch>,
    ItemReader<User, UserUnlockAllInBatchCommand, UserUnlocksInBatchExecutor.UserPaginableBatch>,
    ItemWriter<User, UserUnlockAllInBatchCommand, UserUnlocksInBatchExecutor.UserPaginableBatch>,
    ItemProcessor<User, User, UserUnlockAllInBatchCommand, UserUnlocksInBatchExecutor.UserPaginableBatch>,
    ItemDescriptor<User, UserUnlockAllInBatchCommand, UserUnlocksInBatchExecutor.UserPaginableBatch> {

  /**
   * @autogenerated EntityGenerator
   */
  @Data
  public static class UserPaginableBatch {

    /**
     * @autogenerated EntityGenerator
     */
    private String since;
  }

  /**
   * @autogenerated EntityGenerator
   */
  private final int size = 10;

  /**
   * @autogenerated EntityGenerator
   */
  private final UserUnlockUsecase usecase;

  /**
   * @autogenerated EntityGenerator
   */
  private final UsersVisibility visibility;

  /**
   * @autogenerated EntityGenerator
   * @param context
   * @return
   */
  @Override
  public long approximatedItems(
      final StepContext<UserUnlockAllInBatchCommand, UserPaginableBatch> context) {
    return visibility.countVisibles(context.getParams().getInteraction(),
        context.getParams().getFilter());
  }

  /**
   * @autogenerated EntityGenerator
   * @param context
   */
  @Override
  public void finish(final StepContext<UserUnlockAllInBatchCommand, UserPaginableBatch> context) {
    usecase.flush();
  }

  /**
   * @autogenerated EntityGenerator
   * @param context
   */
  @Override
  public void init(final StepContext<UserUnlockAllInBatchCommand, UserPaginableBatch> context) {
    context.setState(new UserPaginableBatch());
  }

  /**
   * @autogenerated EntityGenerator
   * @param item
   * @param context
   * @return
   */
  @Override
  public String itemDescription(final User item,
      final StepContext<UserUnlockAllInBatchCommand, UserPaginableBatch> context) {
    return item.getUidValue();
  }

  /**
   * @autogenerated EntityGenerator
   * @param item
   * @param context
   * @return
   */
  @Override
  public User process(final User item,
      final StepContext<UserUnlockAllInBatchCommand, UserPaginableBatch> context) {
    Allow allowed = usecase.allow(context.getParams().getInteraction(), item);
    if (!allowed.isAllowed()) {
      throw new ExecutionException("not-allowed", null);
    }
    return item;
  }

  /**
   * @autogenerated EntityGenerator
   * @param context
   * @return
   */
  @Override
  public List<User> read(
      final StepContext<UserUnlockAllInBatchCommand, UserPaginableBatch> context) {
    List<User> page = visibility.listVisiblesForUpdate(context.getParams().getInteraction(),
        context.getParams().getFilter(),
        UserCursor.builder().limit(size).sinceUid(context.getState().getSince()).build());
    context.getState().setSince(page.isEmpty() ? null : page.get(page.size() - 1).getUidValue());
    return page;
  }

  /**
   * @autogenerated EntityGenerator
   * @param items
   * @param context
   */
  @Override
  public void write(final List<User> items,
      final StepContext<UserUnlockAllInBatchCommand, UserPaginableBatch> context) {
    items.forEach(item -> usecase.unlock(context.getParams().getInteraction(), item));
  }
}
