package net.civeira.phylax.features.document.templateversion.infrastructure.driver.rest;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.ws.rs.core.Response;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.infrastructure.CurrentRequest;
import net.civeira.phylax.common.telemetry.ApiObserved;
import net.civeira.phylax.common.telemetry.Trace;
import net.civeira.phylax.features.document.templateversion.application.usecase.retrieve.TemplateVersionRetrieveProjection;
import net.civeira.phylax.features.document.templateversion.application.usecase.retrieve.TemplateVersionRetrieveUsecase;
import net.civeira.phylax.features.document.templateversion.domain.TemplateVersionReference;
import net.civeira.phylax.generated.openapi.model.TemplateApiRef;
import net.civeira.phylax.generated.openapi.model.TemplateVersionApiDto;

@RequiredArgsConstructor
@ApplicationScoped
public class TemplateVersionRetrieveController {

  /**
   * @autogenerated RetrieveControllerGenerator
   */
  private final CurrentRequest currentRequest;

  /**
   * @autogenerated RetrieveControllerGenerator
   */
  private final TemplateVersionRetrieveUsecase retrieve;

  /**
   * @autogenerated RetrieveControllerGenerator
   * @param uid
   * @return
   */
  @ApiObserved("Api to retrieve an entity of template version")
  public Response templateVersionApiRetrieve(final String uid) {
    Trace.setAttribute("ref", uid);
    TemplateVersionRetrieveProjection retrieved =
        retrieve.retrieve(currentRequest.interaction(), TemplateVersionReference.of(uid));
    /* .header("Last-Modified", value.getSince().format(DateTimeFormatter.RFC_1123_DATE_TIME))) */
    return Response.ok(toApiModel(retrieved)).build();
  }

  /**
   * @autogenerated RetrieveControllerGenerator
   * @param dto
   * @return
   */
  private TemplateVersionApiDto toApiModel(TemplateVersionRetrieveProjection dto) {
    TemplateVersionApiDto templateVersionApiDto = new TemplateVersionApiDto();
    templateVersionApiDto.setUid(dto.getUid());
    templateVersionApiDto.setTemplate(new TemplateApiRef().$ref(dto.getTemplateReference()));
    templateVersionApiDto.setLocale(dto.getLocale());
    templateVersionApiDto.setSubject(dto.getSubject());
    templateVersionApiDto.setContentHtml(dto.getContentHtml());
    templateVersionApiDto.setContentText(dto.getContentText());
    templateVersionApiDto.setVersion(dto.getVersion());
    return templateVersionApiDto;
  }
}
