package net.civeira.phylax.features.notification.smtpoutboundconfig.application.usecase.delete;

import java.time.Duration;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.batch.BatchIdentificator;
import net.civeira.phylax.common.batch.BatchProgress;
import net.civeira.phylax.common.batch.BatchService;
import net.civeira.phylax.common.batch.ExecutorByDeferSteps;
import net.civeira.phylax.common.batch.ExecutorPlan;
import net.civeira.phylax.common.exception.NotAllowedException;
import net.civeira.phylax.common.exception.NotFoundException;
import net.civeira.phylax.common.security.OperationContext;
import net.civeira.phylax.common.security.Permission;
import net.civeira.phylax.common.telemetry.Observed;
import net.civeira.phylax.common.telemetry.Trace;
import net.civeira.phylax.features.notification.smtpoutboundconfig.application.visibility.SmtpOutboundConfigVisibilityFilter;
import net.civeira.phylax.features.notification.smtpoutboundconfig.application.visibility.SmtpOutboundConfigsVisibility;
import net.civeira.phylax.features.notification.smtpoutboundconfig.domain.SmtpOutboundConfig;
import net.civeira.phylax.features.notification.smtpoutboundconfig.domain.SmtpOutboundConfigRef;
import net.civeira.phylax.features.notification.smtpoutboundconfig.domain.gateway.SmtpOutboundConfigAuditGateway;
import net.civeira.phylax.features.notification.smtpoutboundconfig.domain.gateway.SmtpOutboundConfigCacheGateway;
import net.civeira.phylax.features.notification.smtpoutboundconfig.domain.gateway.SmtpOutboundConfigWriteRepositoryGateway;

@ApplicationScoped
@RequiredArgsConstructor
public class SmtpOutboundConfigDeleteUsecase {

  /**
   * Service to register audit events
   *
   * @autogenerated DeleteUsecaseGenerator
   */
  private final SmtpOutboundConfigAuditGateway audit;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final BatchService batch;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final SmtpOutboundConfigCacheGateway cache;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final Event<SmtpOutboundConfigDeleteAuthorizationDecision> deleteAllowEmitter;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final Event<SmtpOutboundConfigDeleteCheck> deleteCheckEmitter;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final SmtpOutboundConfigWriteRepositoryGateway gateway;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final SmtpOutboundConfigsVisibility visibility;

  /**
   * @autogenerated DeleteUsecaseGenerator
   * @param context
   * @param reference
   * @return
   */
  @Observed("Chekcing if is allowed to delete an entity of smtp outbound config")
  public Permission allow(final OperationContext context, final SmtpOutboundConfigRef reference) {
    Trace.setAttribute("ref", reference.getUid());
    Permission response = checkPermission(context, reference);
    Trace.setAttribute("allowed", response.isAllowed());
    return response;
  }

  /**
   * @autogenerated DeleteUsecaseGenerator
   * @param context
   * @return
   */
  @Observed("Checking if is allowed to delete a set of entities of smtp outbound config")
  public Permission allow(final OperationContext context) {
    Permission response = checkPermission(context);
    Trace.setAttribute("allowed", response.isAllowed());
    return response;
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated DeleteUsecaseGenerator
   * @param context
   * @param filter
   * @return The slide with some values
   */
  @Observed("Deleting a set of entities of smtp outbound config")
  public BatchIdentificator batchDelete(final OperationContext context,
      final SmtpOutboundConfigDeleteFilter filter) {
    Permission permission = checkPermission(context);
    if (!permission.isAllowed()) {
      Trace.addEvent("The policies for smtp outbound config dont allow to delete: "
          + permission.getDescription());
      throw new NotAllowedException(permission.getDescription());
    }
    SmtpOutboundConfigVisibilityFilter filterOnVisibles =
        SmtpOutboundConfigVisibilityFilter.builder().uid(filter.getUid().orElse(null))
            .uids(filter.getUids().stream().toList()).search(filter.getSearch().orElse(null))
            .tenant(filter.getTenant().orElse(null)).tenants(filter.getTenants())
            .tenantTenantAccesible(filter.getTenantTenantAccesible().orElse(null)).build();
    SmtpOutboundConfigDeleteAllInBatchCommand command =
        new SmtpOutboundConfigDeleteAllInBatchCommand(context, filterOnVisibles);
    return batch.start(context.getActor().getName().orElse("-"), Duration.ofHours(6), ExecutorPlan
        .<SmtpOutboundConfigDeleteAllInBatchCommand>builder().params(command).name("delete-color")
        .executor(
            ExecutorByDeferSteps.<SmtpOutboundConfig, SmtpOutboundConfig, SmtpOutboundConfigDeleteAllInBatchCommand, SmtpOutboundConfigsInBatchExecutor.SmtpOutboundConfigPaginableBatch>builder()
                .initializer(SmtpOutboundConfigsInBatchExecutor.class)
                .counter(SmtpOutboundConfigsInBatchExecutor.class)
                .descriptor(SmtpOutboundConfigsInBatchExecutor.class)
                .reader(SmtpOutboundConfigsInBatchExecutor.class)
                .processor(SmtpOutboundConfigsInBatchExecutor.class)
                .writer(SmtpOutboundConfigsInBatchExecutor.class)
                .finalizer(SmtpOutboundConfigsInBatchExecutor.class).build())
        .build());
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated DeleteUsecaseGenerator
   * @param context
   * @param query a filter to retrieve only matching values
   * @return The slide with some values
   */
  public BatchProgress checkProgress(final OperationContext context,
      final SmtpOutboundConfigCheckBatchDeleteStatus query) {
    return context.getActor().getName()
        .flatMap(name -> batch.retrieve(query.getTaskId(), context.getSource().getLocale(), name))
        .orElseThrow(() -> new NotFoundException());
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated DeleteUsecaseGenerator
   * @param context
   * @param reference
   */
  @Observed("Deleting an entity of smtp outbound config")
  public void delete(final OperationContext context, final SmtpOutboundConfigRef reference) {
    Trace.setAttribute("ref", reference.getUid());
    Permission permission = checkPermission(context, reference);
    if (!permission.isAllowed()) {
      Trace.addEvent("The policies for smtp outbound config dont allow to delete: "
          + permission.getDescription());
      throw new NotAllowedException(permission.getDescription());
    }
    SmtpOutboundConfig original = visibility.retrieveVisibleForUpdate(context, reference.getUid())
        .orElseThrow(() -> new NotFoundException(""));
    doDelete(context, original);
    cacheEvict();
    // Register audit operation
    audit.deleted("delete", original, context);
  }

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  void cacheEvict() {
    cache.evict();
  }

  /**
   * @autogenerated DeleteUsecaseGenerator
   * @param context
   * @param reference
   * @return
   */
  Permission checkPermission(final OperationContext context,
      final SmtpOutboundConfigRef reference) {
    SmtpOutboundConfigDeleteAuthorizationDecision proposal =
        new SmtpOutboundConfigDeleteAuthorizationDecision(context, reference,
            Permission.allow("Allowed by default"));
    deleteAllowEmitter.fire(proposal);
    return proposal.getPermission();
  }

  /**
   * @autogenerated DeleteUsecaseGenerator
   * @param context
   * @return
   */
  Permission checkPermission(final OperationContext context) {
    SmtpOutboundConfigDeleteAuthorizationDecision proposal =
        new SmtpOutboundConfigDeleteAuthorizationDecision(context,
            Permission.allow("Allowed by default"));
    deleteAllowEmitter.fire(proposal);
    return proposal.getPermission();
  }

  /**
   * @autogenerated DeleteUsecaseGenerator
   * @param context
   * @param original
   */
  void doDelete(final OperationContext context, final SmtpOutboundConfig original) {
    SmtpOutboundConfigDeleteCheck proposal = new SmtpOutboundConfigDeleteCheck(context, original);
    deleteCheckEmitter.fire(proposal);
    SmtpOutboundConfig clean = original.delete();
    gateway.delete(clean);
  }
}
