package net.civeira.phylax.features.document.templatesnippet.application.usecase.enable;

import java.util.Optional;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import net.civeira.phylax.features.access.tenant.domain.TenantRef;
import net.civeira.phylax.features.document.templatesnippet.application.visibility.TemplateSnippetVisibleProjection;
import net.civeira.phylax.features.document.templatesnippet.domain.TemplateSnippet;
import net.civeira.phylax.features.document.templatesnippet.domain.valueobject.CodeVO;
import net.civeira.phylax.features.document.templatesnippet.domain.valueobject.ContentHtmlVO;
import net.civeira.phylax.features.document.templatesnippet.domain.valueobject.EnabledVO;
import net.civeira.phylax.features.document.templatesnippet.domain.valueobject.TenantVO;
import net.civeira.phylax.features.document.templatesnippet.domain.valueobject.UidVO;
import net.civeira.phylax.features.document.templatesnippet.domain.valueobject.VersionVO;

/**
 * A dto transfer to hold template snippet attribute values
 */
@NoArgsConstructor(access = AccessLevel.PRIVATE)
@Getter
public class TemplateSnippetEnableProjection {

  /**
   * Create a dto instance with all the values of an entity
   *
   * @autogenerated ActionProjectionGenerator
   * @param visible The entity who provide values.
   * @return
   */
  public static TemplateSnippetEnableProjection from(
      final TemplateSnippetVisibleProjection visible) {
    TemplateSnippetEnableProjection instance = new TemplateSnippetEnableProjection();
    instance.uidValue = visible.getUid();
    instance.codeValue = visible.getCode();
    instance.tenantValue = visible.getTenant();
    instance.contentHtmlValue = visible.getContentHtml();
    instance.enabledValue = visible.getEnabled();
    instance.versionValue = visible.getVersion();
    return instance;
  }

  /**
   * HEADER, FOOTER...
   *
   * @autogenerated ActionProjectionGenerator
   */
  private Optional<CodeVO> codeValue;

  /**
   * El content html de template snippet
   *
   * @autogenerated ActionProjectionGenerator
   */
  private Optional<ContentHtmlVO> contentHtmlValue;

  /**
   * El enabled de template snippet
   *
   * @autogenerated ActionProjectionGenerator
   */
  private Optional<EnabledVO> enabledValue;

  /**
   * El tenant de template snippet
   *
   * @autogenerated ActionProjectionGenerator
   */
  private Optional<TenantVO> tenantValue;

  /**
   * El uid de template snippet
   *
   * @autogenerated ActionProjectionGenerator
   */
  private Optional<UidVO> uidValue;

  /**
   * Campo con el número de version de template snippet para controlar bloqueos optimistas
   *
   * @autogenerated ActionProjectionGenerator
   */
  private Optional<VersionVO> versionValue;

  /**
   * Create a dto instance with all the values of an entity
   *
   * @autogenerated ActionProjectionGenerator
   * @param entity The entity who provide values.
   */
  public TemplateSnippetEnableProjection(final TemplateSnippet entity) {
    uidValue = Optional.of(entity.getUidValue());
    codeValue = Optional.of(entity.getCodeValue());
    tenantValue = Optional.of(entity.getTenantValue());
    contentHtmlValue = Optional.of(entity.getContentHtmlValue());
    enabledValue = Optional.of(entity.getEnabledValue());
    versionValue = Optional.of(entity.getVersionValue());
  }

  /**
   * Inform for a possible change propolsal in Code
   *
   * @autogenerated ActionProjectionGenerator
   * @return empty if there is no change proposal for Code, otherwise the value for Code
   */
  public String getCode() {
    return getCodeOrDefault(null);
  }

  /**
   * Inform for a possible change propolsal in Code
   *
   * @autogenerated ActionProjectionGenerator
   * @param orDefault Default value if is null
   * @return empty if there is no change proposal for Code, otherwise the value for Code
   */
  public String getCodeOrDefault(final String orDefault) {
    return codeValue.map(CodeVO::getCode).orElse(orDefault);
  }

  /**
   * Inform for a possible change propolsal in ContentHtml
   *
   * @autogenerated ActionProjectionGenerator
   * @return empty if there is no change proposal for ContentHtml, otherwise the value for
   *         ContentHtml
   */
  public String getContentHtml() {
    return getContentHtmlOrDefault(null);
  }

  /**
   * Inform for a possible change propolsal in ContentHtml
   *
   * @autogenerated ActionProjectionGenerator
   * @param orDefault Default value if is null
   * @return empty if there is no change proposal for ContentHtml, otherwise the value for
   *         ContentHtml
   */
  public String getContentHtmlOrDefault(final String orDefault) {
    return contentHtmlValue.map(ContentHtmlVO::getContentHtml).orElse(orDefault);
  }

  /**
   * Inform for a possible change propolsal in Enabled
   *
   * @autogenerated ActionProjectionGenerator
   * @return empty if there is no change proposal for Enabled, otherwise the value for Enabled
   */
  public Boolean getEnabled() {
    return getEnabledOrDefault(null);
  }

  /**
   * Inform for a possible change propolsal in Enabled
   *
   * @autogenerated ActionProjectionGenerator
   * @param orDefault Default value if is null
   * @return empty if there is no change proposal for Enabled, otherwise the value for Enabled
   */
  public Boolean getEnabledOrDefault(final Boolean orDefault) {
    return enabledValue.map(EnabledVO::isEnabled).orElse(orDefault);
  }

  /**
   * Inform for a possible change propolsal in Tenant
   *
   * @autogenerated ActionProjectionGenerator
   * @return empty if there is no change proposal for Tenant, otherwise the value for Tenant
   */
  public TenantRef getTenant() {
    return tenantValue.map(TenantVO::getTenant).orElse(null);
  }

  /**
   * Inform for a possible change propolsal in Tenant
   *
   * @autogenerated ActionProjectionGenerator
   * @return empty if there is no change proposal for Tenant, otherwise the value for Tenant
   */
  public String getTenantReference() {
    return getTenantReferenceOrDefault(null);
  }

  /**
   * Inform for a possible change propolsal in Tenant
   *
   * @autogenerated ActionProjectionGenerator
   * @param orDefault
   * @return empty if there is no change proposal for Tenant, otherwise the value for Tenant
   */
  public String getTenantReferenceOrDefault(final String orDefault) {
    return tenantValue.map(TenantVO::getTenant).map(TenantRef::getUid).orElse(orDefault);
  }

  /**
   * Inform for a possible change propolsal in Uid
   *
   * @autogenerated ActionProjectionGenerator
   * @return empty if there is no change proposal for Uid, otherwise the value for Uid
   */
  public String getUid() {
    return getUidOrDefault(null);
  }

  /**
   * Inform for a possible change propolsal in Uid
   *
   * @autogenerated ActionProjectionGenerator
   * @param orDefault Default value if is null
   * @return empty if there is no change proposal for Uid, otherwise the value for Uid
   */
  public String getUidOrDefault(final String orDefault) {
    return uidValue.map(UidVO::getUid).orElse(orDefault);
  }

  /**
   * Inform for a possible change propolsal in Version
   *
   * @autogenerated ActionProjectionGenerator
   * @return empty if there is no change proposal for Version, otherwise the value for Version
   */
  public Integer getVersion() {
    return getVersionOrDefault(null);
  }

  /**
   * Inform for a possible change propolsal in Version
   *
   * @autogenerated ActionProjectionGenerator
   * @param orDefault Default value if is null
   * @return empty if there is no change proposal for Version, otherwise the value for Version
   */
  public Integer getVersionOrDefault(final Integer orDefault) {
    return versionValue.flatMap(VersionVO::getVersion).orElse(orDefault);
  }
}
