package net.civeira.phylax.features.access.usermfarecoverycode.domain.valueobject;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import net.civeira.phylax.common.exception.ConstraintException;

class CodeHashVOUnitTest {

  /**
   * @autogenerated ValueObjectGenerator
   */
  @Test
  @DisplayName("Test value object contruction for property code hash of user mfa recovery code ")
  void test_code_hash_v_o_builder() {
    Assertions.assertThrows(ConstraintException.class, () -> CodeHashVO.tryFrom(null));
    Assertions.assertEquals("one", CodeHashVO.from("one").getCodeHash());
    Object falingInstance = new Object() {};
    Assertions.assertThrows(ConstraintException.class, () -> CodeHashVO.tryFrom(falingInstance));
    Assertions.assertEquals("[" + "one" + "]", CodeHashVO.from("one").toString());
  }
}
