package net.civeira.phylax.features.access.user.application.usecase.delete;

import java.time.Duration;

import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.SpanKind;
import io.opentelemetry.api.trace.Tracer;
import io.opentelemetry.context.Context;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.batch.BatchIdentificator;
import net.civeira.phylax.common.batch.BatchProgress;
import net.civeira.phylax.common.batch.BatchService;
import net.civeira.phylax.common.batch.ExecutorByDeferSteps;
import net.civeira.phylax.common.batch.ExecutorPlan;
import net.civeira.phylax.common.exception.NotAllowedException;
import net.civeira.phylax.common.exception.NotFoundException;
import net.civeira.phylax.common.security.Allow;
import net.civeira.phylax.common.security.Interaction;
import net.civeira.phylax.features.access.user.application.visibility.UserVisibilityFilter;
import net.civeira.phylax.features.access.user.application.visibility.UsersVisibility;
import net.civeira.phylax.features.access.user.domain.User;
import net.civeira.phylax.features.access.user.domain.UserRef;
import net.civeira.phylax.features.access.user.domain.gateway.UserAuditGateway;
import net.civeira.phylax.features.access.user.domain.gateway.UserCacheGateway;
import net.civeira.phylax.features.access.user.domain.gateway.UserWriteRepositoryGateway;

@ApplicationScoped
@RequiredArgsConstructor
public class UserDeleteUsecase {

  /**
   * Service to register audit events
   *
   * @autogenerated DeleteUsecaseGenerator
   */
  private final UserAuditGateway audit;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final BatchService batch;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final UserCacheGateway cache;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final Event<UserDeleteAllowDecision> deleteAllowEmitter;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final Event<UserDeleteCheck> deleteCheckEmitter;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final UserWriteRepositoryGateway gateway;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final Tracer tracer;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final UsersVisibility visibility;

  /**
   * @autogenerated DeleteUsecaseGenerator
   * @param query
   * @param reference
   * @return
   */
  public Allow allow(final Interaction query, final UserRef reference) {
    Span span = tracer.spanBuilder("Checking if is allowed to delete an entity of user")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      span.setAttribute("ref", reference.getUid());
      Allow response = checkAllow(query, reference);
      span.setAttribute("allowed", response.isAllowed());
      return response;
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * @autogenerated DeleteUsecaseGenerator
   * @param query
   * @return
   */
  public Allow allow(final Interaction query) {
    Span span = tracer.spanBuilder("Checking if is allowed to delete an entity of user")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      Allow response = checkAllow(query);
      span.setAttribute("allowed", response.isAllowed());
      return response;
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated DeleteUsecaseGenerator
   * @param query
   * @param filter
   * @return The slide with some values
   */
  public BatchIdentificator batchDelete(final Interaction query, final UserDeleteFilter filter) {
    Span span = tracer.spanBuilder("Deleting a set of entities of user")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      Allow detail = checkAllow(query);
      if (!detail.isAllowed()) {
        span.addEvent("The policies for user dont allow to delete: " + detail.getDescription());
        throw new NotAllowedException(detail.getDescription());
      }
      UserVisibilityFilter filterOnVisibles =
          UserVisibilityFilter.builder().uid(filter.getUid().orElse(null))
              .uids(filter.getUids().stream().toList()).search(filter.getSearch().orElse(null))
              .nameOrEmail(filter.getNameOrEmail().orElse(null)).name(filter.getName().orElse(null))
              .tenant(filter.getTenant().orElse(null)).tenants(filter.getTenants())
              .tenantTenantAccesible(filter.getTenantTenantAccesible().orElse(null)).build();
      UserDeleteAllInBatchCommand command =
          UserDeleteAllInBatchCommand.builder().interaction(query).filter(filterOnVisibles).build();
      return batch.start(query.getActor().getName().orElse("-"), Duration.ofHours(6), ExecutorPlan
          .<UserDeleteAllInBatchCommand>builder().params(command).name("delete-color")
          .executor(
              ExecutorByDeferSteps.<User, User, UserDeleteAllInBatchCommand, UsersInBatchExecutor.UserPaginableBatch>builder()
                  .initializer(UsersInBatchExecutor.class).counter(UsersInBatchExecutor.class)
                  .descriptor(UsersInBatchExecutor.class).reader(UsersInBatchExecutor.class)
                  .processor(UsersInBatchExecutor.class).writer(UsersInBatchExecutor.class)
                  .finalizer(UsersInBatchExecutor.class).build())
          .build());
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated DeleteUsecaseGenerator
   * @param query a filter to retrieve only matching values
   * @return The slide with some values
   */
  public BatchProgress checkProgress(final UserCheckBatchDeleteStatus query) {
    return query.getActor().getName()
        .flatMap(name -> batch.retrieve(query.getTaskId(), query.getConnection().getLocale(), name))
        .orElseThrow(() -> new NotFoundException());
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated DeleteUsecaseGenerator
   * @param query
   * @param reference
   */
  public void delete(final Interaction query, final UserRef reference) {
    Span span = tracer.spanBuilder("Deleting an entity of user")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      span.setAttribute("ref", reference.getUid());
      Allow detail = checkAllow(query, reference);
      if (!detail.isAllowed()) {
        span.addEvent("The policies for user dont allow to delete: " + detail.getDescription());
        throw new NotAllowedException(detail.getDescription());
      }
      User original = visibility.retrieveVisibleForUpdate(query, reference.getUid())
          .orElseThrow(() -> new NotFoundException(""));
      doDelete(query, original);
      cacheEvict();
      // Register audit operation
      audit.deleted("delete", original, query);
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  void cacheEvict() {
    cache.evict();
  }

  /**
   * @autogenerated DeleteUsecaseGenerator
   * @param query
   * @param reference
   * @return
   */
  Allow checkAllow(final Interaction query, final UserRef reference) {
    UserDeleteAllowDecision base = UserDeleteAllowDecision.builder()
        .detail(Allow.builder().allowed(true).description("Allowed by default").build())
        .query(query).reference(reference).build();
    deleteAllowEmitter.fire(base);
    return base.getDetail();
  }

  /**
   * @autogenerated DeleteUsecaseGenerator
   * @param query
   * @return
   */
  Allow checkAllow(final Interaction query) {
    UserDeleteAllowDecision base = UserDeleteAllowDecision.builder()
        .detail(Allow.builder().allowed(true).description("Allowed by default").build())
        .query(query).build();
    deleteAllowEmitter.fire(base);
    return base.getDetail();
  }

  /**
   * @autogenerated DeleteUsecaseGenerator
   * @param interaction
   * @param original
   */
  void doDelete(final Interaction interaction, final User original) {
    UserDeleteCheck proposal =
        UserDeleteCheck.builder().reference(original).interaction(interaction).build();
    deleteCheckEmitter.fire(proposal);
    User clean = original.delete();
    gateway.delete(clean);
  }
}
