package net.civeira.phylax.features.access.useraccesstemporalcode.transition.markloginblock;

import java.util.function.Function;

import net.civeira.phylax.features.access.useraccesstemporalcode.UserAccessTemporalCode;

public interface UserAccessTemporalCodeMarkLoginBlockStep {

  /**
   * @autogenerated UpdateEntityRuleGenerator
   * @param transition
   * @param next
   * @return
   */
  UserAccessTemporalCode markLoginBlock(UserAccessTemporalCodeMarkLoginBlockTransition transition,
      Function<UserAccessTemporalCodeMarkLoginBlockTransition, UserAccessTemporalCode> next);
}
