package net.civeira.phylax.features.access.userinvitation.domain;

import java.time.LocalDateTime;
import java.time.ZoneId;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import net.civeira.phylax.features.access.tenant.domain.TenantReference;
import net.civeira.phylax.features.access.user.domain.UserReference;

class UserInvitationChangeSetUnitTest {

  /**
   * @autogenerated CachedGenerator
   */
  @Test
  @DisplayName("Test a entity reference contruction")
  void test_user_invitation_change_set_builder() {
    UserInvitationChangeSet one =
        new UserInvitationChangeSet().uid("one").tenant(TenantReference.of("one")).email("one")
            .roles("one").invitedBy(UserReference.of("one")).tokenHash("one").metadataJson("one")
            .status(UserInvitationStatusOptions.PENDING)
            .createdAt(LocalDateTime.of(1980, 8, 20, 0, 0).atZone(ZoneId.of("Europe/Madrid"))
                .toOffsetDateTime())
            .expiredAt(LocalDateTime.of(1980, 8, 20, 0, 0).atZone(ZoneId.of("Europe/Madrid"))
                .toOffsetDateTime())
            .acceptedAt(LocalDateTime.of(1980, 8, 20, 0, 0).atZone(ZoneId.of("Europe/Madrid"))
                .toOffsetDateTime())
            .acceptedBy(UserReference.of("one")).version(1).newUid();
    one.uid("two");
    Assertions.assertEquals("two", one.getUid().get(), "Value must equals to the assigned value");
    one.unset("uid");
    Assertions.assertFalse(one.getUid().isPresent(), "After unset, the valeue must be dissapear");
    Assertions.assertEquals(TenantReference.of("one"), one.getTenant().get(),
        "Value must equals to the intial value");
    one.tenant(TenantReference.of("two"));
    Assertions.assertEquals(TenantReference.of("two"), one.getTenant().get(),
        "Value must equals to the assigned value");
    one.unset("tenant");
    Assertions.assertFalse(one.getTenant().isPresent(),
        "After unset, the valeue must be dissapear");
    Assertions.assertEquals("one", one.getEmail().get(), "Value must equals to the intial value");
    one.email("two");
    Assertions.assertEquals("two", one.getEmail().get(), "Value must equals to the assigned value");
    one.unset("email");
    Assertions.assertFalse(one.getEmail().isPresent(), "After unset, the valeue must be dissapear");
    Assertions.assertEquals("one", one.getRoles().get(), "Value must equals to the intial value");
    one.roles("two");
    Assertions.assertEquals("two", one.getRoles().get(), "Value must equals to the assigned value");
    one.unset("roles");
    Assertions.assertFalse(one.getRoles().isPresent(), "After unset, the valeue must be dissapear");
    Assertions.assertEquals(UserReference.of("one"), one.getInvitedBy().get(),
        "Value must equals to the intial value");
    one.invitedBy(UserReference.of("two"));
    Assertions.assertEquals(UserReference.of("two"), one.getInvitedBy().get(),
        "Value must equals to the assigned value");
    one.unset("invitedBy");
    Assertions.assertFalse(one.getInvitedBy().isPresent(),
        "After unset, the valeue must be dissapear");
    Assertions.assertEquals("one", one.getTokenHash().get(),
        "Value must equals to the intial value");
    one.tokenHash("two");
    Assertions.assertEquals("two", one.getTokenHash().get(),
        "Value must equals to the assigned value");
    one.unset("tokenHash");
    Assertions.assertFalse(one.getTokenHash().isPresent(),
        "After unset, the valeue must be dissapear");
    Assertions.assertEquals("one", one.getMetadataJson().get(),
        "Value must equals to the intial value");
    one.metadataJson("two");
    Assertions.assertEquals("two", one.getMetadataJson().get(),
        "Value must equals to the assigned value");
    one.unset("metadataJson");
    Assertions.assertFalse(one.getMetadataJson().isPresent(),
        "After unset, the valeue must be dissapear");
    Assertions.assertEquals(UserInvitationStatusOptions.PENDING, one.getStatus().get(),
        "Value must equals to the intial value");
    one.status(UserInvitationStatusOptions.ACCEPTED);
    Assertions.assertEquals(UserInvitationStatusOptions.ACCEPTED, one.getStatus().get(),
        "Value must equals to the assigned value");
    one.unset("status");
    Assertions.assertFalse(one.getStatus().isPresent(),
        "After unset, the valeue must be dissapear");
    Assertions.assertEquals(
        LocalDateTime.of(1980, 8, 20, 0, 0).atZone(ZoneId.of("Europe/Madrid")).toOffsetDateTime(),
        one.getCreatedAt().get(), "Value must equals to the intial value");
    one.createdAt(
        LocalDateTime.of(1981, 9, 6, 0, 0).atZone(ZoneId.of("Europe/Madrid")).toOffsetDateTime());
    Assertions.assertEquals(
        LocalDateTime.of(1981, 9, 6, 0, 0).atZone(ZoneId.of("Europe/Madrid")).toOffsetDateTime(),
        one.getCreatedAt().get(), "Value must equals to the assigned value");
    one.unset("createdAt");
    Assertions.assertFalse(one.getCreatedAt().isPresent(),
        "After unset, the valeue must be dissapear");
    Assertions.assertEquals(
        LocalDateTime.of(1980, 8, 20, 0, 0).atZone(ZoneId.of("Europe/Madrid")).toOffsetDateTime(),
        one.getExpiredAt().get(), "Value must equals to the intial value");
    one.expiredAt(
        LocalDateTime.of(1981, 9, 6, 0, 0).atZone(ZoneId.of("Europe/Madrid")).toOffsetDateTime());
    Assertions.assertEquals(
        LocalDateTime.of(1981, 9, 6, 0, 0).atZone(ZoneId.of("Europe/Madrid")).toOffsetDateTime(),
        one.getExpiredAt().get(), "Value must equals to the assigned value");
    one.unset("expiredAt");
    Assertions.assertFalse(one.getExpiredAt().isPresent(),
        "After unset, the valeue must be dissapear");
    Assertions.assertEquals(
        LocalDateTime.of(1980, 8, 20, 0, 0).atZone(ZoneId.of("Europe/Madrid")).toOffsetDateTime(),
        one.getAcceptedAt().get(), "Value must equals to the intial value");
    one.acceptedAt(
        LocalDateTime.of(1981, 9, 6, 0, 0).atZone(ZoneId.of("Europe/Madrid")).toOffsetDateTime());
    Assertions.assertEquals(
        LocalDateTime.of(1981, 9, 6, 0, 0).atZone(ZoneId.of("Europe/Madrid")).toOffsetDateTime(),
        one.getAcceptedAt().get(), "Value must equals to the assigned value");
    one.unset("acceptedAt");
    Assertions.assertFalse(one.getAcceptedAt().isPresent(),
        "After unset, the valeue must be dissapear");
    Assertions.assertEquals(UserReference.of("one"), one.getAcceptedBy().get(),
        "Value must equals to the intial value");
    one.acceptedBy(UserReference.of("two"));
    Assertions.assertEquals(UserReference.of("two"), one.getAcceptedBy().get(),
        "Value must equals to the assigned value");
    one.unset("acceptedBy");
    Assertions.assertFalse(one.getAcceptedBy().isPresent(),
        "After unset, the valeue must be dissapear");
    Assertions.assertEquals(0, one.getVersion().get(), "Value must equals to the intial value");
    one.version(2);
    Assertions.assertEquals(2, one.getVersion().get(), "Value must equals to the assigned value");
    one.unset("version");
    Assertions.assertFalse(one.getVersion().isPresent(),
        "After unset, the valeue must be dissapear");
  }
}
