package net.civeira.phylax.features.access.tenant;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.ToString;
import lombok.With;
import net.civeira.phylax.features.access.tenant.valueobject.UidVO;

@Getter
@ToString
@RequiredArgsConstructor
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class TenantReference implements TenantRef {

  /**
   * @autogenerated EntityReferenceImplGenerator
   * @param uid
   * @return
   */
  public static TenantReference of(final String uid) {
    return new TenantReference(UidVO.from(uid));
  }

  /**
   * A uid string to identify the entity
   *
   * @autogenerated EntityReferenceImplGenerator
   */
  @EqualsAndHashCode.Include
  @NonNull
  private UidVO uid;

  /**
   * @autogenerated EntityReferenceImplGenerator
   * @return
   */
  public String getUidValue() {
    return getUid().getValue();
  }

  /**
   * @autogenerated EntityReferenceImplGenerator
   * @param uid
   * @return
   */
  public TenantReference withUidValue(final String uid) {
    return withUid(UidVO.from(uid));
  }
}
