/* @autogenerated */
package net.civeira.phylax.features.oauth.authentication.domain;

/**
 * Challenge steps that can be satisfied during authentication.
 *
 * Responsibilities: - Enumerate required checkpoints in the login flow. - Provide a shared
 * vocabulary across services.
 *
 * Design notes: - Used to track which challenges are complete. - Used to decide next steps in the
 * UI flow.
 */
public enum AuthenticationChallege {

  PASSWORD, MFA, FRESH_PASSWORD, USE_CONSENT, CLIENT_CONSENT;
}
