package net.civeira.phylax.features.access.userprofile.domain.valueholder;

import java.util.Optional;

import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.value.validation.ConstraintFailList;
import net.civeira.phylax.features.access.userprofile.domain.UserProfile;
import net.civeira.phylax.features.access.userprofile.domain.valueobject.PhoneNumberVerifiedVO;

@RequiredArgsConstructor
public class PhoneNumberVerifiedValueHolder<T> {

  /**
   * @autogenerated ValueHolderGenerator
   */
  private final T holder;

  /**
   * @autogenerated ValueHolderGenerator
   */
  private Optional<PhoneNumberVerifiedVO> value = Optional.empty();

  /**
   * @autogenerated ValueHolderGenerator
   * @return
   */
  public Optional<Boolean> getPhoneNumberVerified() {
    return value.map(PhoneNumberVerifiedVO::isPhoneNumberVerified);
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @return
   */
  public Optional<PhoneNumberVerifiedVO> getPhoneNumberVerifiedValue() {
    return value;
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @param phoneNumberVerified
   * @return
   */
  public T phoneNumberVerified(PhoneNumberVerifiedVO phoneNumberVerified) {
    this.value = Optional.of(phoneNumberVerified);
    return this.holder;
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @param phoneNumberVerified
   * @return
   */
  public T phoneNumberVerified(Optional<PhoneNumberVerifiedVO> phoneNumberVerified) {
    this.value = phoneNumberVerified;
    return this.holder;
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @param phoneNumberVerified
   * @return
   */
  public T phoneNumberVerified(Boolean phoneNumberVerified) {
    this.value = Optional.of(PhoneNumberVerifiedVO.from(phoneNumberVerified));
    return this.holder;
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @return
   */
  public T phoneNumberVerifiedNull() {
    this.value = Optional.empty();
    return this.holder;
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @param original
   * @param fails
   * @return
   */
  public PhoneNumberVerifiedVO readPhoneNumberVerified(final Optional<UserProfile> original,
      final ConstraintFailList fails) {
    return value.orElse(original.map(UserProfile::getPhoneNumberVerifiedValue)
        .orElseGet(PhoneNumberVerifiedVO::nullValue));
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @return
   */
  public T unsetPhoneNumberVerified() {
    value = Optional.empty();
    return holder;
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @param field
   * @return
   */
  public T unsetPhoneNumberVerifiedIfMatches(final String field) {
    if ("phoneNumberVerified".equals(field)) {
      value = Optional.empty();
    }
    return holder;
  }
}
