package net.civeira.phylax.features.access.scopeassignation.application.usecase.update;

import java.util.Optional;
import java.util.function.UnaryOperator;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.With;
import net.civeira.phylax.common.security.Interaction;
import net.civeira.phylax.features.access.scopeassignation.domain.ScopeAssignationRef;

@Data
@Builder(toBuilder = true)
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class ScopeAssignationUpdateEnrich {

  /**
   * @autogenerated UpdateEnrichGenerator
   */
  @NonNull
  private final Interaction interaction;

  /**
   * @autogenerated UpdateEnrichGenerator
   */
  private final ScopeAssignationRef reference;

  /**
   * @autogenerated UpdateEnrichGenerator
   */
  @NonNull
  private ScopeAssignationUpdateInput input;

  /**
   * @autogenerated UpdateEnrichGenerator
   * @return
   */
  public Optional<ScopeAssignationRef> getReference() {
    return Optional.ofNullable(reference);
  }

  /**
   * @autogenerated UpdateEnrichGenerator
   * @param mapper
   */
  public void map(UnaryOperator<ScopeAssignationUpdateInput> mapper) {
    input = mapper.apply(input);
  }
}
