package net.civeira.phylax.features.access.loginprovider.valueobject;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.With;
import net.civeira.phylax.common.exception.ConstraintException;
import net.civeira.phylax.common.value.validation.AbstractFailList;
import net.civeira.phylax.common.value.validation.ConstraintFail;
import net.civeira.phylax.common.value.validation.ConstraintFailList;
import net.civeira.phylax.features.access.loginprovider.LoginProviderSourceOptions;

/**
 * Value Object representing the source protocol or system used for authentication (e.g., GOOGLE,
 * GITHUB, SAML). of loginProvider.
 * <p>
 * This class ensures that the source is a non-null {@code String} and encapsulates its validation
 * and formatting logic. It is immutable and compliant with DDD (Domain-Driven Design) principles.
 * </p>
 * <p>
 * Use {@link #from(String)} or {@link #tryFrom(Object)} to safely create instances. Validation
 * errors are reported via {@link ConstraintFailList} or thrown as {@link ConstraintException}.
 * </p>
 */
@Getter
@RequiredArgsConstructor
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class SourceVO {

  /**
   * An empty instance
   *
   * @autogenerated ValueObjectGenerator
   * @param source
   * @return An empty instance
   */
  public static SourceVO from(final LoginProviderSourceOptions source) {
    return tryFrom(source);
  }

  /**
   * An empty instance
   *
   * @autogenerated ValueObjectGenerator
   * @param source
   * @return An empty instance
   */
  public static SourceVO tryFrom(final Object source) {
    ConstraintFailList list = new ConstraintFailList();
    SourceVO result = tryFrom(source, list);
    if (list.hasErrors()) {
      throw new ConstraintException(list);
    }
    return result;
  }

  /**
   * An empty instance
   *
   * @autogenerated ValueObjectGenerator
   * @param source temptative value
   * @param fails Error list
   * @return An empty instance
   */
  public static <T extends AbstractFailList> SourceVO tryFrom(final Object source, final T fails) {
    if (null == source) {
      fails.add(new ConstraintFail("not-null", "source", null, "Cant be null"));
      return null;
    } else if (source instanceof LoginProviderSourceOptions castedSource) {
      return new SourceVO(castedSource);
    } else if (source instanceof String castedSource) {
      try {
        return new SourceVO(LoginProviderSourceOptions.valueOf(castedSource));
      } catch (IllegalArgumentException err) {
        fails.add(new ConstraintFail("wrong-option", "source", castedSource,
            "A valid enum option is expected for source"));
        return null;
      }
    } else {
      fails.add(new ConstraintFail("wrong-type", "source", source.getClass(),
          "A LoginProviderSourceOptions type is expected for source"));
      return null;
    }
  }

  /**
   * The actual value of the name. * It is guaranteed to be a non-null String after successful
   * value.validation.
   *
   * @autogenerated ValueObjectGenerator
   */
  private final LoginProviderSourceOptions value;

  /**
   * the string value wrapped in square brackets.
   *
   * @autogenerated ValueObjectGenerator
   * @return the string value wrapped in square brackets.
   */
  @Override
  public String toString() {
    return "[" + value + "]";
  }
}
