package net.civeira.phylax.features.access.role.transition.create;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Function;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.inject.Instance;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.features.access.role.Role;
import net.civeira.phylax.features.access.role.command.RoleWriteAttributes;
import net.civeira.phylax.features.access.role.transition.RoleChangeProposal;

@ApplicationScoped
@RequiredArgsConstructor
public class RoleCreatePipeline {

  /**
   * @autogenerated UpdateEntityRuleGenerator
   */
  private final Instance<RoleCreateStep> steps;

  /**
   * @autogenerated UpdateEntityRuleGenerator
   * @param attributes
   * @param last
   * @return
   */
  public Role create(final RoleWriteAttributes attributes,
      final Function<RoleChangeProposal, Role> last) {
    Function<RoleCreateTransition, Role> finalHandler = t -> {
      if (t.hasErrors()) {
        throw t.asConstraintException();
      }
      return last.apply(t.getData());
    };
    List<RoleCreateStep> reversed = new ArrayList<>(steps.stream().toList()).reversed();
    Function<RoleCreateTransition, Role> pipeline = reversed.stream().reduce(finalHandler,
        (next, step) -> transition -> step.create(transition, next), (f1, f2) -> f1);
    return pipeline
        .apply(RoleCreateTransition.builder().data(new RoleChangeProposal(attributes)).build());
  }
}
