package net.civeira.phylax.features.access.securityscope.valueobject;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.With;
import net.civeira.phylax.common.exception.ConstraintException;
import net.civeira.phylax.common.value.validation.AbstractFailList;
import net.civeira.phylax.common.value.validation.ConstraintFail;
import net.civeira.phylax.common.value.validation.ConstraintFailList;

/**
 * Value Object representing a label to show the scope of securityScope.
 * <p>
 * This class ensures that the scope is a non-null {@code String} and encapsulates its validation
 * and formatting logic. It is immutable and compliant with DDD (Domain-Driven Design) principles.
 * </p>
 * <p>
 * Use {@link #from(String)} or {@link #tryFrom(Object)} to safely create instances. Validation
 * errors are reported via {@link ConstraintFailList} or thrown as {@link ConstraintException}.
 * </p>
 */
@Getter
@RequiredArgsConstructor
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class ScopeVO {

  /**
   * An empty instance
   *
   * @autogenerated ValueObjectGenerator
   * @param scope
   * @return An empty instance
   */
  public static ScopeVO from(final String scope) {
    return tryFrom(scope);
  }

  /**
   * An empty instance
   *
   * @autogenerated ValueObjectGenerator
   * @param scope
   * @return An empty instance
   */
  public static ScopeVO tryFrom(final Object scope) {
    ConstraintFailList list = new ConstraintFailList();
    ScopeVO result = tryFrom(scope, list);
    if (list.hasErrors()) {
      throw new ConstraintException(list);
    }
    return result;
  }

  /**
   * An empty instance
   *
   * @autogenerated ValueObjectGenerator
   * @param scope temptative value
   * @param fails Error list
   * @return An empty instance
   */
  public static <T extends AbstractFailList> ScopeVO tryFrom(final Object scope, final T fails) {
    if (null == scope) {
      fails.add(new ConstraintFail("not-null", "scope", null, "Cant be null"));
      return null;
    } else if (scope instanceof String castedScope) {
      return new ScopeVO(castedScope);
    } else {
      fails.add(new ConstraintFail("wrong-type", "scope", scope.getClass(),
          "A String type is expected for scope"));
      return null;
    }
  }

  /**
   * The actual value of the name. * It is guaranteed to be a non-null String after successful
   * value.validation.
   *
   * @autogenerated ValueObjectGenerator
   */
  private final String value;

  /**
   * the string value wrapped in square brackets.
   *
   * @autogenerated ValueObjectGenerator
   * @return the string value wrapped in square brackets.
   */
  @Override
  public String toString() {
    return "[" + value + "]";
  }
}
