package net.civeira.phylax.features.access.tenant.infrastructure.driver.rest;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.stream.Stream;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.ws.rs.core.Response;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.infrastructure.CurrentRequest;
import net.civeira.phylax.common.telemetry.ApiObserved;
import net.civeira.phylax.features.access.tenant.application.usecase.list.TenantListCursor;
import net.civeira.phylax.features.access.tenant.application.usecase.list.TenantListFilter;
import net.civeira.phylax.features.access.tenant.application.usecase.list.TenantListOrder;
import net.civeira.phylax.features.access.tenant.application.usecase.list.TenantListProjection;
import net.civeira.phylax.features.access.tenant.application.usecase.list.TenantListUsecase;
import net.civeira.phylax.generated.openapi.model.TenantApiDto;
import net.civeira.phylax.generated.openapi.model.TenantApiDtoList;

@RequiredArgsConstructor
@ApplicationScoped
public class TenantListController {

  /**
   * @autogenerated ListControllerGenerator
   */
  private static final String LIMIT_APPEND = "&limit=";

  /**
   * @autogenerated ListControllerGenerator
   */
  private static final String NAME_APPEND = "&name=";

  /**
   * @autogenerated ListControllerGenerator
   */
  private static final String SEARCH_APPEND = "&search=";

  /**
   * @autogenerated ListControllerGenerator
   */
  private static final String SINCE_APPEND = "&since-uid=";

  /**
   * @autogenerated ListControllerGenerator
   */
  private static final String UID_APPEND = "&uid=";

  /**
   * Tenant
   *
   * @autogenerated ListControllerGenerator
   */
  private final CurrentRequest currentRequest;

  /**
   * @autogenerated ListControllerGenerator
   */
  private final TenantListUsecase list;

  /**
   * @autogenerated ListControllerGenerator
   * @param uids
   * @param search
   * @param name
   * @param limit
   * @param sinceUid
   * @param sinceName
   * @param sinceDomain
   * @param order
   * @return
   */
  @ApiObserved("Api to list an entity of tenant")
  public Response tenantApiList(final List<String> uids, final String search, final String name,
      final Integer limit, final String sinceUid, final String sinceName, final String sinceDomain,
      final String order) {
    List<TenantListOrder> orderSteps = null == order ? List.of()
        : Arrays.asList(order.split(",")).stream().map(this::mapOrder).filter(Objects::nonNull)
            .toList();
    TenantListFilter.TenantListFilterBuilder filterBuilder = TenantListFilter.builder();
    TenantListCursor.TenantListCursorBuilder cursorBuilder = TenantListCursor.builder();
    filterBuilder = filterBuilder.uids(
        null == uids ? null : uids.stream().flatMap(part -> Stream.of(part.split(","))).toList());
    filterBuilder = filterBuilder.search(search);
    filterBuilder = filterBuilder.name(name);
    cursorBuilder = cursorBuilder.limit(limit);
    cursorBuilder = cursorBuilder.sinceUid(sinceUid);
    cursorBuilder = cursorBuilder.sinceName(sinceName);
    cursorBuilder = cursorBuilder.sinceDomain(sinceDomain);
    cursorBuilder = cursorBuilder.order(orderSteps);
    TenantListFilter filter = filterBuilder.build();
    TenantListCursor cursor = cursorBuilder.build();
    List<TenantListProjection> listed = list.list(currentRequest.interaction(), filter, cursor);
    return currentRequest.cacheableResponse(listed, toListApiModel(listed, filter, cursor),
        "tenant-" + ("" + filter + cursor).hashCode());
  }

  /**
   * @autogenerated ListControllerGenerator
   * @param label
   * @return
   */
  private TenantListOrder mapOrder(final String label) {
    if (null == label) {
      return null;
    } else if (label.trim().equals("name-asc")) {
      return TenantListOrder.NAME_ASC;
    } else if (label.trim().equals("name-desc")) {
      return TenantListOrder.NAME_DESC;
    } else if (label.trim().equals("domain-asc")) {
      return TenantListOrder.DOMAIN_ASC;
    } else if (label.trim().equals("domain-desc")) {
      return TenantListOrder.DOMAIN_DESC;
    } else {
      return null;
    }
  }

  /**
   * @autogenerated ListControllerGenerator
   * @param dto
   * @return
   */
  private TenantApiDto toApiModel(TenantListProjection dto) {
    TenantApiDto tenantApiDto = new TenantApiDto();
    tenantApiDto.setUid(dto.getUid());
    tenantApiDto.setName(dto.getName());
    tenantApiDto.setRoot(dto.getRoot());
    tenantApiDto.setDomain(dto.getDomain());
    tenantApiDto.setEnabled(dto.getEnabled());
    tenantApiDto.setMarkForDelete(dto.getMarkForDelete());
    tenantApiDto.setMarkForDeleteTime(dto.getMarkForDeleteTime());
    tenantApiDto.setVersion(dto.getVersion());
    return tenantApiDto;
  }

  /**
   * @autogenerated ListControllerGenerator
   * @param tenants
   * @param filter
   * @param cursor
   * @return
   */
  private TenantApiDtoList toListApiModel(List<TenantListProjection> tenants,
      TenantListFilter filter, TenantListCursor cursor) {
    Optional<TenantListProjection> last =
        tenants.isEmpty() ? Optional.empty() : Optional.of(tenants.get(tenants.size() - 1));
    StringBuilder self = new StringBuilder();
    StringBuilder next = new StringBuilder();
    StringBuilder first = new StringBuilder();
    if (!filter.getUids().isEmpty()) {
      String uidsValue =
          URLEncoder.encode(String.join(",", filter.getUids()), StandardCharsets.UTF_8);
      self.append(UID_APPEND + uidsValue);
      next.append(UID_APPEND + uidsValue);
      first.append(UID_APPEND + uidsValue);
    }
    filter.getSearch().ifPresent(search -> {
      String searchValue = URLEncoder.encode(search, StandardCharsets.UTF_8);
      self.append(SEARCH_APPEND + searchValue);
      next.append(SEARCH_APPEND + searchValue);
      first.append(SEARCH_APPEND + searchValue);
    });
    filter.getName().ifPresent(filterName -> {
      String nameValue = URLEncoder.encode(String.valueOf(filterName), StandardCharsets.UTF_8);
      self.append(NAME_APPEND + nameValue);
      next.append(NAME_APPEND + nameValue);
      first.append(NAME_APPEND + nameValue);
    });
    cursor.getLimit().ifPresent(limit -> {
      self.append(LIMIT_APPEND + limit);
      first.append(LIMIT_APPEND + limit);
      next.append(LIMIT_APPEND + limit);
    });
    cursor.getSinceUid().ifPresent(
        since -> self.append(SINCE_APPEND + URLEncoder.encode(since, StandardCharsets.UTF_8)));
    cursor.getSinceName().ifPresent(sinceName -> self
        .append("&since-name=" + URLEncoder.encode(sinceName, StandardCharsets.UTF_8)));
    cursor.getSinceDomain().ifPresent(sinceDomain -> self
        .append("&since-domain=" + URLEncoder.encode(sinceDomain, StandardCharsets.UTF_8)));
    if (!cursor.getOrder().isEmpty()) {
      String urlOrder = URLEncoder.encode(
          String.join(",",
              cursor.getOrder().stream().map(this::writeOrder).filter(Objects::nonNull).toList()),
          StandardCharsets.UTF_8);
      self.append("&order=" + urlOrder);
      next.append("&order=" + urlOrder);
      first.append("&order=" + urlOrder);
    }
    last.ifPresent(lastDto -> {
      next.append(SINCE_APPEND + URLEncoder.encode(lastDto.getUid(), StandardCharsets.UTF_8));;
      cursor.getSinceName().ifPresent(sinceName -> next
          .append("&since-name=" + URLEncoder.encode(sinceName, StandardCharsets.UTF_8)));
      cursor.getSinceDomain().ifPresent(sinceDomain -> next
          .append("&since-domain=" + URLEncoder.encode(sinceDomain, StandardCharsets.UTF_8)));
    });
    return new TenantApiDtoList().items(tenants.stream().map(this::toApiModel).toList())
        .next(next.length() > 1 ? "?" + next.substring(1) : "")
        .self(self.length() > 1 ? "?" + self.substring(1) : "")
        .first(first.length() > 1 ? "?" + first.substring(1) : "");
  }

  /**
   * @autogenerated ListControllerGenerator
   * @param order
   * @return
   */
  private String writeOrder(final TenantListOrder order) {
    if (null == order) {
      return null;
    } else if (order == TenantListOrder.NAME_ASC) {
      return "name-asc";
    } else if (order == TenantListOrder.NAME_DESC) {
      return "name-desc";
    } else if (order == TenantListOrder.DOMAIN_ASC) {
      return "domain-asc";
    } else if (order == TenantListOrder.DOMAIN_DESC) {
      return "domain-desc";
    } else {
      return null;
    }
  }
}
