package net.civeira.phylax.features.access.tenant.infrastructure.driver.rest;

import jakarta.enterprise.context.RequestScoped;
import jakarta.ws.rs.core.Response;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.infrastructure.CurrentRequest;
import net.civeira.phylax.features.access.tenant.application.usecase.retrieve.TenantRetrieveProjection;
import net.civeira.phylax.features.access.tenant.application.usecase.retrieve.TenantRetrieveUsecase;
import net.civeira.phylax.features.access.tenant.domain.TenantReference;
import net.civeira.phylax.generated.openapi.model.TenantApiDto;

@RequiredArgsConstructor
@RequestScoped
public class TenantRetrieveController {

  /**
   * @autogenerated RetrieveControllerGenerator
   */
  private final CurrentRequest currentRequest;

  /**
   * @autogenerated RetrieveControllerGenerator
   */
  private final TenantRetrieveUsecase retrieve;

  /**
   * @autogenerated RetrieveControllerGenerator
   * @param uid
   * @return
   */
  public Response tenantApiRetrieve(final String uid) {
    TenantRetrieveProjection retrieved =
        retrieve.retrieve(currentRequest.interaction(), TenantReference.of(uid));
    /* .header("Last-Modified", value.getSince().format(DateTimeFormatter.RFC_1123_DATE_TIME))) */
    return Response.ok(toApiModel(retrieved)).build();
  }

  /**
   * @autogenerated RetrieveControllerGenerator
   * @param dto
   * @return
   */
  private TenantApiDto toApiModel(TenantRetrieveProjection dto) {
    TenantApiDto tenantApiDto = new TenantApiDto();
    tenantApiDto.setUid(dto.getUid());
    tenantApiDto.setName(dto.getName());
    tenantApiDto.setRoot(dto.getRoot());
    tenantApiDto.setDomain(dto.getDomain());
    tenantApiDto.setEnabled(dto.getEnabled());
    tenantApiDto.setMarkForDelete(dto.getMarkForDelete());
    tenantApiDto.setMarkForDeleteTime(dto.getMarkForDeleteTime());
    tenantApiDto.setVersion(dto.getVersion());
    return tenantApiDto;
  }
}
