package net.civeira.phylax.features.access.tenant.infrastructure.driver.rest;

import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;

import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.SpanKind;
import io.opentelemetry.api.trace.Tracer;
import io.opentelemetry.context.Context;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.transaction.Transactional;
import jakarta.ws.rs.core.Response;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.batch.BatchIdentificator;
import net.civeira.phylax.common.batch.BatchProgress;
import net.civeira.phylax.common.batch.BatchProgress.GlobalStatus;
import net.civeira.phylax.common.batch.BatchStepProgress.ErrorInfo;
import net.civeira.phylax.common.batch.BatchStepProgress.Status;
import net.civeira.phylax.common.infrastructure.CurrentRequest;
import net.civeira.phylax.features.access.tenant.application.usecase.enable.TenantEnableFilter;
import net.civeira.phylax.features.access.tenant.application.usecase.enable.TenantEnableProjection;
import net.civeira.phylax.features.access.tenant.application.usecase.enable.TenantEnableStatus;
import net.civeira.phylax.features.access.tenant.application.usecase.enable.TenantEnableUsecase;
import net.civeira.phylax.features.access.tenant.domain.TenantReference;
import net.civeira.phylax.generated.openapi.model.BatchResultErrorItem;
import net.civeira.phylax.generated.openapi.model.BatchStepProgress;
import net.civeira.phylax.generated.openapi.model.BatchStepProgress.StepStatusEnum;
import net.civeira.phylax.generated.openapi.model.BatchTaskDetail;
import net.civeira.phylax.generated.openapi.model.BatchTaskDetail.DetailStatusEnum;
import net.civeira.phylax.generated.openapi.model.BatchTaskLocalizator;
import net.civeira.phylax.generated.openapi.model.ConstraintFail;
import net.civeira.phylax.generated.openapi.model.MultipleErrorCodes;
import net.civeira.phylax.generated.openapi.model.TenantApiDto;

@RequiredArgsConstructor
@ApplicationScoped
public class TenantEnableController {

  /**
   * @autogenerated ActionControllerGenerator
   */
  private final CurrentRequest currentRequest;

  /**
   * @autogenerated ActionControllerGenerator
   */
  private final TenantEnableUsecase enable;

  /**
   * @autogenerated ActionControllerGenerator
   */
  private final Tracer tracer;

  /**
   * @autogenerated ActionControllerGenerator
   * @param uids
   * @param search
   * @param name
   * @return
   */
  public Response tenantApiBatchEnable(final List<String> uids, final String search,
      final String name) {
    Span span = tracer.spanBuilder("Api to enable on massive entitites of tenant")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.SERVER).startSpan();
    try {
      TenantEnableFilter.TenantEnableFilterBuilder filterBuilder = TenantEnableFilter.builder();
      filterBuilder =
          filterBuilder.uids(uids.stream().flatMap(part -> Stream.of(part.split(","))).toList());
      filterBuilder = filterBuilder.search(search);
      filterBuilder = filterBuilder.uids(
          null == uids ? null : uids.stream().flatMap(part -> Stream.of(part.split(","))).toList());
      filterBuilder = filterBuilder.search(search);
      filterBuilder = filterBuilder.name(name);
      TenantEnableFilter filter = filterBuilder.build();
      BatchIdentificator task = enable.enable(currentRequest.interaction(), filter);
      /* .header("Last-Modified", value.getSince().format(DateTimeFormatter.RFC_1123_DATE_TIME)) */
      BatchTaskLocalizator response = new BatchTaskLocalizator();
      response.setUid(task.getUid());
      response.setSteps(task.getSteps());
      return Response.ok(response).build();
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * @autogenerated ActionControllerGenerator
   * @param batchId
   * @return
   */
  public Response tenantApiBatchEnableQuery(final String batchId) {
    Span span = tracer.spanBuilder("Api to check masive enable on entity of tenant")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.SERVER).startSpan();
    try {
      BatchProgress task = enable.checkProgress(
          TenantEnableStatus.builder().taskId(batchId).build(currentRequest.interaction()));
      BatchTaskDetail response = new BatchTaskDetail();
      response.setUid(task.getUid());
      GlobalStatus taskStatus = task.getStatus();
      if (null != taskStatus) {
        response.setDetailStatus(DetailStatusEnum.valueOf(taskStatus.name()));
      }
      Instant taskStart = task.getStartTime();
      if (null != taskStart) {
        response.setStartTime(OffsetDateTime.ofInstant(taskStart, ZoneId.systemDefault()));
      }
      Instant taskEnd = task.getEndTime();
      if (null != taskEnd) {
        response.setEndTime(OffsetDateTime.ofInstant(taskEnd, ZoneId.systemDefault()));
      }
      response.setSteps(task.getSteps().stream().map(step -> {
        BatchStepProgress bsp = new BatchStepProgress();
        Status stepStatus = step.getStatus();
        if (null != stepStatus) {
          bsp.setStepStatus(StepStatusEnum.valueOf(stepStatus.name()));
        }
        Instant stepStart = step.getStartTime();
        if (null != stepStart) {
          bsp.setStartTime(OffsetDateTime.ofInstant(stepStart, ZoneId.systemDefault()));
        }
        Instant stepEnd = step.getEndTime();
        if (null != stepEnd) {
          bsp.setEndTime(OffsetDateTime.ofInstant(stepEnd, ZoneId.systemDefault()));
        }
        bsp.setError(step.getError());
        bsp.setName(step.getName());
        bsp.setOks(step.getOks());
        bsp.setProcessedItems(step.getProcessedItems());
        bsp.setTotalItems(step.getTotalItems());
        bsp.setErrors(new ArrayList<>());
        bsp.setWarns(new ArrayList<>());
        Map<String, ErrorInfo> stepErrors = step.getErrors();
        if (null != stepErrors) {
          bsp.getErrors().addAll(stepErrors.entrySet().stream()
              .map(entry -> new BatchResultErrorItem().item(entry.getKey())
                  .fails(entry.getValue().getFails().stream()
                      .map(fail -> new MultipleErrorCodes().code(fail.getCode())
                          .violation(fail.getViolation())
                          .wrongValues(fail.getWrongValues().stream()
                              .map(wv -> new ConstraintFail().error(wv.getErrorMessage())
                                  .field(wv.getField()).wrong(String.valueOf(wv.getWrongValue())))
                              .toList()))
                      .toList()))
              .toList());
        }
        Map<String, ErrorInfo> stepWarns = step.getWarns();
        if (null != stepWarns) {
          bsp.getWarns().addAll(stepErrors.entrySet().stream()
              .map(entry -> new BatchResultErrorItem().item(entry.getKey())
                  .fails(entry.getValue().getFails().stream()
                      .map(fail -> new MultipleErrorCodes().code(fail.getCode())
                          .violation(fail.getViolation())
                          .wrongValues(fail.getWrongValues().stream()
                              .map(wv -> new ConstraintFail().error(wv.getErrorMessage())
                                  .field(wv.getField()).wrong(String.valueOf(wv.getWrongValue())))
                              .toList()))
                      .toList()))
              .toList());
        }
        return bsp;
      }).toList());
      return Response.ok(response).build();
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * @autogenerated ActionControllerGenerator
   * @param uid
   * @return
   */
  @Transactional
  public Response tenantApiEnable(final String uid) {
    Span span = tracer.spanBuilder("Api to enable an entity of tenant")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.SERVER).startSpan();
    try {
      span.setAttribute("ref", uid);
      TenantEnableProjection updated =
          enable.enable(currentRequest.interaction(), TenantReference.of(uid));
      return Response.ok(toApiModel(updated)).build();
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * @autogenerated ActionControllerGenerator
   * @param dto
   * @return
   */
  private TenantApiDto toApiModel(TenantEnableProjection dto) {
    Span span = tracer
        .spanBuilder("Mapper to build api content to response from model for entity of tenant")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      TenantApiDto tenantApiDto = new TenantApiDto();
      tenantApiDto.setUid(dto.getUid());
      tenantApiDto.setName(dto.getName());
      tenantApiDto.setRoot(dto.getRoot());
      tenantApiDto.setDomain(dto.getDomain());
      tenantApiDto.setEnabled(dto.getEnabled());
      tenantApiDto.setMarkForDelete(dto.getMarkForDelete());
      tenantApiDto.setMarkForDeleteTime(dto.getMarkForDeleteTime());
      tenantApiDto.setVersion(dto.getVersion());
      return tenantApiDto;
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }
}
