package net.civeira.phylax.features.document.templatevariable.infrastructure.repository;

import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Predicate;

import javax.sql.DataSource;

import io.opentelemetry.api.trace.Tracer;
import jakarta.enterprise.context.ApplicationScoped;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import net.civeira.phylax.common.algorithms.Slider;
import net.civeira.phylax.common.exception.ConstraintException;
import net.civeira.phylax.common.exception.NotFoundException;
import net.civeira.phylax.common.infrastructure.sql.OptimistLockException;
import net.civeira.phylax.common.infrastructure.sql.PartialWhere;
import net.civeira.phylax.common.infrastructure.sql.SqlCommand;
import net.civeira.phylax.common.infrastructure.sql.SqlConverter;
import net.civeira.phylax.common.infrastructure.sql.SqlListParameterValue;
import net.civeira.phylax.common.infrastructure.sql.SqlOperator;
import net.civeira.phylax.common.infrastructure.sql.SqlParameterValue;
import net.civeira.phylax.common.infrastructure.sql.SqlQuery;
import net.civeira.phylax.common.infrastructure.sql.SqlResult;
import net.civeira.phylax.common.infrastructure.sql.SqlSchematicQuery;
import net.civeira.phylax.common.infrastructure.sql.SqlTemplate;
import net.civeira.phylax.features.document.templatevariable.domain.TemplateVariable;
import net.civeira.phylax.features.document.templatevariable.domain.TemplateVariableRef;
import net.civeira.phylax.features.document.templatevariable.domain.gateway.TemplateVariableCursor;
import net.civeira.phylax.features.document.templatevariable.domain.gateway.TemplateVariableFilter;
import net.civeira.phylax.features.document.templatevariable.domain.gateway.TemplateVariableOrder;
import net.civeira.phylax.features.document.templatevariable.domain.valueobject.CodeVO;
import net.civeira.phylax.features.document.templatevariable.domain.valueobject.EnabledVO;
import net.civeira.phylax.features.document.templatevariable.domain.valueobject.TenantVO;
import net.civeira.phylax.features.document.templatevariable.domain.valueobject.TypeVO;
import net.civeira.phylax.features.document.templatevariable.domain.valueobject.UidVO;
import net.civeira.phylax.features.document.templatevariable.domain.valueobject.ValueVO;
import net.civeira.phylax.features.document.templatevariable.domain.valueobject.VersionVO;

@ApplicationScoped
@RequiredArgsConstructor
@Slf4j
public class TemplateVariableRepository {

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String CODE = "code";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_TEMPLATE_VARIABLE_CODE = "document_template_variable.code";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_TEMPLATE_VARIABLE_ENABLED =
      "document_template_variable.enabled";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_TEMPLATE_VARIABLE_SNAKE = "document_template_variable";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_TEMPLATE_VARIABLE_TENANT =
      "document_template_variable.tenant";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_TEMPLATE_VARIABLE_TYPE = "document_template_variable.type";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_TEMPLATE_VARIABLE_UID = "document_template_variable.uid";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_TEMPLATE_VARIABLE_VALUE = "document_template_variable.value";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_TEMPLATE_VARIABLE_VERSION =
      "document_template_variable.version";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String ENABLED = "enabled";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String TENANT = "tenant";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String TYPE = "type";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String UID = "uid";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String VALUE = "value";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String VERSION = "version";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private final DataSource datasource;

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private final Tracer tracer;

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public long count(TemplateVariableFilter filter) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlSchematicQuery<Long> sq = filteredQuery(template, filter);
      sq.select("count(uid) as uid");
      return sq.query(row -> Optional.of(row.getLong(1))).one().orElse(0l);
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   * @return
   */
  public TemplateVariable create(TemplateVariable entity) {
    return runCreate(entity, null);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   * @param verifier
   * @return
   */
  public TemplateVariable create(TemplateVariable entity, Predicate<TemplateVariable> verifier) {
    return runCreate(entity, verifier);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   */
  public void delete(TemplateVariable entity) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlCommand sq = template
          .createSqlCommand("delete from \"document_template_variable\" where \"uid\" = :uid");
      sq.with(UID, SqlParameterValue.of(entity.getUid()));
      int num = sq.execute();
      if (0 == num) {
        throw new IllegalArgumentException("No delete from");
      }
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param uid
   * @param filter
   * @return
   */
  public boolean exists(String uid, Optional<TemplateVariableFilter> filter) {
    return retrieve(uid, filter).isPresent();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param uid
   * @param filter
   * @return
   */
  public boolean existsForUpdate(String uid, Optional<TemplateVariableFilter> filter) {
    return retrieveForUpdate(uid, filter).isPresent();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public Optional<TemplateVariable> find(TemplateVariableFilter filter) {
    TemplateVariableCursor cursor = TemplateVariableCursor.builder().build();
    return new TemplateVariableSlider(runList(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor).one();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public Optional<TemplateVariable> find(final String sql,
      final Map<String, SqlParameterValue> params) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlQuery<TemplateVariable> createSqlQuery = template.createSqlQuery(sql);
      params.forEach(createSqlQuery::with);
      return createSqlQuery.query(converter()).one();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public Optional<TemplateVariable> findForUpdate(TemplateVariableFilter filter) {
    TemplateVariableCursor cursor = TemplateVariableCursor.builder().build();
    return new TemplateVariableSlider(runListForUpdate(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor).one();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public Optional<TemplateVariable> findForUpdate(final String sql,
      final Map<String, SqlParameterValue> params) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlQuery<TemplateVariable> createSqlQuery = template.createSqlQuery(sql);
      params.forEach(createSqlQuery::with);
      return createSqlQuery.forUpdate().query(converter()).one();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public List<TemplateVariable> list(TemplateVariableFilter filter) {
    TemplateVariableCursor cursor = TemplateVariableCursor.builder().build();
    return new TemplateVariableSlider(runList(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor).all();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public List<TemplateVariable> list(final String sql,
      final Map<String, SqlParameterValue> params) {
    return list(sql, params, null, false);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @param limit
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public List<TemplateVariable> list(final String sql, final Map<String, SqlParameterValue> params,
      final int limit) {
    return list(sql, params, Integer.valueOf(limit), false);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public List<TemplateVariable> listForUpdate(TemplateVariableFilter filter) {
    TemplateVariableCursor cursor = TemplateVariableCursor.builder().build();
    return new TemplateVariableSlider(runListForUpdate(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor).all();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public List<TemplateVariable> listForUpdate(final String sql,
      final Map<String, SqlParameterValue> params) {
    return list(sql, params, null, true);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @param limit
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public List<TemplateVariable> listForUpdate(final String sql,
      final Map<String, SqlParameterValue> params, final int limit) {
    return list(sql, params, Integer.valueOf(limit), true);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param reference
   * @return
   */
  public TemplateVariable resolve(TemplateVariableRef reference) {
    return reference instanceof TemplateVariable templateVariable ? templateVariable
        : retrieve(reference.getUid(), Optional.empty()).orElseThrow(() -> new NotFoundException(
            "Trying to resolve inexistent TemplateVariable: " + reference.getUid()));
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param reference
   * @return
   */
  public TemplateVariable resolveForUpdate(TemplateVariableRef reference) {
    return reference instanceof TemplateVariable templateVariable ? templateVariable
        : retrieveForUpdate(reference.getUid(), Optional.empty())
            .orElseThrow(() -> new NotFoundException(
                "Trying to resolve inexistent TemplateVariable: " + reference.getUid()));
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param uid
   * @param filter
   * @return
   */
  public Optional<TemplateVariable> retrieve(String uid, Optional<TemplateVariableFilter> filter) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      TemplateVariableFilter readyFilter = filter.map(val -> val.withUid(uid))
          .orElseGet(() -> TemplateVariableFilter.builder().uid(uid).build());
      SqlSchematicQuery<TemplateVariable> sq = filteredQuery(template, readyFilter);
      return sq.query(converter()).one();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param uid
   * @param filter
   * @return
   */
  public Optional<TemplateVariable> retrieveForUpdate(String uid,
      Optional<TemplateVariableFilter> filter) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      TemplateVariableFilter readyFilter = filter.map(val -> val.withUid(uid))
          .orElseGet(() -> TemplateVariableFilter.builder().uid(uid).build());
      SqlSchematicQuery<TemplateVariable> sq = filteredQuery(template, readyFilter);
      return sq.forUpdate().query(converter()).one();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @param cursor
   * @return
   */
  public Slider<TemplateVariable> slide(TemplateVariableFilter filter,
      TemplateVariableCursor cursor) {
    return new TemplateVariableSlider(runList(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @param cursor
   * @return
   */
  public Slider<TemplateVariable> slideForUpdate(TemplateVariableFilter filter,
      TemplateVariableCursor cursor) {
    return new TemplateVariableSlider(runListForUpdate(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   * @return
   */
  public TemplateVariable update(TemplateVariable entity) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlCommand sq = template.createSqlCommand(
          "update \"document_template_variable\" set  \"code\" = :code, \"tenant\" = :tenant, \"type\" = :type, \"value\" = :value, \"enabled\" = :enabled, \"version\" = \"version\" + 1 where \"uid\" = :uid and \"version\" = :version");
      sq.with(UID, SqlParameterValue.of(entity.getUid()));
      sq.with(CODE, SqlParameterValue.of(entity.getCode()));
      sq.with(TENANT, SqlParameterValue.of(entity.getTenantUid()));
      sq.with(TYPE, SqlParameterValue.of(entity.getType()));
      sq.with(VALUE,
          entity.getValue().map(SqlParameterValue::of).orElseGet(SqlParameterValue::ofNullString));
      sq.with(ENABLED, SqlParameterValue.of(entity.isEnabled()));
      sq.with(VERSION, entity.getVersion().map(SqlParameterValue::of)
          .orElseGet(SqlParameterValue::ofNullInteger));
      int num = sq.execute();
      if (0 == num) {
        throw new OptimistLockException("No delete from");
      }
      return entity.withNextVersion();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sq
   * @param cursor
   */
  private void attachWithOrder(SqlSchematicQuery<TemplateVariable> sq,
      TemplateVariableCursor cursor) {
    PartialWhere[] offset = new PartialWhere[] {PartialWhere.empty(), PartialWhere.empty()};
    for (TemplateVariableOrder order : cursor.getOrder()) {
      tryToOrderByCodeAsc(sq, offset, cursor, order);
      tryToOrderByCodeDesc(sq, offset, cursor, order);
    }
    Optional<String> sinceUid = cursor.getSinceUid();
    if (sinceUid.isPresent()) {
      offset[0] = PartialWhere.or(offset[0], PartialWhere.and(offset[1],
          PartialWhere.where("uid", SqlOperator.GT, SqlParameterValue.of(sinceUid.get()))));
    }
    sq.where(offset[0]);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @return
   */
  private SqlConverter<TemplateVariable> converter() {
    return row -> {
      try {
        return Optional.of(TemplateVariable.builder().uidValue(UidVO.from(row.getString(UID)))
            .codeValue(CodeVO.from(row.getString(CODE)))
            .tenantValue(TenantVO.fromReference(row.getString(TENANT)))
            .typeValue(TypeVO.from(row.getString(TYPE)))
            .valueValue(ValueVO.from(row.getString(VALUE)))
            .enabledValue(EnabledVO.from(row.getBoolean(ENABLED)))
            .versionValue(VersionVO.from(row.getInt(VERSION))).build());
      } catch (ConstraintException ce) {
        log.error("Unable to map data for {}", row.getString(1), ce);
        return Optional.empty();
      }
    };
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param template
   * @param filter
   * @return
   */
  private <T> SqlSchematicQuery<T> filteredQuery(SqlTemplate template,
      TemplateVariableFilter filter) {
    SqlSchematicQuery<T> sq = template.createSqlSchematicQuery(DOCUMENT_TEMPLATE_VARIABLE_SNAKE);
    sq.selectFields(DOCUMENT_TEMPLATE_VARIABLE_UID, DOCUMENT_TEMPLATE_VARIABLE_CODE,
        DOCUMENT_TEMPLATE_VARIABLE_TENANT, DOCUMENT_TEMPLATE_VARIABLE_TYPE,
        DOCUMENT_TEMPLATE_VARIABLE_VALUE, DOCUMENT_TEMPLATE_VARIABLE_ENABLED,
        DOCUMENT_TEMPLATE_VARIABLE_VERSION);
    filter.getUid().ifPresent(uid -> sq.where(UID, SqlOperator.EQ, SqlParameterValue.of(uid)));
    if (!filter.getUids().isEmpty()) {
      sq.where(UID, SqlOperator.IN, SqlListParameterValue.strings(filter.getUids()));
    }
    filter.getSearch().ifPresent(
        search -> sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%")));
    filter.getCode()
        .ifPresent(codeParam -> sq.where(CODE, SqlOperator.EQ, SqlParameterValue.of(codeParam)));
    filter.getTenant().ifPresent(tenantParam -> sq.where(TENANT, SqlOperator.EQ,
        SqlParameterValue.of(tenantParam.getUid())));
    if (!filter.getTenants().isEmpty()) {
      sq.where(TENANT, SqlOperator.IN, SqlListParameterValue.strings(filter.getTenants()));
    }
    filter.getTenantAccesible()
        .ifPresent(tenantAccesibleParam -> sq.where(DOCUMENT_TEMPLATE_VARIABLE_TENANT,
            SqlOperator.EQ, SqlParameterValue.of(tenantAccesibleParam)));
    return sq;
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @param limit
   * @param forUpdate
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  private List<TemplateVariable> list(final String sql, final Map<String, SqlParameterValue> params,
      final Integer limit, final boolean forUpdate) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlQuery<TemplateVariable> createSqlQuery = template.createSqlQuery(sql);
      params.forEach(createSqlQuery::with);
      if (forUpdate) {
        createSqlQuery = createSqlQuery.forUpdate();
      }
      SqlResult<TemplateVariable> query = createSqlQuery.query(converter());
      return null == limit ? query.all() : query.limit(limit);
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   * @param verifier
   * @return
   */
  private TemplateVariable runCreate(TemplateVariable entity,
      Predicate<TemplateVariable> verifier) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlCommand sq = template.createSqlCommand(
          "insert into \"document_template_variable\" ( \"uid\", \"code\", \"tenant\", \"type\", \"value\", \"enabled\", \"version\") values ( :uid, :code, :tenant, :type, :value, :enabled, :version)");
      sq.with(UID, SqlParameterValue.of(entity.getUid()));
      sq.with(CODE, SqlParameterValue.of(entity.getCode()));
      sq.with(TENANT, SqlParameterValue.of(entity.getTenantUid()));
      sq.with(TYPE, SqlParameterValue.of(entity.getType()));
      sq.with(VALUE,
          entity.getValue().map(SqlParameterValue::of).orElseGet(SqlParameterValue::ofNullString));
      sq.with(ENABLED, SqlParameterValue.of(entity.isEnabled()));
      sq.with(VERSION, entity.getVersion().map(SqlParameterValue::of)
          .orElseGet(SqlParameterValue::ofNullInteger));
      int num = sq.execute();
      if (0 == num) {
        throw new IllegalArgumentException("No insert into");
      }
      return verifier == null ? entity : verified(verifier.test(entity), entity, template);
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @param cursor
   * @return
   */
  private Iterator<TemplateVariable> runList(TemplateVariableFilter filter,
      TemplateVariableCursor cursor) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlSchematicQuery<TemplateVariable> sq = filteredQuery(template, filter);
      if (null != cursor.getOrder()) {
        attachWithOrder(sq, cursor);
      } else {
        cursor.getSinceUid()
            .ifPresent(since -> sq.where(UID, SqlOperator.GT, SqlParameterValue.of(since)));
      }
      sq.orderAsc("uid");
      return sq.query(converter()).limit(cursor.getLimit()).iterator();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @param cursor
   * @return
   */
  private Iterator<TemplateVariable> runListForUpdate(TemplateVariableFilter filter,
      TemplateVariableCursor cursor) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlSchematicQuery<TemplateVariable> sq = filteredQuery(template, filter);
      if (null != cursor.getOrder()) {
        attachWithOrder(sq, cursor);
      } else {
        cursor.getSinceUid()
            .ifPresent(since -> sq.where(UID, SqlOperator.GT, SqlParameterValue.of(since)));
      }
      sq.orderAsc("uid");
      return sq.forUpdate().query(converter()).limit(cursor.getLimit()).iterator();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sq
   * @param offset
   * @param cursor
   * @param order
   * @return
   */
  private PartialWhere[] tryToOrderByCodeAsc(SqlSchematicQuery<TemplateVariable> sq,
      PartialWhere[] offset, TemplateVariableCursor cursor, TemplateVariableOrder order) {
    if (order == TemplateVariableOrder.CODE_ASC) {
      sq.addOrderAsc("code");
      Optional<String> sinceCode = cursor.getSinceCode();
      if (sinceCode.isPresent()) {
        String sinceCodeValue = sinceCode.get();
        offset[0] = PartialWhere.or(offset[0], PartialWhere.and(offset[1],
            PartialWhere.where("code", SqlOperator.GT, SqlParameterValue.of(sinceCodeValue))));
        offset[1] = PartialWhere.and(offset[1],
            PartialWhere.where("code", SqlOperator.EQ, SqlParameterValue.of(sinceCodeValue)));
      }
    }
    return offset;
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sq
   * @param offset
   * @param cursor
   * @param order
   * @return
   */
  private PartialWhere[] tryToOrderByCodeDesc(SqlSchematicQuery<TemplateVariable> sq,
      PartialWhere[] offset, TemplateVariableCursor cursor, TemplateVariableOrder order) {
    if (order == TemplateVariableOrder.CODE_DESC) {
      sq.addOrderDesc("code");
      Optional<String> sinceCode = cursor.getSinceCode();
      if (sinceCode.isPresent()) {
        String sinceCodeValue = sinceCode.get();
        offset[0] = PartialWhere.or(offset[0], PartialWhere.and(offset[1],
            PartialWhere.where("code", SqlOperator.GT, SqlParameterValue.of(sinceCodeValue))));
        offset[1] = PartialWhere.and(offset[1],
            PartialWhere.where("code", SqlOperator.EQ, SqlParameterValue.of(sinceCodeValue)));
      }
    }
    return offset;
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param exists
   * @param entity
   * @param template
   * @return
   */
  private TemplateVariable verified(boolean exists, TemplateVariable entity, SqlTemplate template) {
    if (exists) {
      return entity;
    } else {
      template.createSqlCommand("delete from \"document_template_variable\" where \"uid\" = :uid")
          .with("uid", SqlParameterValue.of(entity.getUid())).execute();
      throw new NotFoundException("");
    }
  }
}
