package net.civeira.phylax.features.document.snippetasset.application.policy;

import jakarta.enterprise.event.Observes;
import net.civeira.phylax.common.security.Actor;
import net.civeira.phylax.features.document.snippetasset.application.visibility.SnippetAssetVisibilityCheck;

public class TenantAccesible {

  /**
   * Constant for platformGlobalAccess scope
   *
   * @autogenerated VisibilityPolicyGenerator
   */
  private static final String SCOPE_PLATFORM_GLOBAL_ACCESS = "platform:global_access";

  /**
   * @autogenerated VisibilityPolicyGenerator
   * @param filter
   */
  public void filterVisibles(@Observes SnippetAssetVisibilityCheck filter) {
    Actor actor = filter.getActor();
    if (!actor.hasScope(SCOPE_PLATFORM_GLOBAL_ACCESS)) {
      filter.peek(fl -> fl.setSnippetTenantTenantAccesible(actor.getTenant().orElse(null)));
    }
  }
}
