/* @autogenerated */
/**
 * Reusable application services shared across usecases.
 *
 * <p>
 * Responsibilities:
 * <ul>
 * <li>{@code ActiveUserFindService} — looks up enabled users and tenants with multiple search
 * strategies (by name, email, audience list).</li>
 * <li>{@code RequiredConsentService} — finds and records pending terms acceptance.</li>
 * <li>{@code OtpMfaService} — TOTP/OTP validation and setup.</li>
 * <li>{@code SecureCodeGenerator} — generates cryptographically-secure codes for recovery and
 * registration flows.</li>
 * </ul>
 *
 * <p>
 * Design notes:
 * <ul>
 * <li>Services here are stateless and injected via CDI into the usecases.</li>
 * <li>They do not implement any gateway port — they are internal helpers.</li>
 * </ul>
 *
 * <p>
 * Stability: internal.
 */
package net.civeira.phylax.features.oauth.authentication.application.service;
