package net.civeira.phylax.features.access.trustedclient.application.policy;

import jakarta.enterprise.event.Observes;
import net.civeira.phylax.common.security.Actor;
import net.civeira.phylax.features.access.trustedclient.application.usecase.create.TrustedClientCreateAuthorizationDecision;
import net.civeira.phylax.features.access.trustedclient.application.usecase.delete.TrustedClientDeleteAuthorizationDecision;
import net.civeira.phylax.features.access.trustedclient.application.usecase.disable.TrustedClientDisableAuthorizationDecision;
import net.civeira.phylax.features.access.trustedclient.application.usecase.enable.TrustedClientEnableAuthorizationDecision;
import net.civeira.phylax.features.access.trustedclient.application.usecase.list.TrustedClientListAuthorizationDecision;
import net.civeira.phylax.features.access.trustedclient.application.usecase.retrieve.TrustedClientRetrieveAuthorizationDecision;
import net.civeira.phylax.features.access.trustedclient.application.usecase.update.TrustedClientUpdateAuthorizationDecision;
import net.civeira.phylax.features.access.trustedclient.domain.TrustedClient;

public class OnlyForRoot {

  /**
   * @autogenerated ConditionPolicyGenerator
   * @param allowDecision
   * @param actor
   * @param instance
   */
  public void checkAllow(TrustedClientDisableAuthorizationDecision allowDecision, Actor actor,
      TrustedClient instance) {
    if (!((actor.hasScope("platform:global_access") && actor.hasRole("admin")))) {
      allowDecision.deny("Disable only for root");
    }
  }

  /**
   * @autogenerated ConditionPolicyCreateGenerator
   * @param allowDecision
   */
  public void checkAllowCreate(@Observes TrustedClientCreateAuthorizationDecision allowDecision) {
    Actor actor = allowDecision.getActor();
    allowDecision.getReference().ifPresent(ref -> {
      if (ref instanceof TrustedClient entity) {
        checkAllow(allowDecision, actor, entity);
      }
    });
  }

  /**
   * @autogenerated ConditionPolicyDeleteGenerator
   * @param allowDecision
   */
  public void checkAllowDelete(@Observes TrustedClientDeleteAuthorizationDecision allowDecision) {
    Actor actor = allowDecision.getActor();
    allowDecision.getReference().ifPresent(ref -> {
      if (ref instanceof TrustedClient entity) {
        checkAllow(allowDecision, actor, entity);
      }
    });
  }

  /**
   * @autogenerated ConditionPolicyDisableGenerator
   * @param allowDecision
   */
  public void checkAllowDisable(@Observes TrustedClientDisableAuthorizationDecision allowDecision) {
    Actor actor = allowDecision.getActor();
    allowDecision.getReference().ifPresent(ref -> {
      if (ref instanceof TrustedClient entity) {
        checkAllow(allowDecision, actor, entity);
      }
    });
  }

  /**
   * @autogenerated ConditionPolicyEnableGenerator
   * @param allowDecision
   */
  public void checkAllowEnable(@Observes TrustedClientEnableAuthorizationDecision allowDecision) {
    Actor actor = allowDecision.getActor();
    allowDecision.getReference().ifPresent(ref -> {
      if (ref instanceof TrustedClient entity) {
        checkAllow(allowDecision, actor, entity);
      }
    });
  }

  /**
   * @autogenerated ConditionPolicyListGenerator
   * @param allowDecision
   */
  public void checkAllowList(@Observes TrustedClientListAuthorizationDecision allowDecision) {
    Actor actor = allowDecision.getActor();
    allowDecision.getReference().ifPresent(ref -> {
      if (ref instanceof TrustedClient entity) {
        checkAllow(allowDecision, actor, entity);
      }
    });
  }

  /**
   * @autogenerated ConditionPolicyRetrieveGenerator
   * @param allowDecision
   */
  public void checkAllowRetrieve(
      @Observes TrustedClientRetrieveAuthorizationDecision allowDecision) {
    Actor actor = allowDecision.getActor();
    allowDecision.getReference().ifPresent(ref -> {
      if (ref instanceof TrustedClient entity) {
        checkAllow(allowDecision, actor, entity);
      }
    });
  }

  /**
   * @autogenerated ConditionPolicyUpdateGenerator
   * @param allowDecision
   */
  public void checkAllowUpdate(@Observes TrustedClientUpdateAuthorizationDecision allowDecision) {
    Actor actor = allowDecision.getActor();
    allowDecision.getReference().ifPresent(ref -> {
      if (ref instanceof TrustedClient entity) {
        checkAllow(allowDecision, actor, entity);
      }
    });
  }
}
