package net.civeira.phylax.features.document.template.infrastructure.repository;

import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Predicate;

import javax.sql.DataSource;

import io.opentelemetry.api.trace.Tracer;
import jakarta.enterprise.context.ApplicationScoped;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import net.civeira.phylax.common.algorithms.Slider;
import net.civeira.phylax.common.exception.ConstraintException;
import net.civeira.phylax.common.exception.NotFoundException;
import net.civeira.phylax.common.infrastructure.sql.OptimistLockException;
import net.civeira.phylax.common.infrastructure.sql.PartialWhere;
import net.civeira.phylax.common.infrastructure.sql.SqlCommand;
import net.civeira.phylax.common.infrastructure.sql.SqlConverter;
import net.civeira.phylax.common.infrastructure.sql.SqlListParameterValue;
import net.civeira.phylax.common.infrastructure.sql.SqlOperator;
import net.civeira.phylax.common.infrastructure.sql.SqlParameterValue;
import net.civeira.phylax.common.infrastructure.sql.SqlQuery;
import net.civeira.phylax.common.infrastructure.sql.SqlResult;
import net.civeira.phylax.common.infrastructure.sql.SqlSchematicQuery;
import net.civeira.phylax.common.infrastructure.sql.SqlTemplate;
import net.civeira.phylax.features.document.template.domain.Template;
import net.civeira.phylax.features.document.template.domain.TemplateRef;
import net.civeira.phylax.features.document.template.domain.gateway.TemplateCursor;
import net.civeira.phylax.features.document.template.domain.gateway.TemplateFilter;
import net.civeira.phylax.features.document.template.domain.gateway.TemplateOrder;
import net.civeira.phylax.features.document.template.domain.valueobject.ChannelVO;
import net.civeira.phylax.features.document.template.domain.valueobject.CodeVO;
import net.civeira.phylax.features.document.template.domain.valueobject.EnabledVO;
import net.civeira.phylax.features.document.template.domain.valueobject.TenantVO;
import net.civeira.phylax.features.document.template.domain.valueobject.ThemeVO;
import net.civeira.phylax.features.document.template.domain.valueobject.UidVO;
import net.civeira.phylax.features.document.template.domain.valueobject.VersionVO;

@ApplicationScoped
@RequiredArgsConstructor
@Slf4j
public class TemplateRepository {

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String CHANNEL = "channel";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String CODE = "code";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_TEMPLATE_CHANNEL = "document_template.channel";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_TEMPLATE_CODE = "document_template.code";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_TEMPLATE_ENABLED = "document_template.enabled";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_TEMPLATE_SNAKE = "document_template";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_TEMPLATE_TENANT = "document_template.tenant";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_TEMPLATE_THEME = "document_template.theme";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_TEMPLATE_UID = "document_template.uid";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String DOCUMENT_TEMPLATE_VERSION = "document_template.version";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String ENABLED = "enabled";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String TENANT = "tenant";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String THEME = "theme";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String UID = "uid";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private static final String VERSION = "version";

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private final DataSource datasource;

  /**
   * @autogenerated RepositoryJdbcGenerator
   */
  private final Tracer tracer;

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public long count(TemplateFilter filter) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlSchematicQuery<Long> sq = filteredQuery(template, filter);
      sq.select("count(uid) as uid");
      return sq.query(row -> Optional.of(row.getLong(1))).one().orElse(0l);
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   * @return
   */
  public Template create(Template entity) {
    return runCreate(entity, null);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   * @param verifier
   * @return
   */
  public Template create(Template entity, Predicate<Template> verifier) {
    return runCreate(entity, verifier);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   */
  public void delete(Template entity) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlCommand sq =
          template.createSqlCommand("delete from \"document_template\" where \"uid\" = :uid");
      sq.with(UID, SqlParameterValue.of(entity.getUid()));
      int num = sq.execute();
      if (0 == num) {
        throw new IllegalArgumentException("No delete from");
      }
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param uid
   * @param filter
   * @return
   */
  public boolean exists(String uid, Optional<TemplateFilter> filter) {
    return retrieve(uid, filter).isPresent();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param uid
   * @param filter
   * @return
   */
  public boolean existsForUpdate(String uid, Optional<TemplateFilter> filter) {
    return retrieveForUpdate(uid, filter).isPresent();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public Optional<Template> find(TemplateFilter filter) {
    TemplateCursor cursor = TemplateCursor.builder().build();
    return new TemplateSlider(runList(filter, cursor), cursor.getLimit().orElse(0), this::runList,
        filter, cursor).one();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public Optional<Template> find(final String sql, final Map<String, SqlParameterValue> params) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlQuery<Template> createSqlQuery = template.createSqlQuery(sql);
      params.forEach(createSqlQuery::with);
      return createSqlQuery.query(converter()).one();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public Optional<Template> findForUpdate(TemplateFilter filter) {
    TemplateCursor cursor = TemplateCursor.builder().build();
    return new TemplateSlider(runListForUpdate(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor).one();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public Optional<Template> findForUpdate(final String sql,
      final Map<String, SqlParameterValue> params) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlQuery<Template> createSqlQuery = template.createSqlQuery(sql);
      params.forEach(createSqlQuery::with);
      return createSqlQuery.forUpdate().query(converter()).one();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public List<Template> list(TemplateFilter filter) {
    TemplateCursor cursor = TemplateCursor.builder().build();
    return new TemplateSlider(runList(filter, cursor), cursor.getLimit().orElse(0), this::runList,
        filter, cursor).all();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public List<Template> list(final String sql, final Map<String, SqlParameterValue> params) {
    return list(sql, params, null, false);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @param limit
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public List<Template> list(final String sql, final Map<String, SqlParameterValue> params,
      final int limit) {
    return list(sql, params, Integer.valueOf(limit), false);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @return
   */
  public List<Template> listForUpdate(TemplateFilter filter) {
    TemplateCursor cursor = TemplateCursor.builder().build();
    return new TemplateSlider(runListForUpdate(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor).all();
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public List<Template> listForUpdate(final String sql,
      final Map<String, SqlParameterValue> params) {
    return list(sql, params, null, true);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @param limit
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  public List<Template> listForUpdate(final String sql, final Map<String, SqlParameterValue> params,
      final int limit) {
    return list(sql, params, Integer.valueOf(limit), true);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param reference
   * @return
   */
  public Template resolve(TemplateRef reference) {
    return reference instanceof Template template ? template
        : retrieve(reference.getUid(), Optional.empty()).orElseThrow(() -> new NotFoundException(
            "Trying to resolve inexistent Template: " + reference.getUid()));
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param reference
   * @return
   */
  public Template resolveForUpdate(TemplateRef reference) {
    return reference instanceof Template template ? template
        : retrieveForUpdate(reference.getUid(), Optional.empty())
            .orElseThrow(() -> new NotFoundException(
                "Trying to resolve inexistent Template: " + reference.getUid()));
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param uid
   * @param filter
   * @return
   */
  public Optional<Template> retrieve(String uid, Optional<TemplateFilter> filter) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      TemplateFilter readyFilter = filter.map(val -> val.withUid(uid))
          .orElseGet(() -> TemplateFilter.builder().uid(uid).build());
      SqlSchematicQuery<Template> sq = filteredQuery(template, readyFilter);
      return sq.query(converter()).one();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param uid
   * @param filter
   * @return
   */
  public Optional<Template> retrieveForUpdate(String uid, Optional<TemplateFilter> filter) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      TemplateFilter readyFilter = filter.map(val -> val.withUid(uid))
          .orElseGet(() -> TemplateFilter.builder().uid(uid).build());
      SqlSchematicQuery<Template> sq = filteredQuery(template, readyFilter);
      return sq.forUpdate().query(converter()).one();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @param cursor
   * @return
   */
  public Slider<Template> slide(TemplateFilter filter, TemplateCursor cursor) {
    return new TemplateSlider(runList(filter, cursor), cursor.getLimit().orElse(0), this::runList,
        filter, cursor);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @param cursor
   * @return
   */
  public Slider<Template> slideForUpdate(TemplateFilter filter, TemplateCursor cursor) {
    return new TemplateSlider(runListForUpdate(filter, cursor), cursor.getLimit().orElse(0),
        this::runList, filter, cursor);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   * @return
   */
  public Template update(Template entity) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlCommand sq = template.createSqlCommand(
          "update \"document_template\" set  \"code\" = :code, \"tenant\" = :tenant, \"theme\" = :theme, \"channel\" = :channel, \"enabled\" = :enabled, \"version\" = \"version\" + 1 where \"uid\" = :uid and \"version\" = :version");
      sq.with(UID, SqlParameterValue.of(entity.getUid()));
      sq.with(CODE, SqlParameterValue.of(entity.getCode()));
      sq.with(TENANT, entity.getTenantUid().map(SqlParameterValue::of)
          .orElseGet(SqlParameterValue::ofNullString));
      sq.with(THEME, entity.getThemeUid().map(SqlParameterValue::of)
          .orElseGet(SqlParameterValue::ofNullString));
      sq.with(CHANNEL, SqlParameterValue.of(entity.getChannel().toString()));
      sq.with(ENABLED, SqlParameterValue.of(entity.isEnabled()));
      sq.with(VERSION, entity.getVersion().map(SqlParameterValue::of)
          .orElseGet(SqlParameterValue::ofNullInteger));
      int num = sq.execute();
      if (0 == num) {
        throw new OptimistLockException("No delete from");
      }
      return entity.withNextVersion();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sq
   * @param cursor
   */
  private void attachWithOrder(SqlSchematicQuery<Template> sq, TemplateCursor cursor) {
    PartialWhere[] offset = new PartialWhere[] {PartialWhere.empty(), PartialWhere.empty()};
    for (TemplateOrder order : cursor.getOrder()) {
      tryToOrderByCodeAsc(sq, offset, cursor, order);
      tryToOrderByCodeDesc(sq, offset, cursor, order);
    }
    Optional<String> sinceUid = cursor.getSinceUid();
    if (sinceUid.isPresent()) {
      offset[0] = PartialWhere.or(offset[0], PartialWhere.and(offset[1],
          PartialWhere.where("uid", SqlOperator.GT, SqlParameterValue.of(sinceUid.get()))));
    }
    sq.where(offset[0]);
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @return
   */
  private SqlConverter<Template> converter() {
    return row -> {
      try {
        return Optional.of(Template.builder().uidValue(UidVO.from(row.getString(UID)))
            .codeValue(CodeVO.from(row.getString(CODE)))
            .tenantValue(TenantVO.fromReference(row.getString(TENANT)))
            .themeValue(ThemeVO.fromReference(row.getString(THEME)))
            .channelValue(ChannelVO.tryFrom(row.getString(CHANNEL)))
            .enabledValue(EnabledVO.from(row.getBoolean(ENABLED)))
            .versionValue(VersionVO.from(row.getInt(VERSION))).build());
      } catch (ConstraintException ce) {
        log.error("Unable to map data for {}", row.getString(1), ce);
        return Optional.empty();
      }
    };
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param template
   * @param filter
   * @return
   */
  private <T> SqlSchematicQuery<T> filteredQuery(SqlTemplate template, TemplateFilter filter) {
    SqlSchematicQuery<T> sq = template.createSqlSchematicQuery(DOCUMENT_TEMPLATE_SNAKE);
    sq.selectFields(DOCUMENT_TEMPLATE_UID, DOCUMENT_TEMPLATE_CODE, DOCUMENT_TEMPLATE_TENANT,
        DOCUMENT_TEMPLATE_THEME, DOCUMENT_TEMPLATE_CHANNEL, DOCUMENT_TEMPLATE_ENABLED,
        DOCUMENT_TEMPLATE_VERSION);
    filter.getUid().ifPresent(uid -> sq.where(UID, SqlOperator.EQ, SqlParameterValue.of(uid)));
    if (!filter.getUids().isEmpty()) {
      sq.where(UID, SqlOperator.IN, SqlListParameterValue.strings(filter.getUids()));
    }
    filter.getSearch().ifPresent(
        search -> sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%")));
    filter.getCode()
        .ifPresent(codeParam -> sq.where(CODE, SqlOperator.EQ, SqlParameterValue.of(codeParam)));
    filter.getTenant().ifPresent(tenantParam -> sq.where(TENANT, SqlOperator.EQ,
        SqlParameterValue.of(tenantParam.getUid())));
    if (!filter.getTenants().isEmpty()) {
      sq.where(TENANT, SqlOperator.IN, SqlListParameterValue.strings(filter.getTenants()));
    }
    filter.getTheme().ifPresent(
        themeParam -> sq.where(THEME, SqlOperator.EQ, SqlParameterValue.of(themeParam.getUid())));
    if (!filter.getThemes().isEmpty()) {
      sq.where(THEME, SqlOperator.IN, SqlListParameterValue.strings(filter.getThemes()));
    }
    filter.getTenantTenantAccesible()
        .ifPresent(tenantTenantAccesibleParam -> sq.where(DOCUMENT_TEMPLATE_TENANT, SqlOperator.EQ,
            SqlParameterValue.of(tenantTenantAccesibleParam)));
    return sq;
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sql
   * @param params
   * @param limit
   * @param forUpdate
   * @return sq.where("code", SqlOperator.LIKE, SqlParameterValue.of("%" + search + "%"))
   */
  private List<Template> list(final String sql, final Map<String, SqlParameterValue> params,
      final Integer limit, final boolean forUpdate) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlQuery<Template> createSqlQuery = template.createSqlQuery(sql);
      params.forEach(createSqlQuery::with);
      if (forUpdate) {
        createSqlQuery = createSqlQuery.forUpdate();
      }
      SqlResult<Template> query = createSqlQuery.query(converter());
      return null == limit ? query.all() : query.limit(limit);
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param entity
   * @param verifier
   * @return
   */
  private Template runCreate(Template entity, Predicate<Template> verifier) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlCommand sq = template.createSqlCommand(
          "insert into \"document_template\" ( \"uid\", \"code\", \"tenant\", \"theme\", \"channel\", \"enabled\", \"version\") values ( :uid, :code, :tenant, :theme, :channel, :enabled, :version)");
      sq.with(UID, SqlParameterValue.of(entity.getUid()));
      sq.with(CODE, SqlParameterValue.of(entity.getCode()));
      sq.with(TENANT, entity.getTenantUid().map(SqlParameterValue::of)
          .orElseGet(SqlParameterValue::ofNullString));
      sq.with(THEME, entity.getThemeUid().map(SqlParameterValue::of)
          .orElseGet(SqlParameterValue::ofNullString));
      sq.with(CHANNEL, SqlParameterValue.of(entity.getChannel().toString()));
      sq.with(ENABLED, SqlParameterValue.of(entity.isEnabled()));
      sq.with(VERSION, entity.getVersion().map(SqlParameterValue::of)
          .orElseGet(SqlParameterValue::ofNullInteger));
      int num = sq.execute();
      if (0 == num) {
        throw new IllegalArgumentException("No insert into");
      }
      return verifier == null ? entity : verified(verifier.test(entity), entity, template);
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @param cursor
   * @return
   */
  private Iterator<Template> runList(TemplateFilter filter, TemplateCursor cursor) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlSchematicQuery<Template> sq = filteredQuery(template, filter);
      if (null != cursor.getOrder()) {
        attachWithOrder(sq, cursor);
      } else {
        cursor.getSinceUid()
            .ifPresent(since -> sq.where(UID, SqlOperator.GT, SqlParameterValue.of(since)));
      }
      sq.orderAsc("uid");
      return sq.query(converter()).limit(cursor.getLimit()).iterator();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param filter
   * @param cursor
   * @return
   */
  private Iterator<Template> runListForUpdate(TemplateFilter filter, TemplateCursor cursor) {
    try (SqlTemplate template = new SqlTemplate(datasource, tracer)) {
      SqlSchematicQuery<Template> sq = filteredQuery(template, filter);
      if (null != cursor.getOrder()) {
        attachWithOrder(sq, cursor);
      } else {
        cursor.getSinceUid()
            .ifPresent(since -> sq.where(UID, SqlOperator.GT, SqlParameterValue.of(since)));
      }
      sq.orderAsc("uid");
      return sq.forUpdate().query(converter()).limit(cursor.getLimit()).iterator();
    }
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sq
   * @param offset
   * @param cursor
   * @param order
   * @return
   */
  private PartialWhere[] tryToOrderByCodeAsc(SqlSchematicQuery<Template> sq, PartialWhere[] offset,
      TemplateCursor cursor, TemplateOrder order) {
    if (order == TemplateOrder.CODE_ASC) {
      sq.addOrderAsc("code");
      Optional<String> sinceCode = cursor.getSinceCode();
      if (sinceCode.isPresent()) {
        String sinceCodeValue = sinceCode.get();
        offset[0] = PartialWhere.or(offset[0], PartialWhere.and(offset[1],
            PartialWhere.where("code", SqlOperator.GT, SqlParameterValue.of(sinceCodeValue))));
        offset[1] = PartialWhere.and(offset[1],
            PartialWhere.where("code", SqlOperator.EQ, SqlParameterValue.of(sinceCodeValue)));
      }
    }
    return offset;
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param sq
   * @param offset
   * @param cursor
   * @param order
   * @return
   */
  private PartialWhere[] tryToOrderByCodeDesc(SqlSchematicQuery<Template> sq, PartialWhere[] offset,
      TemplateCursor cursor, TemplateOrder order) {
    if (order == TemplateOrder.CODE_DESC) {
      sq.addOrderDesc("code");
      Optional<String> sinceCode = cursor.getSinceCode();
      if (sinceCode.isPresent()) {
        String sinceCodeValue = sinceCode.get();
        offset[0] = PartialWhere.or(offset[0], PartialWhere.and(offset[1],
            PartialWhere.where("code", SqlOperator.GT, SqlParameterValue.of(sinceCodeValue))));
        offset[1] = PartialWhere.and(offset[1],
            PartialWhere.where("code", SqlOperator.EQ, SqlParameterValue.of(sinceCodeValue)));
      }
    }
    return offset;
  }

  /**
   * @autogenerated RepositoryJdbcGenerator
   * @param exists
   * @param entity
   * @param template
   * @return
   */
  private Template verified(boolean exists, Template entity, SqlTemplate template) {
    if (exists) {
      return entity;
    } else {
      template.createSqlCommand("delete from \"document_template\" where \"uid\" = :uid")
          .with("uid", SqlParameterValue.of(entity.getUid())).execute();
      throw new NotFoundException("");
    }
  }
}
