package net.civeira.phylax.features.document.templateasset.application.usecase.disable;

import java.time.Duration;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.batch.BatchIdentificator;
import net.civeira.phylax.common.batch.BatchProgress;
import net.civeira.phylax.common.batch.BatchService;
import net.civeira.phylax.common.batch.ExecutorByDeferSteps;
import net.civeira.phylax.common.batch.ExecutorPlan;
import net.civeira.phylax.common.exception.NotAllowedException;
import net.civeira.phylax.common.exception.NotFoundException;
import net.civeira.phylax.common.security.OperationContext;
import net.civeira.phylax.common.security.Permission;
import net.civeira.phylax.common.telemetry.Observed;
import net.civeira.phylax.common.telemetry.Trace;
import net.civeira.phylax.features.document.templateasset.application.visibility.TemplateAssetVisibilityFilter;
import net.civeira.phylax.features.document.templateasset.application.visibility.TemplateAssetsVisibility;
import net.civeira.phylax.features.document.templateasset.domain.TemplateAsset;
import net.civeira.phylax.features.document.templateasset.domain.TemplateAssetRef;
import net.civeira.phylax.features.document.templateasset.domain.gateway.TemplateAssetAuditGateway;
import net.civeira.phylax.features.document.templateasset.domain.gateway.TemplateAssetCacheGateway;
import net.civeira.phylax.features.document.templateasset.domain.gateway.TemplateAssetWriteRepositoryGateway;

@ApplicationScoped
@RequiredArgsConstructor
public class TemplateAssetDisableUsecase {

  /**
   * Service to register audit events
   *
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final TemplateAssetAuditGateway audit;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final BatchService batch;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final TemplateAssetCacheGateway cache;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final Event<TemplateAssetDisableAuthorizationDecision> execAllowEmitter;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final Event<TemplateAssetDisableCheck> execProposalEmitter;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final TemplateAssetWriteRepositoryGateway gateway;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final TemplateAssetsVisibility visibility;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param reference
   * @return
   */
  @Observed("disable an entity of template asset")
  public Permission allow(final OperationContext context, final TemplateAssetRef reference) {
    Trace.setAttribute("ref", reference.getUid());
    Permission response = checkPermission(context, reference);
    Trace.setAttribute("allowed", response.isAllowed());
    return response;
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @return
   */
  @Observed("disable an entity of template asset")
  public Permission allow(final OperationContext context) {
    Permission response = checkPermission(context);
    Trace.setAttribute("allowed", response.isAllowed());
    return response;
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param filter
   * @return The slide with some values
   */
  @Observed("disable a set of entity of template asset")
  public BatchIdentificator batchDisable(final OperationContext context,
      final TemplateAssetDisableFilter filter) {
    Permission detail = checkPermission(context);
    if (!detail.isAllowed()) {
      Trace.addEvent(
          "The policies for template asset dont allow to disable: " + detail.getDescription());
      throw new NotAllowedException(detail.getDescription());
    }
    TemplateAssetVisibilityFilter filterWithVisibility = TemplateAssetVisibilityFilter.builder()
        .uid(filter.getUid().orElse(null)).uids(filter.getUids().stream().toList())
        .search(filter.getSearch().orElse(null)).code(filter.getCode().orElse(null))
        .template(filter.getTemplate().orElse(null)).templates(filter.getTemplates())
        .tenant(filter.getTenant().orElse(null)).tenants(filter.getTenants())
        .tenantTenantAccesible(filter.getTenantTenantAccesible().orElse(null)).build();
    TemplateAssetDisableAllInBatchCommand command =
        new TemplateAssetDisableAllInBatchCommand(context, filterWithVisibility);
    return batch.start(context.getActor().getName().orElse("-"), Duration.ofHours(6), ExecutorPlan
        .<TemplateAssetDisableAllInBatchCommand>builder().params(command)
        .name("disable-template-asset")
        .executor(
            ExecutorByDeferSteps.<TemplateAsset, TemplateAsset, TemplateAssetDisableAllInBatchCommand, TemplateAssetDisablesInBatchExecutor.TemplateAssetPaginableBatch>builder()
                .initializer(TemplateAssetDisablesInBatchExecutor.class)
                .counter(TemplateAssetDisablesInBatchExecutor.class)
                .descriptor(TemplateAssetDisablesInBatchExecutor.class)
                .reader(TemplateAssetDisablesInBatchExecutor.class)
                .processor(TemplateAssetDisablesInBatchExecutor.class)
                .writer(TemplateAssetDisablesInBatchExecutor.class)
                .finalizer(TemplateAssetDisablesInBatchExecutor.class).build())
        .build());
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param query a filter to retrieve only matching values
   * @return The slide with some values
   */
  public BatchProgress checkProgress(final OperationContext context,
      final TemplateAssetDisableStatus query) {
    return context.getActor().getName()
        .flatMap(name -> batch.retrieve(query.getTaskId(), context.getSource().getLocale(), name))
        .orElseThrow(() -> new NotFoundException());
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param reference
   * @return The slide with some values
   */
  @Observed("disable an entity of template asset")
  public TemplateAssetDisableProjection disable(final OperationContext context,
      final TemplateAssetRef reference) {
    Trace.setAttribute("ref", reference.getUid());
    Permission detail = checkPermission(context, reference);
    if (!detail.isAllowed()) {
      Trace.addEvent(
          "The policies for template asset dont allow to disable: " + detail.getDescription());
      throw new NotAllowedException(detail.getDescription());
    }
    TemplateAsset original = visibility.retrieveVisibleForUpdate(context, reference.getUid())
        .orElseThrow(() -> new NotFoundException(""));
    TemplateAsset saved = doDisable(context, original);
    cacheUpdate(saved);
    // Register audit operation
    audit.updated("disable", saved, original, context);
    return TemplateAssetDisableProjection.from(visibility.copyWithHidden(context, saved));
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param saved
   */
  void cacheUpdate(final TemplateAsset saved) {
    cache.update(saved);
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param reference
   * @return
   */
  Permission checkPermission(final OperationContext context, final TemplateAssetRef reference) {
    TemplateAssetDisableAuthorizationDecision proposal =
        new TemplateAssetDisableAuthorizationDecision(context, reference,
            Permission.allow("Allow to disable by default"));
    execAllowEmitter.fire(proposal);
    return proposal.getPermission();
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @return
   */
  Permission checkPermission(final OperationContext context) {
    TemplateAssetDisableAuthorizationDecision proposal =
        new TemplateAssetDisableAuthorizationDecision(context,
            Permission.allow("Allow to disable by default"));
    execAllowEmitter.fire(proposal);
    return proposal.getPermission();
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param original
   * @return
   */
  TemplateAsset doDisable(final OperationContext context, final TemplateAsset original) {
    TemplateAssetDisableCheck proposal = new TemplateAssetDisableCheck(context, original);
    execProposalEmitter.fire(proposal);
    TemplateAsset result = original.disable();
    TemplateAsset saved = gateway.update(original, result);
    return saved;
  }
}
