/* @autogenerated */
package net.civeira.phylax.features.oauth.tokensecurity.application;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Base64;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.stream.Collectors;

import org.eclipse.microprofile.config.ConfigProvider;

import com.auth0.jwt.JWT;
import com.auth0.jwt.JWTCreator.Builder;
import com.fasterxml.jackson.databind.ObjectMapper;

import jakarta.enterprise.context.RequestScoped;
import lombok.Data;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import net.civeira.phylax.common.exception.NotAllowedException;
import net.civeira.phylax.common.infrastructure.CurrentRequest;
import net.civeira.phylax.features.oauth.authentication.domain.AuthRequest;
import net.civeira.phylax.features.oauth.authentication.domain.AuthenticationData;
import net.civeira.phylax.features.oauth.client.domain.ClientDetails;
import net.civeira.phylax.features.oauth.tokensecurity.domain.AutorizationToken;
import net.civeira.phylax.features.oauth.tokensecurity.domain.IdToken;
import net.civeira.phylax.features.oauth.tokensecurity.domain.MfaToken;
import net.civeira.phylax.features.oauth.tokensecurity.domain.gateway.TokenSigner;

/**
 * JWT token builder for OAuth and OIDC flows.
 *
 * Responsibilities: - Build access, refresh, ID, and MFA tokens. - Verify and parse token payloads
 * for authentication flows.
 *
 * Design notes: - Delegates signing to TokenSigner. - Uses ObjectMapper to map claim payloads.
 */
@Slf4j
@RequestScoped
@RequiredArgsConstructor
public class JwtTokenBuilder {
  /**
   * Claim name used to store challenge payloads.
   */
  private static final String CHALLENGE = "challenge";
  /**
   * Token type value for bearer tokens.
   */
  private static final String BEARER = "Bearer";
  /**
   * Configuration key for access token expiration.
   */
  private static final String EXPIRATION_CONF = "oauth.jwt.expiration.access-token";
  /**
   * Claim name for the subject/username.
   */
  private static final String CLAIM_USER_NAME = "sub";
  /**
   * Claim name for grant type.
   */
  private static final String CLAIM_GRANT_TYPE = "grant_type";
  /**
   * Claim name for client id.
   */
  private static final String CLAIM_CLIENT_ID = "azp";
  /**
   * Claim name for audience.
   */
  private static final String CLAIM_AUDIENCE_ID = "aud";
  /**
   * Claim name for authorities/roles.
   */
  private static final String CLAIM_ROLES = "roles";
  /**
   * Claim name for authorities/roles.
   */
  private static final String CLAIM_GROUPS = "groups";
  /**
   * Claim name for scopes.
   */
  private static final String CLAIM_SCOPE = "scope";
  /**
   * Scope value used for refresh tokens.
   */
  private static final String REFRESH_SCOPE = "refresh";
  /**
   * Scope value used for MFA tokens.
   */
  private static final String MFA_SCOPE = "mfa";

  @Data
  @lombok.Builder
  /**
   * Information extracted from a refresh token.
   *
   * Carries username, audiences, and client id. Used to rehydrate authentication state.
   */
  public static class RefreshTokenInfo {
    /**
     * Username associated with the refresh token.
     */
    private final String username;
    /**
     * Audiences associated with the refresh token.
     */
    private final List<String> audiences;
    /**
     * Client id associated with the refresh token.
     */
    private final String client;
  }

  /**
   * Object mapper used for claim conversions.
   */
  private final ObjectMapper mapper;
  /**
   * Token signer used to sign and verify JWTs.
   */
  private final TokenSigner tokenSigner;
  /**
   * Request context used to build issuer URLs.
   */
  private final CurrentRequest current;

  /**
   * Builds an ID token response for OIDC flows.
   *
   * Creates access and ID tokens and sets session state. Uses configured expiration values for
   * token lifetimes.
   *
   * @param tenant tenant identifier
   * @param state OAuth state value
   * @param nonce OIDC nonce value
   * @param details client details
   * @param grantType grant type used
   * @param validationData authentication data
   * @return ID token response payload
   */
  public IdToken buildIdToken(String tenant, String state, String nonce, ClientDetails details,
      String grantType, AuthenticationData validationData) {
    Duration expiration = propiedadEntera(EXPIRATION_CONF);
    Instant authExpires = Instant.now().plus(expiration);
    Instant refreshExpires = Instant.now().plus(propiedadEntera(EXPIRATION_CONF));

    String sessionState = UUID.randomUUID().toString();

    String accessToken = tokenSigner.sign(tenant,
        accessToken(tenant, details, grantType, validationData), authExpires);

    Builder identityToken = identityToken(tenant, accessToken, details, grantType, validationData);
    withChallenge(identityToken, state, sessionState, nonce);

    String idtToken = tokenSigner.sign(tenant, identityToken, refreshExpires);

    IdToken idToken = new IdToken();
    idToken.setIss(issuer(tenant));
    idToken.setTokenType(BEARER);
    idToken.setExpiresIn(expiration.getSeconds());
    idToken.setAccessToken(accessToken);
    idToken.setIdToken(idtToken);
    idToken.setSessionState(sessionState);
    return idToken;
  }

  /**
   * Builds a challenge token for pre-session flows.
   *
   * Serializes the provided bean as a challenge claim. Uses keypass signing and the provided
   * expiration.
   *
   * @param tenant tenant identifier
   * @param bean payload to include
   * @param expiration token lifetime
   * @return signed challenge token
   */
  public <T> String buildChallengerToken(String tenant, T bean, Duration expiration) {
    String jti = UUID.randomUUID().toString();

    @SuppressWarnings("unchecked")
    Map<String, Object> map = mapper.convertValue(bean, Map.class);

    Builder accessTokenInfo =
        JWT.create().withIssuer(issuer(tenant)).withIssuedAt(new Date()).withJWTId(jti)
            .withClaim(CHALLENGE, map).withArrayClaim(CLAIM_SCOPE, new String[] {CHALLENGE});

    return tokenSigner.signKeypass(tenant, accessTokenInfo, Instant.now().plus(expiration));
  }

  /**
   * Verifies and parses a challenge token.
   *
   * Validates the token scope and converts the challenge payload. Returns empty when validation
   * fails.
   *
   * @param type target payload type
   * @param token challenge token
   * @param tenant tenant identifier
   * @return optional parsed payload
   */
  public <T> Optional<T> verifyChalleger(Class<T> type, String token, String tenant) {
    try {
      Map<String, Object> payload = tokenSigner.verifyTokenPayload(tenant, token);
      if (payload.isEmpty()) {
        return Optional.empty();
      }
      List<String> scopes = claimAsList(payload.get(CLAIM_SCOPE));
      if (scopes.size() == 1 && scopes.contains(CHALLENGE)) {
        @SuppressWarnings("unchecked")
        Map<String, Object> asMap = (Map<String, Object>) payload.get(CHALLENGE);
        return Optional.of(mapper.convertValue(asMap, type));
      }
      return Optional.empty();
    } catch (NotAllowedException nae) {
      log.warn("Wrong challenger", nae);
      return Optional.empty();
    }
  }

  /**
   * Builds an MFA token response.
   *
   * Creates a short-lived token with MFA scope. Used to continue MFA verification flows.
   *
   * @param username username
   * @param tenant tenant identifier
   * @return MFA token response
   */
  public MfaToken buildMfaToken(String username, String tenant) {
    String jti = UUID.randomUUID().toString();

    Duration expiration = propiedadEntera("oauth.jwt.expiration.mfa-token");
    Instant authExpires = Instant.now().plus(expiration);
    MfaToken authorization = new MfaToken();
    authorization.setExpiresIn(expiration.getSeconds());
    Builder accessTokenInfo = JWT.create().withIssuer(issuer(tenant)).withIssuedAt(new Date())
        .withJWTId(jti).withClaim(CLAIM_USER_NAME, username)
        .withArrayClaim(CLAIM_SCOPE, new String[] {MFA_SCOPE});
    authorization.setError("mfa_required");
    authorization.setToken(tokenSigner.sign(tenant, accessTokenInfo, authExpires));
    return authorization;
  }

  /**
   * Builds an authorization token response without a request context.
   *
   * When no request is provided, audience information is omitted. Delegates to the overload that
   * accepts an AuthRequest.
   *
   * @param tenant tenant identifier
   * @param details client details
   * @param grantType grant type used
   * @param validationData authentication data
   * @return authorization token response
   */
  @Deprecated
  public AutorizationToken buildToken(String tenant, ClientDetails details, String grantType,
      AuthenticationData validationData) {
    return buildToken(tenant, details, grantType, validationData, null);
  }

  /**
   * Builds an authorization token response.
   *
   * Creates access and refresh tokens and optional ID token. Applies scope filtering when a request
   * is provided.
   *
   * @param tenant tenant identifier
   * @param details client details
   * @param grantType grant type used
   * @param validationData authentication data
   * @param request auth request context (optional)
   * @return authorization token response
   */
  public AutorizationToken buildToken(String tenant, ClientDetails details, String grantType,
      AuthenticationData validationData, AuthRequest request) {
    if (request != null && validationData.getScopes().isEmpty()) {
      List<String> requested = request.getScope().map(s -> Arrays.stream(s.split("\\s+"))
          .filter(sc -> !sc.isBlank()).collect(Collectors.toList())).orElse(List.of());
      boolean wildcard = details.getAllowedScopes().contains("*");
      List<String> granted = wildcard ? requested
          : requested.stream().filter(details.getAllowedScopes()::contains)
              .collect(Collectors.toList());
      validationData.setScopes(granted);
    }
    Builder accessToken = accessToken(tenant, details, grantType, validationData);
    Builder refreshToken = refreshToken(tenant, details, validationData);

    Duration expiration = propiedadEntera(EXPIRATION_CONF);
    Instant authExpires = Instant.now().plus(expiration);
    Instant refreshExpires = Instant.now().plus(propiedadEntera(EXPIRATION_CONF));

    AutorizationToken authorization = new AutorizationToken();
    authorization.setGrantType(grantType);
    authorization.setTokenType(BEARER);
    authorization.setUsername(validationData.getUsername());
    authorization.setExpiresIn(expiration.getSeconds());

    authorization.setAccessToken(tokenSigner.sign(tenant, accessToken, authExpires));
    authorization.setRefreshToken(tokenSigner.sign(tenant, refreshToken, refreshExpires));

    if (null != request) {
      String sessionState = UUID.randomUUID().toString();
      Builder identityToken =
          identityToken(tenant, authorization.getAccessToken(), details, grantType, validationData);
      withChallenge(identityToken, request.getState().orElse(""), sessionState,
          request.getNonce().orElse(""));
      authorization.setIdToken(tokenSigner.sign(tenant, identityToken, refreshExpires));
    }

    return authorization;
  }

  /**
   * Verifies an MFA token and returns the username.
   *
   * Validates the token and ensures the MFA scope is present. Returns empty when verification
   * fails.
   *
   * @param token MFA token
   * @param tenant tenant identifier
   * @return optional username
   */
  public Optional<String> verifyMfa(String token, String tenant) {
    return verifyToken(token, MFA_SCOPE, tenant);
  }

  /**
   * Verifies a refresh token and returns the username.
   *
   * Validates the token and ensures the refresh scope is present. Returns empty when verification
   * fails.
   *
   * @param token refresh token
   * @param tenant tenant identifier
   * @return optional username
   */
  public Optional<String> verifyRefresh(String token, String tenant) {
    return verifyToken(token, REFRESH_SCOPE, tenant);
  }

  /**
   * Verifies a refresh token and returns detailed info.
   *
   * Extracts username, audiences, and client id from claims. Returns empty when verification fails.
   *
   * @param token refresh token
   * @param tenant tenant identifier
   * @return optional refresh token info
   */
  public Optional<RefreshTokenInfo> verifyRefreshInfo(String token, String tenant) {
    String scope = REFRESH_SCOPE;
    Optional<RefreshTokenInfo> response = Optional.empty();
    try {
      Map<String, Object> payload = tokenSigner.verifyTokenPayload(tenant, token);
      if (payload.isEmpty()) {
        return Optional.empty();
      }
      List<String> scopes = claimAsList(payload.get(CLAIM_SCOPE));
      if (scopes.size() == 1 && scopes.contains(scope)) {
        List<String> aud = claimAsList(payload.get(CLAIM_AUDIENCE_ID));
        response = Optional
            .of(RefreshTokenInfo.builder().username(claimAsString(payload.get(CLAIM_USER_NAME)))
                .client(claimAsString(payload.get(CLAIM_CLIENT_ID)))
                .audiences(null == aud ? List.of() : aud).build());
      }
      return response;
    } catch (NotAllowedException nae) {
      return Optional.empty();
    }
  }



  /**
   * Verifies a token for a specific scope and returns username.
   *
   * Ensures the token contains only the expected scope. Returns empty when verification fails.
   *
   * @param token token to verify
   * @param scope expected scope value
   * @param tenant tenant identifier
   * @return optional username
   */
  public Optional<String> verifyToken(String token, String scope, String tenant) {
    Optional<String> response = Optional.empty();
    try {
      Map<String, Object> payload = tokenSigner.verifyTokenPayload(tenant, token);
      if (payload.isEmpty()) {
        return Optional.empty();
      }
      List<String> scopes = claimAsList(payload.get(CLAIM_SCOPE));
      if (scopes.size() == 1 && scopes.contains(scope)) {
        response = Optional.ofNullable(claimAsString(payload.get(CLAIM_USER_NAME)));
      }
      return response;
    } catch (NotAllowedException nae) {
      log.warn("Wrong {0} token", scope);
      return Optional.empty();
    }
  }

  /**
   * Builds the JWT builder for an ID token.
   *
   * Includes auth level, audience, and hash claims. Adds auth_time claim when present.
   *
   * @param tenant tenant identifier
   * @param accessToken access token value
   * @param client client details
   * @param grantType grant type used
   * @param validationData authentication data
   * @return JWT builder for ID token
   */
  private Builder identityToken(String tenant, String accessToken, ClientDetails client,
      String grantType, AuthenticationData validationData) {
    String jti = UUID.randomUUID().toString();
    String authLevel = null == validationData.getMode() ? "0" : validationData.getMode().getAcr();
    Instant authTime = validationData.getTime();

    Builder builder = JWT.create().withIssuer(issuer(tenant)).withJWTId(jti)
        .withClaim("acr", authLevel).withIssuedAt(new Date())
        .withSubject(validationData.getUsername()).withClaim("at_hash", generateHash(accessToken));
    if (null != authTime) {
      builder = builder.withClaim("auth_time", authTime.getEpochSecond());
    }
    return builder.withClaim("typ", "ID")
        .withClaim(CLAIM_AUDIENCE_ID, validationData.getAudiences())
        .withClaim(CLAIM_GRANT_TYPE, grantType)
        .withClaim(CLAIM_USER_NAME, validationData.getUsername())
        .withClaim(CLAIM_CLIENT_ID, client.getClientId())
        .withClaim(CLAIM_ROLES, validationData.getRoles())
        .withClaim(CLAIM_GROUPS, validationData.getGroups());
  }

  /**
   * Adds challenge-related claims to a JWT builder.
   *
   * Includes state hash, session state, and nonce when provided. Returns the updated builder for
   * chaining.
   *
   * @param builder JWT builder
   * @param state OAuth state value
   * @param session session state value
   * @param nonce OIDC nonce value
   * @return updated JWT builder
   */
  private Builder withChallenge(Builder builder, String state, String session, String nonce) {
    if (null != state) {
      builder = builder.withClaim("s_hash", generateHash(state));
    }
    if (null != session) {
      builder = builder.withClaim("session_state", session);
    }
    if (null != nonce) {
      builder = builder.withClaim("nonce", nonce);
    }
    return builder;
  }

  /**
   * Builds the JWT builder for an access token.
   *
   * Includes audience, grant type, roles, and scopes. Adds tenant claim when available.
   *
   * @param tenant tenant identifier
   * @param client client details
   * @param grantType grant type used
   * @param validationData authentication data
   * @return JWT builder for access token
   */
  private Builder accessToken(String tenant, ClientDetails client, String grantType,
      AuthenticationData validationData) {
    String jti = UUID.randomUUID().toString();

    Builder accessTokenInfo = JWT.create();
    List<String> scopes = validationData.getScopes().isEmpty() ? new ArrayList<>()
        : new ArrayList<>(validationData.getScopes());

    accessTokenInfo = accessTokenInfo.withIssuer(issuer(tenant)).withJWTId(jti)
        .withIssuedAt(new Date()).withSubject(validationData.getUsername())
        .withClaim("aud", validationData.getAudiences()).withClaim(CLAIM_GRANT_TYPE, grantType)
        .withClaim("typ", BEARER).withClaim(CLAIM_USER_NAME, validationData.getUsername());

    if (null != validationData.getTenant()) {
      accessTokenInfo = accessTokenInfo.withClaim("tid", validationData.getTenant());
    }

    accessTokenInfo = accessTokenInfo.withClaim(CLAIM_AUDIENCE_ID, validationData.getAudiences())
        .withClaim("aud", validationData.getAudiences())
        .withClaim(CLAIM_ROLES, validationData.getRoles())
        .withArrayClaim(CLAIM_SCOPE, scopes.toArray(new String[0]));
    return accessTokenInfo;
  }

  /**
   * Builds the JWT builder for a refresh token.
   *
   * Includes audience, username, and client id claims. Adds the refresh scope to identify the
   * token.
   *
   * @param tenant tenant identifier
   * @param client client details
   * @param validationData authentication data
   * @return JWT builder for refresh token
   */
  private Builder refreshToken(String tenant, ClientDetails client,
      AuthenticationData validationData) {
    String jti = UUID.randomUUID().toString();
    return JWT.create().withIssuer(issuer(tenant)).withJWTId(jti).withIssuedAt(new Date())
        .withClaim("aud", validationData.getAudiences())
        .withClaim(CLAIM_USER_NAME, validationData.getUsername())
        .withClaim(CLAIM_CLIENT_ID, client.getClientId())
        .withArrayClaim(CLAIM_SCOPE, new String[] {REFRESH_SCOPE});
  }

  /**
   * Builds the issuer URL for the tenant.
   *
   * Uses the public host from the current request context. Keeps issuer construction consistent
   * across tokens.
   *
   * @param tenant tenant identifier
   * @return issuer URL
   */
  private String issuer(String tenant) {
    return current.getPublicHost() + "/oauth/openid/" + tenant;
  }

  /**
   * Converts a claim value to a string.
   *
   * Uses ObjectMapper for conversion when necessary. Returns null when the input is null.
   *
   * @param value claim value
   * @return string value or null
   */
  private String claimAsString(Object value) {
    return null == value ? null : mapper.convertValue(value, String.class);
  }

  /**
   * Converts a claim value into a list of strings.
   *
   * Handles lists, arrays, and single values. Returns an empty list when the input is null.
   *
   * @param value claim value
   * @return list of strings
   */
  @SuppressWarnings("unchecked")
  private List<String> claimAsList(Object value) {
    if (null == value) {
      return List.of();
    }
    if (value instanceof List) {
      return (List<String>) value;
    }
    if (value instanceof String[]) {
      return Arrays.asList((String[]) value);
    }
    return List.of(mapper.convertValue(value, String.class));
  }

  /**
   * Generates a base64url hash for token challenge claims.
   *
   * Uses SHA-256 and returns the first half of the hash. Throws when the algorithm is not
   * available.
   *
   * @param value value to hash
   * @return base64url hash string
   */
  private static String generateHash(String value) {
    try {
      // Obtener instancia de SHA-256
      MessageDigest digest = MessageDigest.getInstance("SHA-256");

      // Aplicar SHA-256 al valor dado
      byte[] hashedValue = digest.digest(value.getBytes());

      // Tomar la primera mitad de los bytes resultantes
      byte[] halfHashedValue = new byte[hashedValue.length / 2];
      System.arraycopy(hashedValue, 0, halfHashedValue, 0, halfHashedValue.length);

      // Codificar la mitad del hash en base64url sin relleno
      return Base64.getUrlEncoder().withoutPadding().encodeToString(halfHashedValue);
    } catch (NoSuchAlgorithmException e) {
      throw new NotAllowedException(
          "Imposible generar el token, por un error [" + e.getClass() + "]: " + e.getMessage());
    }
  }

  /**
   * Reads a Duration value from configuration.
   *
   * Uses the provided configuration key. Throws when the configuration value is missing.
   *
   * @param clave configuration key
   * @return duration value
   */
  private Duration propiedadEntera(String clave) {
    return ConfigProvider.getConfig().getValue(clave, Duration.class);
  }
}
