/* @autogenerated */
package net.civeira.phylax.features.oauth.tokensecurity.application;

import java.time.Duration;
import java.time.Instant;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.stream.Collectors;

import com.auth0.jwt.JWT;
import com.auth0.jwt.JWTCreator.Builder;
import com.fasterxml.jackson.databind.ObjectMapper;

import jakarta.enterprise.context.RequestScoped;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.features.oauth.authentication.domain.AuthRequest;
import net.civeira.phylax.features.oauth.authentication.domain.AuthenticationData;
import net.civeira.phylax.features.oauth.client.domain.ClientDetails;
import net.civeira.phylax.features.oauth.tokensecurity.domain.AutorizationToken;
import net.civeira.phylax.features.oauth.tokensecurity.domain.IdToken;
import net.civeira.phylax.features.oauth.tokensecurity.domain.MfaToken;
import net.civeira.phylax.features.oauth.tokensecurity.domain.gateway.TokenSigner;

/**
 * Thin facade for JWT token issuance and verification.
 *
 * Delegates claim construction to {@link ClaimsMapper} and verification logic to
 * {@link TokenVerifier}. Orchestrates signing via {@link TokenSigner}.
 */
@RequestScoped
@RequiredArgsConstructor
public class JwtTokenBuilder {

  private static final String BEARER = "Bearer";
  private static final String CLAIM_SCOPE = "scope";
  private static final String CHALLENGE = "challenge";
  private static final String MFA_SCOPE = "mfa";

  private final ClaimsMapper claimsMapper;
  private final TokenVerifier tokenVerifier;
  private final TokenSigner tokenSigner;
  private final ObjectMapper objectMapper;

  public IdToken buildIdToken(String tenant, String state, String nonce, ClientDetails details,
      String grantType, AuthenticationData validationData) {
    return buildIdToken(tenant, state, nonce, details, grantType, validationData, null);
  }

  public IdToken buildIdToken(String tenant, String state, String nonce, ClientDetails details,
      String grantType, AuthenticationData validationData, String authorizationCode) {
    Duration expiration = claimsMapper.accessTokenTtl();
    Instant authExpires = Instant.now().plus(expiration);
    Instant refreshExpires = Instant.now().plus(claimsMapper.refreshTtl(tenant));

    String sessionState = UUID.randomUUID().toString();
    String accessToken = tokenSigner.sign(tenant,
        claimsMapper.accessToken(tenant, details, grantType, validationData), authExpires);

    Builder identityBuilder =
        claimsMapper.identityToken(tenant, accessToken, details, grantType, validationData);
    claimsMapper.withChallengeClaims(identityBuilder, state, sessionState, nonce);
    claimsMapper.withCodeHash(identityBuilder, authorizationCode);

    IdToken idToken = new IdToken();
    idToken.setIss(claimsMapper.issuer(tenant));
    idToken.setTokenType(BEARER);
    idToken.setExpiresIn(expiration.getSeconds());
    idToken.setAccessToken(accessToken);
    idToken.setIdToken(tokenSigner.sign(tenant, identityBuilder, refreshExpires));
    idToken.setSessionState(sessionState);
    return idToken;
  }

  public <T> String buildChallengerToken(String tenant, T bean, Duration expiration) {
    String jti = UUID.randomUUID().toString();
    @SuppressWarnings("unchecked")
    Map<String, Object> map = objectMapper.convertValue(bean, Map.class);

    Builder builder =
        JWT.create().withIssuer(claimsMapper.issuer(tenant)).withIssuedAt(new Date()).withJWTId(jti)
            .withClaim(CHALLENGE, map).withArrayClaim(CLAIM_SCOPE, new String[] {CHALLENGE});

    return tokenSigner.signKeypass(tenant, builder, Instant.now().plus(expiration));
  }

  public <T> Optional<T> verifyChalleger(Class<T> type, String token, String tenant) {
    return tokenVerifier.verifyChallenger(type, token, tenant);
  }

  public MfaToken buildMfaToken(String username, String tenant) {
    String jti = UUID.randomUUID().toString();
    Duration expiration = claimsMapper.tokenTtl("oauth.jwt.expiration.mfa-token");
    Instant authExpires = Instant.now().plus(expiration);

    Builder builder =
        JWT.create().withIssuer(claimsMapper.issuer(tenant)).withIssuedAt(new Date()).withJWTId(jti)
            .withClaim("sub", username).withArrayClaim(CLAIM_SCOPE, new String[] {MFA_SCOPE});

    MfaToken authorization = new MfaToken();
    authorization.setExpiresIn(expiration.getSeconds());
    authorization.setError("mfa_required");
    authorization.setToken(tokenSigner.sign(tenant, builder, authExpires));
    return authorization;
  }

  @Deprecated
  public AutorizationToken buildToken(String tenant, ClientDetails details, String grantType,
      AuthenticationData validationData) {
    return buildToken(tenant, details, grantType, validationData, null);
  }

  public AutorizationToken buildToken(String tenant, ClientDetails details, String grantType,
      AuthenticationData validationData, AuthRequest request) {
    if (request != null && validationData.getScopes().isEmpty()) {
      List<String> requested = request.getScope().map(s -> Arrays.stream(s.split("\\s+"))
          .filter(sc -> !sc.isBlank()).collect(Collectors.toList())).orElse(List.of());
      boolean wildcard = details.getAllowedScopes().contains("*");
      List<String> granted = wildcard ? requested
          : requested.stream().filter(details.getAllowedScopes()::contains)
              .collect(Collectors.toList());
      validationData.setScopes(granted);
    }

    Duration expiration = claimsMapper.accessTokenTtl();
    Instant authExpires = Instant.now().plus(expiration);
    Instant refreshExpires = Instant.now().plus(claimsMapper.refreshTtl(tenant));

    AutorizationToken authorization = new AutorizationToken();
    authorization.setGrantType(grantType);
    authorization.setTokenType(BEARER);
    authorization.setUsername(validationData.getUsername());
    authorization.setExpiresIn(expiration.getSeconds());
    authorization.setAccessToken(tokenSigner.sign(tenant,
        claimsMapper.accessToken(tenant, details, grantType, validationData), authExpires));
    authorization.setRefreshToken(tokenSigner.sign(tenant,
        claimsMapper.refreshToken(tenant, details, validationData), refreshExpires));

    if (null != request) {
      String sessionState = UUID.randomUUID().toString();
      Builder identityBuilder = claimsMapper.identityToken(tenant, authorization.getAccessToken(),
          details, grantType, validationData);
      claimsMapper.withChallengeClaims(identityBuilder, request.getState().orElse(""), sessionState,
          request.getNonce().orElse(""));
      authorization.setIdToken(tokenSigner.sign(tenant, identityBuilder, refreshExpires));
    }

    return authorization;
  }

  public AutorizationToken buildClientCredentialsToken(String tenant, ClientDetails client,
      List<String> scopes) {
    Duration expiration =
        client.getM2mTokenTtlSeconds() != null ? Duration.ofSeconds(client.getM2mTokenTtlSeconds())
            : claimsMapper.accessTokenTtl();
    Instant expires = Instant.now().plus(expiration);

    AuthenticationData data = new AuthenticationData();
    data.setUsername(client.getClientId());
    data.setTenant(tenant);
    data.setScopes(scopes != null ? scopes : List.of());

    AutorizationToken token = new AutorizationToken();
    token.setGrantType("client_credentials");
    token.setTokenType(BEARER);
    token.setUsername(client.getClientId());
    token.setExpiresIn(expiration.getSeconds());
    token.setAccessToken(tokenSigner.sign(tenant,
        claimsMapper.accessToken(tenant, client, "client_credentials", data), expires));
    return token;
  }

  public Optional<String> verifyMfa(String token, String tenant) {
    return tokenVerifier.verifyMfa(token, tenant);
  }

  public Optional<String> verifyRefresh(String token, String tenant) {
    return tokenVerifier.verifyRefresh(token, tenant);
  }

  public Optional<RefreshTokenInfo> verifyRefreshInfo(String token, String tenant) {
    return tokenVerifier.verifyRefreshInfo(token, tenant);
  }

  public Optional<String> tokenJti(String token, String tenant) {
    return tokenVerifier.tokenJti(token, tenant);
  }

  public Optional<String> verifyToken(String token, String scope, String tenant) {
    return tokenVerifier.verifyToken(token, scope, tenant);
  }
}
