package net.civeira.phylax.features.access.apikeyclient.infrastructure.driver.rest;

import java.util.List;
import java.util.stream.Stream;

import jakarta.enterprise.context.RequestScoped;
import jakarta.transaction.Transactional;
import jakarta.ws.rs.core.Response;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.batch.BatchIdentificator;
import net.civeira.phylax.common.batch.BatchProgress;
import net.civeira.phylax.common.infrastructure.CurrentRequest;
import net.civeira.phylax.features.access.apikeyclient.application.usecase.enable.ApiKeyClientEnableFilter;
import net.civeira.phylax.features.access.apikeyclient.application.usecase.enable.ApiKeyClientEnableProjection;
import net.civeira.phylax.features.access.apikeyclient.application.usecase.enable.ApiKeyClientEnableStatus;
import net.civeira.phylax.features.access.apikeyclient.application.usecase.enable.ApiKeyClientEnableUsecase;
import net.civeira.phylax.features.access.apikeyclient.domain.ApiKeyClientReference;
import net.civeira.phylax.generated.openapi.model.ApiKeyClientApiDto;

@RequiredArgsConstructor
@RequestScoped
public class ApiKeyClientEnableController {

  /**
   * @autogenerated ActionControllerGenerator
   */
  private final CurrentRequest currentRequest;

  /**
   * @autogenerated ActionControllerGenerator
   */
  private final ApiKeyClientEnableUsecase enable;

  /**
   * @autogenerated ActionControllerGenerator
   * @param uids
   * @param search
   * @param key
   * @return
   */
  public Response apiKeyClientApiBatchEnable(final List<String> uids, final String search,
      final String key) {
    ApiKeyClientEnableFilter.ApiKeyClientEnableFilterBuilder filterBuilder =
        ApiKeyClientEnableFilter.builder();
    filterBuilder =
        filterBuilder.uids(uids.stream().flatMap(part -> Stream.of(part.split(","))).toList());
    filterBuilder = filterBuilder.search(search);
    filterBuilder = filterBuilder.uids(
        null == uids ? null : uids.stream().flatMap(part -> Stream.of(part.split(","))).toList());
    filterBuilder = filterBuilder.search(search);
    filterBuilder = filterBuilder.key(key);
    ApiKeyClientEnableFilter filter = filterBuilder.build();
    BatchIdentificator task = enable.enable(currentRequest.interaction(), filter);
    /* .header("Last-Modified", value.getSince().format(DateTimeFormatter.RFC_1123_DATE_TIME)) */
    return Response.ok(task).build();
  }

  /**
   * @autogenerated ActionControllerGenerator
   * @param batchId
   * @return
   */
  public Response apiKeyClientApiBatchEnableQuery(final String batchId) {
    BatchProgress task = enable.checkProgress(
        ApiKeyClientEnableStatus.builder().taskId(batchId).build(currentRequest.interaction()));
    return Response.ok(task).build();
  }

  /**
   * @autogenerated ActionControllerGenerator
   * @param uid
   * @return
   */
  @Transactional
  public Response apiKeyClientApiEnable(final String uid) {
    ApiKeyClientEnableProjection updated =
        enable.enable(currentRequest.interaction(), ApiKeyClientReference.of(uid));
    return Response.ok(toApiModel(updated)).build();
  }

  /**
   * @autogenerated ActionControllerGenerator
   * @param dto
   * @return
   */
  private ApiKeyClientApiDto toApiModel(ApiKeyClientEnableProjection dto) {
    ApiKeyClientApiDto apiKeyClientApiDto = new ApiKeyClientApiDto();
    apiKeyClientApiDto.setUid(dto.getUid());
    apiKeyClientApiDto.setCode(dto.getCode());
    apiKeyClientApiDto.setKey(dto.getKey());
    apiKeyClientApiDto.setEnabled(dto.getEnabled());
    apiKeyClientApiDto.setScopes(dto.getScopes());
    apiKeyClientApiDto.setVersion(dto.getVersion());
    return apiKeyClientApiDto;
  }
}
