package net.civeira.phylax.features.access.tenant.application.usecase.delete;

import java.util.List;

import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.SpanKind;
import io.opentelemetry.api.trace.Tracer;
import io.opentelemetry.context.Context;
import io.quarkus.arc.Unremovable;
import jakarta.enterprise.context.ApplicationScoped;
import lombok.Data;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.batch.stepper.ItemDescriptor;
import net.civeira.phylax.common.batch.stepper.ItemProcessor;
import net.civeira.phylax.common.batch.stepper.ItemReader;
import net.civeira.phylax.common.batch.stepper.ItemWriter;
import net.civeira.phylax.common.batch.stepper.StepContext;
import net.civeira.phylax.common.batch.stepper.StepCounter;
import net.civeira.phylax.common.batch.stepper.StepFinalizer;
import net.civeira.phylax.common.batch.stepper.StepInitializer;
import net.civeira.phylax.common.exception.ExecutionException;
import net.civeira.phylax.common.security.Allow;
import net.civeira.phylax.features.access.tenant.application.visibility.TenantsVisibility;
import net.civeira.phylax.features.access.tenant.domain.Tenant;
import net.civeira.phylax.features.access.tenant.domain.gateway.TenantAuditGateway;
import net.civeira.phylax.features.access.tenant.domain.gateway.TenantCursor;

@Unremovable
@ApplicationScoped
@RequiredArgsConstructor
class TenantsInBatchExecutor implements
    StepCounter<TenantDeleteAllInBatchCommand, TenantsInBatchExecutor.TenantPaginableBatch>,
    StepFinalizer<TenantDeleteAllInBatchCommand, TenantsInBatchExecutor.TenantPaginableBatch>,
    StepInitializer<TenantDeleteAllInBatchCommand, TenantsInBatchExecutor.TenantPaginableBatch>,
    ItemReader<Tenant, TenantDeleteAllInBatchCommand, TenantsInBatchExecutor.TenantPaginableBatch>,
    ItemWriter<Tenant, TenantDeleteAllInBatchCommand, TenantsInBatchExecutor.TenantPaginableBatch>,
    ItemProcessor<Tenant, Tenant, TenantDeleteAllInBatchCommand, TenantsInBatchExecutor.TenantPaginableBatch>,
    ItemDescriptor<Tenant, TenantDeleteAllInBatchCommand, TenantsInBatchExecutor.TenantPaginableBatch> {

  /**
   * @autogenerated EntityGenerator
   */
  @Data
  public static class TenantPaginableBatch {

    /**
     * @autogenerated EntityGenerator
     */
    private String since;
  }

  /**
   * Service to register audit events
   *
   * @autogenerated EntityGenerator
   */
  private final TenantAuditGateway audit;

  /**
   * @autogenerated EntityGenerator
   */
  private final int size = 10;

  /**
   * @autogenerated EntityGenerator
   */
  private final Tracer tracer;

  /**
   * @autogenerated EntityGenerator
   */
  private final TenantDeleteUsecase usecase;

  /**
   * @autogenerated EntityGenerator
   */
  private final TenantsVisibility visibility;

  /**
   * @autogenerated EntityGenerator
   * @param context
   * @return
   */
  @Override
  public long approximatedItems(
      final StepContext<TenantDeleteAllInBatchCommand, TenantPaginableBatch> context) {
    Span span = tracer
        .spanBuilder("Count selected items to the batch delete for a set of entities of tenant")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      return visibility.countVisibles(context.getParams().getInteraction(),
          context.getParams().getFilter());
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * @autogenerated EntityGenerator
   * @param context
   */
  @Override
  public void finish(
      final StepContext<TenantDeleteAllInBatchCommand, TenantPaginableBatch> context) {
    usecase.cacheEvict();
  }

  /**
   * @autogenerated EntityGenerator
   * @param context
   */
  @Override
  public void init(final StepContext<TenantDeleteAllInBatchCommand, TenantPaginableBatch> context) {
    context.setState(new TenantPaginableBatch());
  }

  /**
   * @autogenerated EntityGenerator
   * @param item
   * @param context
   * @return
   */
  @Override
  public String itemDescription(final Tenant item,
      final StepContext<TenantDeleteAllInBatchCommand, TenantPaginableBatch> context) {
    return item.getUid();
  }

  /**
   * @autogenerated EntityGenerator
   * @param item
   * @param context
   * @return
   */
  @Override
  public Tenant process(final Tenant item,
      final StepContext<TenantDeleteAllInBatchCommand, TenantPaginableBatch> context) {
    Span span = tracer
        .spanBuilder("Prepare individual data for the batch delete on a set of entities of tenant")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      Allow allowed = usecase.checkAllow(context.getParams().getInteraction(), item);
      if (!allowed.isAllowed()) {
        span.addEvent("The policies for tenant dont allow to delete: " + allowed.getDescription());
        throw new ExecutionException("not-allowed", null);
      }
      return item;
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * @autogenerated EntityGenerator
   * @param context
   * @return
   */
  @Override
  public List<Tenant> read(
      final StepContext<TenantDeleteAllInBatchCommand, TenantPaginableBatch> context) {
    Span span = tracer
        .spanBuilder("Read selected entitites for a batch delete for a set of entities of tenant")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      List<Tenant> page = visibility.listVisiblesForUpdate(context.getParams().getInteraction(),
          context.getParams().getFilter(),
          TenantCursor.builder().limit(size).sinceUid(context.getState().getSince()).build());
      context.getState().setSince(page.isEmpty() ? null : page.get(page.size() - 1).getUid());
      span.setAttribute("size", page.size());
      return page;
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * @autogenerated EntityGenerator
   * @param items
   * @param context
   */
  @Override
  public void write(final List<Tenant> items,
      final StepContext<TenantDeleteAllInBatchCommand, TenantPaginableBatch> context) {
    Span span = tracer.spanBuilder("Perform the batch delete for a set of entities of tenant")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      span.setAttribute("size", items.size());
      items.forEach(item -> {
        usecase.doDelete(context.getParams().getInteraction(), item);
        usecase.cacheEvict();
        audit.deleted("batch-delete", item, context.getParams().getInteraction());
      });
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }
}
