package net.civeira.phylax.features.document.templatevariable.application.usecase.disable;

import java.time.Duration;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.batch.BatchIdentificator;
import net.civeira.phylax.common.batch.BatchProgress;
import net.civeira.phylax.common.batch.BatchService;
import net.civeira.phylax.common.batch.ExecutorByDeferSteps;
import net.civeira.phylax.common.batch.ExecutorPlan;
import net.civeira.phylax.common.exception.NotAllowedException;
import net.civeira.phylax.common.exception.NotFoundException;
import net.civeira.phylax.common.security.OperationContext;
import net.civeira.phylax.common.security.Permission;
import net.civeira.phylax.common.telemetry.Observed;
import net.civeira.phylax.common.telemetry.Trace;
import net.civeira.phylax.features.document.templatevariable.application.visibility.TemplateVariableVisibilityFilter;
import net.civeira.phylax.features.document.templatevariable.application.visibility.TemplateVariablesVisibility;
import net.civeira.phylax.features.document.templatevariable.domain.TemplateVariable;
import net.civeira.phylax.features.document.templatevariable.domain.TemplateVariableRef;
import net.civeira.phylax.features.document.templatevariable.domain.gateway.TemplateVariableAuditGateway;
import net.civeira.phylax.features.document.templatevariable.domain.gateway.TemplateVariableCacheGateway;
import net.civeira.phylax.features.document.templatevariable.domain.gateway.TemplateVariableWriteRepositoryGateway;

@ApplicationScoped
@RequiredArgsConstructor
public class TemplateVariableDisableUsecase {

  /**
   * Service to register audit events
   *
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final TemplateVariableAuditGateway audit;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final BatchService batch;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final TemplateVariableCacheGateway cache;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final Event<TemplateVariableDisableAuthorizationDecision> execAllowEmitter;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final Event<TemplateVariableDisableCheck> execProposalEmitter;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final TemplateVariableWriteRepositoryGateway gateway;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final TemplateVariablesVisibility visibility;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param reference
   * @return
   */
  @Observed("disable an entity of template variable")
  public Permission allow(final OperationContext context, final TemplateVariableRef reference) {
    Trace.setAttribute("ref", reference.getUid());
    Permission response = checkPermission(context, reference);
    Trace.setAttribute("allowed", response.isAllowed());
    return response;
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @return
   */
  @Observed("disable an entity of template variable")
  public Permission allow(final OperationContext context) {
    Permission response = checkPermission(context);
    Trace.setAttribute("allowed", response.isAllowed());
    return response;
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param filter
   * @return The slide with some values
   */
  @Observed("disable a set of entity of template variable")
  public BatchIdentificator batchDisable(final OperationContext context,
      final TemplateVariableDisableFilter filter) {
    Permission detail = checkPermission(context);
    if (!detail.isAllowed()) {
      Trace.addEvent(
          "The policies for template variable dont allow to disable: " + detail.getDescription());
      throw new NotAllowedException(detail.getDescription());
    }
    TemplateVariableVisibilityFilter filterWithVisibility = TemplateVariableVisibilityFilter
        .builder().uid(filter.getUid().orElse(null)).uids(filter.getUids().stream().toList())
        .search(filter.getSearch().orElse(null)).code(filter.getCode().orElse(null))
        .tenant(filter.getTenant().orElse(null)).tenants(filter.getTenants())
        .tenantTenantAccesible(filter.getTenantTenantAccesible().orElse(null)).build();
    TemplateVariableDisableAllInBatchCommand command =
        new TemplateVariableDisableAllInBatchCommand(context, filterWithVisibility);
    return batch.start(context.getActor().getName().orElse("-"), Duration.ofHours(6), ExecutorPlan
        .<TemplateVariableDisableAllInBatchCommand>builder().params(command)
        .name("disable-template-variable")
        .executor(
            ExecutorByDeferSteps.<TemplateVariable, TemplateVariable, TemplateVariableDisableAllInBatchCommand, TemplateVariableDisablesInBatchExecutor.TemplateVariablePaginableBatch>builder()
                .initializer(TemplateVariableDisablesInBatchExecutor.class)
                .counter(TemplateVariableDisablesInBatchExecutor.class)
                .descriptor(TemplateVariableDisablesInBatchExecutor.class)
                .reader(TemplateVariableDisablesInBatchExecutor.class)
                .processor(TemplateVariableDisablesInBatchExecutor.class)
                .writer(TemplateVariableDisablesInBatchExecutor.class)
                .finalizer(TemplateVariableDisablesInBatchExecutor.class).build())
        .build());
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param query a filter to retrieve only matching values
   * @return The slide with some values
   */
  public BatchProgress checkProgress(final OperationContext context,
      final TemplateVariableDisableStatus query) {
    return context.getActor().getName()
        .flatMap(name -> batch.retrieve(query.getTaskId(), context.getSource().getLocale(), name))
        .orElseThrow(() -> new NotFoundException());
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param reference
   * @return The slide with some values
   */
  @Observed("disable an entity of template variable")
  public TemplateVariableDisableProjection disable(final OperationContext context,
      final TemplateVariableRef reference) {
    Trace.setAttribute("ref", reference.getUid());
    Permission detail = checkPermission(context, reference);
    if (!detail.isAllowed()) {
      Trace.addEvent(
          "The policies for template variable dont allow to disable: " + detail.getDescription());
      throw new NotAllowedException(detail.getDescription());
    }
    TemplateVariable original = visibility.retrieveVisibleForUpdate(context, reference.getUid())
        .orElseThrow(() -> new NotFoundException(""));
    TemplateVariable saved = doDisable(context, original);
    cacheUpdate(saved);
    // Register audit operation
    audit.updated("disable", saved, original, context);
    return TemplateVariableDisableProjection.from(visibility.copyWithHidden(context, saved));
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param saved
   */
  void cacheUpdate(final TemplateVariable saved) {
    cache.update(saved);
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param reference
   * @return
   */
  Permission checkPermission(final OperationContext context, final TemplateVariableRef reference) {
    TemplateVariableDisableAuthorizationDecision proposal =
        new TemplateVariableDisableAuthorizationDecision(context, reference,
            Permission.allow("Allow to disable by default"));
    execAllowEmitter.fire(proposal);
    return proposal.getPermission();
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @return
   */
  Permission checkPermission(final OperationContext context) {
    TemplateVariableDisableAuthorizationDecision proposal =
        new TemplateVariableDisableAuthorizationDecision(context,
            Permission.allow("Allow to disable by default"));
    execAllowEmitter.fire(proposal);
    return proposal.getPermission();
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param original
   * @return
   */
  TemplateVariable doDisable(final OperationContext context, final TemplateVariable original) {
    TemplateVariableDisableCheck proposal = new TemplateVariableDisableCheck(context, original);
    execProposalEmitter.fire(proposal);
    TemplateVariable result = original.disable();
    TemplateVariable saved = gateway.update(original, result);
    return saved;
  }
}
