package net.civeira.phylax.features.document.templatevariable.application.usecase.disable;

import java.util.List;

import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.SpanKind;
import io.opentelemetry.api.trace.Tracer;
import io.opentelemetry.context.Context;
import io.quarkus.arc.Unremovable;
import jakarta.enterprise.context.ApplicationScoped;
import lombok.Data;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.batch.stepper.ItemDescriptor;
import net.civeira.phylax.common.batch.stepper.ItemProcessor;
import net.civeira.phylax.common.batch.stepper.ItemReader;
import net.civeira.phylax.common.batch.stepper.ItemWriter;
import net.civeira.phylax.common.batch.stepper.StepContext;
import net.civeira.phylax.common.batch.stepper.StepCounter;
import net.civeira.phylax.common.batch.stepper.StepFinalizer;
import net.civeira.phylax.common.batch.stepper.StepInitializer;
import net.civeira.phylax.common.exception.ExecutionException;
import net.civeira.phylax.common.security.Permission;
import net.civeira.phylax.features.document.templatevariable.application.visibility.TemplateVariablesVisibility;
import net.civeira.phylax.features.document.templatevariable.domain.TemplateVariable;
import net.civeira.phylax.features.document.templatevariable.domain.gateway.TemplateVariableAuditGateway;
import net.civeira.phylax.features.document.templatevariable.domain.gateway.TemplateVariableCursor;

@Unremovable
@ApplicationScoped
@RequiredArgsConstructor
class TemplateVariableDisablesInBatchExecutor implements
    StepCounter<TemplateVariableDisableAllInBatchCommand, TemplateVariableDisablesInBatchExecutor.TemplateVariablePaginableBatch>,
    StepFinalizer<TemplateVariableDisableAllInBatchCommand, TemplateVariableDisablesInBatchExecutor.TemplateVariablePaginableBatch>,
    StepInitializer<TemplateVariableDisableAllInBatchCommand, TemplateVariableDisablesInBatchExecutor.TemplateVariablePaginableBatch>,
    ItemReader<TemplateVariable, TemplateVariableDisableAllInBatchCommand, TemplateVariableDisablesInBatchExecutor.TemplateVariablePaginableBatch>,
    ItemWriter<TemplateVariable, TemplateVariableDisableAllInBatchCommand, TemplateVariableDisablesInBatchExecutor.TemplateVariablePaginableBatch>,
    ItemProcessor<TemplateVariable, TemplateVariable, TemplateVariableDisableAllInBatchCommand, TemplateVariableDisablesInBatchExecutor.TemplateVariablePaginableBatch>,
    ItemDescriptor<TemplateVariable, TemplateVariableDisableAllInBatchCommand, TemplateVariableDisablesInBatchExecutor.TemplateVariablePaginableBatch> {

  /**
   * @autogenerated EntityGenerator
   */
  @Data
  public static class TemplateVariablePaginableBatch {

    /**
     * @autogenerated EntityGenerator
     */
    private String since;
  }

  /**
   * Service to register audit events
   *
   * @autogenerated EntityGenerator
   */
  private final TemplateVariableAuditGateway audit;

  /**
   * @autogenerated EntityGenerator
   */
  private final int size = 10;

  /**
   * @autogenerated EntityGenerator
   */
  private final Tracer tracer;

  /**
   * @autogenerated EntityGenerator
   */
  private final TemplateVariableDisableUsecase usecase;

  /**
   * @autogenerated EntityGenerator
   */
  private final TemplateVariablesVisibility visibility;

  /**
   * @autogenerated EntityGenerator
   * @param context
   * @return
   */
  @Override
  public long approximatedItems(
      final StepContext<TemplateVariableDisableAllInBatchCommand, TemplateVariablePaginableBatch> context) {
    Span span = tracer
        .spanBuilder(
            "Count selected items to the batch disable for a set of entities of template variable")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      return visibility.countVisibles(context.getParams().getContext(),
          context.getParams().getFilter());
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * @autogenerated EntityGenerator
   * @param context
   */
  @Override
  public void finish(
      final StepContext<TemplateVariableDisableAllInBatchCommand, TemplateVariablePaginableBatch> context) {
    /* do nothing */
  }

  /**
   * @autogenerated EntityGenerator
   * @param context
   */
  @Override
  public void init(
      final StepContext<TemplateVariableDisableAllInBatchCommand, TemplateVariablePaginableBatch> context) {
    context.setState(new TemplateVariablePaginableBatch());
  }

  /**
   * @autogenerated EntityGenerator
   * @param item
   * @param context
   * @return
   */
  @Override
  public String itemDescription(final TemplateVariable item,
      final StepContext<TemplateVariableDisableAllInBatchCommand, TemplateVariablePaginableBatch> context) {
    return item.getUid();
  }

  /**
   * @autogenerated EntityGenerator
   * @param item
   * @param context
   * @return
   */
  @Override
  public TemplateVariable process(final TemplateVariable item,
      final StepContext<TemplateVariableDisableAllInBatchCommand, TemplateVariablePaginableBatch> context) {
    Span span = tracer.spanBuilder(
        "Prepare individual data for the batch disable on a set of entities of template variable")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      Permission permission = usecase.checkPermission(context.getParams().getContext(), item);
      if (!permission.isAllowed()) {
        span.addEvent("The policies for template variable dont allow to delete: "
            + permission.getDescription());
        throw new ExecutionException("not-allowed", null);
      }
      return item;
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * @autogenerated EntityGenerator
   * @param context
   * @return
   */
  @Override
  public List<TemplateVariable> read(
      final StepContext<TemplateVariableDisableAllInBatchCommand, TemplateVariablePaginableBatch> context) {
    Span span = tracer.spanBuilder(
        "Read selected entitites for a batch disable for a set of entities of template variable")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      List<TemplateVariable> page = visibility.listVisiblesForUpdate(
          context.getParams().getContext(), context.getParams().getFilter(), TemplateVariableCursor
              .builder().limit(size).sinceUid(context.getState().getSince()).build());
      context.getState().setSince(page.isEmpty() ? null : page.get(page.size() - 1).getUid());
      return page;
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * @autogenerated EntityGenerator
   * @param items
   * @param context
   */
  @Override
  public void write(final List<TemplateVariable> items,
      final StepContext<TemplateVariableDisableAllInBatchCommand, TemplateVariablePaginableBatch> context) {
    Span span =
        tracer.spanBuilder("Perform the batch disable for a set of entities of template variable")
            .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
            .startSpan();
    try {
      span.setAttribute("size", items.size());
      items.forEach(item -> {
        TemplateVariable changed = usecase.doDisable(context.getParams().getContext(), item);
        usecase.cacheUpdate(changed);
        audit.updated("batch-disable", changed, item, context.getParams().getContext());
      });
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }
}
