package net.civeira.phylax.features.access.tenant.application.usecase.list;

import java.util.List;
import java.util.Optional;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.With;

@Data
@Builder(toBuilder = true)
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class TenantListFilter {

  /**
   * @autogenerated ListFilterGenerator
   */
  private String name;

  /**
   * The filter to select the results to retrieve
   *
   * @autogenerated ListFilterGenerator
   */
  private String search;

  /**
   * @autogenerated ListFilterGenerator
   */
  private String tenantAccesible;

  /**
   * The filter to select the results to retrieve
   *
   * @autogenerated ListFilterGenerator
   */
  private String uid;

  /**
   * The filter to select the results to retrieve
   *
   * @autogenerated ListFilterGenerator
   */
  private List<String> uids;

  /**
   * @autogenerated ListFilterGenerator
   * @return
   */
  public Optional<String> getName() {
    return Optional.ofNullable(name);
  }

  /**
   * @autogenerated ListFilterGenerator
   * @return
   */
  public Optional<String> getSearch() {
    return Optional.ofNullable(search);
  }

  /**
   * @autogenerated ListFilterGenerator
   * @return
   */
  public Optional<String> getTenantAccesible() {
    return Optional.ofNullable(tenantAccesible);
  }

  /**
   * @autogenerated ListFilterGenerator
   * @return
   */
  public Optional<String> getUid() {
    return Optional.ofNullable(uid);
  }

  /**
   * @autogenerated ListFilterGenerator
   * @return
   */
  public List<String> getUids() {
    return null == uids ? List.of() : List.copyOf(uids);
  }
}
