package net.civeira.phylax.features.document.templatesnippet.application.usecase.delete;

import java.time.Duration;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.batch.BatchIdentificator;
import net.civeira.phylax.common.batch.BatchProgress;
import net.civeira.phylax.common.batch.BatchService;
import net.civeira.phylax.common.batch.ExecutorByDeferSteps;
import net.civeira.phylax.common.batch.ExecutorPlan;
import net.civeira.phylax.common.exception.NotAllowedException;
import net.civeira.phylax.common.exception.NotFoundException;
import net.civeira.phylax.common.security.OperationContext;
import net.civeira.phylax.common.security.Permission;
import net.civeira.phylax.common.telemetry.Observed;
import net.civeira.phylax.common.telemetry.Trace;
import net.civeira.phylax.features.document.templatesnippet.application.visibility.TemplateSnippetVisibilityFilter;
import net.civeira.phylax.features.document.templatesnippet.application.visibility.TemplateSnippetsVisibility;
import net.civeira.phylax.features.document.templatesnippet.domain.TemplateSnippet;
import net.civeira.phylax.features.document.templatesnippet.domain.TemplateSnippetRef;
import net.civeira.phylax.features.document.templatesnippet.domain.gateway.TemplateSnippetAuditGateway;
import net.civeira.phylax.features.document.templatesnippet.domain.gateway.TemplateSnippetCacheGateway;
import net.civeira.phylax.features.document.templatesnippet.domain.gateway.TemplateSnippetWriteRepositoryGateway;

@ApplicationScoped
@RequiredArgsConstructor
public class TemplateSnippetDeleteUsecase {

  /**
   * Service to register audit events
   *
   * @autogenerated DeleteUsecaseGenerator
   */
  private final TemplateSnippetAuditGateway audit;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final BatchService batch;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final TemplateSnippetCacheGateway cache;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final Event<TemplateSnippetDeleteAuthorizationDecision> deleteAllowEmitter;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final Event<TemplateSnippetDeleteCheck> deleteCheckEmitter;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final TemplateSnippetWriteRepositoryGateway gateway;

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  private final TemplateSnippetsVisibility visibility;

  /**
   * @autogenerated DeleteUsecaseGenerator
   * @param context
   * @param reference
   * @return
   */
  @Observed("Chekcing if is allowed to delete an entity of template snippet")
  public Permission allow(final OperationContext context, final TemplateSnippetRef reference) {
    Trace.setAttribute("ref", reference.getUid());
    Permission response = checkPermission(context, reference);
    Trace.setAttribute("allowed", response.isAllowed());
    return response;
  }

  /**
   * @autogenerated DeleteUsecaseGenerator
   * @param context
   * @return
   */
  @Observed("Checking if is allowed to delete a set of entities of template snippet")
  public Permission allow(final OperationContext context) {
    Permission response = checkPermission(context);
    Trace.setAttribute("allowed", response.isAllowed());
    return response;
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated DeleteUsecaseGenerator
   * @param context
   * @param filter
   * @return The slide with some values
   */
  @Observed("Deleting a set of entities of template snippet")
  public BatchIdentificator batchDelete(final OperationContext context,
      final TemplateSnippetDeleteFilter filter) {
    Permission permission = checkPermission(context);
    if (!permission.isAllowed()) {
      Trace.addEvent(
          "The policies for template snippet dont allow to delete: " + permission.getDescription());
      throw new NotAllowedException(permission.getDescription());
    }
    TemplateSnippetVisibilityFilter filterOnVisibles = TemplateSnippetVisibilityFilter.builder()
        .uid(filter.getUid().orElse(null)).uids(filter.getUids().stream().toList())
        .search(filter.getSearch().orElse(null)).code(filter.getCode().orElse(null))
        .tenant(filter.getTenant().orElse(null)).tenants(filter.getTenants())
        .tenantTenantAccesible(filter.getTenantTenantAccesible().orElse(null)).build();
    TemplateSnippetDeleteAllInBatchCommand command =
        new TemplateSnippetDeleteAllInBatchCommand(context, filterOnVisibles);
    return batch.start(context.getActor().getName().orElse("-"), Duration.ofHours(6), ExecutorPlan
        .<TemplateSnippetDeleteAllInBatchCommand>builder().params(command).name("delete-color")
        .executor(
            ExecutorByDeferSteps.<TemplateSnippet, TemplateSnippet, TemplateSnippetDeleteAllInBatchCommand, TemplateSnippetsInBatchExecutor.TemplateSnippetPaginableBatch>builder()
                .initializer(TemplateSnippetsInBatchExecutor.class)
                .counter(TemplateSnippetsInBatchExecutor.class)
                .descriptor(TemplateSnippetsInBatchExecutor.class)
                .reader(TemplateSnippetsInBatchExecutor.class)
                .processor(TemplateSnippetsInBatchExecutor.class)
                .writer(TemplateSnippetsInBatchExecutor.class)
                .finalizer(TemplateSnippetsInBatchExecutor.class).build())
        .build());
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated DeleteUsecaseGenerator
   * @param context
   * @param query a filter to retrieve only matching values
   * @return The slide with some values
   */
  public BatchProgress checkProgress(final OperationContext context,
      final TemplateSnippetCheckBatchDeleteStatus query) {
    return context.getActor().getName()
        .flatMap(name -> batch.retrieve(query.getTaskId(), context.getSource().getLocale(), name))
        .orElseThrow(() -> new NotFoundException());
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated DeleteUsecaseGenerator
   * @param context
   * @param reference
   */
  @Observed("Deleting an entity of template snippet")
  public void delete(final OperationContext context, final TemplateSnippetRef reference) {
    Trace.setAttribute("ref", reference.getUid());
    Permission permission = checkPermission(context, reference);
    if (!permission.isAllowed()) {
      Trace.addEvent(
          "The policies for template snippet dont allow to delete: " + permission.getDescription());
      throw new NotAllowedException(permission.getDescription());
    }
    TemplateSnippet original = visibility.retrieveVisibleForUpdate(context, reference.getUid())
        .orElseThrow(() -> new NotFoundException(""));
    doDelete(context, original);
    cacheEvict();
    // Register audit operation
    audit.deleted("delete", original, context);
  }

  /**
   * @autogenerated DeleteUsecaseGenerator
   */
  void cacheEvict() {
    cache.evict();
  }

  /**
   * @autogenerated DeleteUsecaseGenerator
   * @param context
   * @param reference
   * @return
   */
  Permission checkPermission(final OperationContext context, final TemplateSnippetRef reference) {
    TemplateSnippetDeleteAuthorizationDecision proposal =
        new TemplateSnippetDeleteAuthorizationDecision(context, reference,
            Permission.allow("Allowed by default"));
    deleteAllowEmitter.fire(proposal);
    return proposal.getPermission();
  }

  /**
   * @autogenerated DeleteUsecaseGenerator
   * @param context
   * @return
   */
  Permission checkPermission(final OperationContext context) {
    TemplateSnippetDeleteAuthorizationDecision proposal =
        new TemplateSnippetDeleteAuthorizationDecision(context,
            Permission.allow("Allowed by default"));
    deleteAllowEmitter.fire(proposal);
    return proposal.getPermission();
  }

  /**
   * @autogenerated DeleteUsecaseGenerator
   * @param context
   * @param original
   */
  void doDelete(final OperationContext context, final TemplateSnippet original) {
    TemplateSnippetDeleteCheck proposal = new TemplateSnippetDeleteCheck(context, original);
    deleteCheckEmitter.fire(proposal);
    TemplateSnippet clean = original.delete();
    gateway.delete(clean);
  }
}
