/* @autogenerated */
package net.civeira.phylax.bootstrap.telemetry;

import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.SpanKind;
import io.opentelemetry.api.trace.Tracer;
import io.opentelemetry.context.Context;
import io.opentelemetry.context.Scope;
import jakarta.enterprise.inject.Instance;
import jakarta.interceptor.InvocationContext;

final class TelemetryInterceptor {
  private TelemetryInterceptor() {}

  static Object around(final InvocationContext context, final Instance<Tracer> tracerInstance,
      final SpanKind kind, final String title, final String value) throws Exception {
    Tracer tracer =
        tracerInstance != null && tracerInstance.isResolvable() ? tracerInstance.get() : null;
    if (tracer == null) {
      return context.proceed();
    }

    String spanName = resolveSpanName(title, value);
    if (spanName == null) {
      return context.proceed();
    }

    Span span = tracer.spanBuilder(spanName).setParent(Context.current().with(Span.current()))
        .setSpanKind(kind == null ? SpanKind.INTERNAL : kind).startSpan();

    try (Scope scope = span.makeCurrent()) {
      return context.proceed();
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  private static String resolveSpanName(final String title, final String value) {
    if (title != null && !title.isBlank()) {
      return title;
    }
    if (value != null && !value.isBlank()) {
      return value;
    }
    return null;
  }
}
