package net.civeira.phylax.features.access.userprofile.domain;

import lombok.NoArgsConstructor;
import lombok.experimental.Delegate;
import net.civeira.phylax.common.value.Uuid;
import net.civeira.phylax.features.access.userprofile.domain.valueholder.AddressJsonValueHolder;
import net.civeira.phylax.features.access.userprofile.domain.valueholder.BirthdateValueHolder;
import net.civeira.phylax.features.access.userprofile.domain.valueholder.FamilyNameValueHolder;
import net.civeira.phylax.features.access.userprofile.domain.valueholder.GenderValueHolder;
import net.civeira.phylax.features.access.userprofile.domain.valueholder.GivenNameValueHolder;
import net.civeira.phylax.features.access.userprofile.domain.valueholder.LocaleValueHolder;
import net.civeira.phylax.features.access.userprofile.domain.valueholder.MiddleNameValueHolder;
import net.civeira.phylax.features.access.userprofile.domain.valueholder.NicknameValueHolder;
import net.civeira.phylax.features.access.userprofile.domain.valueholder.PhoneNumberValueHolder;
import net.civeira.phylax.features.access.userprofile.domain.valueholder.PhoneNumberVerifiedValueHolder;
import net.civeira.phylax.features.access.userprofile.domain.valueholder.PictureUrlValueHolder;
import net.civeira.phylax.features.access.userprofile.domain.valueholder.PreferredUsernameValueHolder;
import net.civeira.phylax.features.access.userprofile.domain.valueholder.UidValueHolder;
import net.civeira.phylax.features.access.userprofile.domain.valueholder.UpdatedAtValueHolder;
import net.civeira.phylax.features.access.userprofile.domain.valueholder.UserValueHolder;
import net.civeira.phylax.features.access.userprofile.domain.valueholder.VersionValueHolder;
import net.civeira.phylax.features.access.userprofile.domain.valueholder.WebsiteUrlValueHolder;
import net.civeira.phylax.features.access.userprofile.domain.valueholder.ZoneinfoValueHolder;

/**
 * A dto transfer to hold user profile attribute values
 */
@NoArgsConstructor
public class UserProfileChangeSet {

  /**
   * El address json de user profile
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private AddressJsonValueHolder<UserProfileChangeSet> addressJsonValue =
      new AddressJsonValueHolder<>(this);

  /**
   * El birthdate de user profile
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private BirthdateValueHolder<UserProfileChangeSet> birthdateValue =
      new BirthdateValueHolder<>(this);

  /**
   * El family name de user profile
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private FamilyNameValueHolder<UserProfileChangeSet> familyNameValue =
      new FamilyNameValueHolder<>(this);

  /**
   * El gender de user profile
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private GenderValueHolder<UserProfileChangeSet> genderValue = new GenderValueHolder<>(this);

  /**
   * El given name de user profile
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private GivenNameValueHolder<UserProfileChangeSet> givenNameValue =
      new GivenNameValueHolder<>(this);

  /**
   * El locale de user profile
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private LocaleValueHolder<UserProfileChangeSet> localeValue = new LocaleValueHolder<>(this);

  /**
   * El middle name de user profile
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private MiddleNameValueHolder<UserProfileChangeSet> middleNameValue =
      new MiddleNameValueHolder<>(this);

  /**
   * El nickname de user profile
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private NicknameValueHolder<UserProfileChangeSet> nicknameValue = new NicknameValueHolder<>(this);

  /**
   * El phone number de user profile
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private PhoneNumberValueHolder<UserProfileChangeSet> phoneNumberValue =
      new PhoneNumberValueHolder<>(this);

  /**
   * El phone number verified de user profile
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private PhoneNumberVerifiedValueHolder<UserProfileChangeSet> phoneNumberVerifiedValue =
      new PhoneNumberVerifiedValueHolder<>(this);

  /**
   * El picture url de user profile
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private PictureUrlValueHolder<UserProfileChangeSet> pictureUrlValue =
      new PictureUrlValueHolder<>(this);

  /**
   * El preferred username de user profile
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private PreferredUsernameValueHolder<UserProfileChangeSet> preferredUsernameValue =
      new PreferredUsernameValueHolder<>(this);

  /**
   * El identificador de la aplicacion
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private UidValueHolder<UserProfileChangeSet> uidValue = new UidValueHolder<>(this);

  /**
   * El updated at de user profile
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private UpdatedAtValueHolder<UserProfileChangeSet> updatedAtValue =
      new UpdatedAtValueHolder<>(this);

  /**
   * El user de user profile
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private UserValueHolder<UserProfileChangeSet> userValue = new UserValueHolder<>(this);

  /**
   * Campo con el número de version de user profile para controlar bloqueos optimistas
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private VersionValueHolder<UserProfileChangeSet> versionValue = new VersionValueHolder<>(this);

  /**
   * El website url de user profile
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private WebsiteUrlValueHolder<UserProfileChangeSet> websiteUrlValue =
      new WebsiteUrlValueHolder<>(this);

  /**
   * El zoneinfo de user profile
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private ZoneinfoValueHolder<UserProfileChangeSet> zoneinfoValue = new ZoneinfoValueHolder<>(this);

  /**
   * @autogenerated EntityChangeSetGenerator
   * @return
   */
  public UserProfileChangeSet newUid() {
    return version(0).uid(Uuid.comb().toString());
  }

  /**
   * Unset a value by the property name. Unset values will no provide command change neither provide
   * information to the output context (hidden or readonly fields, or policy restrictions).
   *
   * @autogenerated EntityChangeSetGenerator
   * @param field The field name to unset.
   */
  public void unset(final String field) {
    uidValue.unsetUidIfMatches(field);
    userValue.unsetUserIfMatches(field);
    givenNameValue.unsetGivenNameIfMatches(field);
    familyNameValue.unsetFamilyNameIfMatches(field);
    middleNameValue.unsetMiddleNameIfMatches(field);
    nicknameValue.unsetNicknameIfMatches(field);
    preferredUsernameValue.unsetPreferredUsernameIfMatches(field);
    pictureUrlValue.unsetPictureUrlIfMatches(field);
    websiteUrlValue.unsetWebsiteUrlIfMatches(field);
    genderValue.unsetGenderIfMatches(field);
    birthdateValue.unsetBirthdateIfMatches(field);
    zoneinfoValue.unsetZoneinfoIfMatches(field);
    localeValue.unsetLocaleIfMatches(field);
    phoneNumberValue.unsetPhoneNumberIfMatches(field);
    phoneNumberVerifiedValue.unsetPhoneNumberVerifiedIfMatches(field);
    addressJsonValue.unsetAddressJsonIfMatches(field);
    updatedAtValue.unsetUpdatedAtIfMatches(field);
    versionValue.unsetVersionIfMatches(field);
  }
}
