package net.civeira.phylax.features.access.platformidentity.domain;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NonNull;
import lombok.ToString;
import lombok.experimental.Delegate;
import net.civeira.phylax.features.access.platformidentity.domain.valueobject.UidVO;

/**
 * A simple implementación for a reference to a entity, that only holds the id.
 */
@Getter
@AllArgsConstructor
@ToString
@EqualsAndHashCode
public class PlatformIdentityReference implements PlatformIdentityRef {

  /**
   * @autogenerated EntityReferenceImplGenerator
   * @param uid
   * @return
   */
  public static PlatformIdentityReference of(final String uid) {
    return new PlatformIdentityReference(UidVO.from(uid));
  }

  /**
   * El identificador de la aplicacion
   *
   * @autogenerated EntityReferenceImplGenerator
   */
  @Delegate
  @NonNull
  private UidVO uidValue;
}
