package net.civeira.phylax.features.access.securityscope.transition.disable;

import java.util.function.Function;

import net.civeira.phylax.features.access.securityscope.SecurityScope;

public interface SecurityScopeDisableStep {

  /**
   * @autogenerated UpdateEntityRuleGenerator
   * @param transition
   * @param next
   * @return
   */
  SecurityScope disable(SecurityScopeDisableTransition transition,
      Function<SecurityScopeDisableTransition, SecurityScope> next);
}
