package net.civeira.phylax.features.access.tenantloginprovider.infrastructure.driver.rest;

import org.apache.commons.lang3.StringUtils;

import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.SpanKind;
import io.opentelemetry.api.trace.Tracer;
import io.opentelemetry.context.Context;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.transaction.Transactional;
import jakarta.ws.rs.core.Response;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.infrastructure.CurrentRequest;
import net.civeira.phylax.features.access.tenant.domain.TenantReference;
import net.civeira.phylax.features.access.tenantloginprovider.application.usecase.create.TenantLoginProviderCreateInput;
import net.civeira.phylax.features.access.tenantloginprovider.application.usecase.create.TenantLoginProviderCreateProjection;
import net.civeira.phylax.features.access.tenantloginprovider.application.usecase.create.TenantLoginProviderCreateUsecase;
import net.civeira.phylax.features.access.tenantloginprovider.domain.TenantLoginProviderSourceOptions;
import net.civeira.phylax.generated.openapi.model.TenantApiRef;
import net.civeira.phylax.generated.openapi.model.TenantLoginProviderApiDto;
import net.civeira.phylax.generated.openapi.model.TenantLoginProviderApiDto.SourceEnum;

@RequiredArgsConstructor
@ApplicationScoped
public class TenantLoginProviderCreateController {

  /**
   * @autogenerated CreateControllerGenerator
   */
  private final TenantLoginProviderCreateUsecase create;

  /**
   * @autogenerated CreateControllerGenerator
   */
  private final CurrentRequest currentRequest;

  /**
   * @autogenerated CreateControllerGenerator
   */
  private final Tracer tracer;

  /**
   * @autogenerated CreateControllerGenerator
   * @param tenantLoginProvider
   * @return
   */
  @Transactional
  public Response tenantLoginProviderApiCreate(TenantLoginProviderApiDto tenantLoginProvider) {
    Span span = tracer.spanBuilder("Api to create an entity of tenant login provider")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.SERVER).startSpan();
    try {
      TenantLoginProviderCreateProjection created =
          create.create(currentRequest.interaction(), toDomainModel(tenantLoginProvider));
      return Response.ok(toApiModel(created)).build();
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * @autogenerated CreateControllerGenerator
   * @param domainEnum
   * @return
   */
  private SourceEnum sourceEnumToApi(TenantLoginProviderSourceOptions domainEnum) {
    SourceEnum result;
    if (domainEnum == TenantLoginProviderSourceOptions.GOOGLE) {
      result = SourceEnum.GOOGLE;
    } else if (domainEnum == TenantLoginProviderSourceOptions.GITHUB) {
      result = SourceEnum.GITHUB;
    } else if (domainEnum == TenantLoginProviderSourceOptions.SAML) {
      result = SourceEnum.SAML;
    } else {
      result = null;
    }
    return result;
  }

  /**
   * @autogenerated CreateControllerGenerator
   * @param apiEnum
   * @return
   */
  private TenantLoginProviderSourceOptions sourceEnumToDomain(SourceEnum apiEnum) {
    TenantLoginProviderSourceOptions result;
    if (apiEnum == SourceEnum.GOOGLE) {
      result = TenantLoginProviderSourceOptions.GOOGLE;
    } else if (apiEnum == SourceEnum.GITHUB) {
      result = TenantLoginProviderSourceOptions.GITHUB;
    } else if (apiEnum == SourceEnum.SAML) {
      result = TenantLoginProviderSourceOptions.SAML;
    } else if (null == apiEnum) {
      result = null;
    } else {
      throw new IllegalArgumentException();
    }
    return result;
  }

  /**
   * @autogenerated CreateControllerGenerator
   * @param dto
   * @return
   */
  private TenantLoginProviderApiDto toApiModel(TenantLoginProviderCreateProjection dto) {
    Span span = tracer.spanBuilder(
        "Mapper to build api content to response from model for entity of tenant login provider")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      TenantLoginProviderApiDto tenantLoginProviderApiDto = new TenantLoginProviderApiDto();
      tenantLoginProviderApiDto.setUid(dto.getUid());
      tenantLoginProviderApiDto.setTenant(new TenantApiRef().$ref(dto.getTenantReference()));
      tenantLoginProviderApiDto.setName(dto.getName());
      tenantLoginProviderApiDto.setSource(sourceEnumToApi(dto.getSource()));
      tenantLoginProviderApiDto.setDisabled(dto.getDisabled());
      tenantLoginProviderApiDto.setDirectAccess(dto.getDirectAccess());
      tenantLoginProviderApiDto.setPublicKey(dto.getPublicKey());
      tenantLoginProviderApiDto.setPrivateKey(dto.getPrivateKey());
      tenantLoginProviderApiDto.setCertificate(dto.getCertificate());
      String metadata = dto.getMetadata();
      if (null != metadata) {
        tenantLoginProviderApiDto.setMetadata(currentRequest.getPublicHost()
            + "/api/access/login-providers/" + dto.getUidOrDefault("-") + "/metadata");
      }
      tenantLoginProviderApiDto.setUsersEnabledByDefault(dto.getUsersEnabledByDefault());
      tenantLoginProviderApiDto.setVersion(dto.getVersion());
      return tenantLoginProviderApiDto;
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }

  /**
   * @autogenerated CreateControllerGenerator
   * @param tenantLoginProviderApiDto
   * @return
   */
  private TenantLoginProviderCreateInput toDomainModel(
      TenantLoginProviderApiDto tenantLoginProviderApiDto) {
    Span span = tracer
        .spanBuilder(
            "Mapper to build model content to request from api for entity of tenant login provider")
        .setParent(Context.current().with(Span.current())).setSpanKind(SpanKind.INTERNAL)
        .startSpan();
    try {
      TenantLoginProviderCreateInput dto = new TenantLoginProviderCreateInput();
      if (null != tenantLoginProviderApiDto.getUid()) {
        dto.setUid(tenantLoginProviderApiDto.getUid());
      }
      if (null != tenantLoginProviderApiDto.getTenant()) {
        dto.setTenant(TenantReference.of(tenantLoginProviderApiDto.getTenant().get$Ref()));
      }
      if (null != tenantLoginProviderApiDto.getName()) {
        dto.setName(tenantLoginProviderApiDto.getName());
      }
      if (null != tenantLoginProviderApiDto.getSource()) {
        dto.setSource(sourceEnumToDomain(tenantLoginProviderApiDto.getSource()));
      }
      if (null != tenantLoginProviderApiDto.getDisabled()) {
        dto.setDisabled(tenantLoginProviderApiDto.getDisabled());
      }
      if (null != tenantLoginProviderApiDto.getDirectAccess()) {
        dto.setDirectAccess(tenantLoginProviderApiDto.getDirectAccess());
      }
      if (null != tenantLoginProviderApiDto.getPublicKey()) {
        dto.setPublicKey(tenantLoginProviderApiDto.getPublicKey());
      }
      if (null != tenantLoginProviderApiDto.getPrivateKey()) {
        dto.setPrivateKey(tenantLoginProviderApiDto.getPrivateKey());
      }
      if (null != tenantLoginProviderApiDto.getCertificate()) {
        dto.setCertificate(tenantLoginProviderApiDto.getCertificate());
      }
      if (!StringUtils.isBlank(tenantLoginProviderApiDto.getMetadata())) {
        String url = tenantLoginProviderApiDto.getMetadata();
        if (tenantLoginProviderApiDto.getMetadata().startsWith(
            currentRequest.getPublicHost() + "/api/access/login-providers/-/temp-metadata?temp=")) {
          dto.setMetadata("temp://" + (url.substring(
              (currentRequest.getPublicHost() + "/api/access/login-providers/-/temp-metadata?temp=")
                  .length())));
        } else if (!(url.equals(currentRequest.getPublicHost() + "/api/access/login-providers/"
            + tenantLoginProviderApiDto.getUid() + "/metadata"))) {
          dto.setMetadata(tenantLoginProviderApiDto.getMetadata());
        }
      }
      if (null != tenantLoginProviderApiDto.getUsersEnabledByDefault()) {
        dto.setUsersEnabledByDefault(tenantLoginProviderApiDto.getUsersEnabledByDefault());
      }
      if (null != tenantLoginProviderApiDto.getVersion()) {
        dto.setVersion(tenantLoginProviderApiDto.getVersion());
      }
      return dto;
    } catch (RuntimeException ex) {
      span.setAttribute("error", true);
      span.recordException(ex);
      throw ex;
    } finally {
      span.end();
    }
  }
}
