package net.civeira.phylax.features.access.tenant.application.usecase.update;

import java.util.Optional;
import java.util.function.UnaryOperator;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.With;
import net.civeira.phylax.common.security.Interaction;
import net.civeira.phylax.features.access.tenant.domain.TenantRef;

@Data
@Builder(toBuilder = true)
@With
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class TenantUpdateEnrich {

  /**
   * @autogenerated UpdateEnrichGenerator
   */
  @NonNull
  private final Interaction interaction;

  /**
   * @autogenerated UpdateEnrichGenerator
   */
  private final TenantRef reference;

  /**
   * @autogenerated UpdateEnrichGenerator
   */
  @NonNull
  private TenantUpdateInput input;

  /**
   * @autogenerated UpdateEnrichGenerator
   * @return
   */
  public Optional<TenantRef> getReference() {
    return Optional.ofNullable(reference);
  }

  /**
   * @autogenerated UpdateEnrichGenerator
   * @param mapper
   */
  public void map(UnaryOperator<TenantUpdateInput> mapper) {
    input = mapper.apply(input);
  }
}
