package net.civeira.phylax.features.access.userinvitation.domain;

import lombok.NoArgsConstructor;
import lombok.experimental.Delegate;
import net.civeira.phylax.common.value.Uuid;
import net.civeira.phylax.features.access.userinvitation.domain.valueholder.AcceptedAtValueHolder;
import net.civeira.phylax.features.access.userinvitation.domain.valueholder.AcceptedByValueHolder;
import net.civeira.phylax.features.access.userinvitation.domain.valueholder.CreatedAtValueHolder;
import net.civeira.phylax.features.access.userinvitation.domain.valueholder.EmailValueHolder;
import net.civeira.phylax.features.access.userinvitation.domain.valueholder.ExpiredAtValueHolder;
import net.civeira.phylax.features.access.userinvitation.domain.valueholder.InvitedByValueHolder;
import net.civeira.phylax.features.access.userinvitation.domain.valueholder.MetadataJsonValueHolder;
import net.civeira.phylax.features.access.userinvitation.domain.valueholder.RolesValueHolder;
import net.civeira.phylax.features.access.userinvitation.domain.valueholder.StatusValueHolder;
import net.civeira.phylax.features.access.userinvitation.domain.valueholder.TenantValueHolder;
import net.civeira.phylax.features.access.userinvitation.domain.valueholder.TokenHashValueHolder;
import net.civeira.phylax.features.access.userinvitation.domain.valueholder.UidValueHolder;
import net.civeira.phylax.features.access.userinvitation.domain.valueholder.VersionValueHolder;

/**
 * A dto transfer to hold user invitation attribute values
 */
@NoArgsConstructor
public class UserInvitationChangeSet {

  /**
   * El accepted at de user invitation
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private AcceptedAtValueHolder<UserInvitationChangeSet> acceptedAtValue =
      new AcceptedAtValueHolder<>(this);

  /**
   * El accepted by de user invitation
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private AcceptedByValueHolder<UserInvitationChangeSet> acceptedByValue =
      new AcceptedByValueHolder<>(this);

  /**
   * El created at de user invitation
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private CreatedAtValueHolder<UserInvitationChangeSet> createdAtValue =
      new CreatedAtValueHolder<>(this);

  /**
   * El email de user invitation
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private EmailValueHolder<UserInvitationChangeSet> emailValue = new EmailValueHolder<>(this);

  /**
   * El expired at de user invitation
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private ExpiredAtValueHolder<UserInvitationChangeSet> expiredAtValue =
      new ExpiredAtValueHolder<>(this);

  /**
   * El invited by de user invitation
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private InvitedByValueHolder<UserInvitationChangeSet> invitedByValue =
      new InvitedByValueHolder<>(this);

  /**
   * El metadata json de user invitation
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private MetadataJsonValueHolder<UserInvitationChangeSet> metadataJsonValue =
      new MetadataJsonValueHolder<>(this);

  /**
   * El roles de user invitation
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private RolesValueHolder<UserInvitationChangeSet> rolesValue = new RolesValueHolder<>(this);

  /**
   * El status de user invitation
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private StatusValueHolder<UserInvitationChangeSet> statusValue = new StatusValueHolder<>(this);

  /**
   * El tenant de user invitation
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private TenantValueHolder<UserInvitationChangeSet> tenantValue = new TenantValueHolder<>(this);

  /**
   * El token hash de user invitation
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private TokenHashValueHolder<UserInvitationChangeSet> tokenHashValue =
      new TokenHashValueHolder<>(this);

  /**
   * A number to identify the db record
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private UidValueHolder<UserInvitationChangeSet> uidValue = new UidValueHolder<>(this);

  /**
   * Campo con el número de version de user invitation para controlar bloqueos optimistas
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private VersionValueHolder<UserInvitationChangeSet> versionValue = new VersionValueHolder<>(this);

  /**
   * @autogenerated EntityChangeSetGenerator
   * @return
   */
  public UserInvitationChangeSet newUid() {
    return version(0).uid(Uuid.comb().toString());
  }

  /**
   * Unset a value by the property name. Unset values will no provide command change neither provide
   * information to the output context (hidden or readonly fields, or policy restrictions).
   *
   * @autogenerated EntityChangeSetGenerator
   * @param field The field name to unset.
   */
  public void unset(final String field) {
    uidValue.unsetUidIfMatches(field);
    tenantValue.unsetTenantIfMatches(field);
    emailValue.unsetEmailIfMatches(field);
    rolesValue.unsetRolesIfMatches(field);
    invitedByValue.unsetInvitedByIfMatches(field);
    tokenHashValue.unsetTokenHashIfMatches(field);
    metadataJsonValue.unsetMetadataJsonIfMatches(field);
    statusValue.unsetStatusIfMatches(field);
    createdAtValue.unsetCreatedAtIfMatches(field);
    expiredAtValue.unsetExpiredAtIfMatches(field);
    acceptedAtValue.unsetAcceptedAtIfMatches(field);
    acceptedByValue.unsetAcceptedByIfMatches(field);
    versionValue.unsetVersionIfMatches(field);
  }
}
