package net.civeira.phylax.features.access.trustedclient.domain;

import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import net.civeira.phylax.common.crypto.AesCipherService;

class TrustedClientChangeSetUnitTest {

  /**
   * @autogenerated CachedGenerator
   */
  @Test
  @DisplayName("Test a entity reference contruction")
  void test_trusted_client_change_set_builder() {
    AesCipherService cypher = Mockito.mock(AesCipherService.class);
    TrustedClientChangeSet one = TrustedClientChangeSet.builder().uid("one").code("one")
        .publicAllow(true).secretOauth("one").enabled(true)
        .allowedRedirects(
            List.of(AllowedRedirects.builder().uid("one").url("one").version(1).build()))
        .version(1).newUid().build();
    one.setUid("two");
    Assertions.assertEquals("two", one.getUid().get().getUid(),
        "Value must equals to the assigned value");
    one.unset("uid");
    Assertions.assertFalse(one.getUid().isPresent(), "After unset, the valeue must be dissapear");
    Assertions.assertEquals("one", one.getCode().get().getCode(),
        "Value must equals to the intial value");
    one.setCode("two");
    Assertions.assertEquals("two", one.getCode().get().getCode(),
        "Value must equals to the assigned value");
    one.unset("code");
    Assertions.assertFalse(one.getCode().isPresent(), "After unset, the valeue must be dissapear");
    Assertions.assertEquals(true, one.getPublicAllow().get().isPublicAllow(),
        "Value must equals to the intial value");
    one.setPublicAllow(false);
    Assertions.assertEquals(false, one.getPublicAllow().get().isPublicAllow(),
        "Value must equals to the assigned value");
    one.unset("publicAllow");
    Assertions.assertFalse(one.getPublicAllow().isPresent(),
        "After unset, the valeue must be dissapear");
    Assertions.assertEquals("one", one.getSecretOauth().get().getPlainSecretOauth(cypher).get(),
        "Value must equals to the intial value");
    one.setSecretOauth("two");
    Assertions.assertEquals("two", one.getSecretOauth().get().getPlainSecretOauth(cypher).get(),
        "Value must equals to the assigned value");
    one.unset("secretOauth");
    Assertions.assertFalse(one.getSecretOauth().isPresent(),
        "After unset, the valeue must be dissapear");
    Assertions.assertEquals(true, one.getEnabled().get().isEnabled(),
        "Value must equals to the intial value");
    one.setEnabled(false);
    Assertions.assertEquals(false, one.getEnabled().get().isEnabled(),
        "Value must equals to the assigned value");
    one.unset("enabled");
    Assertions.assertFalse(one.getEnabled().isPresent(),
        "After unset, the valeue must be dissapear");
    Assertions.assertEquals(
        List.of(AllowedRedirects.builder().uid("one").url("one").version(1).build()),
        one.getAllowedRedirects().get().getAllowedRedirects(),
        "Value must equals to the intial value");
    one.setAllowedRedirects(
        List.of(AllowedRedirects.builder().uid("two").url("two").version(2).build()));
    Assertions.assertEquals(
        List.of(AllowedRedirects.builder().uid("two").url("two").version(2).build()),
        one.getAllowedRedirects().get().getAllowedRedirects(),
        "Value must equals to the assigned value");
    one.unset("allowedRedirects");
    Assertions.assertFalse(one.getAllowedRedirects().isPresent(),
        "After unset, the valeue must be dissapear");
    Assertions.assertEquals(0, one.getVersion().get().getVersion().get(),
        "Value must equals to the intial value");
    one.setVersion(2);
    Assertions.assertEquals(2, one.getVersion().get().getVersion().get(),
        "Value must equals to the assigned value");
    one.unset("version");
    Assertions.assertFalse(one.getVersion().isPresent(),
        "After unset, the valeue must be dissapear");
  }
}
