package net.civeira.phylax.features.access.trustedclient.application.usecase.create;

import java.util.List;
import java.util.Optional;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import net.civeira.phylax.common.crypto.AesCipherService;
import net.civeira.phylax.features.access.trustedclient.application.visibility.TrustedClientVisibleProjection;
import net.civeira.phylax.features.access.trustedclient.domain.AllowedRedirects;
import net.civeira.phylax.features.access.trustedclient.domain.TrustedClient;
import net.civeira.phylax.features.access.trustedclient.domain.valueobject.AllowAllScopesVO;
import net.civeira.phylax.features.access.trustedclient.domain.valueobject.AllowedRedirectsVO;
import net.civeira.phylax.features.access.trustedclient.domain.valueobject.BackChannelLogoutSessionRequiredVO;
import net.civeira.phylax.features.access.trustedclient.domain.valueobject.BackChannelLogoutUriVO;
import net.civeira.phylax.features.access.trustedclient.domain.valueobject.CodeVO;
import net.civeira.phylax.features.access.trustedclient.domain.valueobject.EnabledVO;
import net.civeira.phylax.features.access.trustedclient.domain.valueobject.FrontChannelLogoutSessionRequiredVO;
import net.civeira.phylax.features.access.trustedclient.domain.valueobject.FrontChannelLogoutUriVO;
import net.civeira.phylax.features.access.trustedclient.domain.valueobject.PublicAllowVO;
import net.civeira.phylax.features.access.trustedclient.domain.valueobject.SecretOauthVO;
import net.civeira.phylax.features.access.trustedclient.domain.valueobject.UidVO;
import net.civeira.phylax.features.access.trustedclient.domain.valueobject.VersionVO;

/**
 * A dto transfer to hold trusted client attribute values
 */
@NoArgsConstructor(access = AccessLevel.PRIVATE)
@Getter
public class TrustedClientCreateProjection {

  /**
   * Create a dto instance with all the values of an entity
   *
   * @autogenerated CreateProjectionGenerator
   * @param visible The entity who provide values.
   * @return
   */
  public static TrustedClientCreateProjection from(final TrustedClientVisibleProjection visible) {
    TrustedClientCreateProjection instance = new TrustedClientCreateProjection();
    instance.uidValue = visible.getUid();
    instance.codeValue = visible.getCode();
    instance.allowAllScopesValue = visible.getAllowAllScopes();
    instance.publicAllowValue = visible.getPublicAllow();
    instance.secretOauthValue = visible.getSecretOauth();
    instance.backChannelLogoutUriValue = visible.getBackChannelLogoutUri();
    instance.backChannelLogoutSessionRequiredValue = visible.getBackChannelLogoutSessionRequired();
    instance.frontChannelLogoutUriValue = visible.getFrontChannelLogoutUri();
    instance.frontChannelLogoutSessionRequiredValue =
        visible.getFrontChannelLogoutSessionRequired();
    instance.enabledValue = visible.getEnabled();
    instance.allowedRedirectsValue = visible.getAllowedRedirects();
    instance.versionValue = visible.getVersion();
    return instance;
  }

  /**
   * El allow all scopes de trusted client
   *
   * @autogenerated CreateProjectionGenerator
   */
  private Optional<AllowAllScopesVO> allowAllScopesValue;

  /**
   * El allowed redirects de trusted client
   *
   * @autogenerated CreateProjectionGenerator
   */
  private Optional<AllowedRedirectsVO> allowedRedirectsValue;

  /**
   * El back channel logout session required de trusted client
   *
   * @autogenerated CreateProjectionGenerator
   */
  private Optional<BackChannelLogoutSessionRequiredVO> backChannelLogoutSessionRequiredValue;

  /**
   * El back channel logout uri de trusted client
   *
   * @autogenerated CreateProjectionGenerator
   */
  private Optional<BackChannelLogoutUriVO> backChannelLogoutUriValue;

  /**
   * El código identificativo de la aplicación
   *
   * @autogenerated CreateProjectionGenerator
   */
  private Optional<CodeVO> codeValue;

  /**
   * The indicator to allow the account be used without deleting it
   *
   * @autogenerated CreateProjectionGenerator
   */
  private Optional<EnabledVO> enabledValue;

  /**
   * El front channel logout session required de trusted client
   *
   * @autogenerated CreateProjectionGenerator
   */
  private Optional<FrontChannelLogoutSessionRequiredVO> frontChannelLogoutSessionRequiredValue;

  /**
   * El front channel logout uri de trusted client
   *
   * @autogenerated CreateProjectionGenerator
   */
  private Optional<FrontChannelLogoutUriVO> frontChannelLogoutUriValue;

  /**
   * If true, users can use these client to access with public code flow
   *
   * @autogenerated CreateProjectionGenerator
   */
  private Optional<PublicAllowVO> publicAllowValue;

  /**
   * If the user is not delegated, the phrasse to identify
   *
   * @autogenerated CreateProjectionGenerator
   */
  private Optional<SecretOauthVO> secretOauthValue;

  /**
   * El identificador de la aplicacion
   *
   * @autogenerated CreateProjectionGenerator
   */
  private Optional<UidVO> uidValue;

  /**
   * Campo con el número de version de trusted client para controlar bloqueos optimistas
   *
   * @autogenerated CreateProjectionGenerator
   */
  private Optional<VersionVO> versionValue;

  /**
   * Create a dto instance with all the values of an entity
   *
   * @autogenerated CreateProjectionGenerator
   * @param entity The entity who provide values.
   */
  public TrustedClientCreateProjection(final TrustedClient entity) {
    uidValue = Optional.of(entity.getUidValue());
    codeValue = Optional.of(entity.getCodeValue());
    allowAllScopesValue = Optional.of(entity.getAllowAllScopesValue());
    publicAllowValue = Optional.of(entity.getPublicAllowValue());
    secretOauthValue = Optional.of(entity.getSecretOauthValue());
    backChannelLogoutUriValue = Optional.of(entity.getBackChannelLogoutUriValue());
    backChannelLogoutSessionRequiredValue =
        Optional.of(entity.getBackChannelLogoutSessionRequiredValue());
    frontChannelLogoutUriValue = Optional.of(entity.getFrontChannelLogoutUriValue());
    frontChannelLogoutSessionRequiredValue =
        Optional.of(entity.getFrontChannelLogoutSessionRequiredValue());
    enabledValue = Optional.of(entity.getEnabledValue());
    allowedRedirectsValue = Optional.of(entity.getAllowedRedirectsValue());
    versionValue = Optional.of(entity.getVersionValue());
  }

  /**
   * Inform for a possible change propolsal in AllowAllScopes
   *
   * @autogenerated CreateProjectionGenerator
   * @return empty if there is no change proposal for AllowAllScopes, otherwise the value for
   *         AllowAllScopes
   */
  public Boolean getAllowAllScopes() {
    return getAllowAllScopesOrDefault(null);
  }

  /**
   * Inform for a possible change propolsal in AllowAllScopes
   *
   * @autogenerated CreateProjectionGenerator
   * @param orDefault Default value if is null
   * @return empty if there is no change proposal for AllowAllScopes, otherwise the value for
   *         AllowAllScopes
   */
  public Boolean getAllowAllScopesOrDefault(final Boolean orDefault) {
    return allowAllScopesValue.map(AllowAllScopesVO::isAllowAllScopes).orElse(orDefault);
  }

  /**
   * Inform for a possible change propolsal in AllowedRedirects
   *
   * @autogenerated CreateProjectionGenerator
   * @return empty if there is no change proposal for AllowedRedirects, otherwise the value for
   *         AllowedRedirects
   */
  public List<AllowedRedirects> getAllowedRedirects() {
    return allowedRedirectsValue.map(AllowedRedirectsVO::getAllowedRedirects).orElseGet(List::of);
  }

  /**
   * Inform for a possible change propolsal in BackChannelLogoutSessionRequired
   *
   * @autogenerated CreateProjectionGenerator
   * @return empty if there is no change proposal for BackChannelLogoutSessionRequired, otherwise
   *         the value for BackChannelLogoutSessionRequired
   */
  public Boolean getBackChannelLogoutSessionRequired() {
    return getBackChannelLogoutSessionRequiredOrDefault(null);
  }

  /**
   * Inform for a possible change propolsal in BackChannelLogoutSessionRequired
   *
   * @autogenerated CreateProjectionGenerator
   * @param orDefault Default value if is null
   * @return empty if there is no change proposal for BackChannelLogoutSessionRequired, otherwise
   *         the value for BackChannelLogoutSessionRequired
   */
  public Boolean getBackChannelLogoutSessionRequiredOrDefault(final Boolean orDefault) {
    return backChannelLogoutSessionRequiredValue
        .map(BackChannelLogoutSessionRequiredVO::isBackChannelLogoutSessionRequired)
        .orElse(orDefault);
  }

  /**
   * Inform for a possible change propolsal in BackChannelLogoutUri
   *
   * @autogenerated CreateProjectionGenerator
   * @return empty if there is no change proposal for BackChannelLogoutUri, otherwise the value for
   *         BackChannelLogoutUri
   */
  public String getBackChannelLogoutUri() {
    return getBackChannelLogoutUriOrDefault(null);
  }

  /**
   * Inform for a possible change propolsal in BackChannelLogoutUri
   *
   * @autogenerated CreateProjectionGenerator
   * @param orDefault Default value if is null
   * @return empty if there is no change proposal for BackChannelLogoutUri, otherwise the value for
   *         BackChannelLogoutUri
   */
  public String getBackChannelLogoutUriOrDefault(final String orDefault) {
    return backChannelLogoutUriValue.flatMap(BackChannelLogoutUriVO::getBackChannelLogoutUri)
        .orElse(orDefault);
  }

  /**
   * Inform for a possible change propolsal in Code
   *
   * @autogenerated CreateProjectionGenerator
   * @return empty if there is no change proposal for Code, otherwise the value for Code
   */
  public String getCode() {
    return getCodeOrDefault(null);
  }

  /**
   * Inform for a possible change propolsal in Code
   *
   * @autogenerated CreateProjectionGenerator
   * @param orDefault Default value if is null
   * @return empty if there is no change proposal for Code, otherwise the value for Code
   */
  public String getCodeOrDefault(final String orDefault) {
    return codeValue.map(CodeVO::getCode).orElse(orDefault);
  }

  /**
   * Inform for a possible change propolsal in Enabled
   *
   * @autogenerated CreateProjectionGenerator
   * @return empty if there is no change proposal for Enabled, otherwise the value for Enabled
   */
  public Boolean getEnabled() {
    return getEnabledOrDefault(null);
  }

  /**
   * Inform for a possible change propolsal in Enabled
   *
   * @autogenerated CreateProjectionGenerator
   * @param orDefault Default value if is null
   * @return empty if there is no change proposal for Enabled, otherwise the value for Enabled
   */
  public Boolean getEnabledOrDefault(final Boolean orDefault) {
    return enabledValue.map(EnabledVO::isEnabled).orElse(orDefault);
  }

  /**
   * Inform for a possible change propolsal in FrontChannelLogoutSessionRequired
   *
   * @autogenerated CreateProjectionGenerator
   * @return empty if there is no change proposal for FrontChannelLogoutSessionRequired, otherwise
   *         the value for FrontChannelLogoutSessionRequired
   */
  public Boolean getFrontChannelLogoutSessionRequired() {
    return getFrontChannelLogoutSessionRequiredOrDefault(null);
  }

  /**
   * Inform for a possible change propolsal in FrontChannelLogoutSessionRequired
   *
   * @autogenerated CreateProjectionGenerator
   * @param orDefault Default value if is null
   * @return empty if there is no change proposal for FrontChannelLogoutSessionRequired, otherwise
   *         the value for FrontChannelLogoutSessionRequired
   */
  public Boolean getFrontChannelLogoutSessionRequiredOrDefault(final Boolean orDefault) {
    return frontChannelLogoutSessionRequiredValue
        .map(FrontChannelLogoutSessionRequiredVO::isFrontChannelLogoutSessionRequired)
        .orElse(orDefault);
  }

  /**
   * Inform for a possible change propolsal in FrontChannelLogoutUri
   *
   * @autogenerated CreateProjectionGenerator
   * @return empty if there is no change proposal for FrontChannelLogoutUri, otherwise the value for
   *         FrontChannelLogoutUri
   */
  public String getFrontChannelLogoutUri() {
    return getFrontChannelLogoutUriOrDefault(null);
  }

  /**
   * Inform for a possible change propolsal in FrontChannelLogoutUri
   *
   * @autogenerated CreateProjectionGenerator
   * @param orDefault Default value if is null
   * @return empty if there is no change proposal for FrontChannelLogoutUri, otherwise the value for
   *         FrontChannelLogoutUri
   */
  public String getFrontChannelLogoutUriOrDefault(final String orDefault) {
    return frontChannelLogoutUriValue.flatMap(FrontChannelLogoutUriVO::getFrontChannelLogoutUri)
        .orElse(orDefault);
  }

  /**
   * Inform for a possible change propolsal in PublicAllow
   *
   * @autogenerated CreateProjectionGenerator
   * @return empty if there is no change proposal for PublicAllow, otherwise the value for
   *         PublicAllow
   */
  public Boolean getPublicAllow() {
    return getPublicAllowOrDefault(null);
  }

  /**
   * Inform for a possible change propolsal in PublicAllow
   *
   * @autogenerated CreateProjectionGenerator
   * @param orDefault Default value if is null
   * @return empty if there is no change proposal for PublicAllow, otherwise the value for
   *         PublicAllow
   */
  public Boolean getPublicAllowOrDefault(final Boolean orDefault) {
    return publicAllowValue.map(PublicAllowVO::isPublicAllow).orElse(orDefault);
  }

  /**
   * Inform for a possible change propolsal in SecretOauth
   *
   * @autogenerated CreateProjectionGenerator
   * @param cypher
   * @return empty if there is no change proposal for SecretOauth, otherwise the value for
   *         SecretOauth
   */
  public String getSecretOauthCyphered(final AesCipherService cypher) {
    return getSecretOauthCypheredOrDefault(cypher, null);
  }

  /**
   * Inform for a possible change propolsal in SecretOauth
   *
   * @autogenerated CreateProjectionGenerator
   * @param cypher
   * @param orDefault Default value if is null
   * @return empty if there is no change proposal for SecretOauth, otherwise the value for
   *         SecretOauth
   */
  public String getSecretOauthCypheredOrDefault(final AesCipherService cypher,
      final String orDefault) {
    return secretOauthValue.flatMap(vo -> vo.getSecretOauthCyphered(cypher)).orElse(orDefault);
  }

  /**
   * Inform for a possible change propolsal in SecretOauth
   *
   * @autogenerated CreateProjectionGenerator
   * @param cypher
   * @return empty if there is no change proposal for SecretOauth, otherwise the value for
   *         SecretOauth
   */
  public String getSecretOauthPlain(final AesCipherService cypher) {
    return getSecretOauthPlainOrDefault(cypher, null);
  }

  /**
   * Inform for a possible change propolsal in SecretOauth
   *
   * @autogenerated CreateProjectionGenerator
   * @param cypher
   * @param orDefault Default value if is null
   * @return empty if there is no change proposal for SecretOauth, otherwise the value for
   *         SecretOauth
   */
  public String getSecretOauthPlainOrDefault(final AesCipherService cypher,
      final String orDefault) {
    return secretOauthValue.flatMap(vo -> vo.getSecretOauthPlain(cypher)).orElse(orDefault);
  }

  /**
   * Inform for a possible change propolsal in Uid
   *
   * @autogenerated CreateProjectionGenerator
   * @return empty if there is no change proposal for Uid, otherwise the value for Uid
   */
  public String getUid() {
    return getUidOrDefault(null);
  }

  /**
   * Inform for a possible change propolsal in Uid
   *
   * @autogenerated CreateProjectionGenerator
   * @param orDefault Default value if is null
   * @return empty if there is no change proposal for Uid, otherwise the value for Uid
   */
  public String getUidOrDefault(final String orDefault) {
    return uidValue.map(UidVO::getUid).orElse(orDefault);
  }

  /**
   * Inform for a possible change propolsal in Version
   *
   * @autogenerated CreateProjectionGenerator
   * @return empty if there is no change proposal for Version, otherwise the value for Version
   */
  public Integer getVersion() {
    return getVersionOrDefault(null);
  }

  /**
   * Inform for a possible change propolsal in Version
   *
   * @autogenerated CreateProjectionGenerator
   * @param orDefault Default value if is null
   * @return empty if there is no change proposal for Version, otherwise the value for Version
   */
  public Integer getVersionOrDefault(final Integer orDefault) {
    return versionValue.flatMap(VersionVO::getVersion).orElse(orDefault);
  }
}
