package net.civeira.phylax.features.access.userroleassignament.infrastructure.repository;

import java.util.Iterator;
import java.util.List;
import java.util.function.BiFunction;

import net.civeira.phylax.common.algorithms.Slider;
import net.civeira.phylax.features.access.userroleassignament.domain.UserRoleAssignament;
import net.civeira.phylax.features.access.userroleassignament.domain.gateway.UserRoleAssignamentCursor;
import net.civeira.phylax.features.access.userroleassignament.domain.gateway.UserRoleAssignamentFilter;

class UserRoleAssignamentSlider extends Slider<UserRoleAssignament> {

  /**
   * @autogenerated SlideGenerator
   */
  private final UserRoleAssignamentCursor cursor;

  /**
   * @autogenerated SlideGenerator
   */
  private final UserRoleAssignamentFilter filter;

  /**
   * @autogenerated SlideGenerator
   */
  private final BiFunction<UserRoleAssignamentFilter, UserRoleAssignamentCursor, Iterator<UserRoleAssignament>> gateway;

  /**
   * @autogenerated SlideGenerator
   * @param multi
   * @param limit
   * @param gateway
   * @param filter
   * @param cursor
   */
  UserRoleAssignamentSlider(final Iterator<UserRoleAssignament> multi, final int limit,
      final BiFunction<UserRoleAssignamentFilter, UserRoleAssignamentCursor, Iterator<UserRoleAssignament>> gateway,
      final UserRoleAssignamentFilter filter, final UserRoleAssignamentCursor cursor) {
    super(multi, limit);
    this.gateway = gateway;
    this.filter = filter;
    this.cursor = cursor;
  }

  /**
   * @autogenerated SlideGenerator
   * @param userRoleAssignaments
   * @param limit
   * @return
   */
  @Override
  public Iterator<UserRoleAssignament> next(List<UserRoleAssignament> userRoleAssignaments,
      int limit) {
    UserRoleAssignament last = userRoleAssignaments.get(userRoleAssignaments.size() - 1);
    UserRoleAssignamentCursor cr = this.cursor.withSinceUid(last.getUid()).withLimit(limit);
    return gateway.apply(this.filter, cr);
  }
}
