package net.civeira.phylax.features.access.userpersonalapikey.application.usecase.update;

import java.time.OffsetDateTime;
import java.util.Optional;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import net.civeira.phylax.common.value.Uuid;
import net.civeira.phylax.features.access.user.domain.UserRef;
import net.civeira.phylax.features.access.userpersonalapikey.domain.UserPersonalApiKeyChangeSet;
import net.civeira.phylax.features.access.userpersonalapikey.domain.valueobject.CreatedAtVO;
import net.civeira.phylax.features.access.userpersonalapikey.domain.valueobject.EnabledVO;
import net.civeira.phylax.features.access.userpersonalapikey.domain.valueobject.ExpiresAtVO;
import net.civeira.phylax.features.access.userpersonalapikey.domain.valueobject.KeyHashVO;
import net.civeira.phylax.features.access.userpersonalapikey.domain.valueobject.LastUsedAtVO;
import net.civeira.phylax.features.access.userpersonalapikey.domain.valueobject.NameVO;
import net.civeira.phylax.features.access.userpersonalapikey.domain.valueobject.ScopesVO;
import net.civeira.phylax.features.access.userpersonalapikey.domain.valueobject.UidVO;
import net.civeira.phylax.features.access.userpersonalapikey.domain.valueobject.UserVO;
import net.civeira.phylax.features.access.userpersonalapikey.domain.valueobject.VersionVO;

/**
 * A dto transfer to hold user personal api key attribute values
 */
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UserPersonalApiKeyUpdateInput {

  /**
   * @autogenerated UpdateInputGenerator
   */
  public static class UserPersonalApiKeyUpdateInputBuilder {

    /**
     * Append CreatedAt crud value and convert as value object.
     *
     * @autogenerated UpdateInputGenerator
     * @param createdAt The CreatedAt value to wrap in a value object.
     * @return Self instance to continue with a flow build
     */
    public UserPersonalApiKeyUpdateInputBuilder createdAt(final OffsetDateTime createdAt) {
      return createdAt(Optional.of(CreatedAtVO.from(createdAt)));
    }

    /**
     * Append CreatedAt value
     *
     * @autogenerated UpdateInputGenerator
     * @param createdAt The value object with the information.
     * @return Self instance to continue with a flow build
     */
    public UserPersonalApiKeyUpdateInputBuilder createdAt(final Optional<CreatedAtVO> createdAt) {
      this.createdAt$value = createdAt;
      this.createdAt$set = true;
      return this;
    }

    /**
     * Append Enabled crud value and convert as value object.
     *
     * @autogenerated UpdateInputGenerator
     * @param enabled The Enabled value to wrap in a value object.
     * @return Self instance to continue with a flow build
     */
    public UserPersonalApiKeyUpdateInputBuilder enabled(final Boolean enabled) {
      return enabled(Optional.of(EnabledVO.from(enabled)));
    }

    /**
     * Append Enabled value
     *
     * @autogenerated UpdateInputGenerator
     * @param enabled The value object with the information.
     * @return Self instance to continue with a flow build
     */
    public UserPersonalApiKeyUpdateInputBuilder enabled(final Optional<EnabledVO> enabled) {
      this.enabled$value = enabled;
      this.enabled$set = true;
      return this;
    }

    /**
     * Append ExpiresAt crud value and convert as value object.
     *
     * @autogenerated UpdateInputGenerator
     * @param expiresAt The ExpiresAt value to wrap in a value object.
     * @return Self instance to continue with a flow build
     */
    public UserPersonalApiKeyUpdateInputBuilder expiresAt(final OffsetDateTime expiresAt) {
      return expiresAt(Optional.of(ExpiresAtVO.from(expiresAt)));
    }

    /**
     * Append ExpiresAt value
     *
     * @autogenerated UpdateInputGenerator
     * @param expiresAt The value object with the information.
     * @return Self instance to continue with a flow build
     */
    public UserPersonalApiKeyUpdateInputBuilder expiresAt(final Optional<ExpiresAtVO> expiresAt) {
      this.expiresAt$value = expiresAt;
      this.expiresAt$set = true;
      return this;
    }

    /**
     * Append KeyHash crud value and convert as value object.
     *
     * @autogenerated UpdateInputGenerator
     * @param keyHash The KeyHash value to wrap in a value object.
     * @return Self instance to continue with a flow build
     */
    public UserPersonalApiKeyUpdateInputBuilder keyHash(final String keyHash) {
      return keyHash(Optional.of(KeyHashVO.from(keyHash)));
    }

    /**
     * Append KeyHash value
     *
     * @autogenerated UpdateInputGenerator
     * @param keyHash The value object with the information.
     * @return Self instance to continue with a flow build
     */
    public UserPersonalApiKeyUpdateInputBuilder keyHash(final Optional<KeyHashVO> keyHash) {
      this.keyHash$value = keyHash;
      this.keyHash$set = true;
      return this;
    }

    /**
     * Append LastUsedAt crud value and convert as value object.
     *
     * @autogenerated UpdateInputGenerator
     * @param lastUsedAt The LastUsedAt value to wrap in a value object.
     * @return Self instance to continue with a flow build
     */
    public UserPersonalApiKeyUpdateInputBuilder lastUsedAt(final OffsetDateTime lastUsedAt) {
      return lastUsedAt(Optional.of(LastUsedAtVO.from(lastUsedAt)));
    }

    /**
     * Append LastUsedAt value
     *
     * @autogenerated UpdateInputGenerator
     * @param lastUsedAt The value object with the information.
     * @return Self instance to continue with a flow build
     */
    public UserPersonalApiKeyUpdateInputBuilder lastUsedAt(
        final Optional<LastUsedAtVO> lastUsedAt) {
      this.lastUsedAt$value = lastUsedAt;
      this.lastUsedAt$set = true;
      return this;
    }

    /**
     * Append Name crud value and convert as value object.
     *
     * @autogenerated UpdateInputGenerator
     * @param name The Name value to wrap in a value object.
     * @return Self instance to continue with a flow build
     */
    public UserPersonalApiKeyUpdateInputBuilder name(final String name) {
      return name(Optional.of(NameVO.from(name)));
    }

    /**
     * Append Name value
     *
     * @autogenerated UpdateInputGenerator
     * @param name The value object with the information.
     * @return Self instance to continue with a flow build
     */
    public UserPersonalApiKeyUpdateInputBuilder name(final Optional<NameVO> name) {
      this.name$value = name;
      this.name$set = true;
      return this;
    }

    /**
     * @autogenerated UpdateInputGenerator
     * @return
     */
    public UserPersonalApiKeyUpdateInputBuilder newUid() {
      return version(0).uid(Uuid.comb().toString());
    }

    /**
     * Append Scopes crud value and convert as value object.
     *
     * @autogenerated UpdateInputGenerator
     * @param scopes The Scopes value to wrap in a value object.
     * @return Self instance to continue with a flow build
     */
    public UserPersonalApiKeyUpdateInputBuilder scopes(final String scopes) {
      return scopes(Optional.of(ScopesVO.from(scopes)));
    }

    /**
     * Append Scopes value
     *
     * @autogenerated UpdateInputGenerator
     * @param scopes The value object with the information.
     * @return Self instance to continue with a flow build
     */
    public UserPersonalApiKeyUpdateInputBuilder scopes(final Optional<ScopesVO> scopes) {
      this.scopes$value = scopes;
      this.scopes$set = true;
      return this;
    }

    /**
     * Append Uid crud value and convert as value object.
     *
     * @autogenerated UpdateInputGenerator
     * @param uid The Uid value to wrap in a value object.
     * @return Self instance to continue with a flow build
     */
    public UserPersonalApiKeyUpdateInputBuilder uid(final String uid) {
      return uid(Optional.of(UidVO.from(uid)));
    }

    /**
     * Append Uid value
     *
     * @autogenerated UpdateInputGenerator
     * @param uid The value object with the information.
     * @return Self instance to continue with a flow build
     */
    public UserPersonalApiKeyUpdateInputBuilder uid(final Optional<UidVO> uid) {
      this.uid$value = uid;
      this.uid$set = true;
      return this;
    }

    /**
     * Append User crud value and convert as value object.
     *
     * @autogenerated UpdateInputGenerator
     * @param user The User value to wrap in a value object.
     * @return Self instance to continue with a flow build
     */
    public UserPersonalApiKeyUpdateInputBuilder user(final UserRef user) {
      return user(Optional.of(UserVO.from(user)));
    }

    /**
     * Append User value
     *
     * @autogenerated UpdateInputGenerator
     * @param user The value object with the information.
     * @return Self instance to continue with a flow build
     */
    public UserPersonalApiKeyUpdateInputBuilder user(final Optional<UserVO> user) {
      this.user$value = user;
      this.user$set = true;
      return this;
    }

    /**
     * Append Version crud value and convert as value object.
     *
     * @autogenerated UpdateInputGenerator
     * @param version The Version value to wrap in a value object.
     * @return Self instance to continue with a flow build
     */
    public UserPersonalApiKeyUpdateInputBuilder version(final Integer version) {
      return version(Optional.of(VersionVO.from(version)));
    }

    /**
     * Append Version value
     *
     * @autogenerated UpdateInputGenerator
     * @param version The value object with the information.
     * @return Self instance to continue with a flow build
     */
    public UserPersonalApiKeyUpdateInputBuilder version(final Optional<VersionVO> version) {
      this.version$value = version;
      this.version$set = true;
      return this;
    }
  }

  /**
   * @autogenerated UpdateInputGenerator
   * @param input
   * @return
   */
  static UserPersonalApiKeyUpdateInput fromChangeSet(final UserPersonalApiKeyChangeSet input) {
    return UserPersonalApiKeyUpdateInput.builder().uid(input.getUidValue())
        .user(input.getUserValue()).name(input.getNameValue()).keyHash(input.getKeyHashValue())
        .scopes(input.getScopesValue()).lastUsedAt(input.getLastUsedAtValue())
        .expiresAt(input.getExpiresAtValue()).createdAt(input.getCreatedAtValue())
        .enabled(input.getEnabledValue()).version(input.getVersionValue()).build();
  }

  /**
   * El created at de user personal api key
   *
   * @autogenerated UpdateInputGenerator
   */
  @Builder.Default
  private Optional<CreatedAtVO> createdAt = Optional.empty();

  /**
   * El enabled de user personal api key
   *
   * @autogenerated UpdateInputGenerator
   */
  @Builder.Default
  private Optional<EnabledVO> enabled = Optional.empty();

  /**
   * Optional expiry. Null means the key does not expire.
   *
   * @autogenerated UpdateInputGenerator
   */
  @Builder.Default
  private Optional<ExpiresAtVO> expiresAt = Optional.empty();

  /**
   * SHA-256 hex digest of the raw key. Never stored in plain text.
   *
   * @autogenerated UpdateInputGenerator
   */
  @Builder.Default
  private Optional<KeyHashVO> keyHash = Optional.empty();

  /**
   * Timestamp of the most recent successful authentication.
   *
   * @autogenerated UpdateInputGenerator
   */
  @Builder.Default
  private Optional<LastUsedAtVO> lastUsedAt = Optional.empty();

  /**
   * A label to identify the key (e.g. 'CI pipeline', 'local dev').
   *
   * @autogenerated UpdateInputGenerator
   */
  @Builder.Default
  private Optional<NameVO> name = Optional.empty();

  /**
   * Space-separated OAuth scopes granted to this key.
   *
   * @autogenerated UpdateInputGenerator
   */
  @Builder.Default
  private Optional<ScopesVO> scopes = Optional.empty();

  /**
   * El uid de user personal api key
   *
   * @autogenerated UpdateInputGenerator
   */
  @Builder.Default
  private Optional<UidVO> uid = Optional.empty();

  /**
   * El user de user personal api key
   *
   * @autogenerated UpdateInputGenerator
   */
  @Builder.Default
  private Optional<UserVO> user = Optional.empty();

  /**
   * Campo con el número de version de user personal api key para controlar bloqueos optimistas
   *
   * @autogenerated UpdateInputGenerator
   */
  @Builder.Default
  private Optional<VersionVO> version = Optional.empty();

  /**
   * Inform for a possible change propolsal in CreatedAt
   *
   * @autogenerated UpdateInputGenerator
   * @return empty if there is no change proposal for CreatedAt, otherwise the value for CreatedAt
   */
  public Optional<CreatedAtVO> getCreatedAt() {
    return createdAt;
  }

  /**
   * Inform for a possible change propolsal in Enabled
   *
   * @autogenerated UpdateInputGenerator
   * @return empty if there is no change proposal for Enabled, otherwise the value for Enabled
   */
  public Optional<EnabledVO> getEnabled() {
    return enabled;
  }

  /**
   * Inform for a possible change propolsal in ExpiresAt
   *
   * @autogenerated UpdateInputGenerator
   * @return empty if there is no change proposal for ExpiresAt, otherwise the value for ExpiresAt
   */
  public Optional<ExpiresAtVO> getExpiresAt() {
    return expiresAt;
  }

  /**
   * Inform for a possible change propolsal in KeyHash
   *
   * @autogenerated UpdateInputGenerator
   * @return empty if there is no change proposal for KeyHash, otherwise the value for KeyHash
   */
  public Optional<KeyHashVO> getKeyHash() {
    return keyHash;
  }

  /**
   * Inform for a possible change propolsal in LastUsedAt
   *
   * @autogenerated UpdateInputGenerator
   * @return empty if there is no change proposal for LastUsedAt, otherwise the value for LastUsedAt
   */
  public Optional<LastUsedAtVO> getLastUsedAt() {
    return lastUsedAt;
  }

  /**
   * Inform for a possible change propolsal in Name
   *
   * @autogenerated UpdateInputGenerator
   * @return empty if there is no change proposal for Name, otherwise the value for Name
   */
  public Optional<NameVO> getName() {
    return name;
  }

  /**
   * Inform for a possible change propolsal in Scopes
   *
   * @autogenerated UpdateInputGenerator
   * @return empty if there is no change proposal for Scopes, otherwise the value for Scopes
   */
  public Optional<ScopesVO> getScopes() {
    return scopes;
  }

  /**
   * Inform for a possible change propolsal in Uid
   *
   * @autogenerated UpdateInputGenerator
   * @return empty if there is no change proposal for Uid, otherwise the value for Uid
   */
  public Optional<UidVO> getUid() {
    return uid;
  }

  /**
   * Inform for a possible change propolsal in User
   *
   * @autogenerated UpdateInputGenerator
   * @return empty if there is no change proposal for User, otherwise the value for User
   */
  public Optional<UserVO> getUser() {
    return user;
  }

  /**
   * Inform for a possible change propolsal in Version
   *
   * @autogenerated UpdateInputGenerator
   * @return empty if there is no change proposal for Version, otherwise the value for Version
   */
  public Optional<VersionVO> getVersion() {
    return version;
  }

  /**
   * Assigna change proposal for CreatedAt to be apply for the aggregate.
   *
   * @autogenerated UpdateInputGenerator
   * @param value The proposal value for UserPersonalApiKeyUpdateInput
   * @return self instance to enable a flow code
   */
  public UserPersonalApiKeyUpdateInput setCreatedAt(final OffsetDateTime value) {
    this.createdAt = Optional.of(CreatedAtVO.from(value));
    return this;
  }

  /**
   * Assigna change proposal for Enabled to be apply for the aggregate.
   *
   * @autogenerated UpdateInputGenerator
   * @param value The proposal value for UserPersonalApiKeyUpdateInput
   * @return self instance to enable a flow code
   */
  public UserPersonalApiKeyUpdateInput setEnabled(final Boolean value) {
    this.enabled = Optional.of(EnabledVO.from(value));
    return this;
  }

  /**
   * Assigna change proposal for ExpiresAt to be apply for the aggregate.
   *
   * @autogenerated UpdateInputGenerator
   * @param value The proposal value for UserPersonalApiKeyUpdateInput
   * @return self instance to enable a flow code
   */
  public UserPersonalApiKeyUpdateInput setExpiresAt(final OffsetDateTime value) {
    this.expiresAt = Optional.of(ExpiresAtVO.from(value));
    return this;
  }

  /**
   * Assigna change proposal for KeyHash to be apply for the aggregate.
   *
   * @autogenerated UpdateInputGenerator
   * @param value The proposal value for UserPersonalApiKeyUpdateInput
   * @return self instance to enable a flow code
   */
  public UserPersonalApiKeyUpdateInput setKeyHash(final String value) {
    this.keyHash = Optional.of(KeyHashVO.from(value));
    return this;
  }

  /**
   * Assigna change proposal for LastUsedAt to be apply for the aggregate.
   *
   * @autogenerated UpdateInputGenerator
   * @param value The proposal value for UserPersonalApiKeyUpdateInput
   * @return self instance to enable a flow code
   */
  public UserPersonalApiKeyUpdateInput setLastUsedAt(final OffsetDateTime value) {
    this.lastUsedAt = Optional.of(LastUsedAtVO.from(value));
    return this;
  }

  /**
   * Assigna change proposal for Name to be apply for the aggregate.
   *
   * @autogenerated UpdateInputGenerator
   * @param value The proposal value for UserPersonalApiKeyUpdateInput
   * @return self instance to enable a flow code
   */
  public UserPersonalApiKeyUpdateInput setName(final String value) {
    this.name = Optional.of(NameVO.from(value));
    return this;
  }

  /**
   * Assigna change proposal for Scopes to be apply for the aggregate.
   *
   * @autogenerated UpdateInputGenerator
   * @param value The proposal value for UserPersonalApiKeyUpdateInput
   * @return self instance to enable a flow code
   */
  public UserPersonalApiKeyUpdateInput setScopes(final String value) {
    this.scopes = Optional.of(ScopesVO.from(value));
    return this;
  }

  /**
   * Assigna change proposal for Uid to be apply for the aggregate.
   *
   * @autogenerated UpdateInputGenerator
   * @param value The proposal value for UserPersonalApiKeyUpdateInput
   * @return self instance to enable a flow code
   */
  public UserPersonalApiKeyUpdateInput setUid(final String value) {
    this.uid = Optional.of(UidVO.from(value));
    return this;
  }

  /**
   * Assigna change proposal for User to be apply for the aggregate.
   *
   * @autogenerated UpdateInputGenerator
   * @param value The proposal value for UserPersonalApiKeyUpdateInput
   * @return self instance to enable a flow code
   */
  public UserPersonalApiKeyUpdateInput setUser(final UserRef value) {
    this.user = Optional.of(UserVO.from(value));
    return this;
  }

  /**
   * Assigna change proposal for Version to be apply for the aggregate.
   *
   * @autogenerated UpdateInputGenerator
   * @param value The proposal value for UserPersonalApiKeyUpdateInput
   * @return self instance to enable a flow code
   */
  public UserPersonalApiKeyUpdateInput setVersion(final Integer value) {
    this.version = Optional.of(VersionVO.from(value));
    return this;
  }

  /**
   * @autogenerated UpdateInputGenerator
   * @return
   */
  UserPersonalApiKeyChangeSet toChangeSet() {
    return new UserPersonalApiKeyChangeSet().uid(uid).user(user).name(name).keyHash(keyHash)
        .scopes(scopes).lastUsedAt(lastUsedAt).expiresAt(expiresAt).createdAt(createdAt)
        .enabled(enabled).version(version);
  }
}
