package net.civeira.phylax.features.access.trustedclient.application.usecase.delete;

import java.util.List;

import io.quarkus.arc.Unremovable;
import jakarta.enterprise.context.ApplicationScoped;
import lombok.Data;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.batch.stepper.ItemDescriptor;
import net.civeira.phylax.common.batch.stepper.ItemProcessor;
import net.civeira.phylax.common.batch.stepper.ItemReader;
import net.civeira.phylax.common.batch.stepper.ItemWriter;
import net.civeira.phylax.common.batch.stepper.StepContext;
import net.civeira.phylax.common.batch.stepper.StepCounter;
import net.civeira.phylax.common.batch.stepper.StepFinalizer;
import net.civeira.phylax.common.batch.stepper.StepInitializer;
import net.civeira.phylax.common.exception.ExecutionException;
import net.civeira.phylax.common.security.Allow;
import net.civeira.phylax.features.access.trustedclient.application.visibility.TrustedClientsVisibility;
import net.civeira.phylax.features.access.trustedclient.domain.TrustedClient;
import net.civeira.phylax.features.access.trustedclient.domain.gateway.TrustedClientCursor;

@Unremovable
@ApplicationScoped
@RequiredArgsConstructor
class TrustedClientsInBatchExecutor implements
    StepCounter<TrustedClientDeleteAllInBatchCommand, TrustedClientsInBatchExecutor.TrustedClientPaginableBatch>,
    StepFinalizer<TrustedClientDeleteAllInBatchCommand, TrustedClientsInBatchExecutor.TrustedClientPaginableBatch>,
    StepInitializer<TrustedClientDeleteAllInBatchCommand, TrustedClientsInBatchExecutor.TrustedClientPaginableBatch>,
    ItemReader<TrustedClient, TrustedClientDeleteAllInBatchCommand, TrustedClientsInBatchExecutor.TrustedClientPaginableBatch>,
    ItemWriter<TrustedClient, TrustedClientDeleteAllInBatchCommand, TrustedClientsInBatchExecutor.TrustedClientPaginableBatch>,
    ItemProcessor<TrustedClient, TrustedClient, TrustedClientDeleteAllInBatchCommand, TrustedClientsInBatchExecutor.TrustedClientPaginableBatch>,
    ItemDescriptor<TrustedClient, TrustedClientDeleteAllInBatchCommand, TrustedClientsInBatchExecutor.TrustedClientPaginableBatch> {

  /**
   * @autogenerated EntityGenerator
   */
  @Data
  public static class TrustedClientPaginableBatch {

    /**
     * @autogenerated EntityGenerator
     */
    private String since;
  }

  /**
   * @autogenerated EntityGenerator
   */
  private final int size = 10;

  /**
   * @autogenerated EntityGenerator
   */
  private final TrustedClientDeleteUsecase usecase;

  /**
   * @autogenerated EntityGenerator
   */
  private final TrustedClientsVisibility visibility;

  /**
   * @autogenerated EntityGenerator
   * @param context
   * @return
   */
  @Override
  public long approximatedItems(
      final StepContext<TrustedClientDeleteAllInBatchCommand, TrustedClientPaginableBatch> context) {
    return visibility.countVisibles(context.getParams().getInteraction(),
        context.getParams().getFilter());
  }

  /**
   * @autogenerated EntityGenerator
   * @param context
   */
  @Override
  public void finish(
      final StepContext<TrustedClientDeleteAllInBatchCommand, TrustedClientPaginableBatch> context) {
    usecase.flush();
  }

  /**
   * @autogenerated EntityGenerator
   * @param context
   */
  @Override
  public void init(
      final StepContext<TrustedClientDeleteAllInBatchCommand, TrustedClientPaginableBatch> context) {
    context.setState(new TrustedClientPaginableBatch());
  }

  /**
   * @autogenerated EntityGenerator
   * @param item
   * @param context
   * @return
   */
  @Override
  public String itemDescription(final TrustedClient item,
      final StepContext<TrustedClientDeleteAllInBatchCommand, TrustedClientPaginableBatch> context) {
    return item.getUid();
  }

  /**
   * @autogenerated EntityGenerator
   * @param item
   * @param context
   * @return
   */
  @Override
  public TrustedClient process(final TrustedClient item,
      final StepContext<TrustedClientDeleteAllInBatchCommand, TrustedClientPaginableBatch> context) {
    Allow allowed = usecase.allow(context.getParams().getInteraction(), item);
    if (!allowed.isAllowed()) {
      throw new ExecutionException("not-allowed", null);
    }
    return item;
  }

  /**
   * @autogenerated EntityGenerator
   * @param context
   * @return
   */
  @Override
  public List<TrustedClient> read(
      final StepContext<TrustedClientDeleteAllInBatchCommand, TrustedClientPaginableBatch> context) {
    List<TrustedClient> page = visibility.listVisiblesForUpdate(
        context.getParams().getInteraction(), context.getParams().getFilter(),
        TrustedClientCursor.builder().limit(size).sinceUid(context.getState().getSince()).build());
    context.getState().setSince(page.isEmpty() ? null : page.get(page.size() - 1).getUid());
    return page;
  }

  /**
   * @autogenerated EntityGenerator
   * @param items
   * @param context
   */
  @Override
  public void write(final List<TrustedClient> items,
      final StepContext<TrustedClientDeleteAllInBatchCommand, TrustedClientPaginableBatch> context) {
    items.forEach(item -> usecase.delete(context.getParams().getInteraction(), item));
  }
}
