package net.civeira.phylax.features.document.templateasset.infrastructure.driver.rest;

import org.apache.commons.lang3.StringUtils;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.transaction.Transactional;
import jakarta.ws.rs.core.Response;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.infrastructure.CurrentRequest;
import net.civeira.phylax.common.security.MagicLinkService;
import net.civeira.phylax.common.telemetry.ApiObserved;
import net.civeira.phylax.features.access.tenant.domain.TenantReference;
import net.civeira.phylax.features.document.templateasset.application.usecase.create.TemplateAssetCreateInput;
import net.civeira.phylax.features.document.templateasset.application.usecase.create.TemplateAssetCreateProjection;
import net.civeira.phylax.features.document.templateasset.application.usecase.create.TemplateAssetCreateUsecase;
import net.civeira.phylax.generated.openapi.model.TemplateAssetApiDto;
import net.civeira.phylax.generated.openapi.model.TenantApiRef;

@RequiredArgsConstructor
@ApplicationScoped
public class TemplateAssetCreateController {

  /**
   * @autogenerated CreateControllerGenerator
   */
  private final TemplateAssetCreateUsecase create;

  /**
   * @autogenerated CreateControllerGenerator
   */
  private final CurrentRequest currentRequest;

  /**
   * @autogenerated CreateControllerGenerator
   */
  private final MagicLinkService magicLink;

  /**
   * @autogenerated CreateControllerGenerator
   * @param templateAsset
   * @return
   */
  @Transactional
  @ApiObserved("Api to create an entity of template asset")
  public Response templateAssetApiCreate(TemplateAssetApiDto templateAsset) {
    TemplateAssetCreateProjection created =
        create.create(currentRequest.interaction(), toDomainModel(templateAsset));
    return Response.ok(toApiModel(created)).build();
  }

  /**
   * @autogenerated CreateControllerGenerator
   * @param dto
   * @return
   */
  private TemplateAssetApiDto toApiModel(TemplateAssetCreateProjection dto) {
    TemplateAssetApiDto templateAssetApiDto = new TemplateAssetApiDto();
    templateAssetApiDto.setUid(dto.getUid());
    templateAssetApiDto.setTenant(new TenantApiRef().$ref(dto.getTenantReference()));
    templateAssetApiDto.setCode(dto.getCode());
    templateAssetApiDto.setType(dto.getType());
    String content = dto.getContent();
    if (null != content) {
      String url = currentRequest.getPublicHost() + "/api/document/template-asset/"
          + dto.getUidOrDefault("-") + "/content";
      templateAssetApiDto.setContent(magicLink.create(url, currentRequest.interaction()));
    }
    templateAssetApiDto.setEnabled(dto.getEnabled());
    templateAssetApiDto.setVersion(dto.getVersion());
    return templateAssetApiDto;
  }

  /**
   * @autogenerated CreateControllerGenerator
   * @param templateAssetApiDto
   * @return
   */
  private TemplateAssetCreateInput toDomainModel(TemplateAssetApiDto templateAssetApiDto) {
    TemplateAssetCreateInput dto = new TemplateAssetCreateInput();
    if (null != templateAssetApiDto.getUid()) {
      dto.setUid(templateAssetApiDto.getUid());
    }
    if (null != templateAssetApiDto.getTenant()) {
      dto.setTenant(TenantReference.of(templateAssetApiDto.getTenant().get$Ref()));
    }
    if (null != templateAssetApiDto.getCode()) {
      dto.setCode(templateAssetApiDto.getCode());
    }
    if (null != templateAssetApiDto.getType()) {
      dto.setType(templateAssetApiDto.getType());
    }
    if (!StringUtils.isBlank(templateAssetApiDto.getContent())) {
      String url = templateAssetApiDto.getContent();
      if (templateAssetApiDto.getContent().startsWith(
          currentRequest.getPublicHost() + "/api/document/template-asset/-/temp-content?temp=")) {
        dto.setContent("temp://" + (url.substring(
            (currentRequest.getPublicHost() + "/api/document/template-asset/-/temp-content?temp=")
                .length())));
      } else if (!(url.equals(currentRequest.getPublicHost() + "/api/document/template-asset/"
          + templateAssetApiDto.getUid() + "/content"))) {
        dto.setContent(templateAssetApiDto.getContent());
      }
    }
    if (null != templateAssetApiDto.getEnabled()) {
      dto.setEnabled(templateAssetApiDto.getEnabled());
    }
    if (null != templateAssetApiDto.getVersion()) {
      dto.setVersion(templateAssetApiDto.getVersion());
    }
    return dto;
  }
}
