package net.civeira.phylax.features.access.userprofile.domain.valueobject;

import java.util.Map;
import java.util.Optional;

import lombok.EqualsAndHashCode;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.exception.ConstraintException;
import net.civeira.phylax.common.value.validation.AbstractFailList;
import net.civeira.phylax.common.value.validation.ConstraintFail;
import net.civeira.phylax.common.value.validation.ConstraintFailList;

/**
 * Value Object representing el preferred username de user profile of userProfile.
 * <p>
 * This class ensures that the preferred username is a {@code String} and encapsulates its
 * validation and formatting logic. It is immutable and compliant with DDD (Domain-Driven Design)
 * principles.
 * </p>
 * <p>
 * Use {@link #from(String)} or {@link #tryFrom(Object)} to safely create instances. Validation
 * errors are reported via {@link ConstraintFailList} or thrown as {@link ConstraintException}.
 * </p>
 */
@RequiredArgsConstructor
@EqualsAndHashCode
public class PreferredUsernameVO {

  /**
   * Crear an empty instance with no value
   *
   * @autogenerated ValueObjectGenerator
   * @param preferredUsername
   * @return An empty instance
   */
  public static PreferredUsernameVO from(final String preferredUsername) {
    return tryFrom(preferredUsername);
  }

  /**
   * Crear an empty instance with no value
   *
   * @autogenerated ValueObjectGenerator
   * @return An empty instance
   */
  public static PreferredUsernameVO nullValue() {
    return new PreferredUsernameVO(null);
  }

  /**
   * Crear an empty instance with no value
   *
   * @autogenerated ValueObjectGenerator
   * @param preferredUsername
   * @return An empty instance
   */
  public static PreferredUsernameVO tryFrom(final Object preferredUsername) {
    ConstraintFailList list = new ConstraintFailList();
    PreferredUsernameVO result = tryFrom(preferredUsername, list);
    if (list.hasErrors()) {
      throw new ConstraintException("Invalid value for PreferredUsernameVO.preferred-username",
          list);
    }
    return result;
  }

  /**
   * Crear an empty instance with no value
   *
   * @autogenerated ValueObjectGenerator
   * @param preferredUsername temptative value
   * @param fails Error list
   * @return An empty instance
   */
  public static <T extends AbstractFailList> PreferredUsernameVO tryFrom(
      final Object preferredUsername, final T fails) {
    if (null == preferredUsername) {
      return new PreferredUsernameVO(null);
    } else if (preferredUsername instanceof String castedPreferredUsername) {
      return new PreferredUsernameVO(castedPreferredUsername);
    } else {
      fails.add(new ConstraintFail("wrong-type", "preferredUsername", preferredUsername.getClass(),
          "A String type is expected for preferredUsername"));
      return null;
    }
  }

  /**
   * The actual value of the name.
   *
   * @autogenerated ValueObjectGenerator
   */
  private final String value;

  /**
   * Get the vo value
   *
   * @autogenerated ValueObjectGenerator
   * @return
   */
  public Optional<String> getPreferredUsername() {
    return Optional.ofNullable(value);
  }

  /**
   * @autogenerated ValueObjectGenerator
   * @param map
   */
  public void preferredUsernameToMap(final Map<String, String> map) {
    if (null != value) {
      map.put("preferredUsername", String.valueOf(value));
    }
  }

  /**
   * Returns a formatted string representation of the name.
   *
   * @autogenerated ValueObjectGenerator
   * @return the string value wrapped in square brackets.
   */
  @Override
  public String toString() {
    return "[" + value + "]";
  }
}
