package net.civeira.phylax.features.access.userprofile.domain.valueobject;

import java.util.Map;
import java.util.Optional;

import lombok.EqualsAndHashCode;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.exception.ConstraintException;
import net.civeira.phylax.common.value.validation.AbstractFailList;
import net.civeira.phylax.common.value.validation.ConstraintFail;
import net.civeira.phylax.common.value.validation.ConstraintFailList;

/**
 * Value Object representing el updated at de user profile of userProfile.
 * <p>
 * This class ensures that the updated at is a {@code String} and encapsulates its validation and
 * formatting logic. It is immutable and compliant with DDD (Domain-Driven Design) principles.
 * </p>
 * <p>
 * Use {@link #from(String)} or {@link #tryFrom(Object)} to safely create instances. Validation
 * errors are reported via {@link ConstraintFailList} or thrown as {@link ConstraintException}.
 * </p>
 */
@RequiredArgsConstructor
@EqualsAndHashCode
public class UpdatedAtVO {

  /**
   * Crear an empty instance with no value
   *
   * @autogenerated ValueObjectGenerator
   * @param updatedAt
   * @return An empty instance
   */
  public static UpdatedAtVO from(final String updatedAt) {
    return tryFrom(updatedAt);
  }

  /**
   * Crear an empty instance with no value
   *
   * @autogenerated ValueObjectGenerator
   * @return An empty instance
   */
  public static UpdatedAtVO nullValue() {
    return new UpdatedAtVO(null);
  }

  /**
   * Crear an empty instance with no value
   *
   * @autogenerated ValueObjectGenerator
   * @param updatedAt
   * @return An empty instance
   */
  public static UpdatedAtVO tryFrom(final Object updatedAt) {
    ConstraintFailList list = new ConstraintFailList();
    UpdatedAtVO result = tryFrom(updatedAt, list);
    if (list.hasErrors()) {
      throw new ConstraintException("Invalid value for UpdatedAtVO.updated_at", list);
    }
    return result;
  }

  /**
   * Crear an empty instance with no value
   *
   * @autogenerated ValueObjectGenerator
   * @param updatedAt temptative value
   * @param fails Error list
   * @return An empty instance
   */
  public static <T extends AbstractFailList> UpdatedAtVO tryFrom(final Object updatedAt,
      final T fails) {
    if (null == updatedAt) {
      return new UpdatedAtVO(null);
    } else if (updatedAt instanceof String castedUpdatedAt) {
      return new UpdatedAtVO(castedUpdatedAt);
    } else {
      fails.add(new ConstraintFail("wrong-type", "updatedAt", updatedAt.getClass(),
          "A String type is expected for updatedAt"));
      return null;
    }
  }

  /**
   * The actual value of the name.
   *
   * @autogenerated ValueObjectGenerator
   */
  private final String value;

  /**
   * Get the vo value
   *
   * @autogenerated ValueObjectGenerator
   * @return
   */
  public Optional<String> getUpdatedAt() {
    return Optional.ofNullable(value);
  }

  /**
   * Returns a formatted string representation of the name.
   *
   * @autogenerated ValueObjectGenerator
   * @return the string value wrapped in square brackets.
   */
  @Override
  public String toString() {
    return "[" + value + "]";
  }

  /**
   * @autogenerated ValueObjectGenerator
   * @param map
   */
  public void updatedAtToMap(final Map<String, String> map) {
    if (null != value) {
      map.put("updatedAt", String.valueOf(value));
    }
  }
}
