package net.civeira.phylax.features.access.tenantloginprovider.application.usecase.disable;

import java.time.Duration;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Event;
import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.batch.BatchIdentificator;
import net.civeira.phylax.common.batch.BatchProgress;
import net.civeira.phylax.common.batch.BatchService;
import net.civeira.phylax.common.batch.ExecutorByDeferSteps;
import net.civeira.phylax.common.batch.ExecutorPlan;
import net.civeira.phylax.common.exception.NotAllowedException;
import net.civeira.phylax.common.exception.NotFoundException;
import net.civeira.phylax.common.security.OperationContext;
import net.civeira.phylax.common.security.Permission;
import net.civeira.phylax.common.telemetry.Observed;
import net.civeira.phylax.common.telemetry.Trace;
import net.civeira.phylax.features.access.tenantloginprovider.application.visibility.TenantLoginProviderVisibilityFilter;
import net.civeira.phylax.features.access.tenantloginprovider.application.visibility.TenantLoginProvidersVisibility;
import net.civeira.phylax.features.access.tenantloginprovider.domain.TenantLoginProvider;
import net.civeira.phylax.features.access.tenantloginprovider.domain.TenantLoginProviderRef;
import net.civeira.phylax.features.access.tenantloginprovider.domain.gateway.TenantLoginProviderAuditGateway;
import net.civeira.phylax.features.access.tenantloginprovider.domain.gateway.TenantLoginProviderCacheGateway;
import net.civeira.phylax.features.access.tenantloginprovider.domain.gateway.TenantLoginProviderWriteRepositoryGateway;

@ApplicationScoped
@RequiredArgsConstructor
public class TenantLoginProviderDisableUsecase {

  /**
   * Service to register audit events
   *
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final TenantLoginProviderAuditGateway audit;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final BatchService batch;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final TenantLoginProviderCacheGateway cache;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final Event<TenantLoginProviderDisableAuthorizationDecision> execAllowEmitter;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final Event<TenantLoginProviderDisableCheck> execProposalEmitter;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final TenantLoginProviderWriteRepositoryGateway gateway;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   */
  private final TenantLoginProvidersVisibility visibility;

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param reference
   * @return
   */
  @Observed("disable an entity of tenant login provider")
  public Permission allow(final OperationContext context, final TenantLoginProviderRef reference) {
    Trace.setAttribute("ref", reference.getUid());
    Permission response = checkPermission(context, reference);
    Trace.setAttribute("allowed", response.isAllowed());
    return response;
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @return
   */
  @Observed("disable an entity of tenant login provider")
  public Permission allow(final OperationContext context) {
    Permission response = checkPermission(context);
    Trace.setAttribute("allowed", response.isAllowed());
    return response;
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param filter
   * @return The slide with some values
   */
  @Observed("disable a set of entity of tenant login provider")
  public BatchIdentificator batchDisable(final OperationContext context,
      final TenantLoginProviderDisableFilter filter) {
    Permission detail = checkPermission(context);
    if (!detail.isAllowed()) {
      Trace.addEvent("The policies for tenant login provider dont allow to disable: "
          + detail.getDescription());
      throw new NotAllowedException(detail.getDescription());
    }
    TenantLoginProviderVisibilityFilter filterWithVisibility = TenantLoginProviderVisibilityFilter
        .builder().uid(filter.getUid().orElse(null)).uids(filter.getUids().stream().toList())
        .search(filter.getSearch().orElse(null)).name(filter.getName().orElse(null))
        .tenant(filter.getTenant().orElse(null)).tenants(filter.getTenants())
        .tenantAccesible(filter.getTenantAccesible().orElse(null)).build();
    TenantLoginProviderDisableAllInBatchCommand command =
        new TenantLoginProviderDisableAllInBatchCommand(context, filterWithVisibility);
    return batch.start(context.getActor().getName().orElse("-"), Duration.ofHours(6), ExecutorPlan
        .<TenantLoginProviderDisableAllInBatchCommand>builder().params(command)
        .name("disable-tenant-login-provider")
        .executor(
            ExecutorByDeferSteps.<TenantLoginProvider, TenantLoginProvider, TenantLoginProviderDisableAllInBatchCommand, TenantLoginProviderDisablesInBatchExecutor.TenantLoginProviderPaginableBatch>builder()
                .initializer(TenantLoginProviderDisablesInBatchExecutor.class)
                .counter(TenantLoginProviderDisablesInBatchExecutor.class)
                .descriptor(TenantLoginProviderDisablesInBatchExecutor.class)
                .reader(TenantLoginProviderDisablesInBatchExecutor.class)
                .processor(TenantLoginProviderDisablesInBatchExecutor.class)
                .writer(TenantLoginProviderDisablesInBatchExecutor.class)
                .finalizer(TenantLoginProviderDisablesInBatchExecutor.class).build())
        .build());
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param query a filter to retrieve only matching values
   * @return The slide with some values
   */
  public BatchProgress checkProgress(final OperationContext context,
      final TenantLoginProviderDisableStatus query) {
    return context.getActor().getName()
        .flatMap(name -> batch.retrieve(query.getTaskId(), context.getSource().getLocale(), name))
        .orElseThrow(() -> new NotFoundException());
  }

  /**
   * Recover a slide of data.
   *
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param reference
   * @return The slide with some values
   */
  @Observed("disable an entity of tenant login provider")
  public TenantLoginProviderDisableProjection disable(final OperationContext context,
      final TenantLoginProviderRef reference) {
    Trace.setAttribute("ref", reference.getUid());
    Permission detail = checkPermission(context, reference);
    if (!detail.isAllowed()) {
      Trace.addEvent("The policies for tenant login provider dont allow to disable: "
          + detail.getDescription());
      throw new NotAllowedException(detail.getDescription());
    }
    TenantLoginProvider original = visibility.retrieveVisibleForUpdate(context, reference.getUid())
        .orElseThrow(() -> new NotFoundException(""));
    TenantLoginProvider saved = doDisable(context, original);
    cacheUpdate(saved);
    // Register audit operation
    audit.updated("disable", saved, original, context);
    return TenantLoginProviderDisableProjection.from(visibility.copyWithHidden(context, saved));
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param saved
   */
  void cacheUpdate(final TenantLoginProvider saved) {
    cache.update(saved);
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param reference
   * @return
   */
  Permission checkPermission(final OperationContext context,
      final TenantLoginProviderRef reference) {
    TenantLoginProviderDisableAuthorizationDecision proposal =
        new TenantLoginProviderDisableAuthorizationDecision(context, reference,
            Permission.allow("Allow to disable by default"));
    execAllowEmitter.fire(proposal);
    return proposal.getPermission();
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @return
   */
  Permission checkPermission(final OperationContext context) {
    TenantLoginProviderDisableAuthorizationDecision proposal =
        new TenantLoginProviderDisableAuthorizationDecision(context,
            Permission.allow("Allow to disable by default"));
    execAllowEmitter.fire(proposal);
    return proposal.getPermission();
  }

  /**
   * @autogenerated ActionChangeUsecaseGenerator
   * @param context
   * @param original
   * @return
   */
  TenantLoginProvider doDisable(final OperationContext context,
      final TenantLoginProvider original) {
    TenantLoginProviderDisableCheck proposal =
        new TenantLoginProviderDisableCheck(context, original);
    execProposalEmitter.fire(proposal);
    TenantLoginProvider result = original.disable();
    TenantLoginProvider saved = gateway.update(original, result);
    return saved;
  }
}
