package net.civeira.phylax.features.access.userwebauthncredential.domain;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class UserWebauthnCredentialReferenceUnitTest {

  /**
   * @autogenerated ValueObjectGenerator
   */
  @Test
  @DisplayName("Test UserWebauthnCredential reference contruction")
  void test_user_webauthn_credential_reference_builder() {
    UserWebauthnCredentialReference ref = UserWebauthnCredentialReference.of("one");
    Assertions.assertEquals("one", ref.getUid());
  }
}
