package net.civeira.phylax.features.access.tenantloginprovider.domain.valueobject;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import net.civeira.phylax.common.exception.ConstraintException;
import net.civeira.phylax.features.access.tenantloginprovider.domain.TenantLoginProviderSourceOptions;

class SourceVOUnitTest {

  /**
   * @autogenerated ValueObjectGenerator
   */
  @Test
  @DisplayName("Test value object contruction for property source of tenant login provider ")
  void test_source_v_o_builder() {
    Assertions.assertThrows(ConstraintException.class, () -> SourceVO.tryFrom("_GOOGLE_"));
    Assertions.assertEquals(TenantLoginProviderSourceOptions.GOOGLE,
        SourceVO.tryFrom("GOOGLE").getSource());
    Assertions.assertThrows(ConstraintException.class, () -> SourceVO.tryFrom(null));
    Assertions.assertEquals(TenantLoginProviderSourceOptions.GOOGLE,
        SourceVO.from(TenantLoginProviderSourceOptions.GOOGLE).getSource());
    Object falingInstance = new Object() {};
    Assertions.assertThrows(ConstraintException.class, () -> SourceVO.tryFrom(falingInstance));
    Assertions.assertEquals("[" + TenantLoginProviderSourceOptions.GOOGLE + "]",
        SourceVO.from(TenantLoginProviderSourceOptions.GOOGLE).toString());
  }
}
