package net.civeira.phylax.features.document.snippetasset.domain.valueholder;

import java.util.Optional;

import lombok.RequiredArgsConstructor;
import net.civeira.phylax.common.value.validation.ConstraintFail;
import net.civeira.phylax.common.value.validation.ConstraintFailList;
import net.civeira.phylax.features.document.snippet.domain.SnippetChangeSet;
import net.civeira.phylax.features.document.snippet.domain.SnippetRef;
import net.civeira.phylax.features.document.snippet.domain.SnippetReference;
import net.civeira.phylax.features.document.snippetasset.domain.SnippetAsset;
import net.civeira.phylax.features.document.snippetasset.domain.valueobject.SnippetVO;

@RequiredArgsConstructor
public class SnippetValueHolder<T> {

  /**
   * @autogenerated ValueHolderGenerator
   */
  private final T holder;

  /**
   * @autogenerated ValueHolderGenerator
   */
  private Optional<SnippetVO> value = Optional.empty();

  /**
   * @autogenerated ValueHolderGenerator
   * @return
   */
  public Optional<SnippetRef> getSnippet() {
    return value.map(SnippetVO::getSnippet);
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @return
   */
  public Optional<SnippetVO> getSnippetValue() {
    return value;
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @param original
   * @param fails
   * @return
   */
  public SnippetVO readSnippet(final Optional<SnippetAsset> original,
      final ConstraintFailList fails) {
    SnippetVO result = value.orElse(original.map(SnippetAsset::getSnippetValue).orElse(null));
    if (null == result) {
      fails.add(new ConstraintFail("REQUIRED", "snippet", null));
    }
    return result;
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @param snippet
   * @return
   */
  public T snippet(SnippetVO snippet) {
    this.value = Optional.of(snippet);
    return this.holder;
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @param snippet
   * @return
   */
  public T snippet(Optional<SnippetVO> snippet) {
    this.value = snippet;
    return this.holder;
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @param snippet
   * @return
   */
  public T snippet(SnippetRef snippet) {
    this.value = Optional.of(SnippetVO.from(snippet));
    return this.holder;
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @param snippet
   * @return
   */
  public T snippet(SnippetChangeSet snippet) {
    value = Optional.of(SnippetVO.from(SnippetReference.of(snippet.getUid().orElseThrow())));
    return holder;
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @return
   */
  public T unsetSnippet() {
    value = Optional.empty();
    return holder;
  }

  /**
   * @autogenerated ValueHolderGenerator
   * @param field
   * @return
   */
  public T unsetSnippetIfMatches(final String field) {
    if ("snippet".equals(field)) {
      value = Optional.empty();
    }
    return holder;
  }
}
