package net.civeira.phylax.features.access.tenantloginprovider.domain;

import lombok.NoArgsConstructor;
import lombok.experimental.Delegate;
import net.civeira.phylax.common.value.Uuid;
import net.civeira.phylax.features.access.tenantloginprovider.domain.valueholder.CertificateValueHolder;
import net.civeira.phylax.features.access.tenantloginprovider.domain.valueholder.DirectAccessValueHolder;
import net.civeira.phylax.features.access.tenantloginprovider.domain.valueholder.DisabledValueHolder;
import net.civeira.phylax.features.access.tenantloginprovider.domain.valueholder.MetadataValueHolder;
import net.civeira.phylax.features.access.tenantloginprovider.domain.valueholder.NameValueHolder;
import net.civeira.phylax.features.access.tenantloginprovider.domain.valueholder.PrivateKeyValueHolder;
import net.civeira.phylax.features.access.tenantloginprovider.domain.valueholder.PublicKeyValueHolder;
import net.civeira.phylax.features.access.tenantloginprovider.domain.valueholder.SamlIdpEntityIdValueHolder;
import net.civeira.phylax.features.access.tenantloginprovider.domain.valueholder.SamlIdpIdpCertValueHolder;
import net.civeira.phylax.features.access.tenantloginprovider.domain.valueholder.SamlIdpMetadataUrlValueHolder;
import net.civeira.phylax.features.access.tenantloginprovider.domain.valueholder.SamlIdpSsoUrlValueHolder;
import net.civeira.phylax.features.access.tenantloginprovider.domain.valueholder.SourceValueHolder;
import net.civeira.phylax.features.access.tenantloginprovider.domain.valueholder.TenantValueHolder;
import net.civeira.phylax.features.access.tenantloginprovider.domain.valueholder.UidValueHolder;
import net.civeira.phylax.features.access.tenantloginprovider.domain.valueholder.UsersEnabledByDefaultValueHolder;
import net.civeira.phylax.features.access.tenantloginprovider.domain.valueholder.VersionValueHolder;

/**
 * A dto transfer to hold tenant login provider attribute values
 */
@NoArgsConstructor
public class TenantLoginProviderChangeSet {

  /**
   * The provider certificate used for signature verification, if required.
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private CertificateValueHolder<TenantLoginProviderChangeSet> certificateValue =
      new CertificateValueHolder<>(this);

  /**
   * If true, the system will default to this login method without requiring selection.
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private DirectAccessValueHolder<TenantLoginProviderChangeSet> directAccessValue =
      new DirectAccessValueHolder<>(this);

  /**
   * Indicates if this provider is currently disabled.
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private DisabledValueHolder<TenantLoginProviderChangeSet> disabledValue =
      new DisabledValueHolder<>(this);

  /**
   * A metadata file required by some providers for configuration (e.g., SAML descriptor).
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private MetadataValueHolder<TenantLoginProviderChangeSet> metadataValue =
      new MetadataValueHolder<>(this);

  /**
   * A name that identifies this login provider within the tenant.
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private NameValueHolder<TenantLoginProviderChangeSet> nameValue = new NameValueHolder<>(this);

  /**
   * Private key used internally to validate codes returned by the identity provider.
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private PrivateKeyValueHolder<TenantLoginProviderChangeSet> privateKeyValue =
      new PrivateKeyValueHolder<>(this);

  /**
   * A public key shared with users to interact with the identity provider.
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private PublicKeyValueHolder<TenantLoginProviderChangeSet> publicKeyValue =
      new PublicKeyValueHolder<>(this);

  /**
   * El saml idp entity id de tenant login provider
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private SamlIdpEntityIdValueHolder<TenantLoginProviderChangeSet> samlIdpEntityIdValue =
      new SamlIdpEntityIdValueHolder<>(this);

  /**
   * El saml idp idp cert de tenant login provider
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private SamlIdpIdpCertValueHolder<TenantLoginProviderChangeSet> samlIdpIdpCertValue =
      new SamlIdpIdpCertValueHolder<>(this);

  /**
   * El saml idp metadata url de tenant login provider
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private SamlIdpMetadataUrlValueHolder<TenantLoginProviderChangeSet> samlIdpMetadataUrlValue =
      new SamlIdpMetadataUrlValueHolder<>(this);

  /**
   * El saml idp sso url de tenant login provider
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private SamlIdpSsoUrlValueHolder<TenantLoginProviderChangeSet> samlIdpSsoUrlValue =
      new SamlIdpSsoUrlValueHolder<>(this);

  /**
   * The source protocol or system used for authentication (e.g., GOOGLE, GITHUB, SAML).
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private SourceValueHolder<TenantLoginProviderChangeSet> sourceValue =
      new SourceValueHolder<>(this);

  /**
   * The tenant this login provider is configured for.
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private TenantValueHolder<TenantLoginProviderChangeSet> tenantValue =
      new TenantValueHolder<>(this);

  /**
   * A uid string to identify the entity
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private UidValueHolder<TenantLoginProviderChangeSet> uidValue = new UidValueHolder<>(this);

  /**
   * Defines whether the users created with this provider are enabled by default.
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private UsersEnabledByDefaultValueHolder<TenantLoginProviderChangeSet> usersEnabledByDefaultValue =
      new UsersEnabledByDefaultValueHolder<>(this);

  /**
   * Campo con el número de version de tenant login provider para controlar bloqueos optimistas
   *
   * @autogenerated EntityChangeSetGenerator
   */
  @Delegate
  private VersionValueHolder<TenantLoginProviderChangeSet> versionValue =
      new VersionValueHolder<>(this);

  /**
   * @autogenerated EntityChangeSetGenerator
   * @return
   */
  public TenantLoginProviderChangeSet newUid() {
    return version(0).uid(Uuid.comb().toString());
  }

  /**
   * Unset a value by the property name. Unset values will no provide command change neither provide
   * information to the output context (hidden or readonly fields, or policy restrictions).
   *
   * @autogenerated EntityChangeSetGenerator
   * @param field The field name to unset.
   */
  public void unset(final String field) {
    uidValue.unsetUidIfMatches(field);
    tenantValue.unsetTenantIfMatches(field);
    nameValue.unsetNameIfMatches(field);
    sourceValue.unsetSourceIfMatches(field);
    disabledValue.unsetDisabledIfMatches(field);
    directAccessValue.unsetDirectAccessIfMatches(field);
    publicKeyValue.unsetPublicKeyIfMatches(field);
    privateKeyValue.unsetPrivateKeyIfMatches(field);
    certificateValue.unsetCertificateIfMatches(field);
    metadataValue.unsetMetadataIfMatches(field);
    samlIdpMetadataUrlValue.unsetSamlIdpMetadataUrlIfMatches(field);
    samlIdpEntityIdValue.unsetSamlIdpEntityIdIfMatches(field);
    samlIdpSsoUrlValue.unsetSamlIdpSsoUrlIfMatches(field);
    samlIdpIdpCertValue.unsetSamlIdpIdpCertIfMatches(field);
    usersEnabledByDefaultValue.unsetUsersEnabledByDefaultIfMatches(field);
    versionValue.unsetVersionIfMatches(field);
  }
}
